### ISSUE TITLE
How do i "get" this on my google chrome?

### ISSUE THREAD

**Issue by gavintheplague** [gorilla/websocket#100]
Trying to use the kahoot hack, and this is a dependency. sorry im a nub. How do I install the .go file aswell, if you know how.

**Comment by garyburd** [comment]
Use the [go get](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies) command to fetch and install this package:

     go get github.com/gorilla/websocket

This package works with Chrome, but not "on" chrome.  What is the kahoot hack?
