### ISSUE TITLE
Wrong case for Sec-WebSocket-Version

### ISSUE THREAD

**Issue by pjvds** [gorilla/websocket#101]
According to [RFC 6455](https://tools.ietf.org/html/rfc6455#section-11.3.5) the correct header for specifying the web socket version is `Sec-WebSocket-Version`, instead of `Sec-Websocket-Version` as it is [checked by the upgrader](https://github.com/gorilla/websocket/blob/567453a710c89724d4e971da34f613b0b89961cc/server.go#L99).

This means connection upgrading fails for requests that specify the correct header.

**Comment by garyburd** [comment]
Please provide information on how to reproduce the bug.  The code as written should be case insensitive.

**Comment by euforia** [comment]
@pjvds - i've tested with both `WebSocket` and `Websocket` and they both work.

**Comment by garyburd** [comment]
Please reopen if you can provide information on how to reproduce the issue.
