### ISSUE TITLE
How to check if a connection was closed without error?

### ISSUE THREAD

**Issue by mprobst** [gorilla/websocket#104]
I have code to gobble up client pings. When a client "goes away", `ReadMessage` returns an `error`. How do I properly check if the error is a normal condition (tab reload/close, navigate away, explicit ws.close()) as opposed to an error condition (connection failure, incorrect protocol, SSL issue, etc)?

I currently cast the returned `error` to `*websocket.CloseError`, but that seems rather ugly.

```go
_, _, err := ws.ReadMessage()
if ce, ok := err.(*websocket.CloseError); ok {
	switch ce.Code {
	case websocket.CloseNormalClosure,
		websocket.CloseGoingAway,
		websocket.CloseNoStatusReceived:
		s.env.Statusf("Web socket closed by client: %s", err)
		return
	}
}
```

**Comment by garyburd** [comment]
That's the best way to check for those specific close codes. What does your code do for other errors?

**Comment by mprobst** [comment]
It fails with an error, i.e. logs it so I can track how often something
goes wrong with web sockets. I want to keep track of failures and be
alerted, i.e. discern between successfully, normally closed connections and
connections that were closed as a result of some error.

Gary Burd <notifications@github.com> schrieb am Di., 5. Jan. 2016 um
16:20 Uhr:

**Comment by garyburd** [comment]
The application must test for specific close codes.  It might be useful to add  a helper function:

      func IsCloseError(err error, code ...int) bool

**Comment by mprobst** [comment]
@garyburd what I'm specifically looking for is a way to discern a connection failing vs a connection being closed in an expected way. Comparable to reading a file and receiving an error because the hard disk is on fire vs. just receiving the expected `EOF` at the end of the file. Does that make sense?

I think most code using this package will need to handle that and make the distinction, maybe a function  `IsExpectedCloseError(err error)` or `IsSuccessfulCloseError(err error)`, **not** taking `code`s but rather implying what is successful and what isn't.

**Comment by garyburd** [comment]
Most applications do not call [`close()`](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#close()) on the client or only call `close()` in response to a connection error.  These applications do not need to distinguish the errors listed in the issue from a network error. 

If you want to check for the case where the client explicitly called `close()`, then use one of the following tests depending on how the client calls close: 

     if e, ok :=  err.(*websocket.CloseError); ok && 
                 (e.Code == websocket.CloseNormalClosure ||
                 e.Code == websocket.CloseNoStatusReceived) {

     if e, ok :=  err.(*websocket.CloseError); ok && e.Code == websocket.CloseNormalClosure {

     if e, ok :=  err.(*websocket.CloseError); ok && e.Code == websocket.CloseNoStatusReceived {

I don't know of a scenario where it's important distinguish `&CloseError{Code: CloseGoingAway}` from a network error. For both of these errors, the connection is closed outside the control of the client application.

**Comment by garyburd** [comment]
I added IsCloseError in a2d85bcbfc8bbfed695b4f3c5b57e8b89911a727.

I will not add IsExpectedCloseError(err error) or IsSuccessfulCloseError(err error) because what is expected or successful can depend on the application.

**Comment by mprobst** [comment]
@garyburd makes sense, though I think many apps would share my definition of it. Thanks!
