### ISSUE TITLE
How to scale up?

### ISSUE THREAD

**Issue by nguyenthenguyen** [gorilla/websocket#105]
The Node.JS version of socket.io has a concept of a store, to keep track of connections: this allows it to work in a load-balanced setup. How do implements on multiple nodes like:
http://socket.io/docs/using-multiple-nodes/#passing-events-between-nodes

**Comment by garyburd** [comment]
This package is an implementation of the websocket protocol.  Load balancing is outside the scope of this package.

Socket.io is a realtime application framework that uses the websocket protocol as a transport. I do not know of a similar framework for Go.  If somebody else reading this knows of such a framework, please leave a comment.

**Comment by navneetk** [comment]
I am using https://github.com/googollee/go-socket.io for Go Socket.io server
