### ISSUE TITLE
Using Proxy On Dialer?

### ISSUE THREAD

**Issue by whatisgravity** [gorilla/websocket#107]
Can someone please provide an example of using the Proxy option inside the Dialer?

**Comment by whatisgravity** [comment]
I found the following in the issues

    d := websocket.Dialer{
           NetDial: func(network, addr string) (net.Conn, error) {
               return new.Dial(network, proxyHostPort)
          } 
    }


but I get the following error:

    missing ',' before newline in composite literal

**Comment by whatisgravity** [comment]
Should be, but still having trouble getting the actual proxy to work. Would appreciate any guidance as I'm new to golang and the gorilla websocket library.

d := websocket.Dialer{
       NetDial: func(network, addr string) (net.Conn, error) {
           return new.Dial(network, proxyHostPort)
      } ,
}

**Comment by garyburd** [comment]
Here's an simple example showing how to use the proxy option:

     var dialer = websocket.Dialer{
         Proxy: http.ProxyFromEnvironment,
     }

**Comment by whatisgravity** [comment]
I was able to get it working for my purposes perfectly but by overriding/overloading (not sure right term) the Dial function.

How would one generate a http.ProxyFromEnvironment? What goes in that field or how do you set the Proxy to that variable?

**Comment by garyburd** [comment]
The function [http.ProxyFromEnvironment](https://godoc.org/net/http#ProxyFromEnvironment) is in the standard net/http package.

Assign the function to the field as shown in my previous post.

**Comment by whatisgravity** [comment]
I'm sorry, I still do not understand, I read that part of the docs over and over and even looked at the code.

I see that ProxyFromEnvironment takes a req Request as a variable, what I don't understand I guess is how to translate my proxy which is a string "ipaddress:port" into a req. Is there any way to explain it in a simpler way?

With overriding the Dial is was a bit more straight forward, I just had to pass in a function that returned a new Dial. In your example you are just straight calling that method of http, which I'm not understanding how the proxy ever gets assigned. 

Thank you for your patience.

**Comment by garyburd** [comment]
The request argument to the application specified proxy function is the websocket handshake request. The return value from the proxy function is the address of the proxy to use for that request or nil if no proxy should be used.

The function http.ProxyFromEnvironment uses environment variable settings to find the address of the proxy server.

If all requests should use the fixed address "ipaddres:port", then the proxy function can ignore the request argument and return that fixed address.  The [http.ProxyURL](https://godoc.org/net/http#ProxyURL) function supports this common scenario:

     var d = websocket.Dialer{
         Proxy: http.ProxyURL(&url.URL{
              Scheme: "http", // or "https" depending on your proxy
              Host: "ipaddress:port" ,
              Path: "/",
        }
     }

**Comment by whatisgravity** [comment]
Thank you, that makes perfect sense. I really appreciate your patience with explaining it. Thanks for working on this library.
