### ISSUE TITLE
Conn.WriteMessage reports no error after the receiving server has gone down

### ISSUE THREAD

**Issue by urandom** [gorilla/websocket#108]
Hi,

I did a small test to see whether I could replay a message that hasn't been sent correctly (like for instance if the target server is down, or the network is down). So I basically used the echo server as a target and another app that sends sequential data to it. If I stop the echo server before the Nth data has been sent, the next call (at sometimes the one after that) to WriteMessage will not return an error. To the client, it will look like the data was sent successfully. In that case, currently it doesn't look like there's any way to preserve the last payload before sometime goes wrong in hopes to repeat it.

**Comment by garyburd** [comment]
WriteMessage returns the status of writing the data to the TCP transport in the kernel. A successful return does not indicate that the peer has received the data.

**Comment by urandom** [comment]
So how would one know whether the data has been successfully transmitted?

**Comment by garyburd** [comment]
The only way to know whether data has been successfully received by a peer application is for the peer application to send an acknowledgement.
