### ISSUE TITLE
"dial tcp: unknown port tcp/90p;\" on 14.04.1-Ubuntu

### ISSUE THREAD

**Issue by alanywlee** [gorilla/websocket#112]
Dear Sirs,

I used gorilla wobsocket client working perfectly on windows 7, But the same code was not working on ubuntu 14.04.1. It always returned "dial tcp: unknown port tcp/90p;\"  when I called websocket.DefaultDialer.Dial(). Does anyone has the same problem just like I encountered?

My code is very simple like following:

-----------------------------------------
func connect() {
scheme := "ws"
host := "10.16.3.51:8888"
    u := url.URL{Scheme: scheme, Host: host, Path: "/worker/ws/"}
    fmt.Printf("attempt connecting to %s", u.String())

    c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
    if err != nil {
        fmt.Printf("connection failed: %s", id, err)
        return
    }
    defer c.Close()
...
}

-----------------------------------------
Have a nice day

Alan

**Comment by garyburd** [comment]
Run the code using a new empty dialer. If that fixes the problem, then [check your proxy environment variables](https://godoc.org/net/http#ProxyFromEnvironment).

      d := websocket.Dialer{}
      c, _, err := d.Dial(u.String(), nil)
      if err != nil {
        fmt.Printf("connection failed: %s", id, err)
        return
    }
    defer c.Close()

**Comment by alanywlee** [comment]
Dear Gary,

Thanks a lots for your help. Your instruction indeed fixed my problem,
I don't really know why my connection has "SSL port not allowed" error 
when I tried to connect near end "ws://10.1.2.34:8888 "

error message is as following:

--------------------------------
Proxy Error ( The specified Secure Sockets Layer (SSL) port is not allowed.
Forefront TMG is not configured to allow SSL requests from this port.
Most Web browsers use port 443 for SSL requests.  )

--------------------------------

But I am wondering does it make sense to design a try catch mechanism to connect 
as try DefaultDialer first, and in case of proxy error catched, using Dialer to try again?

Have a nice day

Alan

**Comment by garyburd** [comment]
The client tries to CONNECT through your HTTP proxy, but that proxy does not support CONNECT.  There are a couple options:

- modify the proxy environment variables so the application dials directly to the server.
- ignore the proxy environment variables by using websocket.Dialer() instead of websocket.DefaultDialer.
