### ISSUE TITLE
added "Sec-WebSocket-Protocol" header in js , got error code 1006

### ISSUE THREAD

**Issue by zombiecong** [gorilla/websocket#114]
I add "Sec-WebSocket-Protocol" header  in  js code , like : 

`conn = new WebSocket("ws://{{$}}/ws","token");`

in go code ,  my code is 
``` 
protocols := websocket.Subprotocols(r)
fmt.Println(protocols)
```
and I got it  in server , like 
`[token]`

 but the conn closed with error : 

`2016/03/02 01:18:13 error: websocket: close 1006 (abnormal closure): unexpected EOF`

**Comment by garyburd** [comment]
There's not enough information here to act on. Please show more code.

**Comment by zombiecong** [comment]
I  used the chat demo ,  https://github.com/gorilla/websocket/tree/master/examples/chat

I changed "serveWs" function , in the server

```
func serveWs(w http.ResponseWriter, r *http.Request) {
	ws, err := upgrader.Upgrade(w, r, nil)
	protocols := websocket.Subprotocols(r)//  +
	fmt.Println(protocols) // +

	if err != nil {
		log.Println(err)
		return
	}

	c := &connection{send: make(chan []byte, 256), ws: ws}
	h.register <- c
	go c.writePump()
	c.readPump()
}
```

i changed the the client  in home.html 

`
conn = new WebSocket("ws://{{$}}/ws","token");//   added token
`

**Comment by zombiecong** [comment]
no error in the client , just showed `Connection closed.` in  the page.

the server showed the error 
`2016/03/02 01:18:13 error: websocket: close 1006 (abnormal closure): unexpected EOF`

**Comment by garyburd** [comment]
Please show the code you use to initialize the upgrader.

**Comment by garyburd** [comment]
The server application must negotiate a subprotocol by either setting the upgrader [Subprotocols field](https://godoc.org/github.com/gorilla/websocket#Upgrader.Subprotocols) or by passing the subprotocol header to the Upgrade method.

**Comment by zombiecong** [comment]
i want to  pass a variable to the server using the subprotocol ,  so  I can not specify the protocol  :( .

**Comment by garyburd** [comment]
Use the query string to pass arbitrary values to the server.

**Comment by zombiecong** [comment]
I provide  a service which everyone can connect my websocket server .   if  someone passes the subprotocol header ,  it will cause the error .   so  I  think  you should fix it  ,at least show the message like `the  subprotocol  not supports` , not  `2016/03/02 01:18:13 error: websocket: close 1006 (abnormal closure): unexpected EOF`   

:smiley:

**Comment by garyburd** [comment]
Your client closes the connection because the server application does not support a subprotocol requested by the client application. The server reads on the closed connection and returns the error indicating read on a closed connection.

I don't know how to improve this difficult to debug scenario. The Upgrade method should not fail with an error in this situation because the RFC allows for the server application to respond without a negotiated subprotocol.
