### ISSUE TITLE
Return errors without writing to the socket on behalf of the caller

### ISSUE THREAD

**Issue by brianmario** [gorilla/websocket#115]
While searching for usable websocket libraries for go, I recently started playing with this one as it seemed to be the most mature and give me the most low-level control over the socket while still being easy.

I noticed in my testing that in some cases this library will send a close message to the client, _then_ return an error to me. I need to have *full* control of what is sent over the websocket and would love if this library just returned an error back to me so _I_ could decide what to do next. I realize in some cases (protocol errors and such) sending a close message is likely the best action but I still need control over when that happens.

I would have just opened a pull request but wanted to open this for discussion in case it was an intentional design decision that would need more thought.

I haven't scoured the rest of the source to see if this is happening anywhere else but to reiterate, what I'd prefer is: After the initial websocket initialization, nothing is sent or received over the websocket unless I (the caller) did so explicitly.

Thoughts?

**Comment by garyburd** [comment]
The only writes that you cannot control are the [close frames sent on protocol error](https://github.com/gorilla/websocket/blob/master/conn.go#L759). Overriding these writes requires a new setting and possibly a new error type to describe protocol errors.

I am generally opposed to adding features that will be used by one application. Please explain how this feature might generally be useful.

**Comment by brianmario** [comment]
> The only writes that you cannot control are the close frames sent on protocol error.

But why have _any_ writes that are out of the callers control? It's impossible as a websocket library author to anticipate what the client or server-side is or isn't expecting to be sent/received over the wire, so why blindly do so in a way that the binding application has no control over?

> Overriding these writes requires a new setting and possibly a new error type to describe protocol errors.

I would have just expected an error type that wrapped a string similar to what is in the `CloseError` [mapping](https://github.com/gorilla/websocket/blob/master/conn.go#L101-L135). Maybe something like:

```go
var (
	ProtocolError      = fmt.Errorf("protocol error")
	MessageTooBigError = fmt.Errorf("message too big")
)
```

Which I could then turn around and use (if I wanted) as the error message in the `CloseMessage` control packet. In my case, I'd be mapping those errors to different messages or in some cases no message at all and just an empty close packet.

> I am generally opposed to adding features that will be used by one application. Please explain how this feature might generally be useful.

Fair enough, but to flip this on its head - while I understand it can be useful to handle these things automatically to make the library easier to use - I'd argue that sending error packets automatically in some cases and not others leads to more confusion than it's attempting to help.

While having this behavior be baked in by default could make sense for some very early adopters, allowing finer-grained control over how and when the socket is written to would be hugely beneficial for more sophisticated applications. Especially in cases where existing infrastructure is being replaced and replicating the existing architecture is a requirement - including when and what is sent in `CloseMessage` packets.

---

All that said, feel free to close this if you don't think it would be useful for the users of this library. I'm fine running my own fork if it comes to that.

I really appreciate the work you've put into this library. As I said it seems to be the most mature and offer the most flexibility. This relatively small change is all I'd need to start using it for my application.

**Comment by garyburd** [comment]
The connection also echos received close frames outside the application's control.

> But why have any writes that are out of the callers control? 

The connection sends close frames on behalf the application because it simplifies the application code.  This has not been a problem for applications (including sophisticated applications) because close frames are only sent where allowed or required by the websocket protocol.

> I'd argue that sending error packets automatically in some cases and not others leads to more confusion than it's attempting to help.

The connection *always* sends required close frames before returning a read error to the application. Applications should only send close frames when application level logic determines that the connection should be closed.

Can you describe in more detail the close frames that you need to control? Is it's the echoed close frame or is it one of the errors sent in response to a protocol error?

The default ping handler sends a pong. You can disable the default pongs by [setting the ping handler](https://godoc.org/github.com/gorilla/websocket#Conn.SetPingHandler).

**Comment by brianmario** [comment]
> The connection sends close frames on behalf the application because it simplifies the application code. 

This seems like an intentional design decision that I've been unable to convince you away from :)

For what it's worth, I don't think it's unreasonable to let the application decide what to do in the event of error.

Thanks for your feedback, I'll just fork this project or write my own.
