### ISSUE TITLE
Cannot run server.go 

### ISSUE THREAD

**Issue by harryCM** [gorilla/websocket#118]
Hi, I download the code and installation (via github) went smoothly. I built a simple hello-world app in Go and it runs ok. Bur I could not run server.go, got the following error message:

go run: cannot run non-main package

ps: I run from a directory pulled from Github as follows:

../src/github.com/gorilla/websocket

Please help. Thanks!

Harry

**Comment by garyburd** [comment]
The file server.go is part of the websocket package. The file is not runnable.

If you are new to Go, I suggest taking the [tour](https://tour.golang.org/basics/1).
