### ISSUE TITLE
problem with node ws client connect w/ ssl/tls

### ISSUE THREAD

**Issue by mistercorea** [gorilla/websocket#120]
I am trying to connect to chat program with node client(https://www.npmjs.com/package/ws)

I am getting an error message 
`Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1061:38)
    at emitNone (events.js:80:13)
    at TLSSocket.emit (events.js:179:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)`

But with same client when I connect to 'wss://echo.websocket.org/' it works.

I am not sure why it wont verify the first certificate.

My server is using port 8800 and initialize the server i am used code below.
`http.HandleFunc("/", serveHome)
http.HandleFunc("/ws", serveWs)
err := http.ListenAndServeTLS(*addr, "cert.pem", "key.pem",nil)`

It works when I use the chrome to connect to web socket server.

**Comment by garyburd** [comment]
This package does not handle the TLS handshake.  The issue is with the certificate, the node client or the net/http package (or packages called by the net/http package).

**Comment by mistercorea** [comment]
So is that mean I have problem with net/http package and needs to handle
TLS handshake before websocket connection?

**Comment by garyburd** [comment]
The server created by http.ListenAndServeTLS handles the TLS handshake for websocket connections. The server completes the handshake before an application request handler.
