### ISSUE TITLE
how to use with goji

### ISSUE THREAD

**Issue by fmpwizard** [gorilla/websocket#121]
Hi,

I tried the chat sample on its own and works great, but then I tried to port it to my app that uses goji and the pat router and now the ws connections gives me:

`WebSocket connection to 'ws://192.168.1.10:9000/ws' failed: Connection closed before receiving a handshake response`

and the handler `serveWs` is never called (I added a log.Println as the first line inside serveWs and it is not printed)

on main.go I tried:

```
	m.HandleFuncC(
		pat.Get("/ws"),
		srv.WithDataAuth(ws.ServeWs),
	)
```
and

```
	m.HandleFuncC(
		pat.New("/ws"),
		srv.WithDataAuth(ws.ServeWs),
	)
```

both give me the same result, none call my handlers.

Any help would be great.

Thanks

**Comment by garyburd** [comment]
Because the websocket handler is not called, the issue is outside the scope of this package. 

I cannot help you with goji and the pat router. I only know these projects by name.

**Comment by fmpwizard** [comment]
just in case anyone else runs into this, the issue was that I had browsersync between my go app and the browser and that causes the websocket connection to fail.

https://github.com/BrowserSync/browser-sync/issues/780

Thank you.
