### ISSUE TITLE
Implementation 

### ISSUE THREAD

**Issue by mehdigmira** [gorilla/websocket#122]
Hey,

I'm just discovering your library. And i need some explanations on how it is implemented:
Is ReadMessage implemented using go channels (it seems like the easiest way to deal with concurrency).
If so, why isn't their a way to use it as a channel and do something like this ?
```
for {
select{
    case <-conn1.readMessage():
        do smth
    case <-conn2.ReadMessage():
        do smth else
}
}
```
Otherwise I'd have to launch a coroutine to handle every connection, which seems a little bit awkward

**Comment by garyburd** [comment]
> Is ReadMessage implemented using go channels

ReadMessage blocks until a message is available or there's an error. The method does not run a goroutine to pump messages to a channel.

> Otherwise I'd have to launch a coroutine to handle every connection, which seems a little bit awkward

It is common for Go networking applications to run one or two goroutines to manage a network connection. See the [chat](https://github.com/gorilla/websocket/tree/master/examples/chat) and [command](https://github.com/gorilla/websocket/tree/master/examples/command) applications for examples.

**Comment by mehdigmira** [comment]
Thanks for the reply. I know that ReadMessage blocks, but what kind of blocking is that ? Is is the same as when somethings blocks on a channel (which is gracefully handled by go without using any extra thread), or is it a syscall you're making, and thus forcing go to use an extra thread ?

**Comment by garyburd** [comment]
The package calls the [network connection](https://godoc.org/net#Conn) Read method to get data. The implementation of the Read method is responsible for blocking until data is available or there's an error.

TCP connections created by the standard net package do not create an extra thread when reading.

**Comment by mehdigmira** [comment]
Again, thanks for your time. Ok, so the net package is the one responsible
for handling sockets asynchronously and without generating extra threads.
I know this is not related to your library, but do you have any resource
about how this is achieved ? I just want to get the big picture, and i
can't see how this can be done. For me at the end, the net package still
has to use some poll/select syscall, and i don't see how this can be dealed
with without an extra thread. Unless the go scheduler was designed to
cooperate with the net package.
On Apr 13, 2016 8:38 PM, "Gary Burd" <notifications@github.com> wrote:

The package calls the network connection <https://godoc.org/net#Conn> Read
method to get data. The implementation of the Read method is responsible
for blocking until data is available or there's an error.

TCP connections created by the standard net package do not create an extra
thread when reading.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/gorilla/websocket/issues/122#issuecomment-209587839>

**Comment by garyburd** [comment]
The only resource that I know of is the source code. The netpoll*.go files listed at https://golang.org/src/runtime/ are a good place to start examining the source.

I suggest asking this question on the go-nuts mail list.
