### ISSUE TITLE
Please consider tagging releases.

### ISSUE THREAD

**Issue by onlyjob** [gorilla/websocket#131]

**Comment by garyburd** [comment]
Do you have any thoughts on how you want the releases tagged?

**Comment by onlyjob** [comment]
Usual practice with semantic versioning will do. :)

See

 * [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).
 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

Thank you.

**Comment by garyburd** [comment]
See https://github.com/gorilla/websocket/releases/tag/v1.0.0

**Comment by onlyjob** [comment]
Fantastic. :) Thank you very much. :)
