### ISSUE TITLE
Does ReadMessage() support timeout

### ISSUE THREAD

**Issue by alanywlee** [gorilla/websocket#132]
Dear Sir,

I want to terminate connection in case of no message read from remote client/server more than a timeout e.g., 60 secs. It seems conn.ReadMessage() not able to configure a timeout just like handshaketimeout does, Do I miss somthing or are there any other alternative way could do this?

Any suggestion is highly appreciated...

Alan

**Comment by garyburd** [comment]
Call set [SetReadDeadline](https://godoc.org/github.com/gorilla/websocket#Conn.SetReadDeadline) to set the deadline for all read operations including ReadMessage.
