### ISSUE TITLE
websocket/conn.go:647: c.br.Discard  PROBLEM

### ISSUE THREAD

**Issue by lexansoft** [gorilla/websocket#137]
Hi.  After your last commit the package does not compile in go1.4 anymore. It shows:

websocket/conn.go:647: c.br.Discard undefined.

It is a problem for us. We use it in Amazon AWS. And they only support go 1.4

Can you at least tag the previous version that works for 1.4? 

Thank you.

**Comment by gdamore** [comment]
Aargh.  You broke 1.3.  Now 1.4.  This is getting crazy; no thought given to breaking your downstreams.

Call me a very unhappy camper. 

I'm going to start looking back at vanilla Go websocket, to see if I can get on a more stable platform.

**Comment by ansiz** [comment]
git reset --hard 1f512fc  to version 1f512fc @lexansoft

**Comment by garyburd** [comment]
Fixed by 50d660d6ac981c9de3540279f63d163b9a690930

I apologize for the inconvenience.

**Comment by gdamore** [comment]
Thanks for fixing it. :)
