### ISSUE TITLE
How to understand the connection was silently closed?

### ISSUE THREAD

**Issue by allaud** [gorilla/websocket#138]
I found a strange server behavior when, which can be reproduced like this:

1) Connect to server via websocket
2) Switch off your wi-fi (or just plug out internet cord)
3) No disconnect callback being fired

I'm using the following code to read from client:

    func wsHandler(w http.ResponseWriter, r *http.Request) {
      ws, err := upgrader.Upgrade(w, r, nil, false)
      defer func() {
        fmt.Println("DISCONNECT")
      }()
      if err != nil {
        return
      }
      for {
        _, p, err := ws.ReadMessage()
        if err != nil {
          fmt.Println("Connection closed")
          return
        }
        onMessage(ws, p, AppState)
      }
    }

@garyburd any thoughts?

**Comment by garyburd** [comment]
To detect this situation, the application should:
- Periodically send a ping to the client.
- Read with timeout less than the ping period.

See [the chat application](https://github.com/gorilla/websocket/tree/master/examples/chat) for an example of how to do this.

**Comment by garyburd** [comment]
See https://www.joyent.com/blog/tcp-puzzlers#puzzler-2-power-off

**Comment by sunanxiang** [comment]
There is one question:
Client A, Client B and Server. Client A and Client B both  connect to Server. But after few minutes, Client A closed because of power-off or wi-fi off. At this time, Server doesn't know Client A closed and keep the Client A conn. Then I use Client B to send message to Client A(using WriteMessage() method ). Why can't i get any error? @garyburd

**Comment by garyburd** [comment]
@sunanxiang,  The reason that you do not get an error is that write to the underlying network connection is successful.  See my answer above for how to handle this situation.

**Comment by sunanxiang** [comment]
@garyburd , got it, thx~
