### ISSUE TITLE
newConn not released memory

### ISSUE THREAD

**Issue by liutaihua** [gorilla/websocket#141]
thanks thanks for the amazing this library!
my server found memory leak.  i check the goroutine num count, it release after connection closed, but the memory increament as long as time.
go tool pprof:
      flat  flat%   sum%        cum   cum%
 1794.89MB 53.24% 53.24%  1811.39MB 53.73%  github.com/gorilla/websocket.newConn
  611.52MB 18.14% 71.38%   645.59MB 19.15%  main.NewChannel
  115.12MB  3.42% 74.80%   115.12MB  3.42%  main.(*Bucket).Put
I will open a goroutine of newChannel(my private struct) and another goroutine of dispatch for this websocket connection.
after the frequently of  client connect and close.

go tool pprof and execute "list",  most of memory used at:
writeBuf:       make([]byte, writeBufferSize+maxFrameHeaderSize),
the websocket.Conn writeBuf.

i think the websocket.Conn object has been properly closed through conn.Close().   but with serve long time, some  conn.writeBuf not released

**Comment by garyburd** [comment]
It looks like your application is storing pointers to `websocket.Conn` values.

**Comment by liutaihua** [comment]
thank @garyburd  reply.
should be i lost some code,  there has a Closure, i guess it hold the Conn object cause the gc not work
