### ISSUE TITLE
race: limit on 8192 simultaneously alive goroutines is exceeded, dying， what's mean?

### ISSUE THREAD

**Issue by godsoul** [gorilla/websocket#142]
Hi~ i modify example/echo client.go,I use 2000 goroutine connect to example/chat server,
the server error info:

panic: concurrent write to websocket connectiongoroutine 6 [running]:github.com/gorilla/websocket.(*Conn).flushFrame(0xc8208eb300, 0xc826138a01, 0x0, 0x0, 0x0, 0x0, 0x0)        /home/godsoul/code/go/src/github.com/gorilla/websocket/conn.go:481 +0x5bagithub.com/gorilla/websocket.(*Conn).NextWriter(0xc8208eb300, 0x1, 0x0, 0x0, 0x0, 0x0)        /home/godsoul/code/go/src/github.com/gorilla/websocket/conn.go:407 +0x9bgithub.com/gorilla/websocket.(*Conn).WriteMessage(0xc8208eb300, 0x1, 0xc824f3c600, 0x27, 0x600, 0x0, 0x0)        /home/godsoul/code/go/src/github.com/gorilla/websocket/conn.go:613 +0x4fmain.(*Hub).run(0x952900)        /home/godsoul/code/go/src/gotest/im_server/room.go:82 +0x44acreated by main.main        /home/godsoul/code/go/src/gotest/im_server/main.go:30 +0x48goroutine 1 [IO wait]:net.runtime_pollWait(0x7f070e85a728, 0x72, 0xc82000a140)        /usr/local/go/src/runtime/netpoll.go:157 +0x60net.(*pollDesc).Wait(0xc8200521b0, 0x72, 0x0, 0x0)
        /data/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200521b0, 0x0, 0x0)
        /data/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820052150, 0x0, 0x7f070e85a820, 0xc824b50a80)
        /data/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002e040, 0x4519d0, 0x0, 0x0)
        /data/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82002e040, 0x0, 0x0, 0x0, 0x0)
        /data/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc82001c420, 0x7f070e85a7e8, 0xc82002e040, 0x0, 0x0)
       /data/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0x79b448, 0x5, 0x0, 0x0, 0x0, 0x0)
        /data/go/src/net/http/server.go:1967 +0x8f
main.main()
        /home/godsoul/code/go/src/gotest/im_server/main.go:33 +0xba

goroutine 878 [chan send]:
main.(*Client).readPump(0xc82138e380)
        /home/godsoul/code/go/src/gotest/im_server/conn.go:54 +0x3f1
main.serveWs(0x7f7fa75ae648, 0xc8210f3a20, 0xc820dc69a0)
        /home/godsoul/code/go/src/gotest/im_server/conn.go:106 +0x608
net/http.HandlerFunc.ServeHTTP(0x834810, 0x7f7fa75ae648, 0xc8210f3a20, 0xc820dc69a0)
        /data/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820096330, 0x7f7fa75ae648, 0xc8210f3a20, 0xc820dc69a0)
        /data/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc8200a2360, 0x7f7fa75ae648, 0xc8210f3a20, 0xc820dc69a0)
        /data/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820f6f760)
        /data/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /data/go/src/net/http/server.go:1910 +0x3f6

goroutine 606 [select]:
main.(*Client).writePump(0xc8209d50e0)
        /home/godsoul/code/go/src/gotest/im_server/conn.go:70 +0x549
created by main.serveWs
        /home/godsoul/code/go/src/gotest/im_server/conn.go:105 +0x5fa
I run  go run -race client.go,the client error info:
race: limit on 8192 simultaneously alive goroutines is exceeded

Could you help me?Thanks a lot

**Comment by garyburd** [comment]
Show your modified code.

**Comment by garyburd** [comment]
Your application is writing concurrently to a connection.  [Concurrent writes are not supported](https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency).  Use a [mutex](https://godoc.org/sync#Mutex) or a goroutine to ensure that there's no more than one writer at a time.
