### ISSUE TITLE
feture talk: client connection pool

### ISSUE THREAD

**Issue by imiskolee** [gorilla/websocket#143]
its supported client connection pool ?

**Comment by garyburd** [comment]
The package does not support a client connection pool.  What is the problem you are trying to solve?

**Comment by imiskolee** [comment]
i want desgin a http api sender to send message to websocket server.

**Comment by garyburd** [comment]
How will a pool of connections help with this problem?

**Comment by garyburd** [comment]
Closing because insufficient information to understand feature.
