### ISSUE TITLE
How to.. user to user chat?

### ISSUE THREAD

**Issue by Fruchtgummi** [gorilla/websocket#144]
How to.. user to user chat? at their example:

https://github.com/gorilla/websocket/tree/master/examples/chat

**Comment by garyburd** [comment]
I am closing this issue because it's a question about application design and not an issue with the package.

**Comment by iwanbk** [comment]
```
I am closing this issue because it's a question about application design
```
@garyburd maybe you should add link to this mailing list https://groups.google.com/forum/#!forum/gorilla-web?

**Comment by garyburd** [comment]
@iwanbk I'll add the link to the README.  

I will add that the core design of a chat service should be independent of the transport used to send and receive data with a client (WebSocket, HTTP with hanging GET, MQTT, ...).
