### ISSUE TITLE
Api Reference Url in not worling

### ISSUE THREAD

**Issue by Ankur-Jat** [gorilla/websocket#145]
The url you provide for API Reference is not working and my browser, safari, is saying that this url has been blocked.

**Comment by garyburd** [comment]
Please report the problem accessing the API reference on godoc.org on their issue tracker at https://github.com/golang/gddo/issues.

You can view the API reference locally by running these commands:

    go get github.com/gorilla/websockeet
    godoc github.com/gorilla/websocket
