### ISSUE TITLE
How to authentication client connection

### ISSUE THREAD

**Issue by godsoul** [gorilla/websocket#151]
Hi～ This websocket package how to authentication client connection？

**Comment by iwanbk** [comment]
you need to create it by yourself.

example : after connected, client need to send username & password which need to be checked by server. If not match, close the connection

**Comment by garyburd** [comment]
I recommend authenticating the upgrade handshake using the application's code for authenticating HTTP requests. 

I am closing this issue because authentication is outside the scope of this package.
