### ISSUE TITLE
is this map access safe?

### ISSUE THREAD

**Issue by softaria** [gorilla/websocket#153]
Hello,

Just to be sure.

File conn.go  Line 217

func isValidReceivedCloseCode(code int) bool {
	return validReceivedCloseCodes[code] || (code >= 3000 && code <= 4999)
}

This method is not thread safe as it uses maps (Quote: "This was not an easy decision, however, since it means uncontrolled map access can crash the program." from here https://golang.org/doc/faq#atomic_maps )

Are you sure it is not called concurrently?
Please check.

**Comment by elithrar** [comment]
The map isn't being mutated (at all), so that advice does not apply.
