### ISSUE TITLE
Can't clone or compile on Linux subsystem for Windows

### ISSUE THREAD

**Issue by marcelgdotcom** [gorilla/websocket#154]
`go get` gives out this output:

`# github.com/gorilla/websocket
../github.com/gorilla/websocket/client.go:361:32: error: reference to undefined field or method ‘GetCertificate’
   GetCertificate:           cfg.GetCertificate,
                                ^
../github.com/gorilla/websocket/client.go:370:32: error: reference to undefined field or method ‘ClientSessionCache’
   ClientSessionCache:       cfg.ClientSessionCache,
                                ^
../github.com/gorilla/websocket/client.go:373:32: error: reference to undefined field or method ‘CurvePreferences’
   CurvePreferences:         cfg.CurvePreferences,
                                ^
../github.com/gorilla/websocket/client.go:361:3: error: unknown field ‘GetCertificate’ in ‘tls.Config’
   GetCertificate:           cfg.GetCertificate,
   ^`

Running the latest Ubuntu packages and Go version. I cloned the repro from Windows and it builds fine on it, but building from Bash results in the same output at compile time.
Go version: `go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64`

I realize this is most likely caused by this Linux subsystem, but thought you should be aware and I'm listening to any suggestion you might have.

**Comment by garyburd** [comment]
Install Go 1.4 or later.
