### ISSUE TITLE
How to solve webSockets protocol violation in android autobahn

### ISSUE THREAD

**Issue by AditMicrosys1** [gorilla/websocket#155]
In my android application I want to use the autobahn library to use web sockets.
I have done server side code using spring.
Simple socket is working when i am try pub sub then i get error.

My Code :-

final String wsuri = "ws://localhost:8080/ws";
try {
    mConnection.connect(wsuri, new Wamp.ConnectionHandler() 
        @Override
        public void onOpen() {
            Log.d(TAG, "Status: Connected to " + wsuri);
            mConnection.subscribe("ws://localhost:8080/ws/onetoone",
                MyEvent1.class, new Wamp.EventHandler() {
                    @Override
                    public void onEvent(String topicUri, Object event) {
                        Log.d(TAG, "Status: Connected to " + event);
                    }
                });
    }
    @Override
    public void onClose(int code, String reason) {
        Log.d(TAG, "Connection lost." + " " + reason);
    }
 });
} catch (Exception e) {
        Log.d(TAG, e.toString());
}
 

OutOut :-

de.tavendo.autobahn.WebSocketConnection: created
de.tavendo.autobahn.WebSocketReader: created
de.tavendo.autobahn.WampReader: created
de.tavendo.autobahn.WampConnection: reader created and started
de.tavendo.autobahn.WebSocketWriter: created
de.tavendo.autobahn.WampWriter: created
de.tavendo.autobahn.WampConnection: writer created and started
de.tavendo.autobahn.WebSocketReader: running
de.tavendo.autobahn.WebSocketReader: run() : WebSocketException 
(de.tavendo.autobahn.WebSocketException: RSV != 0 and no extension negotiated)
de.tavendo.autobahn.WebSocketReader: ended
de.tavendo.autobahn.WebSocketConnection: opening handshake received
Status: Connected to ws://localhost:8080/Spring4WebSocket/add
de.tavendo.autobahn.WebSocketConnection: fail connection [code = 4, reason = WebSockets protocol violation
de.tavendo.autobahn.WebSocketReader: quit
de.tavendo.autobahn.WebSocketConnection: waiting for reader to finish
de.tavendo.autobahn.WebSocketConnection: readr thread done
de.tavendo.autobahn.WebSocketConnection: sending close message over socket
de.tavendo.autobahn.WebSocketWriter: ended
de.tavendo.autobahn.WebSocketConnection: waiting for writer to finish
de.tavendo.autobahn.WebSocketConnection: writer thread done
Connection lost. WebSockets protocol violation
 

I have pass ip address place on local host(my PC ip address).

Any have solution for how to solve web Sockets protocol violation in android autobahn.

Please help for above problem.

**Comment by garyburd** [comment]
Did you post this to the wrong issue tracker.  This is not the issue tracker for Spring or Autobahn.
