### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by spaceblock** [gorilla/websocket#156]
After update:

DEBUG: 2016/08/26 20:48:49 connecting to  ws://127.0.0.1:8001/ws/
DEBUG: 2016/08/26 20:48:49 dial:dial tcp 127.0.0.1:8001: getsockopt: connection refused

?

**Comment by garyburd** [comment]
There's not much to add beyond what the error message says: the server refused the connection,

**Comment by spaceblock** [comment]
Oh, sorry
