### ISSUE TITLE
wss client sample

### ISSUE THREAD

**Issue by GuyBrand** [gorilla/websocket#158]
Hi .

We are trying to create a secure WS with self signed certificates .
Taken the chat sample changed home.html to use wss and it works.
BUT
When a GO client (already working without tls) , and are getting various results from x509: certificate signed by unknown authority if skipverify = false to tls: oversized record received with length 20527 when its true  .
sample client (with commented code of some of the trial and error) , server , html and cert creator (from tls package) is attached .
 
[chat1.zip](https://github.com/gorilla/websocket/files/465536/chat1.zip)

Thanks,
   Guy .

**Comment by elithrar** [comment]
Can you post the relevant code here instead of a zip file?

**Comment by GuyBrand** [comment]
You mean as files or inline?

**Comment by elithrar** [comment]
Inline, or a gist, or a repo. Minimal is best - something I can run without
having to configure is better.

**Comment by GuyBrand** [comment]
uploaded to git :
https://github.com/GuyBrand/WssSample
Although in 3 folders, very minimal :

Sample repo for using golang wss with gorilla websocket
genCrt - midified copy of tls/generate_cert.go to create local ssl certificate
server - modified copy of the gorilla/websocket chat sample, working with https
client - a gorilla/websocket go client using https , with some tweaks comment out for several attempts

**Comment by garyburd** [comment]
Is the error on [this line](https://github.com/GuyBrand/WssSample/blob/92b40168972b5013dc6d641fbc16107532a84b19/goClient/goClient.go#L56)?

**Comment by GuyBrand** [comment]
Yes .

**Comment by garyburd** [comment]
The issue is with the call to [tls.Dial](https://github.com/GuyBrand/WssSample/blob/92b40168972b5013dc6d641fbc16107532a84b19/goClient/goClient.go#L56) or [http.ListenAndServeTLS](https://github.com/GuyBrand/WssSample/blob/92b40168972b5013dc6d641fbc16107532a84b19/server/main.go#L45).  These calls are made before any code in the websocket package is executed.

**Comment by GuyBrand** [comment]
Well,
Another thing I tried was talking this:
https://github.com/nareix/tls-example
Implementing on both server side and client side.

In this case, tls.dial passes, but the newclient prob gets the handshake
error

**Comment by GuyBrand** [comment]
The error is : oversized record received with length 20527 .

 

But I think the question is a little broader,

We can probably trial and error until we get it working , or at least look like it (does - InsecureSkipVerify: true acount for “working” when security is considered ?)

Assuming we are in a world that switches all services to ssl , 

Can you give an example of how to create a gorilla/websocket server and gorilla websocket client running on top of ssl certificate ?

 

Thanks .

**Comment by elithrar** [comment]
> The error is : oversized record received with length 20527 .

This means the server is responding with a plain HTTP response, and not a
TLS response. Your server does not serve over TLS:
https://github.com/GuyBrand/WssSample/blob/master/server/main.go#L49

This needs to be ListenAndServeTLS - and be provided with a server-side
cert to serve.

**Comment by GuyBrand** [comment]
The code actually goes through :

if _, err := os.Stat("./algo.crt");err==nil{

So the server runs ListenAndServeTLS

**Comment by elithrar** [comment]
Are you sure? Does it actually load the cert?

**Comment by GuyBrand** [comment]
Yes , if you see the line :

fmt.Println("file ", "algo.crt found switching to https")

 

it prints on the console .

**Comment by garyburd** [comment]
> Can you give an example of how to create a gorilla/websocket server and gorilla websocket client running on top of ssl certificate ?


The package has a [test for dialing TLS connections](
https://github.com/gorilla/websocket/blob/2d1e4548da234d9cb742cc3628556fef86aafbac/client_server_test.go#L230-L253).  It's not written as an example, but it might be helpful to you. The TLS listener for this test is [created in the net/http/httptest package](https://github.com/golang/go/blob/dfc56a4cd313c9c5de37f4fadb14912286edc42f/src/net/http/httptest/server.go#L107-L132).

**Comment by GuyBrand** [comment]
I’ve seen the tester , but it looks like both server and client are loading the certificates in the same manner, this is not the way it will happen on a client-server operation (theoretically I wish for the client to not have a certificate , but if not other option , I am willing to install public-private couples) .

**Comment by GuyBrand** [comment]
Just did that again, I’m either getting 

 

x509: certificate signed by unknown authority

 

or 

x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "serial:240832071503402080516336044108555611205")

 

depending on the cert I’m using .

 

added another folder “perTest" to the repo , with two options, with the above error , including certs

**Comment by garyburd** [comment]
Here's how to modify the echo example to use a self-signed cert:

Generate cert with:

    go run `go list -f {{.Dir}} crypto/tls`/generate_cert.go  --rsa-bits 1024 --host 127.0.0.1,::1,localhost --ca --start-date "Jan 1 00:00:00 1970" --duration=1000000h

Change [server](https://github.com/gorilla/websocket/blob/2d1e4548da234d9cb742cc3628556fef86aafbac/examples/echo/server.go#L53) to call:

	log.Fatal(http.ListenAndServeTLS(*addr, "cert.pem", "key.pem", nil))

Change [client](https://github.com/gorilla/websocket/blob/2d1e4548da234d9cb742cc3628556fef86aafbac/examples/echo/client.go#L32) to use dialer configured with root cert:

	roots := x509.NewCertPool()
	ok := roots.AppendCertsFromPEM(rootPEM)
	if !ok {
		log.Fatal("failed to parse root certificate")
	}
	d := websocket.Dialer{TLSClientConfig: &tls.Config{RootCAs: roots}}
	c, _, err := d.Dial(u.String(), nil)

**Comment by GuyBrand** [comment]
This was a good lead , its working with some changes , when We finalise it , I can upload to this ticket , or you can use it as a sample .

 

Thanks !
