### ISSUE TITLE
Add an option to disable compression at the server side

### ISSUE THREAD

**Issue by rotemdan** [gorilla/websocket#160]
My application sends large amounts of pre-encrypted binary data, which is not compressible, from the websocket server. There is no benefit to attempt compressing the frames in this case, resulting in a significant waste of CPU cycles and reduction in throughput. Is it possible to disable compression entirely? or even per frame?

Just a very, very rough solution idea (may be bad). Perhaps add an additional method of the form:

```go
func (c *Conn) NextWriterUncompressed(messageType int)
```
or perhaps alternatively provide an API to modify the currently inaccessible field [enableWriteCompression](https://github.com/gorilla/websocket/blob/master/conn.go#L252) during construction, or later as well?

**Comment by garyburd** [comment]
Compression the compression feature is incomplete and not enabled. See https://github.com/gorilla/websocket/commit/a87eae1d6ff562bf944755f4a6f527b6ef6fb888 for the work remaining.

**Comment by rotemdan** [comment]
By observing the code I somehow got the impression it was already implemented/enabled since in [line 439 in conn.go](https://github.com/gorilla/websocket/blob/master/conn.go#L439) it does actually check for it and in [line 297](https://github.com/gorilla/websocket/blob/master/conn.go#L297) the switch is set to `true`. I see now there's the possibility that [`newCompressionWriter`](https://github.com/gorilla/websocket/blob/master/conn.go#L254) may not be assigned at all, so I guess that may explain it.

I think the `EnableWriteCompression()` suggested/planned  method looks reasonable so I will close this. Thanks for working on this.
