### ISSUE TITLE
Upgrade request with same origin and host gets rejected

### ISSUE THREAD

**Issue by markwongsk** [gorilla/websocket#162]
Using Tyrus' implementation of the Java API for Websockets, the upgrade request created automatically appends headers of the following form:
```
Host: localhost:13000
Origin: localhost:13000
```
This doesn't pass the `checkSameOrigin` check in `server.go` because `url.Parse` returns something without a `Host` (It probably thinks localhost is the scheme). Could an additional check be performed if the request host is equal to the url before parsing? For example `r.Host == origin[0]`

**Comment by garyburd** [comment]
The RFC's state the client must specify the schome.  Your application can work around this issue with the client by supplying a [CheckOrigin}(https://godoc.org/github.com/gorilla/websocket#hdr-Origin_Considerations) function.

**Comment by garyburd** [comment]
To avoid possible security issues, I do not want to relax the same origin check.  There is a workaround for the application.
