### ISSUE TITLE
 Could not decode a text frame as UTF-8.

### ISSUE THREAD

**Issue by EverChris** [gorilla/websocket#168]
help!!!

I used the example but chrome said:

`(index):22 WebSocket connection to 'ws://localhost:8080/echo' failed: Could not decode a text frame as UTF-8.`

How to solve this problem?

**Comment by FZambia** [comment]
@EverChris have you modified example in some way? Do you mean [this](https://github.com/gorilla/websocket/tree/master/examples/echo) example? Which version of Chrome?

**Comment by EverChris** [comment]
@FZambia 

yes, but it's not gorilla's problem.

I send some unicode data, and websocket doesn't support this, then I convert unicode  to utf8, it works.

**Comment by garyburd** [comment]
Text messages are interpreted as UTF-8 encoded text ([doc](https://godoc.org/github.com/gorilla/websocket#hdr-Data_Messages)).  Convert from whatever encoding you have to UTF-8 before sending.
