### ISSUE TITLE
Chrome cannot connect (via jquery AJAX)

### ISSUE THREAD

**Issue by dtromb** [gorilla/websocket#174]
When using jquey AJAX to connect to a websockets service, I receive the error message:

`Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

Conn.Upgrade() returns an object and no error in the second argument.   Connections work fine in firefox.  (Messages are received out of order in FF, but I'm 99% that's on the client side, as I watched the network stream!)

FF is dev edtion 45.3.0 and Chrome is 

`Google Chrome  54.0.2840.59 (Official Build) (64-bit)
Revision    5b2f167ccdaed3f1a90ec1084715fbb91b8d25b0-refs/branch-heads/2840@{#726}
OS  Linux 
JavaScript  V8 5.4.500.31`

**Comment by dtromb** [comment]
The browser request is:

`Hypertext Transfer Protocol
    GET /x/ HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): GET /x/ HTTP/1.1\r\n]
        Request Method: GET
        Request URI: /x/
        Request Version: HTTP/1.1
    Host: www.test01.com:8080\r\n
    Connection: Upgrade\r\n
    Pragma: no-cache\r\n
    Cache-Control: no-cache\r\n
    Upgrade: websocket\r\n
    Origin: http://www.test01.com:8080\r\n
    Sec-WebSocket-Version: 13\r\n
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36\r\n
    Accept-Encoding: gzip, deflate, sdch\r\n
    Accept-Language: en-US,en;q=0.8\r\n
    Cookie: _wg_tiny_session=wrqdwonkog\r\n
        Cookie pair: _wg_tiny_session=wrqdwonkog
    Sec-WebSocket-Key: 1NXvj2meYEVq1k9/0I10hA==\r\n
    Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n
    Sec-WebSocket-Protocol: wg-tiny-v1\r\n
    \r\n`


And the gorllia/websockets response, generated with:
`	s.wsImpl = &ws.Upgrader{
			HandshakeTimeout: time.Duration(5)*time.Second,
			ReadBufferSize: 4096,
			WriteBufferSize: 4096,
			Subprotocols: []string{"wg-tiny-v1"},
			Error: func(rw http.ResponseWriter, req *http.Request, status int, reason error) {
				s.ServeErrorPage(rw, req, status, reason.Error())
			},
			EnableCompression: false,
	}
  ....
        conn, err := s.wsImpl.Upgrade(rw, req, rw.Header())
`

is: 

`    HTTP/1.1 101 Switching Protocols\r\n
        [Expert Info (Chat/Sequence): HTTP/1.1 101 Switching Protocols\r\n]
        Request Version: HTTP/1.1
        Status Code: 101
        Response Phrase: Switching Protocols
    Upgrade: websocket\r\n
    Connection: Upgrade\r\n
    Sec-WebSocket-Accept: Wwy/Dx7cR/OiTOm9eBQwrdhxId4=\r\n
    \r\n
`

**Comment by garyburd** [comment]
Yes, there should be a Sec-WebSocket-Protocol in the response header. If it's easy, please share the client side code that I can use to produce the problem.

**Comment by garyburd** [comment]
I tried to reproduce this issue with the following edits to the [chat example](https://github.com/gorilla/websocket/tree/master/examples/chat):

```
--- a/examples/chat/client.go
+++ b/examples/chat/client.go
@@ -35,6 +35,7 @@ var (
 var upgrader = websocket.Upgrader{
        ReadBufferSize:  1024,
        WriteBufferSize: 1024,
+       Subprotocols:    []string{"wg-tiny-v1"},
 }

 // Client is an middleman between the websocket connection and the hub.
diff --git a/examples/chat/home.html b/examples/chat/home.html
index 7262918..a689332 100644
--- a/examples/chat/home.html
+++ b/examples/chat/home.html
@@ -29,7 +29,7 @@ window.onload = function () {
     };

     if (window["WebSocket"]) {
-        conn = new WebSocket("ws://{{$}}/ws");
+        conn = new WebSocket("ws://{{$}}/ws", ["wg-tiny-v1"]);
         conn.onclose = function (evt) {
             var item = document.createElement("div");
             item.innerHTML = "<b>Connection closed.</b>";
```

The code works correctly with Chrome 54.0.2840.71.  

Please share any info that might help me reproduce the issue.

**Comment by garyburd** [comment]
I don't have enough information to reproduce this issue.
