### ISSUE TITLE
Avoid auto-responding to a close-frame

### ISSUE THREAD

**Issue by KiranRG** [gorilla/websocket#178]
See #177 for more context.

The gorilla-websocket layer auto-responds to a close-frame (ref: https://github.com/gorilla/websocket/blob/master/conn.go#L801) -- when it should probably simply return an error (as part of the read) to the application indicating that a close-frame was seen, and leave it to the application to respond with a close-frame, when it deems appropriate.

Being a general purpose websocket-layer, it should, as far as possible, avoid enforcing "policy".

**Comment by KiranRG** [comment]
(From #177)

Here's our scenario -- we have built a "buffering"/streaming layer atop the websocket, that supports WriteMsg, Flush, ReadMsg. WriteMsg would buffer messages internally until the buffer is full, at which point it would call Flush. Flush (which can be called by the application any time too), will flush out all buffered messages after serializing them into a single "payload" for websocket. ReadMsg reads a payload, deserializes them and returns one message at a time from the buffer, until it is empty, at which time it reads another payload from the wire. Pretty standard buffering mechanism.

Because the websocket layer is automatically responding with a close-frame, the server does not get an opportunity to flush out any messages that it has currently buffered (from previous WriteMsgs calls that have not been flushed).

Ideally, the client should be able to send a close-frame (indicating intent to go away), in response to which our server would flush out any buffered messages, and send a close-frame back before closing the connection. But this cannot be implemented due to the automatic close-frame -- our tail of buffered messages are lost!

While it is great that the gorilla-websocket provides the ability to send a custom close-frame, I think auto-responding internally with a close-frame is forcing policy on the application. It should leave it to the application to choose on when to respond back with a close-frame.

**Comment by garyburd** [comment]
Fixed by 9fbf129ff2a3cf2467f7d0021de2eb4d3aecc109.
