### ISSUE TITLE
TLS handshake hangs and blocks forever

### ISSUE THREAD

**Issue by dannin** [gorilla/websocket#179]
Hi, I logged the following bug against golang.
Not sure if this is actually a symptom from gorilla websocket:
https://github.com/golang/go/issues/17708

**Comment by garyburd** [comment]
Please provide more information. Show the Dialer that you are using.  What software is running on the server?  Can you connect to the server with a different client (a browser for example)?

**Comment by dannin** [comment]
Basically it looks like this:
d := websocket.Dialer{
		ReadBufferSize:  1024,
		WriteBufferSize: 1024,
		NetDial: func(network, addr string) (net.Conn, error) {
			const timeout = 30 * time.Second
			return net.DialTimeout(network, serverAddr, timeout)
		},
		TLSClientConfig: tlsConfig,
	}

	ws, _, err = d.Dial(u.String(), wsHeaders)

**Comment by dannin** [comment]
It also works most of the time.  Just when the server goes down intermittenly or theres dns resolution error, sometimes around that time it hangs

**Comment by dannin** [comment]
@garyburd Any idea.  Does that look right? I return a net.Conn with a timeout via the NetDial
