### ISSUE TITLE
Needing to monitor Conn.closeSent

### ISSUE THREAD

**Issue by chessweb01** [gorilla/websocket#180]
In order to avoid writing to a websocket that was terminated by the client (e.g. browser has been closed) which causes my program to panic, I need to monitor the closeSent field which is set to true when that happens. The solution that is actually working for me, and the only one I could come up with, was to rename closeSent to CloseSent in the conn.go source. With that change the field is exported and accessible via ws.CloseSent (ws is the websocket instance in question). 

However, changing the gorilla/websocket source to solve this problem is unsatisfactory, to say the least. Isn't there a better way?

**Comment by garyburd** [comment]
Show the code that panics.

**Comment by chessweb01** [comment]
for client_id, c := range h.matchingCons[pM] {
		if c.ws.CloseSent {    // this is the fix
			delete(h.matchingCons[pM], client_id)
			continue
		}
		select {
		case c.send <- pM:   //  panics if c.ws is closed
                ...

I hope the snippet is sufficient.

**Comment by garyburd** [comment]
The `closeSent` flag indicates that a close frame was sent, not the the connection was closed.

Because read on the connection can set `closeSent`, the code in the snippet has a data race. Test for error value  [ErrCloseSent](https://godoc.org/github.com/gorilla/websocket#ErrCloseSent) on write operations to determine if close was sent previous to the write.

**Comment by chessweb01** [comment]
I understand, but what I don't see is how to test for the error value where I need it, namely right before the c.send <- pM.

**Comment by garyburd** [comment]
The line panics because the application closed the channel `c.send`.  Remove `c` from `h.matchingCons` before closing the channel or add a flag to `c` to keep track of when the application has closed the channel.
