### ISSUE TITLE
Reduce GC on send and receive

### ISSUE THREAD

**Issue by jgupta** [gorilla/websocket#183]
We connected 20 clients and broadcasted 2Mbps stream (using compression) to each. It appears that about 40% of CPU time is spent on GC. SetGCPercent to 1000 improved about 10% performance.

It may be noted that uncompressed stream might be as high as 200Mbps which is distributed to 20 clients (total 4Gbps data).

It appears that most of GC is happening at ReadMessage and NextWriter functions of conn.go.

**Comment by dcelasun** [comment]
I don't see any significant improvements for `NextWriter`, but for `ReadMessage` we could introduce a new method `ReadMessageInto` additionally also takes a `*bytes.Buffer` supplied by the user, so it can be reused. `ReadMessage` would still be kept around for backwards compatibility.

@garyburd What do you think? I'd like to send a PR if this sounds good.

**Comment by garyburd** [comment]
An application can read to a buffer using the current API:

     mt, r, err := c.NextMessage()
     if err != nil {
         // handle error
    }
    buf.Reset()
    _, err := buf.ReadFrom(r)
    if err != nil {
        // handle error
    }

**Comment by dcelasun** [comment]
Ah yes, silly me. I'll remove my comment.

**Comment by garyburd** [comment]
@jgupta Profile your program and report back where the time / memory is spent.

**Comment by jgupta** [comment]
I am finding it difficult to exactly trace cause and give you useful information. Will it be beneficial if I send a test server and client that reproduce this problem?

**Comment by garyburd** [comment]
Run a [memory profile](https://blog.golang.org/profiling-go-programs) and share the results here.

**Comment by garyburd** [comment]
Open a new issue if you find specific issue with the package.
