### ISSUE TITLE
Unknown opcode -1

### ISSUE THREAD

**Issue by herkyl** [gorilla/websocket#184]
One of my users is getting this error:
```
Websocket connection to URL failed: Could not decode a text frame as utf-8
```

It happens after a while after being connected and successfully receiving/sending frames. When I look at the WS frames the last frame before the disconnection is:
```
Unknown opcode -1
```

This is the first I've seen this error, even though the app is used by millions of users. Do you have any ideas what could cause an `opcode -1` and how could I replicate & test it?

**Comment by garyburd** [comment]
The server application sent invalid UTF-8 encoding as a text message.  It's the [application's responsibility to ensure that text messages are valid UTF-8](https://godoc.org/github.com/gorilla/websocket#hdr-Data_Messages).   The application can use the [utf8](https://godoc.org/unicode/utf8) package to check for valid encodings.

**Comment by garyburd** [comment]
Please clarify what you mean when you say that the last frame before disconnect is `Unknown opcode -1`?   Is that part of an error returned from the package, displayed in a log somewhere or something else?

**Comment by herkyl** [comment]
@garyburd I saw that when inspecting the frames tab under network in Chrome. Now I am not 100% sure if this was what it said character to character, I currently cannot replicate the issue.

Regarding the UTF-8 problem I have tried bombing the server with different non UTF-8 messages and haven't got this issue. Do you have any suggestions of how I should go about sending the non utf-8 message and what the content should be.

**Comment by garyburd** [comment]
Here's an example showing how to write a message with invalid UTF-8 encoding:

       c.WriteMessage(weboscket.TextMessage, []byte{ 0xc3, 0xb1 })

The byte sequence 0xc3, 0xb1 is not allowed in UTF-8.
