### ISSUE TITLE
Compression optional per message

### ISSUE THREAD

**Issue by jgupta** [gorilla/websocket#187]
I do see https://github.com/gorilla/websocket/issues/160 and [Line 440 of conn.go](https://github.com/gorilla/websocket/blob/master/conn.go#L440).

Will it be good to add an optional argument to function NextWriter that controls if the following message will be compressed? For our application, it would be easier to have such control over the message in place of repeatedly enabling/disabling compression for every connected client.

**Comment by garyburd** [comment]
Go does not have optional arguments. Adding an argument will break existing applications. 

Write a function to setup the connection the way you want and use this function throughout your application:

    func nextWriter(c *websocket.Conn, compress bool) (io.WriteCloser, error) {
        c.SetWriteDeadline(time.Now().Add(writeTimeout))
        c.EnableWriteCompression(compress)
        return c.NextWriter(websockt.TextMessage)
    }

**Comment by jgupta** [comment]
Thank you. It was very helpful.
