### ISSUE TITLE
issues ->  incorrect mask flag what*s wrong?

### ISSUE THREAD

**Issue by zuojinmin** [gorilla/websocket#188]
if mask != c.isServer {
		Println("mark ===errr", mask, "c isever", c.isServer)
		return noFrame, c.handleProtocolError("incorrect mask flag")
	}

what means c.isServer? i don*t understand?plz.
help

**Comment by garyburd** [comment]
The field `isServer` is [set to true](https://github.com/gorilla/websocket/blob/e8f0f8aaa98dfb6586cbdf2978d511e3199a960a/server.go#L175) when the connection is on the server.

The error indicates that the client did not set the frame-masked header bit to 1 as [required by the protocol](https://tools.ietf.org/html/rfc6455#section-5.3).
