### ISSUE TITLE
flate.Writer never closed?

### ISSUE THREAD

**Issue by johnwchadwick** [gorilla/websocket#190]
Hello,

I have not confirmed the existence of a memory leak, but I am slightly concerned about [this bit of code](https://github.com/gorilla/websocket/blob/master/compression.go#L75):
```go
func (w *flateWrapper) Close() error {
	err1 := w.fw.Flush()
	if w.tw.p != [4]byte{0, 0, 0xff, 0xff} {
		return errors.New("websocket: internal error, unexpected bytes at end of flate stream")
	}
	err2 := w.tw.w.Close()
	if err1 != nil {
		return err1
	}
	return err2
}
```

Maybe I have the wrong idea, but wouldn't it be semantically necessary to also do `w.fw.Close()`? I do not think it currently matters, because I don't see a whole lot interesting going on in the `Close()` method, looking at `deflate.go`. But certainly that could change in the future.

**Comment by garyburd** [comment]
The requirement to close the writer was removed in https://github.com/golang/go/commit/07acc02a29ac74e7c0b08b4cd382bf71acd262dd. It's unlikely that the requirement will be reintroduced.
