### ISSUE TITLE
Intergrated with fasthttp, I came with the

### ISSUE THREAD

**Issue by likezjuisee** [gorilla/websocket#191]
![image](https://cloud.githubusercontent.com/assets/12730220/20909392/67f76132-bb96-11e6-8a65-eaa34886e851.png)

**Comment by likezjuisee** [comment]
![image](https://cloud.githubusercontent.com/assets/12730220/20909410/8ae306b0-bb96-11e6-94a1-24f161b9e22e.png)

**Comment by garyburd** [comment]
This package does not support fasthttp.

**Comment by kataras** [comment]
@likezjuisee Take a look at [https://github.com/iris-contrib/websocket]

**Comment by kataras** [comment]
@likezjuisee Take a look at [here](https://github.com/iris-contrib/websocket)...
