### ISSUE TITLE
substantial GC overhead with per message deflate compression

### ISSUE THREAD

**Issue by y3llowcake** [gorilla/websocket#193]
I'm noticing a large spikes in heap allocs and GC time when message write volume is high.
My profiles lead me towards flate.NewWriter() in compressNoContextTakeover().

I believe this is causing an allocation of a new sliding window (32k?) for each compressed write. This seems avoidable if the writers are recycled via flate.Writer.Reset().

Probably should be statically allocating the flate writer per connection and also provide an option to get flate writers from a sync.pool.

**Comment by garyburd** [comment]
Start by using a sync.Pool for flate writers and see how that works. I want to avoid adding new knobs in the API.

**Comment by y3llowcake** [comment]
https://github.com/gorilla/websocket/pull/194

**Comment by y3llowcake** [comment]
readers: https://github.com/gorilla/websocket/pull/195

**Comment by garyburd** [comment]
Fixed by 2db2f66488d0a378f61644175cfb19a41a48fef6 and 3ab3a8b8831546bd18fd182c20687ca853b2bb13.
