### ISSUE TITLE
Tag minor releases

### ISSUE THREAD

**Issue by mklimuk** [gorilla/websocket#197]
Hello,

As the v1.0.0 tag on the master branch is quite far away (40 commits), could you please issue a minor version tag on a more recent commit that we could consider stable? I didn't follow all recent development but for example connection CloseHandler is not available on v1.0.0.
It would be useful for all the folks using semantic versioning with tools like glide etc.

Thanks a lot and keep up the good work!
Michal

**Comment by garyburd** [comment]
https://github.com/gorilla/websocket/releases/tag/v1.1.0
