### ISSUE TITLE
How to Implement WSS or how to insecure client request

### ISSUE THREAD

**Issue by PaulB2Code** [gorilla/websocket#198]
Dear Gorilla Team, 

We are working to implement websocket with your amazing driver. But we are facing an issue.. We do not arrive to implement wss...

We do no find any example on the web using a simple wss server/client. 

Do you have anything to help us. 

Thank for your time. 

P

**Comment by garyburd** [comment]
To serve the wss protocol, listen with  [http.ListenAndServeTLS](https://godoc.org/net/http#ListenAndServeTLS) instead of http.ListenAndServe. 

To connect to a wss server, dial with a "wss://" URL.

**Comment by PaulB2Code** [comment]
An other post help to do it. 

https://github.com/gorilla/websocket/issues/158

Thanks anyway.
