### ISSUE TITLE
Gorilla websocket with google app engine

### ISSUE THREAD

**Issue by dheerajsarwaiya** [gorilla/websocket#200]
I am getting following error when I am running "goapp serve myapp/" from Myproject folder inside src.

go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/gorilla/websocket/client.go from GOPATH

my file structure is some something like this
```
$GOPATH/src
|-github.com/gorilla/websocket
|-MyProject
   |-myapp
      |-app.yaml
      |-mainApp.go (which contain init function and part of app package)
```

Is there a safe version of gorilla websocket code for google app engine? 
mine original post was here : 
http://stackoverflow.com/questions/41412317/gorilla-websocket-with-google-app-engine

**Comment by andela-hkoske** [comment]
@dheerajsarwaiya  how did you get gorilla web sockets to work with Google App Engine?

**Comment by dheerajsarwaiya** [comment]
@andela-hkoske - I didnt use web sockets in Google App Engine Standard Environment. Instead I used Google FireBase Database to achieve the same results. 
let me know if you have more question.
