### ISSUE TITLE
how do i write the client js code in chrome

### ISSUE THREAD

**Issue by eruca** [gorilla/websocket#201]
gorilla/websocket have implement the compression,but I look around not found any js client code when i want use compression to communicate with server

```js
let ws = new WebSocket(url)
```
any configure to make it?

**Comment by garyburd** [comment]
Chrome sends the extension header `permessage-deflate; client_max_window_bits` by default. I don't know how to configure what Chrome sends. I suggest asking on a Chrome specific forum.
