### ISSUE TITLE
Chat Readme.md example doesn't work

### ISSUE THREAD

**Issue by qarth** [gorilla/websocket#204]
The readme states go run *.go and it produces the following errors.

root@DESKTOP-UB21P28 MINGW64 /c/users/root/gogo/src/github.com/gorilla/websocket/examples/chat (master)
$ go run *.go
# command-line-arguments
.\conn.go:16: writeWait redeclared in this block
        previous declaration at .\client.go:18
.\conn.go:19: pongWait redeclared in this block
        previous declaration at .\client.go:21
.\conn.go:22: pingPeriod redeclared in this block
        previous declaration at .\client.go:24
.\conn.go:25: maxMessageSize redeclared in this block
        previous declaration at .\client.go:27
.\conn.go:31: upgrader redeclared in this block
        previous declaration at .\client.go:38
.\conn.go:45: undefined: h in h.unregister
.\conn.go:59: undefined: h in h.broadcast
.\conn.go:95: serveWs redeclared in this block
        previous declaration at .\client.go:121
.\conn.go:102: undefined: h in h.register
.\main.go:37: too many arguments in call to serveWs
.\main.go:37: too many errors

**Comment by garyburd** [comment]
The instructions assume that the directory contains the example files only. The file conn.go is not part of the example.  Move conn.go out of the directory or run `go run client.go	hub.go main.go`.
