### ISSUE TITLE
When server closes connection, client is not notified

### ISSUE THREAD

**Issue by RobertGrantEllis** [gorilla/websocket#206]
When the server sends a control message like the below, the (connected) client either (a) does not receive it, or (b) receives it but takes no action (I would expect it to close the connection and/or fire CloseHandler()). In my case, both client and server are implemented using the gorilla websocket library.

I tried working around this using the SetCloseHandler method on the client connection, but that handler never actually fires, even when the server sends the close control message.

So, the result is that, when the server is trying to gracefully go down and disconnect clients, those clients have no idea that they were in fact disconnected.

```go
	err = c.connection.WriteControl(
		gorilla.CloseMessage,
		gorilla.FormatCloseMessage(1001, "server is shutting down"),
		time.Now().Add(1000 * time.Millisecond),
	)

	if err != nil {
		fmt.Println(err.Error())
	}
```

**Comment by garyburd** [comment]
The package returns an error form [NextReader](https://godoc.org/github.com/gorilla/websocket#Conn.NextReader) and [ReadMessage](https://godoc.org/github.com/gorilla/websocket#Conn.ReadMessage) when a close message is received. Is the client reading the connection?

**Comment by RobertGrantEllis** [comment]
In my case, no, the client is not reading. Upon first connection, the client expects the server to send one message with critical information (which it reads), and from then on, the only activity on the websocket is that the client writes data to the server. So, the problem is that, for whatever reason, writes to the server actually succeed from the client's perspective (e.g. after connection.WriteMessage(), error is nil). The server, of course, never gets those messages because it closed the connection at its end. But, this is a problem because the client just keeps sending messages, but they are just going into a black hole.

**Comment by RobertGrantEllis** [comment]
I could hack around this by pulling nextreader on a regular basis (or by writing custom ping handler and pong handler methods), but honestly that is suboptimal since it is happening on a fixed interval as opposed to being event-driven.

**Comment by garyburd** [comment]
The application must read the connection to receive control messages. See end of the [control message](https://godoc.org/github.com/gorilla/websocket#hdr-Control_Messages) section for more information.

**Comment by RobertGrantEllis** [comment]
got it, thanks @garyburd !
