### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by terrylai** [gorilla/websocket#209]
Hello,

Could I add basic authentication to web socket? If yes, how? Is there any example?

BR,
Terry

**Comment by garyburd** [comment]
On the server, call the [request's BasicAuth method](https://godoc.org/net/http#Request.BasicAuth) method to get the username and password.

On the client, create and send the [authorization header](https://tools.ietf.org/html/rfc2617#section-2) as follows:

     h := http.Header{"Authorization", {"Basic " +  base64.StdEncoding.EncodeToString([]byte(username + ":" + password)))
     c, resp, err := dialer.Dial(url, h)
