### ISSUE TITLE
How to send json with websocket？

### ISSUE THREAD

**Issue by haroldTlan** [gorilla/websocket#217]
I am using websocket to send json to client.
like: `{"Type":2,"User":"tom","Timestamp":1487552782,"Content":"haha"}`

But there is always strings:
`data: "{"Type":2,"User":"tom","Timestamp":1487552782,"Content":"haha"}↵"`

Server：
```
if err = ws.WriteJSON(resMap); err != nil {  
                fmt.Println(err)  
                ws.Close()  
                break  
            } 
```
Client:
```
MessageEvent {ports: Array[0], data: "{"Type":2,"User":"tom","Timestamp":1487552782,"Content":"haha"}↵", source: null, lastEventId: "", origin: "ws://192.168.2.86:8500"…}
bubbles: false
cancelBubble: false
cancelable: false
clipboardData: undefined
currentTarget: WebSocket
data: "{"Type":2,"User":"tom","Timestamp":1487552782,"Content":"haha"}↵"
defaultPrevented: false
eventPhase: 0
lastEventId: ""
origin: "ws://192.168.2.86:8500"
ports: Array[0]
returnValue: true
source: null
srcElement: WebSocket
target: WebSocket
timeStamp: 1487552805303
type: "message"
__proto__: MessageEvent
```

**Comment by garyburd** [comment]
The server application is sending the JSON value correctly.  The client application is responsible for [parsing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) the [message event](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent) data.

**Comment by haroldTlan** [comment]
@garyburd So there is no way to be json directly?
Thank you very much. 
I just do not want to use JSON.parse in client.
Anyway, thanks.

**Comment by garyburd** [comment]
As far as I know, the application is responsible for parsing the data.  I suggest asking questions about writing applications in the browser on StackOverflow or other forums where there are experts on that topic.

**Comment by elithrar** [comment]
You must use JSON.parse in the browser to get from bytes ("strings" as
represented) to a JavaScript object ("JSON").
