### ISSUE TITLE
conn.WriteJson() panic: concurrent write to websocket connection 

### ISSUE THREAD

**Issue by AnotherGoogleFan** [gorilla/websocket#218]
While using conn.WriteJosn() I got panic: concurrent write to websocket connection.
I know that this can be easily solved by mutex.
But when I read the source code I found in conn struct there is a mu
    mu            chan bool // used as mutex to protect write to conn
and it works so well in conn.Write.
I wonder why not use it in WriteJson() method.
If do so, such problem won't happen at all.

**Comment by elithrar** [comment]
You shouldn't be writing to the connection concurrently.

What does your code that triggers this look like?

**Comment by kync** [comment]
"Applications are responsible for ensuring that no more than one goroutine calls the write methods concurrently and that no more than one goroutine calls the read methods concurrently."

**Comment by garyburd** [comment]
The channel enables concurrent [frame](https://tools.ietf.org/html/rfc6455#section-5) writers.  There is no synchronization in the package for concurrent message writers.
