### ISSUE TITLE
can't compatible Sec-WebSocket-Protocol header in js

### ISSUE THREAD

**Issue by chukuang2004** [gorilla/websocket#219]
connect server in js like this:
new WebSocket("ws://" + document.location.host + "/msg","12345");

server close connect with error:
websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by garyburd** [comment]
The error indicates that the client closed the connection. 

The likely problem is that the server application does not support the "12345" subprotocol.  Either add "12345" to the [upgraders subprotocols](https://godoc.org/github.com/gorilla/websocket#Upgrader.Subprotocols) or remove "12345" from the requested subprotocols.
