### ISSUE TITLE
[suggest] add Conn method，for websocket proxy to websocket

### ISSUE THREAD

**Issue by myml** [gorilla/websocket#220]
add Conn method at websocket.Conn，for websocket proxy to websocket.
like this
go io.copy(ws1.Conn(),ws2.Conn())
io.copy(ws2.Conn(),ws1.Conn())

**Comment by garyburd** [comment]
https://godoc.org/github.com/gorilla/websocket#Conn.UnderlyingConn

**Comment by myml** [comment]
thank
