### ISSUE TITLE
Disable Nigle algorithm with Gorilla Websockets

### ISSUE THREAD

**Issue by dearcj** [gorilla/websocket#221]
Hi

How can I disable Nigel Algorithm when using gorilla websockets?

Thanks

**Comment by elithrar** [comment]
The Nagel algorithm can be disabled via your operating systems' TCP stack, not in an application.

**Comment by garyburd** [comment]
Nagle's algorithm is disabled by default for TCP connections. See https://golang.org/pkg/net/#TCPConn.SetNoDelay for the details.
