### ISSUE TITLE
Any Idea to improve GC?

### ISSUE THREAD

**Issue by yushengery** [gorilla/websocket#223]
Greetings, 
I am deploying the websocket service for about 70K concurrent users, however, I find the GC cause too much STW,  which reached up to 2 seconds
Then I pprof the program, the most malloc comes from net/http.newBufioReader  net/http.newBufioWriteSize and the net/http.(*conn).hijackLocked,  I found that the hijack breaks the put to the  buffer pool when a connection ended, besides, the hijacked connection has to malloc a pair of new read/write buf,  is there any way to improve this ?
Best Regards.

**Comment by elithrar** [comment]
@yushengery What version of Go are you running?

**Comment by yushengery** [comment]
@elithrar thanks for you reply
I tried both go 1.7.5 and go 1.8
they come out the same result.

**Comment by syhlion** [comment]
I have some issue

**Comment by yushengery** [comment]
@zcdj1987 
All the users are long connection, however there are not so many messages in short time , only about 1 msg / per 10 seconds.
The rss will reach up to be 7GB at most when the server keeps running for one day, thus this can easily tigger OOM...

**Comment by garyburd** [comment]
> I found that the hijack breaks the put to the buffer pool when a connection ended

Because the net/http package returns a new bufio.ReadWriter from the hijack method, the package can pool the original bufio.Reader and bufio.Writer.  This is an issue for the net/http package.

> the hijacked connection has to malloc a pair of new read/write buf, is there any way to improve this ?  

Yes, the upgrade method should attempt to use the slices from the bufio.ReadWriter returned from the hijack method.

**Comment by garyburd** [comment]
My previous comment is not correct. The bufio.Reader is returned from hijack and is therefore not pooled on connection end.

**Comment by garyburd** [comment]
Change 286b5c93713fa86d2782b66fd22e54a3d0f630a7 reuses the reader returned from hijack.  To take advantage of this feature, set Upgrader.ReadBufferSize to 0.

**Comment by garyburd** [comment]
Fixed by b258b4fadb573ac412f187b9f31974ea99d32f50 and 286b5c93713fa86d2782b66fd22e54a3d0f630a7.

Set Upgrader.ReadBufferSize and Upgrader.WriteBufferSize to zero to reuse the buffers allocated by the net/http server.
