### ISSUE TITLE
Does draft-ietf-hybi-websocket-multiplexing in planning? Or other similar features?

### ISSUE THREAD

**Issue by vegertar** [gorilla/websocket#224]
Multiplexing is a very cool feature, HTTP/2 already has a built-in support. However, HTTP/1.1 is still the most wide-spread web protocol, websocket with multiplexing is still a big blank on high performance real-time transport.
How do you think about websocket-multiplexing? Is it a big deal for solving parallel transports?

**Comment by garyburd** [comment]
There are no plans to implement this feature until one or more of the major browsers adds support for the feature.
