### ISSUE TITLE
Linux/Arm : type *tls.Config has no field or method Clone, but does have tls.clone

### ISSUE THREAD

**Issue by bioshock** [gorilla/websocket#225]
i am on a raspberry pi 3. trying to get websocket package . and getting the error below 

go version:   go version go1.8 linux/arm 

**go get github.com/gorilla/websocket**

`github.com/gorilla/websocket
../gopath/src/github.com/gorilla/websocket/client_clone.go:15: cfg.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)`

**Comment by garyburd** [comment]
The [*tls.Config Clone](https://godoc.org/crypto/tls#Config.Clone) method is included in Go 1.8.  I suspect something's wrong with your local configuration.

**Comment by bioshock** [comment]
got it working. reinstalled on a fresh system.
