### ISSUE TITLE
First write to closed connection fails silently

### ISSUE THREAD

**Issue by grepory** [gorilla/websocket#226]
If you attempt to write to a closed connection with WriteMessage, the call to WriteMessage fails silently. I haven't yet tracked down the issue entirely, but wanted to go ahead and file to see if someone might be able to help or point out something I'm doing wrong:

https://gist.github.com/grepory/6a0f3a44ffa7faa8d75a833c6d385f3d

This appears to be affecting the HEAD of master.

I realize that I'm not cleanly closing the connection with a control message, but that's on purpose.

It would be ideal if, like ReadMessage, WriteMessage/NextWriter would return an error.

Sorry for the very long example in the gist, but it seemed useful.

Let me know if I can help in any way.

**Comment by garyburd** [comment]
WriteMessage does not return an error in this scenario because the write to the underlying network connection does not return an error. 

To fix the problem, read the the websocket connection [as mentioned in the documentation](https://godoc.org/github.com/gorilla/websocket#hdr-Control_Messages).  This program works as you expect:

	conn, _, _ := websocket.DefaultDialer.Dial("ws://localhost:10080", nil)
	<-done

	go func(c *websocket.Conn) {
		for {
			if _, _, err := c.NextReader(); err != nil {
				c.Close()
				break
			}
		}
	}(conn)

	time.Sleep(1 * time.Second)
	err := conn.WriteMessage(websocket.BinaryMessage, []byte("message"))
	if err != nil {
		fmt.Printf("first write failed: %s\n", err.Error())  // prints failure message
	}

**Comment by grepory** [comment]
Yeah. That's... sort of how we're handling it right now.

I have two concurrent goroutines: 1 reading, and 1 writing. My "best effort" is to have the reading goroutine communicate to the writing goroutine so that should the reading goroutine encounter an error, the writing goroutine will stop.

It was just very strange to me that the behavior was different.

**Comment by garyburd** [comment]
Writes to the underlying network connection do not return an error in the scenario described in the issue.  This is not something that can be fixed in this package.
