### ISSUE TITLE
websocket cfg.Clone undefined

### ISSUE THREAD

**Issue by hyhlinux** [gorilla/websocket#231]
vendor/github.com/gorilla/websocket/client_clone.go:15: cfg.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)

**Comment by garyburd** [comment]
See #255.

**Comment by garyburd** [comment]
Oops, I typed the wrong issue number. 

See #225.  The [*tls.Config Clone](https://godoc.org/crypto/tls#Config.Clone) method is included in Go 1.8.  Something is wrong with your local installation of Go.
