### ISSUE TITLE
close 1006 (abnormal closure): unexpected EOF 

### ISSUE THREAD

**Issue by sAbakumoff** [gorilla/websocket#235]
I have been writing unit tests for the web-socket handler that receives DB queries, executes them and send back the results. Here is the code that is pretty similar to the test's one:

```go
package main

import (
	"net/http"
	"net/http/httptest"
	"net/url"
	"time"

	"github.com/golang/glog"
	"github.com/gorilla/websocket"
)

var upgrader = websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
	ReadBufferSize:    1024,
	WriteBufferSize:   1024,
	EnableCompression: true,
}

func sendRecv(message string, ws *websocket.Conn) (string, error) {
	if err := ws.SetWriteDeadline(time.Now().Add(time.Second)); err != nil {
		return "", err
	}
	if err := ws.WriteMessage(websocket.TextMessage, []byte(message)); err != nil {
		return "", err
	}
	if err := ws.SetReadDeadline(time.Now().Add(time.Second)); err != nil {
		return "", err
	}
	_, p, err := ws.ReadMessage()
	if err != nil {
		return "", err
	}
	return string(p), nil
}

func serveHttp(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		glog.Errorf("upgrade error %v", err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	defer conn.Close()
	for {
		messageType, message, err := conn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway) {
				glog.Errorf("app or protocol error %v", err)
			}
			break
		}
		err = conn.WriteMessage(messageType, message)
		if err != nil {
			glog.Errorf("write error %v", err)
			break
		}
	}
}

func main() {
	flag.Parse()
	server := httptest.NewServer(http.HandlerFunc(serveHttp))
	defer server.Close()

	u, _ := url.Parse(server.URL)
	u.Scheme = "ws"
	dialer := websocket.Dialer{
		ReadBufferSize:  1024,
		WriteBufferSize: 1024,
	}
	conn, _, err := dialer.Dial(u.String(), nil)
	if err != nil {
		glog.Fatalf("dialing error %v", err)
	}
	defer func() {
		if cer := conn.Close(); cer != nil {
			glog.Fatalf("%v", cer)
		}
	}()
	request := `hello socket`
	response, err := sendRecv(request, conn)
	if err != nil {
		glog.Fatalf("send request error %v", err)
	}
	glog.Errorf("response: %s", response)
}
```

Also available at https://play.golang.org/p/Z8m60nKUgM

The problem is this app produces the following output:
E0329 18:49:03.858662   76292 main.go:89] response: hello socket
E0329 18:49:03.860602   76292 main.go:52] app or protocol error websocket: close 1006 (abnormal closure): unexpected EOF

So, on one hand the request is sent and the response is received, but on the other hand the error signals about "an application or protocol error" according to https://godoc.org/github.com/gorilla/websocket#example-IsUnexpectedCloseError

I am not sure what's wrong with this code. I tried various solutions, but nothing helps. Any ideas?

**Comment by garyburd** [comment]
The client closed the connection without sending a close frame.  The server returns an error with code CloseAbnormalClosure = 1006 as specified by the Websocket RFC. 

Either add CloseAbnormalClosure to the list of expected errors or send a close frame with one of the errors the application does expect.

**Comment by sAbakumoff** [comment]
Thanks a lot, solved by adding the following code before returning from sendRecv:
```go
	closeMsg := websocket.FormatCloseMessage(0, "have a good day!")
	if err := ws.WriteMessage(websocket.CloseMessage, closeMsg); err != nil {
		return "", err
	}
```

**Comment by garyburd** [comment]
The value 0 is not a valid close code.  When the ReadMessage on server receives this invalid close frame, ReadMessage returns an error indicating the protocol error.  This error is not a CloseError (because no close frame was received) and is therefore not logged.

The change removed the noise in your log output by violating the protocol. Either add CloseAbnormalClosure to the list of expected errors or send a close frame with CloseGoingAway.
