### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ilyenkoyaroslav** [gorilla/websocket#236]
Hello, i looked through prev. issues but can not find solution. Maybe someone could help with this code:
```
    var wsMessage WsMessage
    var reader io.Reader
    var err error

    for {
        _, reader, err = c.wsConn.NextReader()
        if err != nil {
            logger.Error("101",
                zap.String("msg", err.Error()))
            break
        }
        err = json.NewDecoder(reader).Decode(&wsMessage)
        if err != nil {
            fmt.Println(err)
            continue
        }
        // handleWsMessage(c, &wsMessage)
    }
```
Recieve memory leak in this line:
`_, reader, err = c.wsConn.NextReader()`
Thanks.

**Comment by garyburd** [comment]
Please share a heap profile or any other information you have about the issue.

**Comment by ilyenkoyaroslav** [comment]
pprof: with and without debug
[heap.txt](https://github.com/gorilla/websocket/files/935825/heap.txt)
[heap2.txt](https://github.com/gorilla/websocket/files/935826/heap2.txt)

**Comment by garyburd** [comment]
I don't see anything out of the ordinary in the profile. Please describe in more detail what the problem is.

**Comment by ilyenkoyaroslav** [comment]
With high load (1000 new connections per second - connection close after 5s) 
Test code  - [https://gist.github.com/anonymous/96b007907753f223ae12d2032b013738](test code)  devours all server's memory. 
I will upload new hipe profile later.

**Comment by garyburd** [comment]
In addition to uploading a profile, please give details on why you think there's a leak in `NextReader()`.

**Comment by FZambia** [comment]
The reason is size of read and write buffers in example - 1mb, with 1000 connections memory usage will be really high, @ilyenkoyaroslav I suppose you can just use `0` for read and write buffers - you are not required to set buffer sizes equal to your `maxMessageSize` option.

**Comment by ilyenkoyaroslav** [comment]
@FZambia Hello, thanks for your reply.
Do you mean in 
```
var upgrader = websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
	ReadBufferSize:  1024 * 1024,
	WriteBufferSize: 1024 * 1024,
}
``` 
I need to use `0` instead of `1024 * 1024` ?

**Comment by FZambia** [comment]
@ilyenkoyaroslav yes

**Comment by garyburd** [comment]
@FZambia Thank you for finding the buffer size issue.

@ilyenkoyaroslav Does that fix the problem?
