### ISSUE TITLE
client_clone.go:15: cfg.Clone undefined

### ISSUE THREAD

**Issue by weihualiu** [gorilla/websocket#238]
I am execute blow code found a error.

weihualiudeMacBook-Pro:logcollect weihualiu$ go get github.com/gorilla/websocket
# github.com/gorilla/websocket
src/github.com/gorilla/websocket/client_clone.go:15: cfg.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
weihualiudeMacBook-Pro:logcollect weihualiu$ go version
go version go1.8 darwin/amd64
weihualiudeMacBook-Pro:logcollect weihualiu$

**Comment by elithrar** [comment]
You need to run Go 1.8 or later.

**Comment by weihualiu** [comment]
i am use  go version go1.8 darwin/amd64

**Comment by elithrar** [comment]
Sorry, I missed that. You shouldn't run into this then. What does `go env` show?

**Comment by garyburd** [comment]
The Clone method is [defined in Go 1.8](https://github.com/golang/go/blob/18fb670e5ee038ab681562a6b018da516f6a6f9f/api/go1.8.txt#L37).   Something is wrong with your local installation of Go.

**Comment by weihualiu** [comment]
weihualiudeMacBook-Pro:logcollect weihualiu$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/weihualiu/workspace/project/work/logcollect/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z0/p4_2z1p952l6cl6m233q1_8w0000gn/T/go-build604874342=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
weihualiudeMacBook-Pro:logcollect weihualiu$ pwd
/Users/weihualiu/workspace/project/work/logcollect
weihualiudeMacBook-Pro:logcollect weihualiu$

**Comment by weihualiu** [comment]
oh, i find this.

weihualiudeMacBook-Pro:logcollect weihualiu$ brew uninstall golang
Uninstalling /usr/local/Cellar/go/1.8... (7,017 files, 281.6MB)
go 1.7.3 is still installed.
Remove all versions with `brew uninstall --force go`.
