### ISSUE TITLE
Hitting race condition using -race in my build of my project

### ISSUE THREAD

**Issue by davidrenne** [gorilla/websocket#239]
Writer:

https://github.com/gorilla/websocket/blob/master/conn.go#L1071

Reader:
https://github.com/gorilla/websocket/blob/master/conn.go#L903

These are colliding in how I am using websocket in goroutines in my application.

I am fixing race conditions in my app and I thought you should know about this before I fork your project just to fix this one thing that needs a RW Mutex of some kind.

Thank you!

ok bak to finding my own Race conditions that I have cleared a bunch in my app in my code that is bad

**Comment by garyburd** [comment]
Per discussion in private email, the application does not need to set the close handler.

**Comment by davidrenne** [comment]
Gary's excellent answer for our problem if anyone Googles and finds this same issue

```
The documentation for SetCloseHandler says:

The connection read methods return a CloseError when a close frame is received. Most applications should handle close messages as part of their normal error handling. Applications should only set a close handler when the application must perform some action before sending a close frame back to the peer.

The application is handling close errors as part of it's normal error handling here: https://github.com/DanielRenne/GoCore/blob/e45f7995dd5bdc9a9949a2e721ad877f0cfe5e05/core/app/app.go#L156.
I didn't see a reason why the application needs to deleteWebSocket(wsConn) before sending a close frame.

The remedy is to delete all of this code: code: https://github.com/DanielRenne/GoCore/blob/e45f7995dd5bdc9a9949a2e721ad877f0cfe5e05/core/app/app.go#L163-L168

It's not needed and causes a race.
```
