### ISSUE TITLE
tow errors when i run example "echo"

### ISSUE THREAD

**Issue by dingconggithub** [gorilla/websocket#240]
i down load the zip and unzip files, but when i run the server.go in example echo, there are two errors:
..\..\client_clone_legacy.go:24: unknown tls.Config field 'GetCertificate' in st
ruct literal
..\..\compression.go:36: undefined: flate.Resetter

**Comment by garyburd** [comment]
The package requires Go 1.4 or later.

**Comment by dingconggithub** [comment]
thanks
