### ISSUE TITLE
[Discussion] Extensive usage of interfaces instead of structs

### ISSUE THREAD

**Issue by migueleliasweb** [gorilla/websocket#242]
Hey guys.

I'm using this lib (which is awesome) for a personal project and I got some problem unittesting some code.

Eg.
```golang

type ws struct {}

func (w *ws) Execute () {
    //bunch of code
    conn, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
    //bunch of code
}
```

Code like this one above is surprisinly hard to test given the structure Go expose to us. And that's what happens at [client.go](https://github.com/gorilla/websocket/blob/3ab3a8b8831546bd18fd182c20687ca853b2bb13/client.go#L51) which does not have an interface. But we could do this instead:

```golang
type DialerInterface interface{
    Dial(string, http.Header) (*Conn, *http.Response, error)
}

type ws struct {
    MyDialer *DialerInterface
}

func (w *ws) Execute () {
    //bunch of code
    conn, _, err := w.MyDialer.Dial(u.String(), nil)
    //bunch of code
}

func New () *ws {
    return &ws{
        MyDialer websocket.DefaultDialer
    }
}
```

With this type of coding is much easier to write tests. Eg.
```golang
type FakeDialer struct{}

func (d *FakeDialer) (s string, h http.Header) (*Conn, *http.Response, error) {
     //bunch of code
}

wsWithFakeDialer := ws{
    MyDialer: &FakeDialer
}
```
So, what do you guys think ? If you want I could do a PR for this.

Ps: I wrote this without any codelinting to there might be some errors, sry.

**Comment by garyburd** [comment]
Declare `DialerInterface` in your application and use it as you described.

An alternative is to declare `MyDialer` as a function:

    type ws struct {
        MyDialer func(string, http.Header) (*websocket.Conn, *http.Response, error)
    }

    func (w *ws) Execute () {
        //bunch of code
        conn, _, err := w.MyDialer(u.String(), nil)
        //bunch of code
    }

    func New () *ws {
        return &ws{
            MyDialer websocket.DefaultDialer.Dial
        }
    }

**Comment by garyburd** [comment]
The application can easily structure the code for testing using Go programming language features.
