### ISSUE TITLE
Cant do go get github.com/gorilla/websocket

### ISSUE THREAD

**Issue by jessej3000** [gorilla/websocket#243]
Hi,

I cannot download the websocket toolkit. Everytime I perform the go get... command this is what I get:

go get github.com/gorilla/websocket
# github.com/gorilla/websocket
src/github.com/gorilla/websocket/compression.go:22:66: error: reference to undefined identifier ‘sync.Pool’
  flateWriterPools [maxCompressionLevel - minCompressionLevel + 1]sync.Pool
                                                                  ^
src/github.com/gorilla/websocket/compression.go:23:26: error: reference to undefined identifier ‘sync.Pool’
  flateReaderPool  = sync.Pool{New: func() interface{} {
                          ^
src/github.com/gorilla/websocket/compression.go:23:30: error: missing ‘)’
  flateReaderPool  = sync.Pool{New: func() interface{} {
                              ^
src/github.com/gorilla/websocket/compression.go:23:43: error: expected ‘;’ or newline after top level declaration
  flateReaderPool  = sync.Pool{New: func() interface{} {
                                           ^
src/github.com/gorilla/websocket/compression.go:25:2: error: expected declaration
  }}
  ^
src/github.com/gorilla/websocket/compression.go:26:1: error: expected declaration
 )
 ^
src/github.com/gorilla/websocket/compression.go:36:6: error: reference to undefined identifier ‘flate.Resetter’
  fr.(flate.Resetter).Reset(io.MultiReader(r, strings.NewReader(tail)), nil)
      ^
src/github.com/gorilla/websocket/compression.go:95:6: error: reference to undefined identifier ‘sync.Pool’
  p  *sync.Pool
      ^
src/github.com/gorilla/websocket/client_clone_legacy.go:24:32: error: reference to undefined field or method ‘GetCertificate’
   GetCertificate:           cfg.GetCertificate,
                                ^
src/github.com/gorilla/websocket/client_clone_legacy.go:33:32: error: reference to undefined field or method ‘ClientSessionCache’
   ClientSessionCache:       cfg.ClientSessionCache,
                                ^
src/github.com/gorilla/websocket/client_clone_legacy.go:36:32: error: reference to undefined field or method ‘CurvePreferences’
   CurvePreferences:         cfg.CurvePreferences,
                                ^
src/github.com/gorilla/websocket/client_clone_legacy.go:24:3: error: unknown field ‘GetCertificate’ in ‘tls.Config’
   GetCertificate:           cfg.GetCertificate,
   ^
src/github.com/gorilla/websocket/compression.go:53:9: error: incompatible type for return value 1 (type has no methods)
  return &flateWriteWrapper{fw: fw, tw: tw, p: p}
         ^
src/github.com/gorilla/websocket/compression.go:102:2: error: not enough arguments to return
  return w.fw.Write(p)

**Comment by garyburd** [comment]
Upgrade your Go installation. The websocket package requires Go 1.4 or later.
