### ISSUE TITLE
How to fix client port to connect server?

### ISSUE THREAD

**Issue by Clago** [gorilla/websocket#244]
I want't to fix client connection port,but I don't know how to set?
For example:
192.2.17.68:52480 -> 192.2.17.119:60002.
Client always use port 52480 to connect server.

**Comment by garyburd** [comment]
Set [Dialer.NetDial](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDial) to a function that dials with a specified local address.

       nd := net.Dialer{LocalAddr: ":9999"}
       wd := websocket.Dialer{NetDial: nd.Dial}
       c, r, err := wd.Dial(u, h)

**Comment by Clago** [comment]
thx

**Comment by Clago** [comment]
```go
netDialer := &net.Dialer{LocalAddr: &net.TCPAddr{Port: 60005}} //Fix local ip port
c, _, err := (&websocket.Dialer{NetDial: netDialer.Dial}).Dial(u.String(), nil)
```
