### ISSUE TITLE
Pass large JSON payloads in one frame

### ISSUE THREAD

**Issue by matthewmueller** [gorilla/websocket#245]
Hey folks,

I'm running into a situation where the websocket server I'm working (chrome headless) will close the connection abruptly when a large JSON payload (> 3903 bytes) gets passed to it from this library.

While I don't know enough about the internals of this library yet (or the internals of the chrome headless websocket server), I believe it's related to this library splitting up payloads into multiple frames because I've found that both `x/net/websocket` and the web's native client-side javascript (e.g. `window.WebSocket`) don't have this limitation when passing large messages to chrome headless websocket server.

I'm hoping for some solution or workaround to this problem since I'm keen to use this library as it has some other niceties that `x/net/websocket` doesn't offer.

The commands I'm using are as follows:

```go
func main () {
	conn, _, err := websocket.DefaultDialer.Dial(url, nil)
	if err != nil {
		return nil, errors.Wrap(err, "unable to connect to websocket")
	}

        // v is a struct containing the large payload
	conn.WriteJSON(v)
}


```

Let me know if you need any more information or a failing test case. Any help or possible avenues I can go down to solve this problem would be much appreciated. Thanks!

**Comment by garyburd** [comment]
- What is the error returned from `WriteJSON`?   
- Add code to read the connection and report the error returned. 

        go func() {
            for {
                if _, _, err := conn.NextReader(); err != nil {
                   log.Fatal("read: ", err)
                }
            }
        }()

**Comment by matthewmueller** [comment]
@garyburd 

> What is the error returned from WriteJSON?

No error returned here, it's nil

> Add code to read the connection and report the error returned.

The error here is: `websocket: close 1006 (abnormal closure): unexpected EOF`. I'm getting the error as a result of running:

```go
var raw json.RawMessage
err := conn.ReadJSON(&raw)
```

It's also the same error when I run the code you posted above.

---

For good measure, here's the full code I'm running:

```go
// spawn a chrome process
c, err := chrome.Spawn(&chrome.Settings{
	ExecutablePath: "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
})
if err != nil {
	t.Fatal(err)
}
defer c.Close()

// get chrome's remote debugging websocket URL
url, err := c.GetURL(time.Second)
if err != nil {
	t.Fatal(err)
}

ws, _, err := gorilla.DefaultDialer.Dial(url, nil)
if err != nil {
	t.Fatal(err)
}
defer ws.Close()

file, err := ioutil.ReadFile("big.json")
if err != nil {
	t.Fatal(err)
}

readCh := make(chan string)
go func() {
	for {
		_, reader, err := ws.NextReader()
		if err != nil {
			log.Fatalf("read: %s", err) // <-- error happens here
		}

		result, err := ioutil.ReadAll(reader)
		if err != nil {
			log.WithError(err).Error("readall err")
		}
		readCh <- string(result)
	}
}()

err = ws.WriteJSON(json.RawMessage(file))
if err != nil {
	t.Fatal(err)
}

log.Info(<-readCh) // we don't make it here
```

Resulting in:

```
 fatal read: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by garyburd** [comment]
I confirmed that message fragmentation causes the issue. I have not determined if the error is with Chrome or this package.

**Comment by garyburd** [comment]
The next step is to write a client in Chrome that sends fragmented messages. If the Chrome client has the same issue, then a bug can be entered for Chrome. I don't recall what size Chrome uses to fragment messages, but I do know it's more than 3903 bytes.

I will not have time to work on this for a week or more.

A workaround is to set the [write buffer size](https://godoc.org/github.com/gorilla/websocket#Dialer.WriteBufferSize) to a value larger than any message.

**Comment by elithrar** [comment]
It [Chrome v59] doesn't appear to [automatically] fragment after ~11k bytes
in my quick test against a websocket/ws (JS) server.

**Comment by garyburd** [comment]
Comments in [issue 420578](https://bugs.chromium.org/p/chromium/issues/detail?id=420578) state that Chrome fragments messages at 128kb.

**Comment by matthewmueller** [comment]
Oh this is wonderful, upping the WriteBufferSize in the Dialer will fix this problem. Thanks for taking the time to reproduce the problem and offer up a solution.

I'm still curious what's going on here though. For example, you can reproduce this connection killer by doing `conn.WriteJSON(json.RawMessage(strings.Repeat("z", 3904)))`.

Definitely wouldn't be surprised if chrome headless has a bug here (it has a few other bugs around websocket connections), but I'm thinking this library has to be doing something differently than the JS or net/x/websocket implementation in order to kill this connection.

**Comment by garyburd** [comment]
The string `strings.Repeat("z", 3904)` is not valid JSON.  The call conn.WriteJSON(json.RawMessage(strings.Repeat("z", 3904))) writes invalid JSON to the network. 

> I'm thinking the default dialer in this library has to be doing something differently 

By default, this package fragments messages at 4096 bytes.  The Chrome client fragments messages at 128k.  The x/net/websocket package does not fragment messages.

**Comment by matthewmueller** [comment]
> The string strings.Repeat("z", 3904) is not valid JSON. The call conn.WriteJSON(json.RawMessage(strings.Repeat("z", 3904))) writes invalid JSON to the network.

Yah totally, but it'll still illustrate the issue of the connection getting terminated. 

> By default, this package fragments messages at 4096 bytes. The Chrome client fragments messages at 128k. The x/net/websocket package does not fragment messages.

Good to know! It doesn't quite explain the 3904 number, but perhaps there's some overhead on the message. Thanks for your help!

**Comment by mafredri** [comment]
I've been debugging this a bit in https://github.com/mafredri/cdp/issues/4 as well, and turns out that raising the write buffer beyond `1048562` does not help (this number represents a 1MB payload, discounting the websocket header). When sending any payload larger than `1048562`, with or without fragmentation, the connection is terminated (by Chrome?) and the error varies. Here are some examples:

```
websocket: close 1006 (abnormal closure): unexpected EOF
read tcp 127.0.0.1:55246->127.0.0.1:9222: read: connection reset by peer
```

The same upper limit is encountered when using `golang.org/x/net/websocket` as well.

This is not to say that we can discount fragmentation in `gorilla/websocket` as a potential problem, but these observations point towards there being problems in Chrome, especially the DevTools websocket implementation (or handler).

**Comment by mafredri** [comment]
I decided to dig a bit furhter and came to the following conclusions:

1. Chrome does not support websocket fragmentation (continuation frames), they remain unimplemented at the time of writing ([net/server/web_socket_encoder.cc#86](https://chromium.googlesource.com/chromium/src/+/master/net/server/web_socket_encoder.cc#86))
2. The underlying HTTP connection does not support bigger payloads than 1MB, I believe the reason is the `kDefaultMaxBufferSize`, defined here: [net/server/http_connection.h#33](https://chromium.googlesource.com/chromium/src/+/master/net/server/http_connection.h#33)

    When we send messages larger than 1MB, Chrome logs the following:
    ```
    [89253:55299:0616/194024.005586:ERROR:http_connection.cc(37)] Too large read data is pending: capacity=1048576, max_buffer_size=1048576, read=1048576
    ```

I don't think there's much we can do here. Of course, for the purposes of using `gorilla/websocket` with the chrome debugging protocol, it would be nice to be able to disable fragmentation, and thus not rely on a default buffer size.

**Comment by garyburd** [comment]
Report the issue to Chrome.  

You can work around the Chrome issue by setting the write buffer size to 1MB.  Any message smaller than 1MB will not be fragmented. Messages larger than 1MB don't work independent of the fragmentation issue.

I don't want to expose a new API or setting in this package to workaround a bug in Chrome.

**Comment by mafredri** [comment]
> Report the issue to Chrome.

Absolutely, going to do that in the coming days.

> You can work around the Chrome issue by setting the write buffer size to 1MB. Any message smaller than 1MB will not be fragmented.

I'm thinking of making this the default setting in `cdp`, but I wish there was a way to avoid the constant 1MB allocation per connection. I'm probably just worrying needlessly though.

> Messages larger than 1MB don't work independent of the fragmentation issue.

This stands when compression isn't enabled, given compression, there's really no way to know if a message is going to fit or not (from outside `gorilla/websocket`) 🙁. As long as it compresses to `<= 1MB` (including headers) it's going to work.

> I don't want to expose a new API or setting in this package to workaround a bug in Chrome.

I totally agree, the reason I mentioned it above was that I thought it could potentially be a wanted feature in other situations as well (to disable fragmentation). But possibly it has no merit, I'm not very familiar with the ws spec.
