### ISSUE TITLE
Websocket Upgrade blocking forever

### ISSUE THREAD

**Issue by truongminh** [gorilla/websocket#246]
### What version of Go are you using (`go version`)?
`go version go1.8.1 windows/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Coding\Go\Lib;E:\Coding\Go\Repo
set GORACE=
set GOROOT=D:\Coding\Go
set GOTOOLDIR=D:\Coding\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```
### What did you do?
```go
var upgrader = websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool {
		return true
	}
}

func (s *RoomServer) upgrade(w http.ResponseWriter, r *http.Request) *websocket.Conn {
   upgrader.Upgrade(w, r, nil)
  // sometime do not reach
}
```

I found that the piece of code that blocks is the hijack method of http conn

**Comment by elithrar** [comment]
Can you show a reproducible example?

Also: the call to upgrader.Upgrade returns a *Conn and an error, and you
don't appear to be assigning either in the code above.

**Comment by garyburd** [comment]
Possible duplicate of #232.

Check that the system time is correct.

**Comment by garyburd** [comment]
The hijack issue was fixed in 1.8.1.  

Please report the stack trace of the blocked goroutine.  You can get a stack dump by sending the process  SIGQUIT.

**Comment by truongminh** [comment]
@garyburd it is the hijack issue, exactly.
A test server using golang net/websocket exposes the same problem.
Would you recommend some workaround?

**Comment by garyburd** [comment]
You report that you are running Go 1.8.1.  The fix for the [hijack issue](https://github.com/golang/go/issues/19747) is included in  [Go 1.8.1](https://github.com/golang/go/issues?q=milestone%3AGo1.8.1). 

Check that your system clock is set to the current time.

**Comment by truongminh** [comment]
The clock is in 2017. It isn't related to the set read time out for net.Conn mentioned in the above case.

**Comment by garyburd** [comment]
Perhaps there's a Windows specific issue with Hijack.

File an issue with the Go project. Include a stack trace of the blocked goroutine.

**Comment by truongminh** [comment]
Thank @garyburd for your helps
Closing this issue for now as out of scope.
