### ISSUE TITLE
Closing a connection with a message (gracefully)

### ISSUE THREAD

**Issue by herkyl** [gorilla/websocket#248]
I want to close a connection with a message and a code.
This is how I see it done in the repo: https://github.com/gorilla/websocket/blob/5ade364dff1f03abefdae800ed19074bf707b08f/examples/command/main.go#L76-L78

However I would prefer not to use sleep but rather finish the closing handshake (wait for a reply from the client). Is there an example of how to do it?

I need this because without waiting for the handshake WS library wont work correctly. See https://github.com/websockets/ws/issues/1134

**Comment by garyburd** [comment]
The command example waits for the client reply and all other messages [here](https://github.com/gorilla/websocket/blob/5ade364dff1f03abefdae800ed19074bf707b08f/examples/command/main.go#L48-L51).   Close messages are returned as errors from `ReadMessage`. The reader breaks out of the loop and closes the connection on all errors.

The code 

	time.Sleep(closeGracePeriod)
	ws.Close()

gives the client a few seconds to reply and closes the connection if not already closed.  If you want to rely on the reply from the client, then delete both of these calls.
