### ISSUE TITLE
How can I send message user to user. Not to all user.. 

### ISSUE THREAD

**Issue by jiharAkakom** [gorilla/websocket#249]
``

**Comment by elithrar** [comment]
What have you tried so far? If you maintain a map of userIDs and associated
metadata (connection, message channels, etc) you can just address that user
by their ID / cache name -> ID lookups locally.

**Comment by garyburd** [comment]
Messages written to a websocket connection are sent to a single peer. The package does not provide functionality for sending messages to multiple peers.

If you are building a chat or similar application, then follow the advice in the previous comment.
