### ISSUE TITLE
websocket.Upgrader considered support for fasthttp?

### ISSUE THREAD

**Issue by snail007** [gorilla/websocket#252]
fasthttp is flexible than net/http,and many user use it.

**Comment by garyburd** [comment]
Here are some approaches for adding support for fasthttp:

- Add a hijack API to fasthttp that's similar in structure to the net/http hijack API. Specifically, don't require a callback.  Write a simple adaptor using this new API.
- Add an API to this package for creating a server websocket connection. Write the fasthttp upgrade code in a package other than github.com/gorilla/websocket.

The following are not acceptable:

- Adding a dependency on fasthttp to the github.com/gorilla/websocket package.
- Adding significant maintenance costs to the maintainers of the github.com/gorilla/websocket package.

**Comment by garyburd** [comment]
fasthttp provides a package. There's no need to duplicate the work here.
