### ISSUE TITLE
Help proxying a websocket twice

### ISSUE THREAD

**Issue by mogthesprog** [gorilla/websocket#254]
Hi guys,

I've written an authenticating reverse proxy which supports websockets, using your library. That all works awesomely :) However, we've also got an application  (using your library) which sits in kubernetes and further proxies websockets to services within the cluster. When i hit the application directly it all works, and when i hit applications via the authenticating gateway it also works :) 

However, when i try to hit this special app (the one that sits in kubernetes and proxies sites and websockets) via the authenticating gateway (which is also proxying the content and websockets) i hit a "bad handshake" error. 

Have you got any ideas about how best to troubleshoot this? I'm convinced i'm screwing up a header somewhere... The weird thing is i'm getting a http.StatusOK propagated back to the front end... but i can't see my code issuing a status 200.

I guess my question is, what's the minimum requirements for a valid websocket client? just so i can check what i'm missing.

Thanks for you time.

**Comment by garyburd** [comment]
The code that checks the handshake response is [here](https://github.com/gorilla/websocket/blob/a91eba7f97777409bc2c443f5534d41dd20c5720/client.go#L359-L370). 

The Dial method returns an [*http.Response](http://godoc.org/net/http#Response) on handshake errors. Examine the response [StatusCode](http://godoc.org/net/http#Response.StatusCode) and [Header](http://godoc.org/net/http#Response.Header) to see what's missing or wrong.

**Comment by mogthesprog** [comment]
Thanks for the speedy response :) 

This looks really helpful, I'll have a look at the http.Response and let you know how I get on. I've got a feeling I'm missing one of those headers when passing the request headers to the backend.

**Comment by mogthesprog** [comment]
Hey guys,

First of all, thanks for your help. Would have taken me considerably longer had you not replied :) 

Explanation for anyone interested:

It turned out that i was getting a status 401, that wasn't bubbling up when the backend was refusing the websocket connection.

We authenticate users in the authenticating proxy, and then forward a JWT in a header `Authorization: bearer <token>`. Then the backend applications can look for this header and perform any validation they like. It turned out that this header was getting forwarded on my behalf by http.ReverseProxy, but since i was using my own proxy for websockets (using your library) I needed to specifically forward the header.

Did that and it's all fixed. Thanks again guys, I owe you a beer! Maybe at golang uk!

**Comment by elithrar** [comment]
Thanks for describing your issue before closing - always helps others who
stumble into this! :)
