### ISSUE TITLE
Mention Upgrade in x/net/websockets comparison

### ISSUE THREAD

**Issue by AndreKR** [gorilla/websocket#258]
I was using x/net/websockets because it seemed more official and I hadn't found https://github.com/golang/go/issues/18152 yet.

I couldn't find out how to upgrade an existing request with it and by now I think it is not possible. It's important for me because I wrapped my HandleFuncs to do some logging and stuff and not being able to upgrade means I would need a whole different path for the incoming websocket connections.

You might want to mention that in the feature comparison.

**Comment by monicaq** [comment]
To upgrade from an HTTP request to a websocket connection using the golang.org/x/net/websocket package, call the [websocket.Server](http://godoc.org/golang.org/x/net/websocket#Server) [ServeHTTP](http://godoc.org/golang.org/x/net/websocket#Server.ServeHTTP) method from an HTTP request handler.

    package main

    import (
        "io"
        "net/http"

        "golang.org/x/net/websocket"
    )

    func echoServer(w http.ResponseWriter, r *http.Request) {
        websocket.Server{
            Handler: func(ws *websocket.Conn) {
                io.Copy(ws, ws)
            },
        }.ServeHTTP(w, r)
    }

    // This example demonstrates a trivial echo server.
    func main() {
        http.HandleFunc("/echo", echoServer)
        err := http.ListenAndServe(":12345", nil)
        if err != nil {
            panic("ListenAndServe: " + err.Error())
        }
    }
