### ISSUE TITLE
fff

### ISSUE THREAD

**Issue by f4nff** [gorilla/websocket#265]
delete

**Comment by garyburd** [comment]
This package does not limit speed or bandwidth.

Share more information about what your application is doing.  Is the the application a client or a server?  Which direction are you observing a slowdown (client to server or server to client)?  What software is running on the peer?  Can you point to some code?

**Comment by f4nff** [comment]
let's  https://github.com/ginuerzh/gost/tree/2.4

This is a server based on websocket socks5.

server:
gost -L=ws://:80 -L=http2://:9090


client:

gost -L=:1080 -F=ws://192.168.1.2:80  -F=http2://192.168.1.2:9090
gost -L=:1080 -F=ws://192.168.1.2:80

This use of websocket transmission, 10Mbps upload, can only run to 3Mbps!

client:
gost -L=:1080   -F=http2://192.168.1.2:9090

Do not use websocket, you can run over 10mbps upload bandwidth.

----------------------------

https://github.com/shadowsocks/shadowsocks-dotcloud

This is using the nodejs websocket library socks5 proxy server, but can run up to 10mbps upload bandwidth!

----------------------------

After testing, based on golang websocket uplink bandwidth will be very slow, but the download is no problem.

**Comment by garyburd** [comment]
The gost application does not use the official Gorilla Websocket package at github.com/gorilla/websocket.

**Comment by f4nff** [comment]
Gost is used https://github.com/ginuerzh/gost/tree/2.4/vendor/gopkg.in/gorilla/websocket.v1
You can take a closer look.

**Comment by f4nff** [comment]
https://github.com/ginuerzh/gost/tree/2.4/vendor/gopkg.in/gorilla/websocket.v1   github.com/gorilla/websocket

The two are the same, I pulled the latest github.com/gorilla/websocket try to compile, the uplink bandwidth is limited.

**Comment by garyburd** [comment]
Does the NodeJS version use compression or TLS?

**Comment by f4nff** [comment]
NodeJS probably did not use the compression, I did not use the test tls,
Golang websocket I tested ws / wss can not run up the uplink bandwidth,

**Comment by f4nff** [comment]
Github.com/gorilla/websocket
Ws / wss upload speed is only a quarter of the normal look.

**Comment by f4nff** [comment]
According to my test, the problem does not appear in the tls, tls will only reduce the small performance loss,

**Comment by garyburd** [comment]
Disable compression. 

Use larger buffers.  The small buffers configured in the application will have an impact on client -> server performance.

**Comment by f4nff** [comment]
upgrader: websocket.Upgrader{
--
  | ReadBufferSize:    1024 * 8,
  | WriteBufferSize:   1024 * 8,
  | CheckOrigin:       func(r *http.Request) bool { return true },
  | EnableCompression: false,
----------------


dialer := websocket.Dialer{
--
  | ReadBufferSize:    1024 * 8,
  | WriteBufferSize:   1024 * 8,
  | TLSClientConfig:   config,
  | HandshakeTimeout:  DialTimeout,
  | EnableCompression: false,



https://github.com/ginuerzh/gost/blob/2.4/ws.go

Disable compression, expand the buffer, without any effect.

**Comment by f4nff** [comment]
Could it be possible to provide a completely remove compressed version
