### ISSUE TITLE
memory grow up with the message send count, but when close conn, memory gc slowly

### ISSUE THREAD

**Issue by xkeyideal** [gorilla/websocket#266]
I use websocket send message to client, like the chat example.

But the memory grow up fast with the message send count,

when close conn, the memory gc slowly, need wait 5-10 minutes

golang version 1.8.3, windows 10 os

**Comment by garyburd** [comment]
Post a memory profile and heap dump.

**Comment by garyburd** [comment]
Closing because OP has not responded in 18 days.
