### ISSUE TITLE
Timeout on network loss

### ISSUE THREAD

**Issue by half2me** [gorilla/websocket#271]
I have the following code, which periodically sends messages to a websocket server. This is a real-time application, and if the message doesn't reach the server in <1sec, it needs to be discarded.
Basically I just want to set a timeout of 1sec for the connection.

In this code, I set a deadline of 1sec right before I send out the message, but I am producing more than 1 msg / sec. and even if I unplug my network cable, this code never errors out.
``` golang
for m := range messages {
	c.SetWriteDeadline(time.Now().Add(time.Second))
	if e := c.WriteMessage(websocket.BinaryMessage, m); e != nil {
		c.Close()
		return
	}
}
```

How can I achieve this result?

**Comment by half2me** [comment]
Is there a default ping/pong handler, or do I have to write my own?

**Comment by garyburd** [comment]
`SetWriteDeadline` sets the deadline for future write calls to complete. ``SetWriteDeadline`` does not set a deadline for the data to be received by the peer. 

Application logic is required to discard old messages.

There is a default PING handler.

Show the code that you use to read the connection.

**Comment by half2me** [comment]
@garyburd I've figured it out now thanks. I was under the impression that there was some default logic for ping/pong handling, where I can just send a ping interval, and it would take care of everything else for me. I've written a pong handler to extend the readDeadline, and the default ping handler on the ws server sends back a pong, which is nice.
