### ISSUE TITLE
WriteMessage is not guaranteed to return an error if the messages cannot be transmitted  

### ISSUE THREAD

**Issue by ThomasAlxDmy** [gorilla/websocket#272]
Hi Gary, 

Thank you for all the work on this library, I've notice during my testing that when I have 1 client and 1 server connected, if I suspend my websocket server (using Ctrl+Z) and then I try to send a message the call to WriteMessage returns without error. I suspect that on flaky connection we would loose some messages. Any idea how we could prevent that? Or am I missing something?

**Comment by garyburd** [comment]
WriteMessage returns the status of writing the data to the underlying network connection.  There's no guarantee that data written to the underlying network connection is received by the peer application.

Use an application-level protocol to detect broken connections. See the  [chat example](https://github.com/gorilla/websocket/tree/master/examples/chat) for one way to do this.
