### ISSUE TITLE
Memory not released after websocket disconnection

### ISSUE THREAD

**Issue by svarunan** [gorilla/websocket#273]
I'm trying load test and memory leak on this websocket lib and found m/y not getting released after client disconnects the websocket connection.

Same echo example
```
import (
	"net/http"
	"log"
	"github.com/gorilla/websocket"
)
var upgrader = websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
} // use default options

func echo(w http.ResponseWriter, r *http.Request) {
	c, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Print("upgrade:", err)
		return
	}
	defer c.Close()
	for {
		mt, message, err := c.ReadMessage()
		if err != nil {
			log.Println("read:", err)
			break
		}
		log.Printf("recv: %s", message)
		err = c.WriteMessage(mt, message)
		if err != nil {
			log.Println("write:", err)
			break
		}
	}
}

func main(){
	http.HandleFunc("/ws", echo)
	http.ListenAndServe("localhost:8082", nil)
}
```
This is a simple html file to connect multiple websocket (concurrent connection supported in Safari, So open this in safari to test)
[wstest.html.zip](https://github.com/gorilla/websocket/files/1211082/wstest.html.zip)

Steps to reproduce.
1. Can use top command to check memory
In macOs top command shows exact memory in mb
`lsof -n -i:8082 | grep LISTEN`
`top -pid <process id>`
1. Open this html file in safari and try adding 1000 connections and open dev console
2. Try reload the browser, so it will disconnect form socket server.

I tried using go's expvar and top command to check the memory.

**Comment by svarunan** [comment]
Heap
(pprof) top
7194.06kB of 7194.06kB total (  100%)
Dropped 16 nodes (cum <= 35.97kB)
Showing top 10 nodes out of 21 (cum >= 512.02kB)
      flat  flat%   sum%        cum   cum%
 4112.02kB 57.16% 57.16%  4112.02kB 57.16%  net/http.newBufioReader
 2056.01kB 28.58% 85.74%  2056.01kB 28.58%  net/http.newBufioWriterSize
     514kB  7.14% 92.88%      514kB  7.14%  net/http.(*conn).hijackLocked
  512.02kB  7.12%   100%   512.02kB  7.12%  net.sockaddrToTCP
         0     0%   100%      514kB  7.14%  github.com/gorilla/websocket.(*Upgrader).Upgrade
         0     0%   100%      514kB  7.14%  main.echo
         0     0%   100%   512.02kB  7.12%  main.main
         0     0%   100%   512.02kB  7.12%  net.(*TCPListener).AcceptTCP
         0     0%   100%   512.02kB  7.12%  net.(*TCPListener).accept
         0     0%   100%   512.02kB  7.12%  net.(*netFD).accept

**Comment by elithrar** [comment]
Before diving deeper: how are you classifying a "leak" - ?

Go will reserve memory and won't release it immediately (because it might
need to use it again), and the GC will not always run immediately. If you
test this over the case of (e.g.) 30 minutes -> do you see memory usage
continue to grow for the same number of concurrent clients?

**Comment by svarunan** [comment]
Ideal m/y was below 1MB and it goes to 220MB with 80k + Connections, Then no more connections and waited... 
It took 15 mins time to do GC and come back to ideal Memory. 
I'll check with every 5-10 sec socket connection and see if it grows over a period.

**Comment by garyburd** [comment]
The `top` command reports memory allocated to the process. The command does not report memory in use within that allocation.

The [allocated memory reported by the runtime](http://godoc.org/runtime#ReadMemStats) drops to the background level after the connections are closed and GC completes.  I see no evidence of a "leak".

**Comment by goith** [comment]
hi,  how solve the problem？ 
thanks.
