### ISSUE TITLE
how to get socket id ?

### ISSUE THREAD

**Issue by ericjjj** [gorilla/websocket#274]
help

**Comment by monicaq** [comment]
What is a socket id?

**Comment by ericjjj** [comment]
oh,  such as random number

**Comment by elithrar** [comment]
This library doesn't provide that. If you need to track clients specifically, create a data structure that provides that for you.

The chat example could be extended to support this: https://github.com/gorilla/websocket/blob/master/examples/chat/client.go#L40-L49

**Comment by ericjjj** [comment]
thanks
