### ISSUE TITLE
[question] the default ping closure holds reference to conn object, will it block GC of con?

### ISSUE THREAD

**Issue by wseternal** [gorilla/websocket#276]
hello,

when creating a new conn ojbect, **conn.hanldePing** is set to the built-in ping closure, which holds a reference to the conn object, so, even no other source codes hold reference to the conn object, will the conn.handlePing closure block the GC of conn itself?

shall we set conn.handlePing, conn.handleClose and conn.handlePong to nil manually to avoid
the circular reference when closing the conn?

**Comment by garyburd** [comment]
The GC collects circular references.
