### ISSUE TITLE
ReadMessage sometimes can get 1006 error, sometimes cannot

### ISSUE THREAD

**Issue by liangfflia** [gorilla/websocket#277]
hi,
   Thank you for this great tool first,and please forgive me for my poor English.
   I make application by gorilla, when PC client is killed, Server sometimes can get 1006 error, sometimes cannot get it, the global read is ReadMessage, no other read, I don't know how to get error for every time,can you help me? thanks.
   My application main struct is:

	sConn.relife = make(chan int, 1)
	sConn.relife <- CONNECTION_REATIVE
        //hold life for check timeout
	go sConn.holdlife()
        c.SetPingHandler(func(message string) error {

		c.WriteControl(websocket.PongMessage, []byte(message), time.Now().Add(time.Second))

		sConn.reActive()

		//reactive timeout time for ping
		return nil
	})

	//main loop
	for {
		_, message, err := sConn.ws.ReadMessage()

		if err != nil {
			sConn.deadConn(STATUS_MSG_CONNECT_FAIL, SERVER_READ_MESSAGE_DEAD)
		}
 
               ...

	}
	
	//holdlife check timeout with ping
	func (c *Connection) reActive(){
		if len(c.relife) == 0{
			c.relife <- CONNECTION_REATIVE
		}
	}
	
	func (c *Connection) holdlife(){
		TIMEOUT := HITS_TO_SET_TIMEOUT * HEART_BEAT * time.Second
		timer := time.NewTimer(TIMEOUT)

		for {
			select {
				case <-timer.C:
					c.deadConn(STATUS_MSG_CONNECT_FAIL, SERVER_TIMEOUT_DEAD)
					break
				case <-c.relife:
					timer.Reset(TIMEOUT)
					break
				}
			}
	}`

**Comment by garyburd** [comment]
Use PING and PONG to detect dead connections.  If a peer does not reply to a PING in a timely fashion, then assume that the peer is gone.

**Comment by liangfflia** [comment]
Thanks. PING and PONG couldn't get error immediately, So I want get error from ReadMessage method. The application is IM voice transfer, two client connect with server, one send message to another by server transfer, so I need to detect close error immediately, now I change check method by wait ack  message when send.

**Comment by garyburd** [comment]
Because a peer may not terminate the TCP connection when going away (example: network cable unplugged), it's not always possible to get an immediate error.  Use PING / PONG to detect dead or missing peers.

**Comment by liangfflia** [comment]
Thanks.
