### ISSUE TITLE
connection close twice, is a bug ?

### ISSUE THREAD

**Issue by ldaochen** [gorilla/websocket#279]
in example chat, in file client.go
method readPump()  close conn in defer 
defer func() {
		c.hub.unregister <- c
		c.conn.Close()
}()

and in method writePump() 
defer func() {
		ticker.Stop()
		c.conn.Close()
}()

c.conn.Close() call TWICE, i think it's a bug.
when readPump()  unregister  c, there may be some message in channel c.send
so in writePump() continue read message from channel c.send and call c.conn.WriteMessage to send message to browser, but c.conn have been closed in readPump, and can't write message to it

**Comment by garyburd** [comment]
It is safe to call Close more than once and concurrently.

The application can be modified to send any remaining messages by modifying the read pump to close the connection when `websocket.IsCloseError(err, websocket.CloseNormalClosure) == false`.

**Comment by ldaochen** [comment]
but conn has been closed in readPump, it's still write message to conn  in write pump

can we write data into a closed connection?

**Comment by garyburd** [comment]
Write message returns an error if the connection is closed.

If it's important for your application to drain every last message (and it's not important for the chat application), then only close the connection in the read pump on abnormal closures.  My previous answer shows one test for abnormal closures.

**Comment by ldaochen** [comment]
i got it. thank u
