### ISSUE TITLE
can‘t send empty data

### ISSUE THREAD

**Issue by shanzhi** [gorilla/websocket#280]
Cannot send an empty packet, the payload length can be equal to  zero  ,on conn.go about line 625 , i see the param p's length must greater than 0, maybe it have a problem. sorry my english ,i hope you can understand what i say

**Comment by garyburd** [comment]
Show the application code that cannot sent an empty message.

The `Write` method starts at line 625 in conn.go.  This method copies application data to `writeBuf` or directly to the network connection.  If len(p) == 0, then there's no data to copy.

**Comment by shanzhi** [comment]
thank you ,i find the problem where is ,it's my problem
