### ISSUE TITLE
大并发下, 关闭连接 消息会丢失. 

### ISSUE THREAD

**Issue by lycblank** [gorilla/websocket#281]
当我发送websocket消息时，服务器关闭websocket连接后，客户端会马上收到关闭事件，然而在关闭之前发送的数据没有收到。导致丢失数据。1000个以上的请求，大概有50个左右的连会丢失关闭之前的已经发送的数据

**Comment by garyburd** [comment]
Use a [closing handshake](https://tools.ietf.org/html/rfc6455#section-7.1.2) to avoid data loss during a "clean" close.  See the [command application](https://github.com/gorilla/websocket/tree/master/examples/command) for an example of a server application that uses a clean close.
