### ISSUE TITLE
Question: Any way to safely get a ReadWriteCloser compatible with x/net/websocket?

### ISSUE THREAD

**Issue by prasannavl** [gorilla/websocket#282]
I'm trying to port https://github.com/rsms/gotalk to use gorilla websockets instead of x/net/websocket. However, it uses a common underlying handler for both the raw TCP stream, and websockets stream. The websockets one uses /x/net/websocket where it upgrades the connection, and the passes it on to the raw TCP handler, that handles things from there. 

To be able to do this, x/net/websocket is pretty trivial. All it does is exposes the Conn after the upgrade that can be sent as a ReadWriteCloser. I'm wondering if it's possible to achieve this using Gorilla websockets, while still retaining the higher level features like compression that gorilla socket provides. From what little I looked under the hood, it only seems to have the raw underlying connection `conn` which cannot be passed since it will include the websocket framing, and reader and writer which are exposed through `NextReader` and `NextWriter` which can change. Any way to do this without writing a complicated abstraction layer on top of NextReader/NextWriter?

**Comment by garyburd** [comment]
The x/net/websocket package implements the net.Conn interface using messages. You can do the same. Here's an untested sketch on how to do this:

    type rwc struct {
        r io.Reader
        c *websocket.Conn
    }

    func (c *rwc) Write(p []byte) (int, error) {
        err := c.c.WriteMessage(websocket.BinaryMessage, p)
        if err != nil {
            return 0, err
        }
        return len(p), nil
    }

    func (c *rwc) Read(p []byte) (int, error) {
        for {
            if c.r == nil {
                // Advance to next message.
                var err error
                _, c.r, err = c.c.NextReader()
                if err != nil {
                    return 0, err
                }
            }
            n, err := c.r.Read(p)
            if err == io.EOF {
                // At end of message.
                c.r = nil
                if n > 0 {
                    return n, nil
                } else {
                    // No data read, continue to next message.
                    continue
                }
            }
            return n, err
        }
    }

**Comment by prasannavl** [comment]
@garyburd , thank you so for the quick sketch. I expected it to be more complex. This is very nice. Switched out my implementations, and works perfectly so far. 

Closing this. But, just out of curiosity, any specific reason, why this can't be a part of websockets itself?
Since the read, write interfaces are pretty standard - or perhaps, you feel, it's just not worth maintaining this in the package itself, considering how simple it is?

**Comment by garyburd** [comment]
The io.Reader and io.Writer interfaces are standard for byte streams.  A websocket connection is a stream of messages, not bytes.

**Comment by prasannavl** [comment]
Ok, makes sense. Thanks.
