### ISSUE TITLE
Need Help: websocket: read limit exceeded

### ISSUE THREAD

**Issue by astromahi** [gorilla/websocket#283]
I've encountered problems sending somewhat large messages (more than 5kb of text msg) from websocket client and having the connection closed on both server & client.. 

The server closed the connection replying: `websocket: read limit exceeded`
Client closes the connection replying: `websocket: close 1009 (message too big)`

I understood that I am sending large amount of data. But How I suppposed to make the websocket to read and write data. Do I have to change any buffersize?.

Thanks,
Mahendra

**Comment by garyburd** [comment]
The application is calling [SetReadLimit](https://godoc.org/github.com/gorilla/websocket#Conn.SetReadLimit).  Increase the limit or remove the call.

**Comment by astromahi** [comment]
Thanks that resolved my problem. 

I have another question. Do we have to set [SetReadDeadline](https://github.com/gorilla/websocket/blob/master/conn.go#L1031) & [SetWriteDeadline](https://github.com/gorilla/websocket/blob/master/conn.go#L759) for every read and write we do on websocket or setting once per connection globally would be suffice?. In your example, you have used per write basis, before writing data to conn you set WriteDeadLine.

**Comment by garyburd** [comment]
A deadline is an absolute time after which the IO operation will fail with a timeout.  There are scenarios where it makes sense to set the deadline once, but most applications will want to set the deadline per message.

**Comment by astromahi** [comment]
Alright!. So Websocket is not like a HTTP, It connects with a client for longer duration.
So this case it would wise to set per message. right?.

**Comment by garyburd** [comment]
Most applications should set the deadline per message.
