### ISSUE TITLE
upgrade: websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header

### ISSUE THREAD

**Issue by scohen28** [gorilla/websocket#285]
Trying to understand how to correct this simple program:

package main

import (
	"log"
	"net/http"
	"github.com/gorilla/websocket"
)

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

func main() {
	http.HandleFunc("/ws", serveWs)
	log.Fatal(http.ListenAndServe(":9000", nil))
}

func serveWs(w http.ResponseWriter, r *http.Request) {
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println("upgrade:", err)
		return
	}

	defer ws.Close()

	ws.WriteMessage(websocket.TextMessage, []byte("Hello"))
}

Not sure what to check - thanks!

**Comment by garyburd** [comment]
The client did not use the websocket protocol when connecting to the websocket endpoint.

**Comment by scohen28** [comment]
OK - thanks!
