### ISSUE TITLE
parseURL() breaks custom Proxy

### ISSUE THREAD

**Issue by canning-duck** [gorilla/websocket#290]
really this is #147, but we're using a custom Proxy and the behavior of parseURL() breaks our code as we pass URL's String() to the function that actually searches for the proxy (Java's URI()/ ProxySelector.Select(), we're running on Android using gomobile)

To restate the issue: the connection URL is "wss://example.com/im/connect?foo=bar". 
- parseURL() returns `&url.URL{Scheme:"wss", Opaque:"/im/connect", Host:"example.com", RawQuery:"foo=bar"}` that resolves to "wss:/im/connect?foo=bar" when calling String(). The problem is that the host is missing. 
- net/url.Parse() would return `&url.URL{Scheme:"wss", Host:"example.com", Path:"/im/connect", RawQuery:"foo=bar"}` that resolves to "wss://example.com/im/connect?foo=bar" as expected (go 1.9).

**Comment by garyburd** [comment]
The parse function works around a bug in Go 1.4 and earlier. See https://go.googlesource.com/go/+/874a605af0764a8f340c3de65406963f514e21bc for the detals.

It's OK to drop support for Go 1.4.  I will accept a PR that replaces `parseURL()` with `url.Parse()`.
