### ISSUE TITLE
Is there socks5 support for websocket connections?

### ISSUE THREAD

**Issue by melnikalex** [gorilla/websocket#297]
Can gorilla establish websocket connections through a socks5 proxy? 

If not, is there a plan to do so?

Thank you!

**Comment by garyburd** [comment]
You can connect through a socks5 proxy by setting the [Dialer.NetDial](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDial) field to the [Dial method](https://godoc.org/golang.org/x/net/proxy#Dialer.Dial) of a [SOCKS5 Dialer](https://godoc.org/golang.org/x/net/proxy#SOCKS5).

     netDialer, err := proxy.SOCKS5( .... )
     if err != nil {
        handle error
     }
     dialer := websocket.Dialer{NetDial: netDialer.Dial}
     c, r, err := dialer.Dial(url, nil)
     if err != nil {
        handle error
    }

**Comment by vitreuz** [comment]
We use the [http.ProxyFromEnvironment function](https://golang.org/pkg/net/http/#ProxyFromEnvironment) to setup the [Dialer.Proxy field](https://godoc.org/github.com/gorilla/websocket#Dialer.Proxy).
``` golang
if proxy == nil {
    proxy = http.ProxyFromEnvironment
}

...

    dialer: websocket.Dialer{
        Proxy:            proxy,
        ...
    },
```
        

Would it be possible to support this out of the box since golang recently added support for SOCKS5 from the environment? They have a similar implementation for the transport package [here](https://github.com/golang/go/blob/master/src/net/http/transport.go#L1149-L1165).

**Comment by garyburd** [comment]
@vitreuz I don't want to add a dependency outside the standard library, nor do I want to vendor the x/net package as was done [here](https://github.com/golang/go/tree/master/src/vendor/golang_org/x/net/proxy).  

I am open to suggestions on how to modify the Dialer to enable easy use of golang.org/x/net/proxy by applications.

**Comment by garyburd** [comment]
How about adding this field to Dialer?

```
// ProxyFromURL returns a Dialer given a Proxy URL specification and an underlying
// Dialer for it to make network requests. 
func ProxyFromURL(u *url.URL, forward Dialer) (Dialer, error) 
```

**Comment by enocom** [comment]
@garyburd Your solution looks great. It will solve the problem of needing to support SOCKS5 in our particular library [NOAA](https://github.com/cloudfoundry/noaa). @melnikalex What do you think?

**Comment by melnikalex** [comment]
@garyburd I like it. Thank you!

**Comment by garyburd** [comment]
Another approach is to [bundle](https://godoc.org/golang.org/x/tools/cmd/bundle) the [x/net/proxy](https://godoc.org/golang.org/x/tools/cmd/bundle) package.  This avoids adding yet another knob to Dialer and is a much better option than vendoring all of x/net.
