### ISSUE TITLE
Heartbeat of client

### ISSUE THREAD

**Issue by pathbox** [gorilla/websocket#304]
I find that when the network of client is down， the websocket server doesn't know it， and the websocket connection is still living in websocket server。If the network of client doesn't work forever，the websocket connection need a long time (about 20minutes？) to know it and close connection。 The connection timeout is about 20minutes

Now I use application level heartbeat to control it。Can I set the connection timeout  in gorilla/websocket?   
The timeout is too long for me

**Comment by elithrar** [comment]
Have you configured Ping/Pong handlers?

See the chat example -
https://github.com/gorilla/websocket/blob/master/examples/chat/client.go -
for how to do this. Clients that fail to return a PONG to your PING can
then be disconnected and removed from your client data-structure.

**Comment by garyburd** [comment]
The application can use PING/PONG with read timeout to check for the health of the connection and peer.  See the [chat](https://github.com/gorilla/websocket/tree/master/examples/chat) and [command](https://github.com/gorilla/websocket/tree/master/examples/command) applications for examples of how to do this.

**Comment by pathbox** [comment]
Thank you very much, I understand it. @elithrar @garyburd
