### ISSUE TITLE
Integrating with gopacket

### ISSUE THREAD

**Issue by shabbyrobe** [gorilla/websocket#307]
I haven't found a good way to assemble websocket streams using gopacket and gorilla. I could be missing something obvious, but I haven't found a way to get access to gorilla's reader in a way that can integrate with gopacket's TCPAssembly without resorting to hacks.

My disgraceful stopgap has been to simply copypasta in a whole bunch of gorilla's unexported types:

```
-flateReadWrapper : struct
-netError : struct
-wsConn : struct
-wsMessageReader : struct
```

My stopgap is working well enough for our project for now (apart from a few minor bugs), but I think it'd be great to get enough of the current unexported API exported to help integrating with gopacket. The pieces are all there, I'm not 100% sure what those pieces are but I'm happy to help work that out if this is something the project would consider.

**Comment by elithrar** [comment]
Hi Blake - could you share a little bit more about how you are
calling/using these private APIs - e.g. example code?

**Comment by shabbyrobe** [comment]
Absolutely, it will take a bit of time to cook something minimal up that is disentangled from our own app; I just wanted to gauge interest before I went to the effort :)

**Comment by elithrar** [comment]
Exposing all of those symbols would add a lot to the API surface (and
provide no gain for many), so understanding how you're using them might
help us see whether there's another [existing] way or whether a hook can be
exposed on the Conn instead.

**Comment by shabbyrobe** [comment]
Time has really gotten away from me on this one. I'm still keen to prepare that example though, it just might take a little longer than I had hoped.

**Comment by garyburd** [comment]
Closing because there's no response from OP in months.
