### ISSUE TITLE
Run web-Socket locally for debug

### ISSUE THREAD

**Issue by RaynDol** [gorilla/websocket#308]
HI,

I’m using gorilla web socket and I want to run it locally , I mean with the following chrome client or other recommended tool …when I run into debug mode I got error

I use

```
"github.com/gorilla/websocket"


var upgrader = websocket.Upgrader{
    ReadBufferSize:  1024,
    WriteBufferSize: 1024,
}

upgrader.CheckOrigin = func(r *http.Request) bool { return true }

c, err := upgrader.Upgrade(w, r, nil)
if err != nil {
    log.Print("upgrade:", err)
    return
}

```
When I run the following url in chrome or web socket client I got error

websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header

localhost:8081/mypath
and I want to run it

ws://localhost:8081/mypath
and provide token for local simulation, how I can do it ?

To check it I use Simple WebSocket Client of chrome. any other client will be helpful

**Comment by garyburd** [comment]
Code is required to connect to a Websocket endpoint from the browser.  See the chat and echo applications in this project for examples of how to do this.
