### ISSUE TITLE
If websockets server goes down, after reconnecting, pong messages are not sent 

### ISSUE THREAD

**Issue by blakeage** [gorilla/websocket#311]
We have a NodeJS websockets server running, and an client written using gorilla websocket.  Upon connecting to the WS server, server pings are correctly responded to by gorilla/websocket with pongs.  However, if for some reason, the websockets server goes down (in our testing, just by stopping the process), when the client tries to read, we get:
websocket: close 1006 (abnormal closure): unexpected EOF

This is expected.  In response to this event, we reconnect (redial) the websockets server until it comes back up.  When it comes back up, we are able to successfully connect and send messages, BUT, the client no longer sends pong messages.

We've tried writing our own ping handler, tried nil-ing the connection object, closing the connection before reconnecting, and several other things, but the client will not send pongs after reconnection.

The side effect of this, is that if the websockets server goes down and comes back up, its pings are not responded to, and so the websocket server closes the connection.  This causes our client to reconnect with every message we try to send.

Is there something I need to do to handle the abnormal closure error, other than just reconnecting, so that the pings will be responded to?

**Comment by garyburd** [comment]
Connections are independent of each other. An error on one connection will not change or impact the default ping handler on connections dialed at a later time.

There are two reasons why a connection will not respond to a ping with a pong:  the application is not reading from the connection or the application set a ping handler that does not respond with a pong.

**Comment by blakeage** [comment]
Ugh, it looks like we were returning from a function that deferred the closing of the connection.  So the reconnect was immediately being closed (and so could not respond to pings).  Sorry for the trouble, it looks like it's our issue!  Thank you.
