### ISSUE TITLE
Consume new messages on events, only when a new message is recieved

### ISSUE THREAD

**Issue by CSNoyes** [gorilla/websocket#313]
Apologies for the simple question. I'm moving a stack over to golang and don't see anything in the documentation about the proper pattern in Go/this lib on how to implement this. Basically I'm consuming a read-only websocket feed with about 30 msgs/sec.  In the python lib I'm moving over from, there was a way to only trigger a message read (here I'm using ReadJSON) on new messages (a bool indicated if the value had been updated since the last call to ReadJSON). 

I'm thinking there's probably a way to do this by having the messages be read in a goroutine and having an indicator variable that triggers execution in the main thread on receipt of a new message. I'm new to go and would like to make sure I'm following the correct event-driven paradigm so any pointers would be greatly appreciated.

**Comment by elithrar** [comment]
What is consuming the messages? An “indicator variable” may not be
concurrency-safe, unless protected by a synchronization primitive (i.e.
mutex).

The chat example shows one approach to consuming messages and distributing
them to many clients (connections):
https://github.com/gorilla/websocket/tree/master/examples/chat
