### ISSUE TITLE
Strange non blocking behavior of WriteMessage

### ISSUE THREAD

**Issue by EvgenySerg** [gorilla/websocket#314]
I'm tying to understand socket timeouts, but here i have a strange behavior of socket write. In this example of code there is no any timeouts, and we get looks like non blocking socket  in rotation write operations (hello1 and hello2 messages).
 If i make comment "//<part>" block of code, then i have desirable timeouts.

I don'understand this behavior.
How can i set different timeouts for different websocket.WriteMessage or Read operations?

Thanks.

 

```
package main

import (
	"log"
	"net/http"
	"time"
	"github.com/gorilla/websocket"
)

func main() {
	go Write()
	Listen()
}

func Write() {
	c, _, err := websocket.DefaultDialer.Dial("ws://127.0.0.1:8555", nil)
	if err != nil {
		log.Println(err.Error())
		return
	}
	err = c.SetWriteDeadline(time.Now().Add(time.Second * 2))
	if err != nil {
		log.Println(err.Error())
		return
	}

	for {
		err = c.WriteMessage(websocket.TextMessage, []byte("Hello 1"))
		if err != nil {
			log.Println(err.Error())
		}
		//<part>
		t := time.Second * 2
		log.Println(t)
		err = c.SetWriteDeadline(time.Now().Add(t))
		if err != nil {
			log.Println("asdasdsad")
			return
		}
		//</part>
		err = c.WriteMessage(websocket.TextMessage, []byte("Hello 2"))
		if err != nil {
			log.Println("c2 timeout " + err.Error())
		}

		time.Sleep(time.Second * 1)
	}
}

func handler(w http.ResponseWriter, r *http.Request) {
	upgrader := websocket.Upgrader{}
	c, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println(err.Error())
		return
	}
	for {
		_, data, err := c.ReadMessage()
		if err != nil {
			log.Println(err.Error())
		}
		log.Println(string(data))
		time.Sleep(time.Second * 5)
	}
}

func Listen() {
	http.HandleFunc("/", handler)
	http.ListenAndServe("127.0.0.1:8555", nil)
}

```

**Comment by garyburd** [comment]
> How can i set different timeouts for different websocket.WriteMessage or Read operations?

Given desired timeout `t` for a write operation, call `c.SetWriteDeadline(time.Now().Add(t))` before the write operation.

Given desired timeout `t` for a read operation, call `c.SetReadDeadline(time.Now().Add(t))` before the read operation.

**Comment by EvgenySerg** [comment]
Thank you for answer.
It looks like the WriteMessage is not blocking, and it doesn't with small amount of data. It just sends the data and go further without any timeouts.

**Comment by garyburd** [comment]
WriteMessage and friends wait until the data is written to the kernel. This operation can take an arbitrary amount of time.
