### ISSUE TITLE
context.Context support

### ISSUE THREAD

**Issue by hanbang-wang** [gorilla/websocket#316]
Support wanted for better coroutine manipulation.

**Comment by garyburd** [comment]
Describe the problem you are trying to solve in more detail.

**Comment by hanbang-wang** [comment]
`context` package, as declared in standard packages and document available here [https://golang.org/pkg/context/](https://golang.org/pkg/context/), is used to handle network requests and responses in goroutine. For example, if a connection holds a cancellable context, does the standard `http` package, and the `context` is canceled, the whole request will be canceled, including connecting, reading or writing, and the open socket will be closed. 

Honestly, this is pretty self-explanatory if you know what `context` package does. Furthermore, the `Dial` param in `http.Transport` is already deprecated, and the `DialContext` is a great replacement for that, so I believe it should be the same for this `websocket` package as well.

**Comment by garyburd** [comment]
I am asking you to describe the problem you are trying to solve in your application, not a description of the context package.

**Comment by hanbang-wang** [comment]
For example, when I am dialing, instead of `HandshakeTimeout` I want to use `context` to `cancel` it.

**Comment by garyburd** [comment]
Why does the timeout not work for your application?  Describe the problem.

I am not going to sprinkle context dust over the package with the hope that it will magically solve actual problems.

**Comment by hanbang-wang** [comment]
As I said, context is created and suggested for problems like this. Let me give you a more detailed and *realistic* situation.


There's a MITM websocket service running, two goroutines respectively handle connections from (client to self) and (self to the real server). 

Say that I am reading data from (self to the real server) connection and to send it to the client side, but since the real server is not sending anything, the procedure is blocked. Now, the client closed the (client to self) connection, so I am supposed to be closing (self to the real server) connection as well. However, since the (self to the real server) goroutine is still blocked on reading, I can do nothing about it. 

Now I know that I can set a ReadTimeout on (self to the real server) side, and detect if the other (client to self) connection is still alive after every timeout, but a cancellable context would be a perfect and quick solution for this: simply calls `cancel()` and the reading is not blocked anymore and returns an error instead.

**Comment by garyburd** [comment]
Context cancelation is **not** the right solution for handling close in a websocket proxy. Let me know if this is an actual problem you are encountering. If it is, then I'lll take the time to describe how to handle close in a proxy.

I know what the context package is and the problems the package is intended to solve.  I am willing to add context related features based on actual application requirements. I don't want to spend time implementing or reviewing features that nobody needs.

**Comment by hanbang-wang** [comment]
Yes, please go ahead. My current solution is inserting detection anywhere in the code, which is really messy.

**Comment by garyburd** [comment]
The [RFC describes how to cleanly close a websocket connection](https://tools.ietf.org/html/rfc6455#section-1.4).

I assume that you have two connections, `serverConn` and `clientConn`.

Create two channels for communicating that the connections are closed:

      serverClosed := make(chan struct{})
      clientClosed := make(chan struct{})

Run goroutines to copy the connections:

     go copyConn(serverConn, clientConn, serverClosed, clientClosed)
     go copyConn(clientConn, serverConn, clientClosed, svererClosed)

where copyConn is:

```
func copyConn(readConn, writeConn *websocket.Conn, readClosed, writeClosed chan struct{}) {
	var rerr error
	for {
		var r io.Reader
		var messageType int

		messageType, r, rerr = readConn.NextReader()
		if rerr != nil {
			break
		}
		w, err := writeConn.NextWriter(messageType)
		if err != nil {
			break
		}
		if _, err := io.Copy(w, r); err != nil {
			break
		}
	}

	// Close the reading connection. If we broke out of the loop because of a
	// normal close, then NextReader echoed the close message and we should now
	// close the connection.  If it's an abnormal close, then we should give up
	// and close the connection.
	readConn.Close()

	// Tell the other goroutine that readConn was closed.
	close(readClosed)

	// Did we break out of the loop because a we received a close message?
	if e, ok := rerr.(*websocket.CloseError); ok && e.Code != websocket.CloseAbnormalClosure {

		// Forward the close message to writeConn.
		var m []byte
		if e.Code != websocket.CloseNoStatusReceived {
			m = websocket.FormatCloseMessage(e.Code, e.Text)
		}
		err := writeConn.WriteMessage(websocket.CloseMessage, m)

		// Did we successfully send the close message?
		if err == nil {
			// Wait with timeout for the other goroutine to handle the handshake.
			select {
			case <-writeClosed:
				// The other goroutine closed writeConn.
				return
			case <-time.After(10 * time.Second):
			}
		}
	}

	writeConn.Close()
}
```

> And would you please explain why a cancellable context is not the right solution?

Coordinating the closing handshake between two connections is an application problem.

**Comment by hanbang-wang** [comment]
That'll do, thanks.

**Comment by finsterdexter** [comment]
I guess what I'm really asking is for clarification about this statement:

> Context cancelation is not the right solution for handling close in a websocket proxy.

In my reading that sounds like exactly what context cancellation was written to handle. I don't understand why one wouldn't want to use context cancellation (assuming context support were available throughout your service stack). Again, I'm just trying to understand the core concepts and why context is not considered idiomatic in this case.

**Comment by garyburd** [comment]
My statement refers to functionality implemented by this package. 

The functionality needed from this package for proxy shutdown is: write a message to a connection, read a message from a connection and close a connection. These features are exposed as methods on the connection object.  Exposing these features through context cancelation is not needed, nor does it make sense.
