### ISSUE TITLE
[Chat example] Websocket can not connect to server. 

### ISSUE THREAD

**Issue by zmzmdr** [gorilla/websocket#319]
When i run the chat example.
I add the following code snipet

conn.onopen = function(e){console.log('### on open ###')}

I found that onopen not be called when refresh webpage. Sometime it worked, but raraly.
How can i explain this situation?

**Comment by garyburd** [comment]
What browser are you using? Did you change any other code on the client or the server?  Are you connecting to a server running on localhost?

**Comment by zmzmdr** [comment]
@garyburd Thanks for your quick reply.


What browser are you using?  
**Chrome latest**

Did you change any other code on the client or the server? 
**Just clone and run**

Are you connecting to a server running on localhost?
**Yes, localhost, follow the readme.**


---------------------------------------
When i debug this. I found the code hang on the following function.

```
func (cr *connReader) abortPendingRead() {
	cr.lock()
	defer cr.unlock()
	if !cr.inRead {
		return
	}
	cr.aborted = true
	cr.conn.rwc.SetReadDeadline(aLongTimeAgo)
	for cr.inRead {
		cr.cond.Wait()
	}
	cr.conn.rwc.SetReadDeadline(time.Time{})
}
```

**Comment by garyburd** [comment]
See https://github.com/golang/go/issues/19747

Upgrade to go 1.8.1 or later.

**Comment by zmzmdr** [comment]
All related issues seems not helpful.
My go version is 1.9.2 windows/amd64.
And my system time is 2017-12-29 12:52:45.5510985 +0800 CST m=+2.390005001
ALongTimeAgo is 1970-01-01 08:00:01 +0800 CST
But still deadlock.

**Comment by garyburd** [comment]
Does the following program deadlock when accessing http://localhost:8080/ ?

```
package main

import (
  "log"
  "net/http"
)

func main() {
  http.HandleFunc("/", handler)
  log.Fatal(http.ListenAndServe(":8080", nil))
}

func handler(w http.ResponseWriter, r *http.Request) {
  h := w.(http.Hijacker)
  log.Println("calling hijack")
  c, _, err := h.Hijack()
  log.Println("hijack returned err=", err)
  c.Close()
}
```

**Comment by zmzmdr** [comment]
Looks like deadlock occurs sometimes.

```
2017/12/29 13:58:49 hijack returned err= <nil>
2017/12/29 13:58:49 hijack returned err= <nil>
2017/12/29 13:58:49 calling hijack
2017/12/29 13:58:49 hijack returned err= <nil>
2017/12/29 13:58:50 calling hijack
2017/12/29 13:58:51 calling hijack
2017/12/29 13:58:52 calling hijack
2017/12/29 13:58:52 hijack returned err= <nil>
2017/12/29 13:58:52 calling hijack
2017/12/29 13:58:52 hijack returned err= <nil>
2017/12/29 13:58:56 calling hijack
2017/12/29 13:58:57 calling hijack
2017/12/29 13:58:57 calling hijack
2017/12/29 13:58:57 calling hijack
2017/12/29 13:58:57 calling hijack
2017/12/29 13:58:57 hijack returned err= <nil>
2017/12/29 13:58:57 calling hijack
```

**Comment by garyburd** [comment]
This is a issue with net/http. Please file an issue at https://github.com/golang/go/issues/new.

**Comment by garyburd** [comment]
Thank you for reporting where the code deadlocks and for opening the issue at golang/go.
