### ISSUE TITLE
how to bench test?

### ISSUE THREAD

**Issue by ruandao** [gorilla/websocket#320]
I try to use [https://github.com/M6Web/websocket-bench](https://github.com/M6Web/websocket-bench), but not success?
can anyone give me a direction, like what tool?

**Comment by ballontt** [comment]
I also need this,help

**Comment by elithrar** [comment]
Can you share how you are using this tool? You should ask for help on the
M6Web/websocket-bench repository as there's not much guidance we can give
for an unfamiliar tool.

Note: I've used https://github.com/observing/thor before.

**Comment by ruandao** [comment]
I can't find satisfied tool so I write websocket bench myself
