### ISSUE TITLE
Chat example error in Safari: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by lkebin** [gorilla/websocket#323]
Hi,

I build and running the [chat](https://github.com/gorilla/websocket/tree/master/examples/chat) example, using Safari browser. 
When I refresh the page in the browser, I got error: 
```
error: websocket: close 1006 (abnormal closure): unexpected EOF
```
from the server console.

Another browser (Chrome) works well without the error.

**Comment by garyburd** [comment]
Thank you for the report.  The error should be included [here](https://github.com/gorilla/websocket/blob/d965e9adc66deebadcc7d0c6c7598e2a4baa7838/examples/chat/client.go#L67).

**Comment by lkebin** [comment]
@garyburd Thanks man.
