### ISSUE TITLE
CloseHandler not called

### ISSUE THREAD

**Issue by alexppxela** [gorilla/websocket#325]
Hi,

My server is reading data looping on `ws.NextReader()`.

The client opens the websocket like this:
```conn, rsp, err := websocket.DefaultDialer.Dial(u.String(), nil)```.
When it closes the websocket `conn.Close()`, the server is not correctly notified.

`ws.NextReader()` returns:
- err: close 1006 (abnormal closure): unexpected EOF

But CloseHandler is not called.

**Comment by garyburd** [comment]
This is expected.  The close handler is called when a close message is received from the peer.  The peer did not send a close message.

What does the application do in the close handler?  

Most applications should handle close messages as part of their normal error handling. Applications should only set a close handler when the application must perform some action before sending a close frame back to the peer.

**Comment by alexppxela** [comment]
I was confused because I thought that close handler was called whatever the cause of close.
My application is a gateway between a client and a server, so when my client websocket is closed, I close the connection to the server. I use close handler as a notification of close event instead of a last action before sending the frame back to peer.
Thanks for your answer.

**Comment by garyburd** [comment]
If you are communicating with the server using the websocket protocol, then you may find [this code](https://github.com/gorilla/websocket/issues/316#issuecomment-353987393) to be helpful.

**Comment by alexppxela** [comment]
Great helpful code, thanks.
Unfortunately, I do nbot use websocket to server.
