### ISSUE TITLE
What websocket javascript clients do you suggest?

### ISSUE THREAD

**Issue by gitleet** [gorilla/websocket#327]
What javascript client's do you guys suggest we use?

Is this websocket implementation work with socket.io's client?

**Comment by garyburd** [comment]
> What javascript client's do you guys suggest we use?

Web browser: Use the browser's built-in API
Node.js: I have no recommendation. Ask on a Node forum.

> Is this websocket implementation work with socket.io's client?

Yes, but you need code that implements the Socket.io protocol. I do not have any recommendations for socket.io packages.

**Comment by elithrar** [comment]
Agree with Gary on the browser side. The WebSocket APIs behave very
consistently across major browsers.

I have used https://github.com/websockets/ws on the Node side (and
contributed some small changes) and liked it; both a client & server.

**Comment by gitleet** [comment]
I looked at some client code in the past and noticed they usually have cross-browser related code, falling back to longpoll also in case the browser doesn't support it.

I just don't want to re-invent the wheel for something like this, and was hoping you guys had some recommendations.

Thanks!

**Comment by elithrar** [comment]
socket.io is probably the premiere solution in that case, but browser
support is extremely widespread now: https://caniuse.com/#feat=websockets

**Comment by garyburd** [comment]
Given current support for websockets, the fallback to long polling may not worth the trouble. A fallback to polling or no dynamic updates at all may be good enough depending on the application requirements and the browsers used by your users.
