### ISSUE TITLE
Option to print out messages about to get sent

### ISSUE THREAD

**Issue by andersfylling** [gorilla/websocket#329]
Is there a functionality for this? I need to verify that my json data sent to the server is correct. Currently I keep getting server errors as my json data is being decoded, but i can't seem to find any errors on my side.

Has anyone played around with this? Any help is appriciated ^^,

**Comment by garyburd** [comment]
Copy the `WriteJSON` code to your application can add whatever printing you need. Something like this:

     func writeJSON(c *websocket.Conn, v interface{}) error {
         p, err := json.Marshal(v)
         if err != nil 
            return err
         }
         fmt.Printf("%s\n", p)
        return c.WriteMessage(websocket.TextMessage, p)
    }
