### ISSUE TITLE
Documentation should compare with net/websocket

### ISSUE THREAD

**Issue by cachvico** [gorilla/websocket#331]
It would be great for the docs to include a quick overview of what exactly gorilla/websocket does that net/websocket does not.

**Comment by elithrar** [comment]
https://github.com/gorilla/websocket/blob/master/README.md#gorilla-websocket-compared-with-other-packages covers the key differences between the two packages.

Is there details you see as missing?

**Comment by cachvico** [comment]
I'm a good example of the user who doesn't read.

Thanks!
