### ISSUE TITLE
The switching protocol response from Apache-Coyote does not include a "Connection upgrade"

### ISSUE THREAD

**Issue by zplzk2** [gorilla/websocket#335]
When trying to connect to a WebSocket server behind Apache-Coyote, gorilla fails and the response is:
> 101 Switching Protocols 101 HTTP/1.1 1 1 map[Upgrade:[websocket] Sec-Websocket-Accept:[somekey] Date:[somedate] Server:[Apache-Coyote/1.1] Set-Cookie:[JSESSIONID=somesessionid; Path=/somepath/; HttpOnly]]

The related code is: https://github.com/gorilla/websocket/blob/b89020ee79b89a7f932c5617d218fc06db382f53/client.go#L295

Apparently there's no "Connection upgrade" in the response. Gorilla will work by removing this line.

But the question is:
Is it because Gorilla's check condition is too tight?
OR
Is it because Apache-Coyote doesn't give a proper response?

**Comment by elithrar** [comment]
Connection: Upgrade is defined in the WebSocket RFC as a MUST:
https://tools.ietf.org/html/rfc6455#section-4.2.2


> If the server chooses to accept the incoming connection, it MUST reply
with a valid HTTP response indicating the following.
> A |Connection| header field with value "Upgrade”.

Thus, Apache Coyote (which I am not familiar with) does not respect the
standard, or doesn’t know about it to begin with.

**Comment by zplzk2** [comment]
@elithrar Thank you so much! I'll check the server side to see if I missed anything.

**Comment by zplzk2** [comment]
Update. I think I've figured out why.
**Long story short, it is not a bug of gorilla.**

The following is what Wireshark captured:
> Hypertext Transfer Protocol
>     HTTP/1.1 101 Switching Protocols\r\n
>     Server: Apache-Coyote/1.1\r\n
>     Set-Cookie: JSESSIONID=somesession; Path=somepath; HttpOnly\r\n
>     Upgrade: websocket\r\n
>     Connection: upgrade\r\n
>     Sec-WebSocket-Accept: somekey\r\n
>     Date: Mon, 29 Jan 2018 18:42:09 GMT\r\n
>     Connection: close\r\n
>     \r\n

And there are two fields "Connection" here (one is **upgrade** and another one is **close**), which is odd.

Dig into the code:
https://github.com/golang/go/blob/d529aa93ea64f234641d638c1bc7df5c568c474a/src/net/http/response.go#L148

Before this function returns, the mimeHeader and resp.Header are correct (with value Connection:[upgrade close])

But then it was deleted then at:
https://github.com/golang/go/blob/d529aa93ea64f234641d638c1bc7df5c568c474a/src/net/http/response.go#L196
by:
https://github.com/golang/go/blob/d529aa93ea64f234641d638c1bc7df5c568c474a/src/net/http/transfer.go#L687

So the header gorilla gets does not include "Connection" any more.

**Comment by garyburd** [comment]
Thank you for debugging the issue. The inclusion of "close" is odd, but the I don't see anything in the spec that forbids it.

Are you opening issue on net/http, Coyote or do you have some other plan for addressing this problem?

**Comment by zplzk2** [comment]
@garyburd Thank you for your reply, sir.

Indeed the spec doesn't forbid that. And gorilla works pretty well if I remove the line locally:
https://github.com/gorilla/websocket/blob/b89020ee79b89a7f932c5617d218fc06db382f53/client.go#L295

First I'm going to check why Coyote returns this odd header. It is on AWS and behind ELB so it may take a while.
Will update this thread later.

**Comment by garyburd** [comment]
One option is to replace [http.ReadResponse](https://godoc.org/net/http#ReadResponse) with custom code in this package. The code would be simpler than the net/http code because there are not as many special cases to consider.  This is not my preferred option.

**Comment by zplzk2** [comment]
@garyburd Hi Sir, the IT team checked with AWS and found an incorrect configuration in cloud side. After fixing that gorilla works happily with the back end.
Thank you for your time and sorry for the inconvenience.

**Comment by garyburd** [comment]
Thank you for the update.  I am glad to see that your problem is fixed elsewhere. I didn't like the idea of duplicating part of http.ReadResponse in this package.
