### ISSUE TITLE
Inflate messages on client side

### ISSUE THREAD

**Issue by KeKs0r** [gorilla/websocket#336]
Hi,

I am trying to connect to a websocket server which compresses its messages. I might be overlooking something, but the compression in this library currently is only implemented for the server side correct?

Would it be possible to inflate incoming messages just via `compress/flate`? Somehow I was not yet able to get this working.

Are there examples of clients that inflate incoming messages?

**Comment by garyburd** [comment]
Client and server connections both support per message compression.  Any client example can be modified to support per message compression by setting [Dialer.EnableCompression](https://godoc.org/github.com/gorilla/websocket#Dialer.EnableCompression) to true.
