### ISSUE TITLE
SetReadDeadline and Concurrency

### ISSUE THREAD

**Issue by rodicus** [gorilla/websocket#338]
Hi,

The Concurrency section of the documentation lists the read-related methods that should only be called by one routine. I am just wondering why SetReadDeadline is listed in there as it only seems to call the respective net.Conn method, which is supposedly [safe for multi-routine use](https://golang.org/pkg/net/#Conn).

Thanks in advance,

Rod

**Comment by garyburd** [comment]
The SetReadDeadline function can be called concurrently in the current implementation.

Do you need to call it concurrently, and if so, why?

**Comment by garyburd** [comment]
Is there a reason why you cannot extend the deadline from the reading goroutine?

**Comment by rodicus** [comment]
I meant to say from the pong and reading routines. IIUC the websocket connection state can become permanently corrupted if a read op times out, so I am just trying to minimize that. However, I do want the connection to tell me something is wrong if I haven't heard from the client for a while either from pongs or regular messages.

**Comment by garyburd** [comment]
The pong handler is called from the reading goroutine and can set the deadline.

**Comment by rodicus** [comment]
I didn't realize the pong handler is called from `advanceFrame` which is itself called from reading methods. I assumed pongs and other control messages were received on a separate routine. Thanks for pointing that out.

**Comment by garyburd** [comment]
The overview documentation says:

> The control message handler functions are called from the NextReader, ReadMessage and message reader Read methods.

I'll repeat this in the SetPing/Pong/CloseHandler documentation.

**Comment by rodicus** [comment]
I overlooked that (my bad). Adding the extra comment sounds great. Thanks Gary!
