### ISSUE TITLE
Built-in MessagePack support

### ISSUE THREAD

**Issue by rocketbitz** [gorilla/websocket#354]
Hi,

For most applications, c.ReadJSON() and c.WriteJSON() are perfectly fine, but for high throughput situations, MessagePack is a great protocol to reduce message size. Obviously right now one can read the raw byte buffer using c.ReadMessage() and decode it themselves, but I think it would be cleaner to have it built in alongside JSON for these higher throughput applications.

I would be more than willing to add support myself.

**Comment by garyburd** [comment]
Thank you for offering, but I don't want to add this feature for the following reasons:

- I do not want to add a dependency on a third party MessagePack package, nor do I want to add a MessagePack codec to this package. 
- Applications can implement the feature with a few of lines of code and NextReader/NextWriter or ReadMessage/WriteMessage.
- It's not obvious which of the actively maintained MessagePack codecs is the best. Even if I were open to adding a third party dependency, the websocket package should not be choosing between these codecs.

It was a mistake to add the ReadJSON and WriteJSON methods to the connection type.  This functionality should have remained in the [ReadJSON](https://godoc.org/github.com/gorilla/websocket#ReadJSON) and [WriteJSON](https://godoc.org/github.com/gorilla/websocket#WriteJSON) helper functions.  The justification for having these helper functions is that they are very useful in the core use case of communicating with a browser client and they do not add a dependency on third party packages.

**Comment by rocketbitz** [comment]
Understood. I figured that the third-party dependency was the main barrier to entry, and as of right now unavoidable.
