### ISSUE TITLE
timeout while receiving big message

### ISSUE THREAD

**Issue by tzapu** [gorilla/websocket#355]
Hello and thank you very much for this lovely library.

I have a problem, most likely because i missed something but when using SetReadDeadline together with a pong handler (and sendings pings ofc) the connection is timing out before being able to receive everything (something around 100MB/message)

Is there a way to prolong the timeout while actively receiving bytes from the server? In my mind that would make sense because it's obvious the connection is still active, but maybe the timeout is supposed to be a hard one, no matter what the state of the connection.

Cheers

**Comment by garyburd** [comment]
> Is there a way to prolong the timeout while actively receiving bytes from the server? 

Call SetReadDeadline in the loop that's reading the data from the message.

**Comment by tzapu** [comment]
i was using `ReadMessage`, i assume i should be using something like `conn.NextReader()` for being able to call SetReadDeadline, right?

and again, thank you

**Comment by garyburd** [comment]
Yes, call conn.NextReader().  Either set a long deadline following this call or set shorter deadlines as the application slurps up the message.

**Comment by tzapu** [comment]
thank you very much
