### ISSUE TITLE
Multiple messages in-flight over one connection?

### ISSUE THREAD

**Issue by brianblakewong** [gorilla/websocket#365]
This is the use-case I'm considering:

One server generates a message about every millisecond, and sends this message to one client. The transmission time between the server and the client is 50ms with low variance. The client wants low latency (to receive each message ~50ms after it is generated) and the ordering of the messages must be maintained.

Here's a websocket solution modeled after the chat application example: the server has a writePump goroutine with a channel buffer. Every time the server generates a message it'll push it onto the buffer. Each time the goroutine notices that its buffer is nonempty, it'll coalesce all the outstanding messages into one, and send that over websocket to the client. 

This would result in undesirable behavior because the transmission time is much greater than the delay between messages. After the first message is generated, the writePump goroutine will start sending the websocket message to the client. After 50ms, it'll check back to find that about 50 new messages have accumulated, and it'll send all these in a batch.

If we start timing in milliseconds, 
Message 1 (generated at time 1), received by client at time 51.
Message 2 (generated at time 2), received by client at time 101. **Very stale**
Message 3 (generated at time 3), received by client at time 101.
Message 4 (generated at time 4), received by client at time 101.
...
Message 50 (generated at time 50), received by client at time 101.
Message 51 (generated at time 51), received by client at time 151. **Very stale**
Message 52 (generated at time 52), received by client at time 151.
...

Is there a solution that gives a time profile like the following:
Message 1 (generated at time 1), received by client at time 51.
Message 2 (generated at time 2), received by client at time 52.
Message 3 (generated at time 3), received by client at time 53.

The only workaround I can think of is to allow multiple websocket messages to be in-flight over the same connection at one time, like pushing two beads down a long straw at the same time, rather than waiting for the first bead to come out on the other side before sending the next bead. Is this possible? It seems to violate the mandate that only one goroutine have access to each websocket connection. It might also require the client to handle reordering of messages (is this done automatically by the websocket?)

I am pretty new to Network I/O, so there's a good chance I am missing something obvious. Please let me know if there's a workaround, or a different protocol than websocket that could accomplish this without too much of a headache.

Thank you!

**Comment by garyburd** [comment]
Write operations complete when the data is written to the operating system, not when the data is received by the peer.  The package does not impose a limit on the number of messages inflight.

**Comment by brianblakewong** [comment]
Oh! That's brilliant. Just got a test working on a remote server and it looks great. Would you mind explaining a bit more of how this works internally? Does the operating system keep a buffer of outgoing messages for the network? Does it send them one at a time? If it doesn't wait for the first to arrive before sending the second, does it do fancy reordering on the client?

Particularly interested because I'm coming from Python's asyncio websocket, which doesn't allow multiple inflight messages on one connection.

**Comment by garyburd** [comment]
There are many resources on the web and books that describe the TCP protocol and how it's implemented.  It's off topic here.
