### ISSUE TITLE
Protocol Error: Unexpected reserved bits

### ISSUE THREAD

**Issue by romshark** [gorilla/websocket#366]
Trying to implement automatic reconnection on connection loss in [WebWire](https://github.com/qbeon/webwire-go/tree/background-autoconnect) which is based on this library.

When the server goes away and the client successfuly reconnects to it when it's back again - most of the time the first message sent by the reconnected client causes the server to close the new reestablished connection with **1002 (protocol error): unexpected reserved bits 0x50**. Sometimes it's **0x50**, sometimes **0x60** or **0x70**, sometimes it even (rarely) works fine, but the second or third message causes it, it's like totaly random.

[Here I create the connection](https://github.com/qbeon/webwire-go/blob/background-autoconnect/client/connect.go#L33) using the default dialer overwriting the old connection, there should theoretically be no state on it to cause such an error, but it still fails for some reason

Any idea what it might be? Is it my fault?

**Comment by garyburd** [comment]
Run your application with the race detector and report back after any races are fixed.

**Comment by romshark** [comment]
Indeed, the race detector detected unsynchronized access to `conn.ReadMessage` caused by a tricky concurrency bug, which is now fixed and works like a charm!

Sorry for the inconvenient issue
