### ISSUE TITLE
upgrade:websocket: request origin not allowed by Upgrader.CheckOrigin

### ISSUE THREAD

**Issue by fghjhuang** [gorilla/websocket#367]
i use the server echo to test,but get this error,can you help me? i am not so good at golang
`package main

import (
	"flag"
	"log"
	"net/http"

	"github.com/gorilla/websocket"
)

var addr = flag.String("addr", ":80", "http service address")

var upgrader = websocket.Upgrader{} // use default options

func echo(w http.ResponseWriter, r *http.Request) {
	c, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Print("upgrade:", err)
		return
	}
	defer c.Close()
	for {
		mt, message, err := c.ReadMessage()
		if err != nil {
			log.Println("read:", err)
			break
		}
		log.Printf("recv: %s", message)
		err = c.WriteMessage(mt, message)
		if err != nil {
			log.Println("write:", err)
			break
		}
	}
}

func main() {
	flag.Parse()
	log.SetFlags(0)
	http.HandleFunc("/", echo)
	log.Fatal(http.ListenAndServe(*addr, nil))
}`

**Comment by garyburd** [comment]
See https://godoc.org/github.com/gorilla/websocket#hdr-Origin_Considerations.

**Comment by fghjhuang** [comment]
add to check :CheckOrigin: func(r *http.Request) bool {
		return true
	},

**Comment by mask3000** [comment]
Insert “upgrader.CheckOrigin = func(r *http.Request) bool { return true }”  before  ”conn, err := upgrader.Upgrade(w, r, nil)”

**Comment by elithrar** [comment]
You should never blindly trust any Origin by `return true`. 

Have the function range over a list of accepted origins.
