### ISSUE TITLE
Parallelize WriteMessage() across goroutines?

### ISSUE THREAD

**Issue by brianblakewong** [gorilla/websocket#369]
I'm having trouble scaling my websocket to 10,000+ clients. Each WriteMessage() call takes about 100 microseconds, and even though each client's connection is managed on a separate goroutine, these writes seem to be not handled concurrently, which caps me at 1 message / second. Here's sample code:

```
import (
    "log"
    "time"
    "github.com/gorilla/websocket"
)

var start int64

func write(conn *websocket.Conn) {
    conn.WriteMessage(websocket.TextMessage, []byte("donkey"))
    end := time.Now().UnixNano()
    log.Printf("Nanos elapsed: %d", end-start)
}

func main() {
    conn1, _, _ := websocket.DefaultDialer.Dial(addr, nil)
    conn2, _, _ := websocket.DefaultDialer.Dial(addr, nil)
    start = time.Now().UnixNano()
    write(conn1)
    write(conn2)
}
```

Output:
```
$ go run src/test/testWebsocketSendBlocking.go
2018/03/31 17:55:54 Nanos elapsed: 90815
2018/03/31 17:55:54 Nanos elapsed: 329490
```

The total time is always more than twice the time required for one WriteMessage.

Is there any workaround here, or is it impossible to parallelize WriteMessage() on different connections?

Thanks!

**Comment by garyburd** [comment]
This package does not impose any limits on concurrent writes to different websocket connections. Websocket connections are independent of each other.

**Comment by brianblakewong** [comment]
Right, but it seems that goroutines can't actually WriteMessage() in parallel. This is about a 100 microsecond operation, and if 10 separate goroutines run WriteMessage() concurrently, the last one will still finish >1 millisecond later, as if they were all run on one goroutine.

Is there any workaround to this? Or perhaps it is just that the underlying kernel thread must actually do 100 mics of work per WriteMessage(), so concurrency doesn't help here...

**Comment by garyburd** [comment]
In the example application, the package calls [Write](https://godoc.org/net#Conn.Write) on the underlying network connection for each call to [WriteMessage](https://godoc.org/github.com/gorilla/websocket#Conn.WriteMessage).  These calls are made on the application's goroutine.    Any performance issue is outside the control of this package.
