### ISSUE TITLE
Chat Example  unavailable

### ISSUE THREAD

**Issue by 107295472** [gorilla/websocket#371]
Error loading page
websocket: close 1001 (going away)

**Comment by garyburd** [comment]
Describe the steps you used to run this example.

**Comment by 107295472** [comment]
@garyburd 
![20180404103923](https://user-images.githubusercontent.com/6436116/38285820-99083536-37f4-11e8-83e0-dea7cff6537f.png)
![20180404104014](https://user-images.githubusercontent.com/6436116/38285821-9962708c-37f4-11e8-9e6c-e5afb2553f41.png)

**Comment by garyburd** [comment]
What is the command you used to run to the server?  What URL did you open in the browser?  What action, if any, resulted in that message?

**Comment by 107295472** [comment]
@garyburd Is the code in the chat example, the page is loaded and the connection is closed

**Comment by garyburd** [comment]
What is the command you used to run to the server? What URL did you open in the browser?

**Comment by 107295472** [comment]
Can't you do this? 
   conn = new WebSocket("ws://localhost:8080/ws");
   conn.send("sdfsdfds");

I want to send data when loading @garyburd

**Comment by 107295472** [comment]
Yes, onopen

**Comment by garyburd** [comment]
I am closing this issue because the problem does not appear to be with the example application.
