### ISSUE TITLE
WebSocket Protocol violation

### ISSUE THREAD

**Issue by Toorion** [gorilla/websocket#374]
According to rfc6455 in handshake should be written "Sec-WebSocket" in terms like:
Sec-WebSocket-Accept:
Sec-Websocket-Protocol:
Sec-Websocket-Version:
But in your implementation "Sec-Websocket" (with small "s").
Some of pedantic protocols unfortunately can't connect with this implementation.

**Comment by garyburd** [comment]
See 21ab95fa12b9bdd8fecf5fa3586aad941cc98785

**Comment by Toorion** [comment]
Thank you so much!

**Comment by garyburd** [comment]
Which library are you using?   

Please report an issue with that library.  The header names are case insensitive.
