### ISSUE TITLE
close 1000 (normal): read tcp ...: read: connection reset by peer

### ISSUE THREAD

**Issue by prologic** [gorilla/websocket#378]
This is unlikely to be a problem with this library, but I'm documenting my observations here for future readers and users of this library. I'm experiencing an issue where the "server" sees an `RST` but I'm pretty sure it's **not** coming from the client(s) but something in-between. My suspicion is either the Traefik load balancer I'm using (*unlikely*) or the Overlay networking in Docker Swarm or some docker networking internals.

Server logs:

```
msgbus_msgbus.1.wwi937nop3bx@dm4.mills.io    | time="2018-05-07T00:39:20Z" level=debug msg="recieved close from client 10.0.2.17:46442"
msgbus_msgbus.1.wwi937nop3bx@dm4.mills.io    | time="2018-05-07T00:39:20Z" level=debug msg="[msgbus] Unsubscribe id=10.0.2.17:46442 topic=hello"
msgbus_msgbus.1.wwi937nop3bx@dm4.mills.io    | time="2018-05-07T00:39:20Z" level=error msg="error reading from 10.0.2.17:46442: websocket: close 1000 (normal): read tcp 10.255.0.13:443->10.255.0.3:54633: read: connection reset by peer"
```

I'm able to reproduce this by:

* `docker stack deploy msgbus.yml` (*see below*)
* msgbus sub hello (*on my Mac*)

So this is going from Mac (*over WIFI*) to my server(s) to `msgbus` running as a service in a Docker Swarm cluster.

`msgbus.yml`:

```#!yaml
version: "3.3"

services:
  msgbus:
    image: prologic/msgbus
    command: -d
    networks:
      - prometheus
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.backend=msgbus"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:msgbus.mills.io"
      restart_policy:
        condition: on-failure
      replicas: 1

networks:
  prometheus:
    external: true
  traefik:
    external: true
```

**Comment by dottyjones** [comment]
The client sent a close frame with code 1000 (normal closure) and the message text "read tcp 10.255.0.13:443->10.255.0.3:54633: read: connection reset by peer".  That's an strange message for the client to send, but it does not indicate that server received a RST.

What are you expecting from the maintainers of this package?  Do you think there's a bug to be fixed or something that needs to be documented?  If not, you should close the issue.

**Comment by prologic** [comment]
I'm doing packet captures to understand this as I write this (*not done yet*).

Expectations: To improve documentation (*if at all*).

I'd prefer to keep this open until I get to the bottom of it; There is no *known* code client-side that would cause this.

**Comment by dottyjones** [comment]
If the third line of the server log in the issue  [is generated on this line](https://github.com/prologic/msgbus/blob/0215f6f9a85580202a0caf10eafd6b04d9174c97/msgbus.go#L524), then it's almost certainly the case that a client sent the text "read tcp 10.255.0.13:443->10.255.0.3:54633: read: connection reset by peer".

If there is nothing that you expect from the maintainers of this package at this time, then you should close and continue your work elsewhere.

**Comment by prologic** [comment]
@dottyjones I would agree with you *except* that the client(s) **never** send a close control message.

**Comment by dottyjones** [comment]
The log message 

    msgbus_msgbus.1.wwi937nop3bx@dm4.mills.io    | time="2018-05-07T00:39:20Z" level=error msg="error reading from 10.0.2.17:46442: websocket: close 1000 (normal): read tcp 10.255.0.13:443->10.255.0.3:54633: read: connection reset by peer

is generated [by this application code](https://github.com/prologic/msgbus/blob/0215f6f9a85580202a0caf10eafd6b04d9174c97/msgbus.go#L524):

    log.Errorf("error reading from %s: %s", c.id, err)

The `log.Errorf` function calls the [Error() string](https://godoc.org/builtin#error.Error) method to convert `err` to the string

    websocket: close 1000 (normal): read tcp 10.255.0.13:443->10.255.0.3:54633: read: connection reset by peer

This is the format used by [websocket.CloseError](https://github.com/gorilla/websocket/blob/21ab95fa12b9bdd8fecf5fa3586aad941cc98785/conn.go#L112).  The string 
 
     read tcp 10.255.0.13:443->10.255.0.3:54633: read: connection reset by peer

comes from the [CloseError.Text](https://github.com/gorilla/websocket/blob/21ab95fa12b9bdd8fecf5fa3586aad941cc98785/conn.go#L141-L143/21ab95fa12b9bdd8fecf5fa3586aad941cc98785/conn.go#L112) field.  

The CloseError.Text field is set using data read from the peer [here](https://github.com/gorilla/websocket/blob/21ab95fa12b9bdd8fecf5fa3586aad941cc98785/conn.go#L892-L907).

It does seem odd for an endpoint to send normal close (code 1000) with what looks like an error message, but that's what the client did.

As far as the use of this package in your application is concerned, nothing is out of the ordinary.  I suggest following up on the load balancer and the client.

**Comment by prologic** [comment]
@dottyjones The weird part is that the client-side doesn't seem to get an
error from the conn.ReadJSON call. Following the code path; I expect to get
the same error client-side so I know to reconnect. I've also (by process of
elimination) ruled out any issues with gorilla/websocket (I never suspected
any in the first place). If I run msgbus without using the swarm overlay
networking (IPVS stuff) it works fine. docker run -p 8000:8000
prologic/msgbus


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
@dottyjones I'm not sure actually (*how would I know?*) -- I'm using [Traefik](https://github.com/containous/traefik)

I've been digging into this further; and after implementing ping/pong in both directions (*was only doing this server->client*) I haven't been able to repro this behavior so far.

How familiar are you with Docker's IPVS load balancing and Overlay networking? If one side of the TCP session sends no data for a period of time does this affect IPVS in some way that would drop the session?

FWIW there are numerous issues on this subject in the moby and swarm project issue trackers but I haven't been able to pinpoint this to a particular thing yet.

**Comment by dottyjones** [comment]
Ask questions about Dcoker and Traefek in forums specific to those tools.  I am not a maintainer of this package (are there any?), but I'd think they would to limit discussion here to the websocket package.

**Comment by prologic** [comment]
@dottyjones Agreed; after many hours of testing, I can no longer repro this behavior with two-way ping/pong in both directions So I'll close this. This *has* to be some kind of IPVS / Overlay issue in Docker Swarm mode services (*running `docker run -d -p 8000:8000 prologic/msgbus` directly which doesn't use IPVS or Overlay networking also doesn't exhibit this behavior*)
