### ISSUE TITLE
concurrent write to websocket connection

### ISSUE THREAD

**Issue by github-steven** [gorilla/websocket#380]
panic("concurrent write to websocket connection"), support concurrent writes?   example documents?

**Comment by JordanP** [comment]
Hi,
It's not because you are posting on Internet that you should be rude or not make complete sentence. 

The document you are looking for is here: https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency

**Comment by dottyjones** [comment]
A general rule of thumb in Go is that types do not support concurrent use unless documented to do so.  In the case of this package, the [documentation covers what is allowed and not allowed](https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency).

The examples in this project show how manage concurrency.  The [chat example](https://github.com/gorilla/websocket/tree/master/examples/chat#readme) is a good place to start.

**Comment by dottyjones** [comment]
@elithrar OP's questions were answered.  This can be closed.
