### ISSUE TITLE
Co-existence with gorilla gin, websocket just not working

### ISSUE THREAD

**Issue by jinfagang** [gorilla/websocket#381]
Very weired problem. Here is the reproduce code:

```
package main



import (
	"log"
	"fmt"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	"github.com/gin-gonic/gin"
	"net/http"
)


// build all routes here
func BuildRoutes() *gin.Engine{
	r := gin.Default()

	// set the v1 version group
	v1 := r.Group("/api/v1")
	{
		// user register and get
		v1.POST("/users", nil)
		v1.GET("/users", nil)

		// user status and get
		v1.POST("/status", nil)
		v1.GET("/status", nil)
	}

	return r
}

// serve the websocket
func wsServe(){
	// serve the js client

	http.HandleFunc("/a", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("FUCK!! called a???")
	})

	err := http.ListenAndServe(":9877", nil)
	if err != nil {
		log.Fatal("ListenAndServe: ", err)
	}
}

func main() {
	gin.SetMode(gin.DebugMode)


	// APIs routes part
	route := BuildRoutes()
	route.Run(":8080")

	// websocket services part
	// open websocket...
	go wsServe()
}


```

Using gin as API routes, and custom websocket using native http, but that http just not response, what am I doing wrong or this is a bug?

**Comment by elithrar** [comment]
What are you expecting to see, and what are you actually seeing?

You aren’t using gorilla/websocket in any of your code.

You should look at the examples if you are writing a websocket server:
https://github.com/gorilla/websocket/tree/master/examples

**Comment by jinfagang** [comment]
Aha.... Damn it, I almost forgot do anything.... Already found it out cause the route.Run() made the rest code are dead.

**Comment by dottyjones** [comment]
It's not necessary to run a separate server for websockets.  See http://arlimus.github.io/articles/gin.and.gorilla/

**Comment by dottyjones** [comment]
@elithrar This can be closed. There's an error in OP's program (main blocks serving :8080 before starting ws server).
