### ISSUE TITLE
Server instantly closes?

### ISSUE THREAD

**Issue by TurtleGamingFTW** [gorilla/websocket#382]
So I'm using gorilla WebSocket to create this function
```go
func (lava *lavalink) createNode(client *discordgo.Session, node Node) {
	headers := http.Header{}

	headers.Add("User-Id", client.State.User.ID)
	headers.Add("Num-Shards", strconv.Itoa(lava.Shards))
	headers.Add("Authorization", node.Password)

	dialer := websocket.Dialer{}
	server := "ws://" + node.Host + ":" + node.Port + "/"
	c, http, err := dialer.Dial(server, headers)
	fmt.Println(http.Header)
	if err != nil {
		fmt.Println(err)
	}
}
```
but when i open up the WebSocket connection, it instantly closes on me after 5 seconds. Idk why

**Comment by dottyjones** [comment]
The code in the issue does not compile, nor is there any code that will detect that the server closed the connection after five seconds. Update the issue with the actual code.

Also, include any errors returned from Dial or method calls on the connection.

**Comment by garyburd** [comment]
I am closing this issue because there's no response from OP in over a month.
