### ISSUE TITLE
reasoning behind panic detection for concurrent writes

### ISSUE THREAD

**Issue by mlsquires** [gorilla/websocket#390]
I've read the other issues about this. I understand that the documentation says that the library does not support concurrent writes. I see this code to in conn.go

	// Write the buffers to the connection with best-effort detection of
	// concurrent writes. See the concurrency section in the package
	// documentation for more info.

	if c.isWriting {
		panic("concurrent write to websocket connection")
	}
	c.isWriting = true

	err := c.write(w.frameType, c.writeDeadline, c.writeBuf[framePos:w.pos], extra)

	if !c.isWriting {
		panic("concurrent write to websocket connection")
	}
	c.isWriting = false

Questions:
1. can the buffer already be trashed by concurrent operations prior to this check?
2. what would be the downside to replacing that detection logic with a simple mutex?

**Comment by kisielk** [comment]
Yes the buffer will likely be trashed, that's why this is a panic, to inform application authors they're doing something wrong.

**Comment by garyburd** [comment]
The buffer is trashed before the concurrent operation is detected.
