### ISSUE TITLE
Can not catch disconnect event

### ISSUE THREAD

**Issue by racketprogram** [gorilla/websocket#391]
I try to simulate websocket disconnect event, so I open a web client from Chrome browser and close it.
But I can't found any response about disconnect.

Could you help me ?

This is my code
```
var wsUpgrader = websocket.Upgrader{
	ReadBufferSize:   1024,
	WriteBufferSize:  1024,
	HandshakeTimeout: 5 * time.Second,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

func WSHandler(w http.ResponseWriter, r *http.Request) {
	conn, err := wsUpgrader.Upgrade(w, r, nil)

	if err != nil {
		fmt.Println(err.Error())
		return
	}

	for {
		messageType, _, err := conn.ReadMessage()

		fmt.Println(messageType)

		if err != nil {
			fmt.Println("over")
			break
		}
	}
}
```

**Comment by dottyjones** [comment]
`ReadMessage` returns an error when a close message is received or when the network stack detects a disconnect.  Use read deadlines and ping/pong messages to reliably detect all disconnects.

**Comment by racketprogram** [comment]
read deadlines ? what do you mean?

**Comment by dottyjones** [comment]
@racketprogram Read [the documentation for information about deadlines](https://godoc.org/github.com/gorilla/websocket#Conn.SetReadDeadline).  Also, see the examples.

**Comment by MiikeWilliams** [comment]
Hey @racketprogram 

I think what you are looking for is in the chat example here...

https://github.com/gorilla/websocket/blob/master/examples/chat/client.go#L57

Basically when the connection returns you could defer and do whatever you want.

**Comment by garyburd** [comment]
The comments from ghost and MiikeWilliams answer the question.
