### ISSUE TITLE
What exactly ping/pong do in the chat example?

### ISSUE THREAD

**Issue by khawerrind** [gorilla/websocket#392]
When i run the chat example locally, i don't see any ping messages in the client. Neither i see javascript handling of the pong replies. So what exactly ping/pong in the chat example really do?

**Comment by elithrar** [comment]
Your browser implicitly handles ping/pong frames and won’t show them in the
inspector (in Chrome).

**Comment by elithrar** [comment]
FYI - https://tools.ietf.org/html/rfc6455#section-5.5

(Going to close this out for now, but feel free to ask follow-up questions; happy to help)
