### ISSUE TITLE
why need <-c.send??

### ISSUE THREAD

**Issue by arkadybag** [gorilla/websocket#394]
Hello, i read chat example and not understand, why need this?
https://github.com/gorilla/websocket/blob/5ed622c449da6d44c3c8329331ff47a9e5844f71/examples/chat/client.go#L108

also, if we already read from channel this -- https://github.com/gorilla/websocket/blob/5ed622c449da6d44c3c8329331ff47a9e5844f71/examples/chat/client.go#L90

**Comment by garyburd** [comment]
The [comment in the code](https://github.com/gorilla/websocket/blob/5ed622c449da6d44c3c8329331ff47a9e5844f71/examples/chat/client.go#L104) states the reason:  the example appends queued chat messages to the websocket message.

[Coalescing multiple chat messages into a single websocket message](https://github.com/gorilla/websocket/blob/5ed622c449da6d44c3c8329331ff47a9e5844f71/examples/chat/client.go#L105-L109) is an optimization.  This optimization is not required.
