### ISSUE TITLE
Fragment Size is not buffer size 

### ISSUE THREAD

**Issue by SergeVL** [gorilla/websocket#395]
Really I can't find size of message when Chrome starts using fragmentation, but I hope
it exists. Anyway it is not 4K.

But in accordance with RFC6455:

> A sender MAY create fragments of any size for non-control
      messages.

Your implementation limits the size of the fragment to the size of the buffer (by default 4K).
As a result traefik proxy server can't send to backend messages longer then 4K.

**Comment by garyburd** [comment]
This package can send a message of any size and will fragment messages in some circumstances.  As the quote from the RFC states, message fragmenting is allowed. 

This package can receive a message of any size, independent of any fragmenting. 

If the  traefik server cannot handle fragmented messages, then report the issue with the traefik server.

**Comment by SergeVL** [comment]
Sorry.
I use websocket to send document to editor in browser and back to server.
Sending to browser is without problems. I assume that python websocket implementation uses a fragmentation.
But on sending from browser to server packet was trimmed.
When I increased the defaultReadBufferSize and defaultWriteBufferSize in gorilla/websocket/conn.go the problem disappeared. But appeared again with larger than buffer size document.
And traefik use yours last version code.

**Comment by garyburd** [comment]
This package does not trim messages.  Based on a quick look at the traefik code, I don't see anything there that will trim a message.   It sounds like the backend server does not support fragmented messages. What is the backend server?

**Comment by SergeVL** [comment]
When working without proxy problem absent.
On the backend side [gevent-websocket](https://github.com/jgelens/gevent-websocket). Citation:
`
def read_message(self):

    message = bytearray()

    while(True):

        header, payload = self.read_frame()
        
        ...

       message += payload

       if header.fin:

                break

    return message
`

**Comment by SergeVL** [comment]
And:
 header.fin = first_byte & FIN_MASK == FIN_MASK
FIN_MASK = 0x80

**Comment by garyburd** [comment]
Does gevent-websocket report an error when reading the fragmented message?  Can the application continue to read the websocket after reading the fragmented message?

**Comment by elithrar** [comment]
I can take a look at this on the weekend.

If the OP can help reproduce with the topology described by Gary, it’d help
speed things up.

**Comment by elithrar** [comment]
@sergeVL 

Can you document the parts at play here? Where does socket.io fit in, since this is the first time you’ve mentioned it. Diagram (ASCII is OK) would be great. 

I want to spin up the same client, Traefik, gevent backend to replicate this first. We need a standalone repro with an echo backend, and then we can look at Traefik & client-side by process of elimination.

**Comment by SergeVL** [comment]
I will make some test/simplified environment

**Comment by garyburd** [comment]
Closing because no response from OP in a month.
