### ISSUE TITLE
lots of goroutines still blocked when the connection is closed

### ISSUE THREAD

**Issue by LichFaker** [gorilla/websocket#396]
I use `locust` to stress-test the websocket server, but the memory usage keep growing. 

Here is the goroutine stack dump:

```
goroutine 109357 [IO wait]:
internal/poll.runtime_pollWait(0x7faa3c0667e0, 0x72, 0xc420655e58)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42014e118, 0x72, 0xffffffffffffff00, 0xa03060, 0xc436e8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42014e118, 0xc42833c100, 0x1, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42014e100, 0xc42833c101, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42014e100, 0xc42833c101, 0x1, 0x1, 0xc429643200, 0x0, 0xc421f4c098)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200a8020, 0xc42833c101, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc42833c0f0)
	/usr/local/go/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:664 +0xce

goroutine 109395 [IO wait]:
internal/poll.runtime_pollWait(0x7faa341479f0, 0x72, 0xc420250868)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42014e018, 0x72, 0xffffffffffffff00, 0xa03060, 0xc436e8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42014e018, 0xc426c9c000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42014e000, 0xc426c9c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42014e000, 0xc426c9c000, 0x1000, 0x1000, 0xc420250978, 0x6905bb, 0x944760)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4201be000, 0xc426c9c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
net/http.(*connReader).Read(0xc429a76030, 0xc426c9c000, 0x1000, 0x1000, 0x100000, 0x7faa3e894d90, 0x3)
	/usr/local/go/src/net/http/server.go:764 +0xf8
bufio.(*Reader).fill(0xc4204a09c0)
	/usr/local/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).ReadSlice(0xc4204a09c0, 0xc420250a0a, 0xc420250ad8, 0x411a06, 0x7faa1d789130, 0x0, 0xc420250ab8)
	/usr/local/go/src/bufio/bufio.go:341 +0x2c
bufio.(*Reader).ReadLine(0xc4204a09c0, 0xc426856000, 0x100, 0xf8, 0x986860, 0x1, 0x100c420044c00)
	/usr/local/go/src/bufio/bufio.go:370 +0x34
net/textproto.(*Reader).readLineSlice(0xc429a76060, 0xc42009c701, 0xc420250ba8, 0x4126e8, 0x100, 0x986860)
	/usr/local/go/src/net/textproto/reader.go:55 +0x70
net/textproto.(*Reader).ReadLine(0xc429a76060, 0xc426856000, 0x0, 0x0, 0x72)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2b
net/http.readRequest(0xc4204a09c0, 0x0, 0xc426856000, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:929 +0x8c
net/http.(*conn).readRequest(0xc4200da140, 0xa07520, 0xc421f4c0c0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:944 +0x16f
net/http.(*conn).serve(0xc4200da140, 0xa07520, 0xc421f4c0c0)
	/usr/local/go/src/net/http/server.go:1768 +0x4dc
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by LichFaker** [comment]
Confirm the problem is not caused by `gorilla/websocket` ?  

I think that when using `net/http`, it doesn't seem to close it properly. There is still a read goroutine blocking in the background, which causes memory surge and slow response.

And I found a blog [https://go-review.googlesource.com/c/go/+/31173](https://go-review.googlesource.com/c/go/+/31173) mentions this issue.

**Comment by wangjingnan** [comment]
> I use `locust` to stress-test the websocket server, but the memory usage keep growing.
> 
> Here is the goroutine stack dump:
> 
> ```
> goroutine 109357 [IO wait]:
> internal/poll.runtime_pollWait(0x7faa3c0667e0, 0x72, 0xc420655e58)
> 	/usr/local/go/src/runtime/netpoll.go:173 +0x57
> internal/poll.(*pollDesc).wait(0xc42014e118, 0x72, 0xffffffffffffff00, 0xa03060, 0xc436e8)
> 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
> internal/poll.(*pollDesc).waitRead(0xc42014e118, 0xc42833c100, 0x1, 0x1)
> 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
> internal/poll.(*FD).Read(0xc42014e100, 0xc42833c101, 0x1, 0x1, 0x0, 0x0, 0x0)
> 	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
> net.(*netFD).Read(0xc42014e100, 0xc42833c101, 0x1, 0x1, 0xc429643200, 0x0, 0xc421f4c098)
> 	/usr/local/go/src/net/fd_unix.go:202 +0x4f
> net.(*conn).Read(0xc4200a8020, 0xc42833c101, 0x1, 0x1, 0x0, 0x0, 0x0)
> 	/usr/local/go/src/net/net.go:176 +0x6a
> net/http.(*connReader).backgroundRead(0xc42833c0f0)
> 	/usr/local/go/src/net/http/server.go:668 +0x5a
> created by net/http.(*connReader).startBackgroundRead
> 	/usr/local/go/src/net/http/server.go:664 +0xce
> 
> goroutine 109395 [IO wait]:
> internal/poll.runtime_pollWait(0x7faa341479f0, 0x72, 0xc420250868)
> 	/usr/local/go/src/runtime/netpoll.go:173 +0x57
> internal/poll.(*pollDesc).wait(0xc42014e018, 0x72, 0xffffffffffffff00, 0xa03060, 0xc436e8)
> 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
> internal/poll.(*pollDesc).waitRead(0xc42014e018, 0xc426c9c000, 0x1000, 0x1000)
> 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
> internal/poll.(*FD).Read(0xc42014e000, 0xc426c9c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
> 	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
> net.(*netFD).Read(0xc42014e000, 0xc426c9c000, 0x1000, 0x1000, 0xc420250978, 0x6905bb, 0x944760)
> 	/usr/local/go/src/net/fd_unix.go:202 +0x4f
> net.(*conn).Read(0xc4201be000, 0xc426c9c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
> 	/usr/local/go/src/net/net.go:176 +0x6a
> net/http.(*connReader).Read(0xc429a76030, 0xc426c9c000, 0x1000, 0x1000, 0x100000, 0x7faa3e894d90, 0x3)
> 	/usr/local/go/src/net/http/server.go:764 +0xf8
> bufio.(*Reader).fill(0xc4204a09c0)
> 	/usr/local/go/src/bufio/bufio.go:100 +0x11e
> bufio.(*Reader).ReadSlice(0xc4204a09c0, 0xc420250a0a, 0xc420250ad8, 0x411a06, 0x7faa1d789130, 0x0, 0xc420250ab8)
> 	/usr/local/go/src/bufio/bufio.go:341 +0x2c
> bufio.(*Reader).ReadLine(0xc4204a09c0, 0xc426856000, 0x100, 0xf8, 0x986860, 0x1, 0x100c420044c00)
> 	/usr/local/go/src/bufio/bufio.go:370 +0x34
> net/textproto.(*Reader).readLineSlice(0xc429a76060, 0xc42009c701, 0xc420250ba8, 0x4126e8, 0x100, 0x986860)
> 	/usr/local/go/src/net/textproto/reader.go:55 +0x70
> net/textproto.(*Reader).ReadLine(0xc429a76060, 0xc426856000, 0x0, 0x0, 0x72)
> 	/usr/local/go/src/net/textproto/reader.go:36 +0x2b
> net/http.readRequest(0xc4204a09c0, 0x0, 0xc426856000, 0x0, 0x0)
> 	/usr/local/go/src/net/http/request.go:929 +0x8c
> net/http.(*conn).readRequest(0xc4200da140, 0xa07520, 0xc421f4c0c0, 0x0, 0x0, 0x0)
> 	/usr/local/go/src/net/http/server.go:944 +0x16f
> net/http.(*conn).serve(0xc4200da140, 0xa07520, 0xc421f4c0c0)
> 	/usr/local/go/src/net/http/server.go:1768 +0x4dc
> created by net/http.(*Server).Serve
> 	/usr/local/go/src/net/http/server.go:2795 +0x27b
> ```

最后是发现什么原因了吗？我也遇到了。

**Comment by ask4ralph** [comment]
Hello,
Were you able to determine the root cause?
Thanks
