### ISSUE TITLE
Measure compressed payload size

### ISSUE THREAD

**Issue by stephen** [gorilla/websocket#397]
I'm interested in measuring how much data the server is writing to the websocket. I can see a way for me to do that for the uncompressed size by measuring the payload before it gets passed to the websocket writer.

I'm curious if there would be a way to do that post-compression, if this library is interested in supporting that use case, and what the rough code changes might look like for that.

**Comment by kisielk** [comment]
That seems like something you should be able to implement by wrapping the `http.ResponseWriter` that's passed into the `Upgrade` function.

**Comment by stephen** [comment]
Thanks! Your suggestion seems to work well. I ended up with something like:
```golang
type InstrumentedResponseWriter struct {
	http.ResponseWriter
	http.Hijacker
}

func (w *InstrumentedResponseWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	conn, rw, err := w.Hijacker.Hijack()
	return &InstrumentedConn{Conn: conn}, rw, err
}

type InstrumentedConn struct {
	net.Conn
	BytesWritten int
}

func (w *InstrumentedConn) Write(p []byte) (n int, err error) {
	n, err = w.Conn.Write(p)
	w.BytesWritten += n
	return n, err
}

// ...
writer := &InstrumentedResponseWriter{ResponseWriter: w, Hijacker: w.(http.Hijacker)}
conn, err := upgrader.Upgrade(writer, r, nil)
```

It appears to me that the `Write()` on the `net.Conn` is what is ultimately used for writes.

**Comment by stephen** [comment]
This works pretty well for getting the raw number of bytes, but I haven't figured out how to correlate 1 logical write size to say, `WriteJSON`, since `conn.Write` gets called in a buffered manner.
