### ISSUE TITLE
Installing Chat Example: Set-Location : A positional parameter cannot be found that accepts argument 'list'.

### ISSUE THREAD

**Issue by Bobbeo** [gorilla/websocket#403]
I am following the instructions to build and run the chat example.
I'm guessing this isn't the right command for powershell. When I execute the following command from powershell:

> cd `go list -f '{{.Dir}}' github.com/gorilla/websocket/examples/chat`

I get the following output:

> Set-Location : A positional parameter cannot be found that accepts argument 'list'.
> At line:1 char:1
> + cd `go list -f '{{.Dir}}' github.com/gorilla/websocket/examples/chat`
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
>     + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by elithrar** [comment]
The “cd” (SetLocation) at the start can’t be combined with “go list”.

**Comment by garyburd** [comment]
The problem line sets the current working directory to the output of `go list -f '{{.Dir}}' github.com/gorilla/websocket/examples/chat` using Bourne shell syntax.  Use whatever syntax is appropriate for Powershell or execute `go list -f '{{.Dir}}' github.com/gorilla/websocket/examples/chat` to find the directory and manually type the appropriate change directory command.
