### ISSUE TITLE
JSON Data fragmentation isssue

### ISSUE THREAD

**Issue by astromahi** [gorilla/websocket#405]
When we write a large JSON data around 10KiB on iOS client connection using `ws.WriteJSON(msg)`.
Client closes the connection replying with `normal closure(1000)`. 

**ISSUE**: Client couldn't detect fragmentation message that is come from gorilla and decide the message is invalid and closes the connection. The client does have the support for fragmentation.

Client using this library: [https://github.com/acmacalister/jetfire](url)

I would be happy If I get some insight on this issue.

Thanks,

**Comment by garyburd** [comment]
The client does not support the websocket protocol. Ask for help there.
