### ISSUE TITLE
Tag a v1.4.0 Release

### ISSUE THREAD

**Issue by elithrar** [gorilla/websocket#413]
Reminder for myself:

* Tag a v1.4.0 release with the changelog - there's been 45 commits since v1.2: https://github.com/gorilla/websocket/compare/v1.2.0...master
* Add Go module support to the package.

Plan is to tag v1.4.0 after https://github.com/gorilla/websocket/pull/412 is merged.

**Comment by stevenscott89** [comment]
Should there be a tag just before #412 for those who are stuck on an old version of Go?

**Comment by elithrar** [comment]
Sure, I can tag v1.2.1 as the "last" Go < 1.7 release as well.

**Comment by elithrar** [comment]
https://github.com/gorilla/websocket/releases/tag/v1.3.0

**Comment by elithrar** [comment]
Done. https://github.com/gorilla/websocket/releases/tag/v1.4.0
