### ISSUE TITLE
Binary data getting corrupted when sent over websocket

### ISSUE THREAD

**Issue by driusan** [gorilla/websocket#418]
I'm trying to use gorilla/websocket to send binary data, and occasionally the data received isn't the same as what was sent. I reduced it to a test program which just sends a bunch of small packets with buf[i] = i  over the loopback device, and all the server does is verifies it and errors out if it's wrong, and after running it for a couple seconds I always get a packet that's been corrupted. I put my test code in a gist here: https://gist.github.com/driusan/2da1062cff4bb4505a3965ec93f1dff6

I'm running it under DragonFlyBSD and don't have access to any other OS to try, but to make sure it's not the OS's network stack corrupting the data I ran the same test with just a plain TCP connection from the net package and don't get any corruption happening.

**Comment by stevenscott89** [comment]
The application assumes that an entire message is read in a single call to the io.Reader Read method, but that's not guaranteed.   See the [io.Reader documentation](https://godoc.org/io#Reader) for more information.  

Use [io.ReadFull](https://godoc.org/io#ReadFull) to read an entire message:

```
func wsHandler(w http.ResponseWriter, req *http.Request) {
	packets := 0
	conn, err := upgrader.Upgrade(w, req, nil)
	if err != nil {
		log.Fatal(err)
	}
	for {
		rcv := make([]byte, testSize)
		_, r, err := conn.NextReader()
		if err != nil {
			log.Println(err)
			continue
		}
		_, err = io.ReadFull(r, rcv)
		if err != nil {
			log.Fatal(err)
		}
		for i := range rcv {
			if rcv[i] != byte(i%255) {
				log.Fatalf("Packet %d: %d != %d (%v)", packets, rcv[i], i, rcv)
			}
			packets++
		}
	}
}
```

**Comment by driusan** [comment]
You're right, that was a stupid mistake of me. (Although in this case I don't see why Read calls from the gorilla websocket wouldn't get the whole message when the size of each read is (significantly) smaller than the packet size of the device it's being sent on.)

**Comment by stevenscott89** [comment]
Partial reads are the result of [buffering by the package](https://github.com/gorilla/websocket/blob/66b9c49e59c6c48f0ffce28c2d8b8a5678502c6d/conn.go#L265), the network stack or both.
