### ISSUE TITLE
TLS connection timeout problem

### ISSUE THREAD

**Issue by silence44** [gorilla/websocket#420]
I'm trying to set websocket connection from one golang app to another one using tls.

On client side I do just simple connect:

```
u := url.URL{Scheme: "wss", Host: "localhost:8000", Path: "/server_client"}
conn, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
log.Info("Tried connect...")
```
On server side I have gin gonic with TLS:

```
r := gin.Default()

r.GET("/server_client", func(c *gin.Context) {
	s.wshandler(hub, c.Writer, c.Request)
})

return r.RunTLS(":8000", certFilePath, keyFilePath)
```
And **problem** that code on client side just stay on dialing forever. I mean that I can't see log "Tried connect...". 

After 10 minutes I killed client app process I saw on server side this message: 
"http: TLS handshake error from [::1]:50194: read tcp [::1]:8000->[::1]:50194: read: connection reset by peer"

All the time I was using my local certificate and after few hours I fixed issue with custom dialer config where I set:

`TLSClientConfig: &tls.Config{InsecureSkipVerify: true}`

Anyway without it my code was waiting forever for something I don't understand. I think it still may be an issue for somebody. Please tell me how I can help you to provide more details about my issue.

**Comment by stevenscott89** [comment]
Show the client code that  is "using my local certificate". 

Kill the client with SIGQUIT to dump the goroutine stack traces  and share the trace of the dialing goroutine here.  To kill with SIGQUIT, type ctrl-backslash on the terminal.

**Comment by silence44** [comment]
Ok, right now I rolled back my code to repeat the issue and now it does not stuck any more. 

So I'm receiving normal error from dialing with message: "ERRO[0004] x509: certificate is valid for Test, not localhost".  Which is normal behaviour I think.

I suppose It may be my antivirus holding connection or smth.

To my mind we can close this issue for now.

**Comment by elithrar** [comment]
Your certificate just isn’t valid, as it’s not signed by a root CA that
your machine (and thus, Go) can validate.

I can highly recommend mkcert (https://github.com/FiloSottile/mkcert) for
helping set up valid test certificates that don’t require you to set
InsecureSkipVerify (a dangerous setting to forget about!) in the client.

**Comment by elithrar** [comment]
Also look at using the new DialContext - as of
https://github.com/gorilla/websocket/releases/tag/v1.4.0 - that will let
you add a context with a deadline to your client connections.

**Comment by stevenscott89** [comment]
PR #429 includes a test with an invalid certificate. The test does not hang.

@silence44 Please share anything you can on how to reproduce this problem.

**Comment by silence44** [comment]
As I mentioned above I can't reproduce it anymore by myself. 
I think that was my antivirus blocking program execution with not valid certificate.

To my mind we can close this issue.
