### ISSUE TITLE
Why does upgrade function ask for GET and only GET method?

### ISSUE THREAD

**Issue by sotnikov-s** [gorilla/websocket#421]
Hello! According to [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism#Handshake) reading, if the client wants to upgrade the connection, it is able to use any method supported by the server. In your Upgrade function you check if the method is GET, and if not you return an error: [link](https://github.com/gorilla/websocket/blob/master/server.go#L123)
I'd appreciate if you could explain me why you've choosen such approach. And how I can handle request that has got to be upgraded and has got to have a body at the same time?
Thanks!

**Comment by stevenscott89** [comment]
The approach follows the WebSocket protocol as defined in RFC 6455.  The [section in the RFC about reading the client's handshake](https://tools.ietf.org/html/rfc6455#section-4.2.1) says:

>    The client's opening handshake consists of the following parts.  If
   the server, while reading the handshake, finds that the client did
   not send a handshake that matches the description below (note that as
   per [RFC2616], the order of the header fields is not important),
   including but not limited to any violations of the ABNF grammar
   specified for the components of the handshake, the server MUST stop
   processing the client's handshake and return an HTTP response with an
   appropriate error code (such as 400 Bad Request).
>   1.   An HTTP/1.1 or higher GET request, including a "Request-URI"
        [RFC2616] that should be interpreted as a /resource name/
        defined in Section 3 (or an absolute HTTP/HTTPS URI containing
        the /resource name/).

If the request is not a GET request, then the server must stop processing the request and return an HTTP response with an error code.
