### ISSUE TITLE
Disconnect on writeBuffer

### ISSUE THREAD

**Issue by qrpike** [gorilla/websocket#422]
I am trying to figure out how to determine when a client is disconnected because the writeBuffer was full. Is there an easy way to determine this?

Thanks,

**Comment by stevenscott89** [comment]
Are you asking how to determine if a peer is disconnected in general, or are you only referring to a case where some buffer is filled.  If the latter, which buffer are you referring to?

**Comment by qrpike** [comment]
Only when disconnected because of the buffer ( write buffer ). When a client connection isn’t processing the messages fast enough and it causes them to be disconnected.  

Thanks,

**Comment by stevenscott89** [comment]
Applications can set a [write deadline](https://godoc.org/github.com/gorilla/websocket#Conn.SetWriteDeadline) on the connection.  Other than that, this package does not disconnect clients that are not processing messages fast enough.   

The write buffer [referred to in the documentation](https://godoc.org/github.com/gorilla/websocket#Upgrader.WriteBufferSize) is used to buffer data written to the underlying network connection. When the buffer fills, the connection writes the buffered data to the underlying network connection .  There is no disconnect.

**Comment by garyburd** [comment]
As stated in the previous comment, this package does not disconnect a client because the write buffer was filled.

**Comment by qrpike** [comment]
@stevenscott89 What does happen when the buffer is filled?

**Comment by stevenscott89** [comment]
The data in the buffer is written to the underlying network connection and then the buffer state is reset for more data.

**Comment by qrpike** [comment]
@stevenscott89 I'm just trying to understand what happens when a client is being slow to consume messages. 

The project I'm working on sends thousands of messages/sec and if a client isn't consuming them fast enough, I am trying to understand the consequences of that. 

Thanks!

**Comment by stevenscott89** [comment]
That's a very different question.

If the buffers at the TCP layer fill, then write to the connection will block.  An application can control how long write blocks by setting the write deadline.

**Comment by qrpike** [comment]
Looking into this further, the code doesn't seem to take into consideration partial writes to the connection:

https://github.com/gorilla/websocket/blob/master/conn.go#L378

This sometimes happens when there is pressure on the connection. It currently considers a partial write fatal and closes the connection. Is there any plan to handle partial writes?

Thanks,

**Comment by stevenscott89** [comment]
The [io.Writer documentation](https://godoc.org/io#Writer.Write) says this:

> Write writes len(p) bytes from p to the underlying data stream. It returns the number of bytes written from p (0 <= n <= len(p)) and any error encountered that caused the write to stop early. Write must return a non-nil error if it returns n < len(p). Write must not modify the slice data, even temporarily.

Partial write implies an error writing to the underlying network connection.  Other than timeout error (which the application is  in control of), are there any other recoverable errors?

**Comment by qrpike** [comment]
@stevenscott89 

"If the write queue is not full and the user calls write(2), the system call will succeed. All of the data will be copied if the write queue has sufficient space. If the write queue only has space for some of the data then a partial write will happen and only some of the data will be copied to the buffer. The caller checks for this by checking the return value of write(2)."

We are seeing an issue when there is a huge spike in messages users are getting disconnected, even though the write deadline isn't close to being triggered. 

It seems it's happening because the underlying network buffer is nearly full and only part of the write is successful. This currently kills the connection, however it should be recoverable. 

Example: https://github.com/nats-io/gnatsd/blob/master/server/client.go#L694

Also, it seems using buffer.WriteTo actually uses writev which uses less syscalls as well.

**Comment by stevenscott89** [comment]
The network connection's Write method invokes the syscall in a loop until the data is written or there's an error. 

The websocket package uses buffer.WriteTo when writing multiple buffers to the network connection.
