### ISSUE TITLE
Socket.io over this package

### ISSUE THREAD

**Issue by haroldrandom** [gorilla/websocket#423]
Hi, guys.

Is there any possible to implement Socket.io protocol over this package?

**Comment by stevenscott89** [comment]
Yes.  This package provides everything that a Socket.io transport might need.

**Comment by haroldrandom** [comment]
@stevenscott89 Appreciate so much for your confirm!

Initially, my guess is as yours. But I got **failed** after reading some documents about socket.io.

Specifically, the doc is here: https://socket.io/docs/internals/#Upgrade

I was trying to simulate the socket.io protocol by following steps:
1. Make a HTTP GET request to the server, and then I got an open message with specific information  `sig`, `pingInterval` and `pingTimeout` for further usage.
2. I try to initialize a websocket connection to the server, the url is like `wss://wsserver.example.com/socket.io/?gid=xxx&id=xxx&sid=xxxxx&t=xxxx&EIO=3`, then I got an error from gorilla which just said `bad handshake`.

I can't event go further. 
Any suggestions would be very appreciated. Thx

**Comment by stevenscott89** [comment]
Are you creating a Socket.io server or a client?   Describe how you initialized the websocket connection in step 2.

**Comment by haroldrandom** [comment]
A client.

there is my code:
```golang
// loginInfo is acquired in step 1.
func preGetData_4_WS(loginInfo *LoginInfo) {
     reqURL := "wss://wsserver.example.com/socket.io/?gid=%s&token=%s&id=%s&rid=2"
     reqURL = fmt.Sprintf(reqURL, loginInfo.GID, loginInfo.Token, loginInfo.UID)
     fmt.Println(reqURL)

     c, _, err := websocket.DefaultDialer.Dial(reqURL, nil)
     if err != nil {
         panic(err)
     }
     defer c.Close()

     c.WriteMessage(websocket.PingMessage, []byte{})

     for {
         mt, message, err := c.ReadMessage()
         if err != nil {
             Info.Println(err)
             return
         }
         Info.Println("recv:", mt, message)
     }
 }
```

**Comment by stevenscott89** [comment]
Either the server rejected the handshake for some reason or the client is not connecting to a websocket endpoint.

The second return value from Dial is an http.Response.  What is the response status code and response body?

**Comment by haroldrandom** [comment]
@stevenscott89 I use a go package `pretty` to print out the response
```
&http.Response{
    Status:     "400 Bad Request",
    StatusCode: 400,
    Proto:      "HTTP/1.1",
    ProtoMajor: 1,
    ProtoMinor: 1,
    Header:     {
        "X-Cdn":          {"Incapsula"},
        "Content-Type":   {"text/html"},
        "Content-Length": {"17"},
        "Set-Cookie":     {"visid_incap_1014031=1A2O096UQWuf9/j9AzLsoEpOlFsAAAAAQUIPAAAAAAB8XeQ3zBZkBhgzV0TV/RZA; expires=Sun, 08 Sep 2019 13:14:15 GMT; path=/; Domain=.example.com", "nlbi_1014031=ExoEf2AHzDZb/Yb8sW5OdgAAAACSUN6Zn14KR/ZBp7W4ugrt; path=/; Domain=.example.com", "incap_ses_635_1014031=5iJrS3mQ4BHEdj5N5vnPCEpOlFsAAAAAP04PoniOqKInZ7sPLunlpw==; path=/; Domain=.example.com"},
        "X-Iinfo":        {"5-26331085-26331004 PNNN RT(1536446026619 316) q(0 0 0 -1) r(0 0) U11"},
    },
    Body: ioutil.nopCloser{
        Reader: &bytes.Reader{
            s:        {0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x20, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e},
            i:        0,
            prevRune: -1,
        },
    },
    ContentLength:    17,
    TransferEncoding: nil,
    Close:            false,
    Uncompressed:     false,
    Trailer:          {},
    Request:          &http.Request{
        Method: "GET",
        URL:    &url.URL{
            Scheme:     "https",
            Opaque:     "",
            User:       (*url.Userinfo)(nil),
            Host:       "wsserver.example.com",
            Path:       "/socket.io/",
            RawPath:    "",
            ForceQuery: false,
            RawQuery:   "gid=9acbf0c5aa20700e&token=abe43520-0592-4e79-9db6-f307acd03dce&id=29993478&rid=2",
            Fragment:   "",
        },
        Proto:      "HTTP/1.1",
        ProtoMajor: 1,
        ProtoMinor: 1,
        Header:     {
            "Sec-WebSocket-Version": {"13"},
            "Upgrade":               {"websocket"},
            "Connection":            {"Upgrade"},
            "Sec-WebSocket-Key":     {"1O/L9M/7F9lprdbcMK9cMg=="},
        },
        Body:             nil,
        GetBody:          func() (io.ReadCloser, error) {...},
        ContentLength:    0,
        TransferEncoding: nil,
        Close:            false,
        Host:             "wsserver.example.com",
        Form:             {},
        PostForm:         {},
        MultipartForm:    (*multipart.Form)(nil),
        Trailer:          {},
        RemoteAddr:       "",
        RequestURI:       "",
        TLS:              (*tls.ConnectionState)(nil),
        Cancel:           0x0,
        Response:         (*http.Response)(nil),
        ctx:              &context.emptyCtx(0),
    },
    TLS: (*tls.ConnectionState)(nil),
}
```

**Comment by haroldrandom** [comment]
@stevenscott89 FYI.
I change the url from `wss://wsserver.example.com/socket.io/?gid=%s&token=%s&id=%s&rid=2` to `wss://wsserver.example.com/socket.io?gid=%s&token=%s&id=%s&rid=2`

I got 502 Bad gateway error instead.

**Comment by haroldrandom** [comment]
@stevenscott89 Hi, Scott, I figured it out. After add another query parameter `transport`, I got normal response from server.

Thx for your advise about print out the response.

Yet, another problem come to me. I think it's step 3 to continue to implement the client-side socket.io protocol.

I got the following output according to my code.
```
[INFO] - 2018/09/09 07:39:54.192181 main.go:841: recv: 1 0{"sid":"t_I0vw4N04RZhpqyACxK","upgrades":[],"pingInterval":25000,"pingTimeout":60000}
[INFO] - 2018/09/09 07:39:54.192266 main.go:841: recv: 1 41
[INFO] - 2018/09/09 07:39:54.192315 main.go:841: recv: 1 44"Not authorized"
```

Since sid come from step 1 not taken by the server, which is weird.
Any thing wrong with my code ?

**Comment by stevenscott89** [comment]
What is the response body as text?

**Comment by stevenscott89** [comment]
The peer closed the connection. ReadMessage returned an error indicating why the connection was closed.  The application calls panic with this error.

The application's read loop should break on error instead of panicking.

**Comment by haroldrandom** [comment]
Got it.

I guess we should move on to step 3, to communicate with the socket.io server, send or listen something like socket.io client do, like `c.On("some event", function() {})` or `c.Emit("some event", function() {})`. Am I right?

1. I guess this package won't automatically send ping and pong for me like other socket.io client in  javascript do, I have to do it by myself .

2. The after that, I finally can enter the business logic event.

Am I right ?

**Comment by stevenscott89** [comment]
The package automatically sends a PONG in response to a received PING.  The application is responsible for sending PINGs and handling received PONGs.

The rest sounds good to me, but I have only a passing knowledge of socket.io!

**Comment by haroldrandom** [comment]
Got it, thx you for your inspiration and kindly answers.

I will continue to find clues on implementing socket.io client-side protocol.

Thx so much.
