### ISSUE TITLE
Closing the connection with AbnormalClosure (1006)

### ISSUE THREAD

**Issue by herkyl** [gorilla/websocket#424]
I'm trying to close the connection with the status code 1006 for testing purposes.

This is how I go about it:
```go
	cm := websocket.FormatCloseMessage(websocket.CloseAbnormalClosure, "🙈")
	if err := c.conn.WriteMessage(websocket.CloseMessage, cm); err != nil {
		log.Error("Unable to send close message")
		log.Error(err)
	}
```

However, in the JS client I get the close code as 1002, instead of 1006. How do I correctly close a connection with the 1006 close code?

**Comment by stevenscott89** [comment]
The [RFC says](https://tools.ietf.org/html/rfc6455#section-7.4.1):

>   1006 is a reserved value and MUST NOT be set as a status code in a Close control frame by an endpoint.  It is designated for use in applications expecting a status code to indicate that the connection was closed abnormally, e.g., without sending or receiving a Close control frame.

Sending a 1006 is a protocol error. I'd expect the client to return 1002 (protocol error) as it does.

Try closing the connection without sending a close frame.

**Comment by herkyl** [comment]
Thanks @stevenscott89 !

This makes sense. In my case I opted for using the 1001 (CloseGoingAway) code instead of 1006. But if anyone else wan't to trigger the 1006 you can do it like so:

```go
wsConn.Close()
```
