### ISSUE TITLE
Release memory on connection close

### ISSUE THREAD

**Issue by jameselder987** [gorilla/websocket#426]
This has been reported previously #141 #236 #273

We are facing issues where process memory is ever increasing and it leads to crashing of process. To test, try allocating 10MB to ReadBufferSize & WriteBufferSize and have few connections loop connect & disconnect repeatedly.

Would something like PR #425 be a good idea?

**Comment by garyburd** [comment]
Closing because no response from OP on this issue or related PR  425.
