### ISSUE TITLE
WriteMessase func always successful in websocket client even if the websocket server is down

### ISSUE THREAD

**Issue by ramvasanth** [gorilla/websocket#430]
// if writes fails, then we do a exchange and get a new web socket
	if err := ws.WriteMessage(websocket.TextMessage, []byte(data)); err != nil {
		if ws, err = pool.Exchange(ws); err != nil {
			return "", err
		}
	}

WriteMessage func does not return error message even when websocket server is down

**Comment by stevenscott89** [comment]
WriteMessage returns success when the data is written to the operating system network stack, not when the data is delivered to the peer.

The operating system's network stack cannot reliably detect a dead or missing peer.  Use PING / PONG messages to test the health of the connection.  The [chat example](https://github.com/gorilla/websocket/tree/master/examples/chat) shows how to do this on the server side.  The same approach can be used in a client.

**Comment by ramvasanth** [comment]
@stevenscott89 , Thanks for the information.
