### ISSUE TITLE
Chat example last message

### ISSUE THREAD

**Issue by croatiangrn** [gorilla/websocket#433]
Is there any way that I can get only last message sent instead of sending them all to socket client?
Should I modify this or?
`
// Add queued chat messages to the current websocket message.

			n := len(c.send)
			for i := 0; i < n; i++ {
				w.Write(newline)
				w.Write(<-c.send)
			}`

**Comment by stevenscott89** [comment]
Are you asking to discard all but the last queued message?  If so, do something like this:


			w, err := c.conn.NextWriter(websocket.TextMessage)
			if err != nil {
				return
			}
			n := len(c.send)
			for i := 0; i < n; i++ {
				message = <-c.send
			}
			w.Write(message)

**Comment by garyburd** [comment]
As best I can tell, previous comment answers the question.
