### ISSUE TITLE
Similar to bufio.Writer Flush

### ISSUE THREAD

**Issue by Geekoo-Joker** [gorilla/websocket#437]
Use WriteWebsocket()
When sending small data (Such as 6 length size)
The client does not receive the message.

**Comment by stevenscott89** [comment]
This package does not have a function or method named WriteWebsocket(). 

Please show your code, describe what's happening and describe what you expect.

**Comment by Geekoo-Joker** [comment]
> This package does not have a function or method named WriteWebsocket().
> 
> Please show your code, describe what's happening and describe what you expect.

My code：
s := [][]byte{buf, p.Body}
body := bytes.Join(s, []byte(""))
err = wr.WriteMessage(websocket.BinaryMessage, body)

See more details link：https://github.com/Geekoo-Joker/im/blob/master/libs/proto/proto.go  
The bottom method WriteWebsocket

This package conn.go method
// WriteMessage is a helper method for getting a writer using NextWriter,
// writing the message and closing the writer.
func (c *Conn) WriteMessage(messageType int, data []byte) error {

**Comment by stevenscott89** [comment]
There are tests in this package and the autobahn test suite that use small messages.  These tests pass.

What is the code on the peer?

What does this have to do with bufio.Writer Flush?  The write code in the websocket package does not use bufio.Writer.

**Comment by Geekoo-Joker** [comment]
When I use the socket's bufio.writer. When flush is called, the client will receive the message immediately.

When I use websocket, the client does not receive the message after the WriteMessage ends.

After the WriteMessage sends more messages, the client can receive it.

**Comment by Geekoo-Joker** [comment]
so ，I guess websocket is temporarily cached.
I need it to send directly，
what should I do

**Comment by stevenscott89** [comment]
I tried to reproduce the problem with this simple program. The program works as expected: the message is received immediately by the peer.

```
package main

import (
	"fmt"
	"github.com/gorilla/websocket"
	"net/http"
	"net/http/httptest"
	"strings"
)

var upgrader = websocket.Upgrader{}

func main() {
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		c, _ := upgrader.Upgrade(w, r, nil)
		c.WriteMessage(websocket.BinaryMessage, []byte("hello"))
		// don't close connection to avoid possible flush there
	}))

	w, _, _ := websocket.DefaultDialer.Dial(strings.Replace(s.URL, "http:", "ws:", 1), nil)
	_, p, _ := w.ReadMessage()
	fmt.Printf("%s\n", p)
}

```

Can you show how to modify this program to reproduce your the issue?

**Comment by Geekoo-Joker** [comment]
I am very sorry about this, it is my mistake.
When the body is nil, it returns, resulting in no data being sent.

**Comment by Geekoo-Joker** [comment]
thank you very much for your help

**Comment by Geekoo-Joker** [comment]
It is already working properly
