### ISSUE TITLE
Count Clients

### ISSUE THREAD

**Issue by howardkitto** [gorilla/websocket#440]
I'm using the connection pool approach from the chat example. I need to get an accurate count of the number of connected peers. I figured I could update a global from the hub routine but it only ever goes up!. What is the correct way to do this?

```
func (h *Hub) run() {
	for {
		select {
		case client := <-h.register:
			h.clients[client] = true
//Update Global Here
			WebSocketConnections = len(h.clients)
		case client := <-h.unregister:
			if _, ok := h.clients[client]; ok {

				delete(h.clients, client)
				close(client.send)
			}
		case message := <-h.broadcast:
			for client := range h.clients {
				select {
				case client.send <- message:
//Update Global Here
					WebSocketConnections = len(h.clients)
				default:

					close(client.send)
					delete(h.clients, client)
				}
			}
		}
	}
}```

**Comment by stevenscott89** [comment]
Update the count in the two locations where values are deleted from the map.  The program updates the count when a message is sent, but that shouldn't be necessary once the deletes are handled.

If something outside the goroutine is reading WebSocketConnections, then protect it with a mutex or use the sync/atomic package to access the value.

**Comment by howardkitto** [comment]
Thanks, works great
