### ISSUE TITLE
Error trying out the client example

### ISSUE THREAD

**Issue by dylankilkenny** [gorilla/websocket#442]
hey, is it possible to use a https endpoint rather than a ws endpoint?
I received the following error using [this](https://github.com/gorilla/websocket/blob/master/examples/echo/client.go) client example:

`dial:malformed ws or wss URL`

**Comment by stevenscott89** [comment]
The client example looks like it's hard coded to use "ws:".  How did you get the example to use to use a different protocol?

The endpoint must be a websocket endpoint as indicated by the error message.  Connecting to an http endpoint is not supported.

**Comment by garyburd** [comment]
> https endpoint rather than a ws endpoint?

If you want to use the secure WebSocket protocol, then use the "wss:" protocol.  If you want to connect to an HTTP endpoint, then that will not work .
