### ISSUE TITLE
How to specify an IP address in the WebSocket client？

### ISSUE THREAD

**Issue by XieXiaomei-ptr** [gorilla/websocket#443]
I wanted to create 100,000 websocket connections on the client, but I had only one machine, so I created some virtual IP addresses. How to use this package to specify the client IP address?

**Comment by stevenscott89** [comment]
Use the [Dialer.NetDial](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDial) or [Dialer.NetDialContext](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDialContext) functions to control how the network connection is created.




       d := websocket.Dialer{
            NetDialContext: (&net.Dialer{LocalAddr: &net.TCPAddr{IP: addr}}).DialContext,
      }
      c, _, err := d.Dial(url, nil)
