### ISSUE TITLE
Add "in bytes" to sizes in documentation

### ISSUE THREAD

**Issue by stevenscott89** [gorilla/websocket#444]
See [this question on SO](https://stackoverflow.com/questions/53041519/gorilla-websocket-setting-read-limit). 

Conn.SetReadLimit, Dialer.ReadBufferSize, Dialer.WriteBufferSize, Upgrader.ReadBufferSize, Dialer.WriteBufferSize

**Comment by garyburd** [comment]
Fixed by #445
