### ISSUE TITLE
Manual EOL - Question

### ISSUE THREAD

**Issue by astromahi** [gorilla/websocket#451]
When we send multiple JSON documents via websocket continuously, Do we have to mark EOL maunally to notify the receiver about the termination of the documents?.

We use `func (*Conn) WriteJSON` to write documents to connection.

Thanks,

**Comment by stevenscott89** [comment]
[WriteJSON](https://godoc.org/github.com/gorilla/websocket#WriteJSON) writes the JSON encoding of the argument as a message.  The peer should assume one JSON value per message.

**Comment by astromahi** [comment]
Thanks Steven,

But Is it not a underlying writer or server responsibility to tell the peer about the termination?. If it is a usual HTTP Request/Response either writer or webserver will mark EOL. 

But In webocket whos responsibility Application or Webserver?. In the chat example, I see a line with manual EOL marking between each write.

https://github.com/gorilla/websocket/blob/483fb8d7c32fcb4b5636cd293a92e3935932e2f4/examples/chat/client.go#L107

**Comment by stevenscott89** [comment]
The chat example uses newline to separate multiple lines of text within a single websocket message.

Because WriteJSON uses a single websocket message for a JSON value, there's no need for any separators within a message.

**Comment by astromahi** [comment]
Ohhh, I got it now.  I thought it was an explicit separator.

thanks steven
