### ISSUE TITLE
WebSocket connection staying in status 101 switching protocols

### ISSUE THREAD

**Issue by bjm88** [gorilla/websocket#452]
Hi - following the examples I see the upgrader doesn't give a response....

ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		u.GetLogger().Errorf("Problem upgrading http GET connection to WebSocket for %v, error=%v\n", r.RemoteAddr, err)
		return
	}

And I can use the ws connection doing a ws.ReadMessage and ws.WriteMessage, however I was surprised my connection hangs as status 101 switching protocols to the browser.  Perhaps for non text/binary messages we need to do something else to acknowledge its established??

Chrome is not showing frame data being sent b/c of this despite it actually workin in app sending message.....but I am concerned I'm missing something....

**Comment by stevenscott89** [comment]
What browser and version are you using?

Are the [onerror](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/onerror), [onclose](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/onclose) or [onopen](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/onopen) events firing in the browser?

**Comment by bjm88** [comment]
Hi - yes I'm using straight websockets directly in Chrome latest (v70), debug mode is showing it as pending and in the network -> ws tab the frames subtab is empty, but the socket does seem to be working, so its weird.  I recall previously seeing the up and down messages in the frames tab....  not sure what is going on.

the onopen event is firing as expected, no error or close.

**Comment by stevenscott89** [comment]
I think I misunderstood the issue.  Can the server and client both send and receive messages?

**Comment by bjm88** [comment]
Yes!  In chrome debug though on network tab says status 101 and pending.  I realize upgrade protocol and 101 standard and it's persistent connection, but was asking if this is how it stays typically or something is off....??

Previously I recall this status changing to like open and being able to see frames sending back and forth, that is just not working for me debug wise in chrome console, but app is working.

**Comment by stevenscott89** [comment]
If the client and server are exchanging messages, then the connection moved past the handshake and upgrade.  It sounds like this package is working as expected, but Chrome is not.

> Perhaps for non text/binary messages we need to do something else to acknowledge its established??

The handshake and protocol switch happen before any messages are sent. No extra action should be required to display the correct connection state in Chrome's tools.

**Comment by elithrar** [comment]
“Pending” indicates that the handshake has not completed.

If you use a CLI client (i.e. using this library, or one of many others)
can you connect to the server directly?

Suspecting firewall/networking stack issues.

**Comment by bjm88** [comment]
ok, will try, any full examples using javascript websockets directly (not socket.io or something)?  I assume handling ping/pong type stuff is internal to libs.  Also any special headers/setup if its different subdomains and ports, example 
web.myapp.com:3000
websocketchat.myapp.com:3001
type of setup . ??
we have CORS that I'd assume would take care of this...

return cors.Config{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"},
		AllowHeaders:     []string{"Content-Type", "Accept", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		AllowOriginFunc: func(origin string) bool {
			return true
		},
		MaxAge: 12 * time.Hour,
	}

**Comment by stevenscott89** [comment]
If the requesting page and websocket endpoint are on different hosts, then the application must set a [Upgrader.CheckOrigin](https://godoc.org/github.com/gorilla/websocket#Upgrader.CheckOrigin) function that allows the connection.   CORS is not used for WebSocket connections.

If the onopen message is fired and the peers are exchanging messages, then cross origin requests are not the issue.

**Comment by elithrar** [comment]
My immediate suggestion: can you run the echo example here: https://github.com/gorilla/websocket/tree/master/examples/echo - ?

Both client & server.

**Comment by bjm88** [comment]
Thx, so I ran test, and FYI I did also have Upgrader.CheckOrigin set to just response true.  I tried the echo server.go and client.go locally, and they work fine.  I went to http://localhost:8080/ for server and used the simple html template to open, and successfully send messages.  functionality wise it is working fine.  However I see the SAME ISSUE in the chrome debugger.....connection status stays in 101 switching protocols and the FRAMEs sub tab in network >> ws does NOT show any data.  Screen shot attached.  Are you all seeing the same behavior in chrome?  I'm on MacOS latest and chrome latest versions.   Bug with chrome?  (I would be surprised, but perhaps need to test on a different tech stack).  I have also in the past seen this work and go to open status and see frames showing send and receive messages, so not sure what changed.

<img width="962" alt="screen shot 2018-11-21 at 8 09 18 am" src="https://user-images.githubusercontent.com/3016277/48843542-58acce80-ed65-11e8-9752-49a2563d5125.png">

**Comment by bjm88** [comment]
Ok, I guess my main confusion was Frames was actually working but hidden.  I can see the data now.  It was a layout issue in my chrome I had to reset, the inner panel was fully collapsed.  So the only thing is the status 101 switching, which I guess is suppose to stay like that vs going to opened status in chrome, seems weird, but not an issue with this lib for sure.  Thanks all for digging in regardless, closing.
