### ISSUE TITLE
Poor performance when communicating with endpoint that is multi-homed

### ISSUE THREAD

**Issue by ayjaym** [gorilla/websocket#455]
Scenario: A web socket connection is established to an endpoint running Gorilla. The endpoint, running Windows, has two network adaptors configured. One of these network adaptors is connected to a subnet which currently is not active. [the issue has been observed on both a Windows Server 2012 and Win 10 endpoint]

Observed behaviour: communications between the controlling client and the endpoint are very slow, and it can take several seconds after transmission for each message to be reported (i.e sent to the message channel in the endpoint code). 

If the second network adaptor is disabled, the problem disappears. I surmise this may be because the default net listener implementation listens on all available incoming network addresses on the endpoint, and that some kind of polling delay occurs on the network adaptor that is not connected to an active network, but is enabled. When the network adaptor is disabled this delay then vanishes.

Is there any way, other than implementing an override wrapper for net.dial and passing that in, to directly control the parameters passed to the listener so as to specifically define the listener network binding, so that only the active network interface is defined?. I could not see anything obvious reading the API reference. 

Edit: I should mention that so far this behaviour has been reproduced on guests running under Hyper-V, so that the network adaptors are bound to Hyper-V virtual switches. I have not had the opportunity yet to confirm whether the problem occurs on physical devices where the network adaptors correspond directly to physical NIC devices.

**Comment by stevenscott89** [comment]
> Is there any way, other than implementing an override wrapper for net.dial and passing that in, to directly control the parameters passed to the listener so as to specifically define the listener network binding,

Server applications listen and client applications dial.  It is not possible to control the parameters of the server application listener by changing how the client application dials. 

Server applications can create a listener directly and then call [Server.Serve](https://godoc.org/net/http#Server.Serve) (or related helper functions) to run the HTTP server.

Client applications can use the [Dialer.NetDial](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDial) and [Dialer.NetDialContext](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDialContext) to dial the underlying network connection.

**Comment by ayjaym** [comment]
Thanks for the reply - much appreciated. Sorry, I phrased my original comment about net.dial very poorly (not enough coffee!). I meant, is there any way, similar to how the override exists for the dialer, but to control the listening side, in a similar manner as WAS DONE for net.dial (i.e to control the listen side of the full duplex communication channel). 

I also failed to make clear that the app is acting as a websocket client, but the problem occurs when the remote server it's talking to sends a message back to the client, presumably - I'm guessing - due to the client socket listener binding to all endpoint NICs. Hence what I need to do is somehow alter that behaviour to ensure that only a specific NIC, bound to a specific set of IP addresses, is used to listen when acting as a client. This should - hopefully - prevent the inactive NIC from compromising performance, though why this happens is not yet clear. Sorry for conveying this poorly.

**Comment by stevenscott89** [comment]
The [Dialer.NetDial](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDial) and [Dialer.NetDialContext](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDialContext) functions provide complete control over how the socket is created.   This includes both the sending and receiving sides (or "listening" as you say) of the socket.

Take note of  [Dialer.DualStack](https://godoc.org/net#Dialer.DualStack) and network argument to [Dial](https://godoc.org/net#Dialer.DualStack) where the application can replace "tcp" with "tcp4" or "tcp6".

**Comment by garyburd** [comment]
The application has full control over how the sockets are dialed through the NetDial and NetDialContext functions.
