### ISSUE TITLE
Is the maximum number of connections supported by websocket stand-alone computer 256?

### ISSUE THREAD

**Issue by masterJiaxing** [gorilla/websocket#456]
I used JS to traverse 500 websocket connections under windows, with only 256 connection states, followed by pending state. Why?

**Comment by stevenscott89** [comment]
You are bumping into limits of your operating system configuration. This package does not impose any limits on the number of connections.

**Comment by elithrar** [comment]
Specifically, on macOS, Linux & BSD systems, this is typically the number
of open file descriptors (which includes network sockets, as they are also
file descriptors) allowed.

The MongoDB docs have a good write-up on how to increase this via ulimit -n

https://docs.mongodb.com/manual/reference/ulimit/
