### ISSUE TITLE
Use WriteMessage send 1M binary data will blocking about 30s

### ISSUE THREAD

**Issue by seventhking** [gorilla/websocket#458]
Hi,  My application as client send data to server. I will send about 1M size of data once time. As my log shows when i call WriteMessage, this function will block me for about 30s.

OS: ubuntu18
use DefaultDialer with specified buffer size
```
	dialer := websocket.DefaultDialer
	dialer.ReadBufferSize = 1024 * 1000 * 5
	dialer.WriteBufferSize = 1024 * 1000 * 2
	conn, response, err := dialer.Dial(websocketUrl, nil)
```

**Comment by stevenscott89** [comment]
The call to WriteMessage blocks on writing data to the operating system.  For large enough messages, the write to the operating system can block on transmitting data to the peer. 

How long does it take to transfer 1MB to the peer using other means?

Is there a reason why you are not using the default buffer sizes?  The sizes that you are using are huge.

**Comment by seventhking** [comment]
Hi, i found that use websocket in python and c to  send 1MB data will  also be blocked.

I will limit transfer data size, and debug with tcp packet.
