### ISSUE TITLE
upgrader.Upgrade hangs when anything is logged before the call

### ISSUE THREAD

**Issue by dakujem** [gorilla/websocket#459]
Hello gophers and gorillas,

Is it a known issue that logging anything before the upgrader is called, the execution hangs at that point and the HTTP connection never switches to the websocket protocol? (All I can see is "pending" status of the connection).

```
// in main.go ::main

	http.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
		// log.Println("Websocket connection pending...") // this breaks the websocket
		hub.connectClient(w, r)
	})

// ...

func (h *Hub) connectClient(w http.ResponseWriter, r *http.Request) {
	upgrader := websocket.Upgrader{
		CheckOrigin: func(r *http.Request) bool {
			return true
		},
	}
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Printf("error: %v\n", err) // this error never logs
		return
	}
	// if I log/print anything here, it never gets to output either
....
```

> The above code has been taken from the chat example, to reproduce, just place any log call before the `upgrader.Upgrade` call.

It does not matter if I use `log.Println`, `log.Printf` or `fmt.Println`, so i'm guessing the issue is not in printing to `stderr`, it relates to `stdout` as well. When I omit the print call, everything works as expected.

I also tried sending a message to the websocket, but I got error from browser saying something like "The socket is in handshake phase".

I'm sorry if this is a dumb question, but I'm new to _go_, _gorilla_, and even _websockets_, any pointers are welcome (except for 0x0). Thanks to anyone in advance!

**Comment by stevenscott89** [comment]
There's no direct interaction between stdout or stderr and a websocket connection.  The only interaction is indirect through use of system resources and timing. If write to stdout blocks for example, then the program will not work as expected when print statements are added.

The chat example works when writes to sdtout or stderr are added before or after [this line](https://github.com/gorilla/websocket/blob/95ba29eb981bbb27d92e1f70bf8a1949452d926b/examples/chat/client.go#L125).

The code in the issue is a not taken directly from the chat example.  I suspect something else is going on in the application.

**Comment by elithrar** [comment]
Where / how are you running your application? Just go run on a local
machine? In a container? Somewhere else?

**Comment by dakujem** [comment]
I'm running it locally/natively on a windows 7 machine with go1.11.2 and i believe it did not work on heroku either, which uses some sort of containerized linux with the same go version. I can confirm that if you wish.

**Comment by elithrar** [comment]
Definitely something strange.

- Does the _unmodified_ chat example run?
- Does adding a single log line to the official chat example work?
- Is your IDE importing some other log library accidentally?
- Can you write to stderr & stdout at the very top of your main function? e.g. `fmt.Fprintln(os.Stdout, “stdout”)` - ?

**Comment by dakujem** [comment]
Okay, this **is** strange. After modifying the code a bit, the upgrades are even worse. I pushed the same code to Heroku (linux containers) and the connection gets upgraded every single time. When I run it locally (native go1.11.2 installation), it upgrades 1-2 times out of 10 for about 4-5 times max, then it stops upgrading at all and I need to restart the server. That is, _without_ the log/print. With the print, it never upgrades. If that is not strange enough, Firefox tends to be less successful with the upgrades than Chrome... :roll_eyes: 

While searching for an answer I found several references with problems on Windows 7 - might that be something that _just happens_?

The code is pretty simple, nothing convoluted happens:
```go
func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	addr := flag.String("addr", ":" + port, "http service address")
	flag.Parse()

	// Mux Router
	r := mux.NewRouter()

	// Serve WebSocket connections
	hub := newHub()
	r.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
		// fmt.Println("Websocket connection prding...") // the upgrader hangs if anything is printed before the call
		hub.connectClient(w, r)
	})
...

func (h *Hub) connectClient(w http.ResponseWriter, r *http.Request) {
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Printf("error: %v\n", err)
		return
	}
...
```
i'm using "modules" so maybe it's relevant to show `mod.go`:
```
module foo/bar

require (
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/gorilla/mux v1.6.2
	github.com/gorilla/websocket v1.4.0
)
```

**Comment by stevenscott89** [comment]
Please try to paste text instead of images in the issue.  

Do you have a handler for /favicon.ico, or is it handled by the handler than prints the "/" log lines?  Show the code that prints these lines.

Include a request id in your log output.  That might help sort out what's going on.  Here's one way to add a request id.:

Add package-level variable:

     var requestID int32

Inside the handler, increment the request ID using the sync/atomic package and use that id when logging:

        id := atomic.AddInt32(&requestID, 1)
        log.Println(id, "Connecting websocket...")
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println(id, err)
		return
	}
	log.Println(id, "Connected...")

**Comment by dakujem** [comment]
@stevenscott89 The code is the chat example in this repository, except for those two `log.println` calls that are mentioned and the added `go.mod` file that I created in order to run the example. I included images because the output from the terminal is useless for anything except suporting what's been written.

**Comment by garyburd** [comment]
Dump the goroutine stacks by sending the process a SIGQUIT and share them here.

Are you using a VPN, antivirus, firewall or other software that might interfere with network connections?

**Comment by dakujem** [comment]
Sorry guys, i stopped working on Go implementation of my project, so I had no time for this issue.
