### ISSUE TITLE
Where does the difference in execution time between conn.ReadMessage and conn.ReadJson come from?

### ISSUE THREAD

**Issue by adrianbrad** [gorilla/websocket#461]
Hello guys, I've been looking into this for 2 days, but I cannot find an explanation for the high execution time for reading binary messages. At least the first time the `.ReadMessage()` and `.ReadJson(&msg)` are called over a new WS conn there is a huge difference in execution time. Those are the results for the same message sent and received over binary and Json. Currently only two bytes are generated from the protobufs marshalling, so the message is really small
```
Protobufs reading elapsed time: 4.195358ms
Protobufs reading elapsed time: 789.84µs
Protobufs reading elapsed time: 279.025µs
Json reading elapsed time: 484.145µs
Json reading elapsed time: 193.691µs
Json reading elapsed time: 189.631µs
```

This is the code I am using for timing:
**Binary Handler**

```golang
func wsHandlerProto(w http.ResponseWriter, r *http.Request) {

	conn, _ := upgrader.Upgrade(w, r, nil) // error ignored

	_ = conn.WriteMessage(websocket.BinaryMessage, data)

	for {
		startReadingBytesTime := time.Now() // save starting time

		_, msg, _ := conn.ReadMessage()

		endReadingBytesTime := time.Now() //save end time

		elapsedTimeReadingBytes := endReadingBytesTime.Sub(startReadingBytesTime) // calculate duration

		fmt.Print("Protobufs reading elapsed time: " + string(elapsedTimeReadingBytes.String()+"\n")) //print execution duration

		receivedMessage := &message.Message{}

		_ = proto.Unmarshal(msg, receivedMessage)

		count++

		toSend, _ := proto.Marshal(receivedMessage)

		if err := conn.WriteMessage(websocket.BinaryMessage, toSend); err != nil {
			return
		}

		if count == times {
			_ = conn.Close()
			count = 0
			return
		}
	}
}
```
**JSON Handler**

```golang
func wsHandlerJson(w http.ResponseWriter, r *http.Request) {
	conn, _ := upgrader.Upgrade(w, r, nil) // error ignored

	_ = conn.WriteJSON(jsonMessage)

	for {
		msg := messageJson{}

		startReadingJsonTime := time.Now()

		_ = conn.ReadJSON(&msg)

		endReadingJsonTime := time.Now()
		elapsedTimeReadingJson := endReadingJsonTime.Sub(startReadingJsonTime)

		fmt.Print("Json reading elapsed time: " + string(elapsedTimeReadingJson.String()) + "\n")

		count++

		if err := conn.WriteJSON(msg); err != nil {
			return
		}

		if count == times {
			_ = conn.Close()
			count = 0
			return
		}
	}

}
```

And this is the data that I am sending, created beforehand:

```golang
	msg := messageJson{
		Times: 12,
	}
```

```golang
	msg := &message.Message{
		Times: 12,
		//Pair:  pairs,
	}
```

And also the client is just sending the data received back:

```javascript
wsProto.on('message', function incoming(data) {
    console.log('proto message received');
    wsProto.send(data);
});
```
```javascript
    wsJson.on('message', function incoming(message) {
        console.log('json message received');
        wsJson.send(message)
    })
```

What should be the cause for this difference in execution time?

**Comment by adrianbrad** [comment]
Just noticed that if I start timing JSON reading first, the time execution is incresead for the first JSON message read.

```
Json reading elapsed time: 4.690029ms
Json reading elapsed time: 260.62µs
Json reading elapsed time: 197.546µs
Protobufs reading elapsed time: 646.482µs
Protobufs reading elapsed time: 214.944µs
Protobufs reading elapsed time: 193.374µs
```

**Comment by stevenscott89** [comment]
One difference is that the JSON program includes the time to decode the JSON while the protobuf program does not include the decoding time.

The JSON decoder caches information the first time it decodes to some type.  As a result, the first decode to a type typically takes longer than subsequent decodes to that type.

The protobuf version uses binary messages and the JSON version uses text messages. Text messages are more expensive for the browser to process, but the additional cost will be negligible.

Here's a version JSON program that eliminates these differences: 

```
func wsHandlerProto(w http.ResponseWriter, r *http.Request) {
	conn, _ := upgrader.Upgrade(w, r, nil) // error ignored
        data, _ := json.Marshal(jsonMessage)
	_ = conn.WriteMessage(websocket.BinaryMessage, data)
	for {
		startReadingBytesTime := time.Now() // save starting time
		_, msg, _ := conn.ReadMessage()
		endReadingBytesTime := time.Now() //save end time
		elapsedTimeReadingBytes := endReadingBytesTime.Sub(startReadingBytesTime) // calculate duration
		fmt.Print("Protobufs reading elapsed time: " + string(elapsedTimeReadingBytes.String()+"\n")) //print execution duration
		var msg messageJson
		_ = json.Unmarshal(msg, &msg)
		count++
		toSend, _ := json.Marshal(&msg)
		if err := conn.WriteMessage(websocket.BinaryMessage, toSend); err != nil {
			return
		}
		if count == times {
			_ = conn.Close()
			count = 0
			return
		}
	}
}
```

The messages have different sizes, but I doubt that makes a difference in the timing.

**Comment by adrianbrad** [comment]
@stevenscott89 Thanks for the insight. I actually want to test the performance of protobufs over binary vs json over text. 
As you can see from the results in my initial post and the results in the first comment, exactly the first message generates that 3.5-4ms overhead and I'm curious what causes that.

**Comment by stevenscott89** [comment]
>  I actually want to test the performance of protobufs over binary vs json over text.

For a fair comparison between your tests, change the protobuf program to include the deocding time in the measurement.

> exactly the first message generates that 3.5-4ms overhead and I'm curious what causes that.

The first time the JSON and protobuf packages decode to some type, they cache information about the type for use in later decode operations.   As a result, the first call to decode a type typically takes longer than subsequent calls to decode a type.

**Comment by adrianbrad** [comment]
> The first time the JSON and protobuf packages decode to some type, they cache information about the type for use in later decode operations. As a result, the first call to decode a type typically takes longer than subsequent calls to decode a type.

Sure I can totally understand that, but I think this is not about the first time JSON and Protobuf decoders get to work on a new type.
The first time the JSON and protobuf packages decode to some type, they cache information about the type for use in later decode operations. As a result, the first call to decode a type typically takes longer than subsequent calls to decode a type. Because for example, here when we time protobufs first, the first message received causes a long time execution: 
```
Protobufs reading elapsed time: 4.195358ms
Protobufs reading elapsed time: 789.84µs
Protobufs reading elapsed time: 279.025µs
Json reading elapsed time: 484.145µs
Json reading elapsed time: 193.691µs
Json reading elapsed time: 189.631µs
```

And here when we time Json first, the behavior is the same.
```
Json reading elapsed time: 4.690029ms
Json reading elapsed time: 260.62µs
Json reading elapsed time: 197.546µs
Protobufs reading elapsed time: 646.482µs
Protobufs reading elapsed time: 214.944µs
Protobufs reading elapsed time: 193.374µs

```

**Comment by elithrar** [comment]
• Run more benchmark iterations (1000+) & calculate the geometric mean, std
dev
• Be mindful that you aren’t benchmarking your terminal’s stdout
• The deltas aren’t big enough to be meaningful (outside of that 4ms
outlier)

**Comment by stevenscott89** [comment]
One way to tease this apart is to measure the time to receive a message, but not decode it.

**Comment by garyburd** [comment]
The measurement in the first iteration in the loop includes the time to transmit the handshake response over the network and the time for the client to  process the handshake response.

Assuming that the client sends a message in response to receiving message, all measurements include the time to transmit and the messages over the network.  Are all messages the same size? In particular, is the first message sent by the server the same size as subsequent messages?

**Comment by adrianbrad** [comment]
It seems like the first message sent over the new established websocket connection caused a longer execution time. I bypassed this by sending an initialization message before actually starting the benchmark.

```go
func (wss *wsServerProtobufs) wsHandlerProto(w http.ResponseWriter, r *http.Request) {
	wss.connection, _ = upgrader.Upgrade(w, r, nil)

	_ = wss.connection.WriteMessage(websocket.BinaryMessage, wss.protoMessageBytes)

	_, _, _ = wss.connection.ReadMessage() //just used for initialization and caching

	wss.init <- true
}
```

Afterward I am actually benchmarking this method:

```go
func (wss *wsServerProtobufs) SendAndReceiveMessage() {
	wss.protoMessageBytes, _ = proto.Marshal(wss.message)
	_ = wss.connection.WriteMessage(websocket.BinaryMessage, wss.protoMessageBytes)
	_, wss.receivedMessageBytes, _ = wss.connection.ReadMessage()
	_ = proto.Unmarshal(wss.receivedMessageBytes, wss.receivedMessage)
}
```

The benchmark method looks like this: 

```go
func BenchmarkSendAndReceiveProto(b *testing.B) {
	b.StopTimer()

	teardownTestCase, ws := setupTestCase("Proto")
	defer teardownTestCase()

	b.StartTimer()

	b.Run("Send and Receive Small Proto", func(b *testing.B) {
		for n := 0; n < b.N; n++ {
			ws.SendAndReceiveMessage()
		}
	})

	ws.SetMessageSize(medium)

	b.Run("Send and Receive Medium Proto", func(b *testing.B) {
		for n := 0; n < b.N; n++ {
			ws.SendAndReceiveMessage()
		}
	})

	ws.SetMessageSize(big)

	b.Run("Send and Receive Big Proto", func(b *testing.B) {
		for n := 0; n < b.N; n++ {
			ws.SendAndReceiveMessage()
		}
	})
}
```

And I use this method (which is called in the above benchmark method) for setup, cleanup and launching the node client:

```go
func setupTestCase(client string) (func(), websocketsServer) {
	cmd := exec.Command("node", "../ws-client/client"+client+".js")
	var ws websocketsServer

	switch client {
	case "Json":
		ws = NewJson()
	case "Proto":
		ws = NewProto()
	}

	ws.SetMessageSize(small)

	go cmd.Run()

	ws.WaitForInitializaion() //this waits for connection initialization
	return func() {
		cmd.Process.Kill()
		ws.CloseConnection()
	}, ws
}
```

I do the same for json and those are the results:
```
BenchmarkSendAndReceiveProto/Send_and_Receive_Small_Proto-4         	   30000	     45208 ns/op	    2184 B/op	       5 allocs/op
BenchmarkSendAndReceiveProto/Send_and_Receive_Medium_Proto-4        	   30000	     47349 ns/op	    2304 B/op	       8 allocs/op
BenchmarkSendAndReceiveProto/Send_and_Receive_Big_Proto-4           	   30000	     50171 ns/op	    3168 B/op	       8 allocs/op
BenchmarkSendAndReceiveJson/Send_and_Receive_Small_Json-4           	   20000	     50877 ns/op	     944 B/op	       7 allocs/op
BenchmarkSendAndReceiveJson/Send_and_Receive_Medium_Json-4          	   30000	     59359 ns/op	    1112 B/op	      14 allocs/op
BenchmarkSendAndReceiveJson/Send_and_Receive_Big_Json-4             	   20000	     76620 ns/op	    3114 B/op	      15 allocs/op
```
You can find the benchmark files [here](https://github.com/adrianbrad/go_node_websockets-protobufs-json-race/tree/master/benchmarks)
