### ISSUE TITLE
Leaking read routines

### ISSUE THREAD

**Issue by pascaldekloe** [gorilla/websocket#462]
If there is no way to stop a WebSocket read then you'll leak routines/memory. As mentioned in #11 and #81, the Go API provides deadlines for this exact scenario.

```go
func NextMessage(ctx context.Context, conn *websocket.Conn) ([]byte, error) {
    // clear timeout
    defer conn.SetReadDeadline(time.Time{})

    _, r, err := conn.NewReader()
    if err != nil {
        return nil, err
    }

    var buf bytes.Buffer
    for {
        select {
        case ctx.Done():
            return nil, ctx.Err()
        default:
            break
        }

        conn.SetReadDeadline(time.Now().Add(time.Second))
        _, err := buf.ReadFrom(r)
        if err == nil {
            return buf.Bytes(), nil
        }
        if e, ok := err.(net.Error); ok && e.Timeout() {
            continue
        }
        return err
}

**Comment by stevenscott89** [comment]
The package does not support polling the connection with timeouts.  Close the connection to cancel reads on the connection.

**Comment by pascaldekloe** [comment]
Closing the connection is a reasonably way to stop the routine indeed. Unfortunately you can't do that in combination with `http.Handler`.

A malicious client may send half of a frame and close the connection. On the server side the read routine will stay open leaking memory. That's a security thread I think.

**Comment by stevenscott89** [comment]
Close on websocket connection calls close on the underlying network connection.  Explain why that cannot be done in combination with http.Handler.

To protect against a client sending most of a large message, set a read deadline after NextReader returns and before reading the message.  A call to Read on the message will return an error when the deadline is breached.


    func NextMessage(conn *websocket.Conn) ([]byte, error) {
         conn.SetReadDeadline(time.Now().Add(messageTimeout))
         _, r, err := conn.NextReader()
         if err != nil {
            return nil, err
         }

        var buf bytes.Buffer
        conn.SetReadDeadline(time.Now().Add(dataTimeout))
        _, err := buf.ReadFrom(r)
        return buf.Bytes(), err
    }

**Comment by pascaldekloe** [comment]
Sometimes my memory is failing. In case of a Hijack you *are* actually supposed to Close the connection.
I see the way of thinking now. Thanks for the support @stevenscott89. :-)
