### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by Seleniums** [gorilla/websocket#463]
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 671 [running]:
io/ioutil.readAll.func1(0xc420743a68)
	/usr/local/go/src/io/ioutil/ioutil.go:30 +0x111
panic(0xaa74a0, 0x10417e0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
bufio.(*Reader).Read(0xc4202fa420, 0xc42029f400, 0x200, 0x200, 0x410d87, 0xc42029f400, 0x200)
	/usr/local/go/src/bufio/bufio.go:224 +0x4fe
github.com/gorilla/websocket.(*messageReader).Read(0xc4205c1100, 0xc42029f400, 0x200, 0x200, 0xc420743980, 0x42a8b9, 0xc400000008)
	/Users/wanlucheng/go/src/github.com/gorilla/websocket/conn.go:988 +0x27b
bytes.(*Buffer).ReadFrom(0xc4207439c0, 0x7f2c6fffd028, 0xc4205c1100, 0xc42029f400, 0x0, 0x200)
	/usr/local/go/src/bytes/buffer.go:209 +0x177
io/ioutil.readAll(0x7f2c6fffd028, 0xc4205c1100, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:33 +0x12c
io/ioutil.ReadAll(0x7f2c6fffd028, 0xc4205c1100, 0x7f2c6fffd028, 0xc4205c1100, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:42 +0x3e
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc4204d8000, 0xbeff2a870711f156, 0x174e2fe95d9e, 0x10575a0, 0x0, 0x0, 0x10575a0)
	/Users/wanlucheng/go/src/github.com/gorilla/websocket/conn.go:1033 +0x97

**Comment by stevenscott89** [comment]
Run the application with the [race detector](https://golang.org/doc/articles/race_detector.html) and fix any problems.

**Comment by ankurnigam** [comment]
I am getting below error while using ioutil.readall function:

panic: runtime error: index out of range [1024] with length 1024 [recovered]
        panic: runtime error: index out of range [1024] with length 1024

goroutine 1 [running]:
io/ioutil.readAll.func1(0xc0000cbd48)
        /usr/local/go/src/io/ioutil/ioutil.go:30 +0x101
panic(0x6d25e0, 0xc0001bc000)
        /usr/local/go/src/runtime/panic.go:969 +0x166
main.(*ReadTillReader).Read(0xc00047e150, 0xc000478800, 0x400, 0x400, 0x200, 0x0, 0x0)
        /u01/golang/codes/soap_new.go:97 +0x1c3
bytes.(*Buffer).ReadFrom(0xc0000cbcd0, 0x75ade0, 0xc00047e150, 0x0, 0xa2b8, 0xc000566000)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
io/ioutil.readAll(0x75ade0, 0xc00047e150, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:36 +0xe3
io/ioutil.ReadAll(...)
        /usr/local/go/src/io/ioutil/ioutil.go:45
main.main()
        /u01/golang/codes/soap_new.go:145 +0x927
exit status 2
[root@78a1c6a6b8fa codes]#
