### ISSUE TITLE
Handling err from ReadMessage(), WriteMessage()

### ISSUE THREAD

**Issue by MichaelHipp** [gorilla/websocket#464]
What is the correct way to handle an err from ReadMessage, WriteMessage and similarly for ReadJSON, WriteJSON, etc.

Do we assume the connection has failed or been closed and just abandon it? Issue an explicit Close()?

**Comment by stevenscott89** [comment]
For ReadMessage and WriteMessage, assume that the connection has failed. Close the connection and cleanup any application resources related to the connection.

The ReadJSON and WriteJSON methods can return errors related to JSON decoding and encoding errors, as well as connection errors.  For the connection errors, do as above for ReadMessage and WriteMessage.   It's up to the application on how to handle the JSON errors.

**Comment by MichaelHipp** [comment]
Thanks.
