### ISSUE TITLE
windows server   websocket  pending

### ISSUE THREAD

**Issue by thl1991** [gorilla/websocket#467]

**Comment by thl1991** [comment]
> Please provide more details about what the issue is.

在做一对一聊天的时候，客户端显示连接服务器正常且客户端能够正常发送消息，但是服务器端无法读取客户端发来的消息。且没有发现服务器端有任何异常，感觉websocket进入了假死状态

When doing one-to-one chat, the client shows that the connection server is normal and the client can send messages normally, but the server can not read the messages sent by the client. And no anomalies were found on the server side. It felt that websocket had entered a pseudo-dead state.

**Comment by stevenscott89** [comment]
There's insufficient information in this issue to act on. 

Why can't the server read the messages?  Do the methods block or return an error?   Show the server code.

**Comment by thl1991** [comment]
> There's insufficient information in this issue to act on.
> 
> Why can't the server read the messages? Do the methods block or return an error? Show the server code.

![Uploading image.png…]()

**Comment by thl1991** [comment]
> There's insufficient information in this issue to act on.
> 
> Why can't the server read the messages? Do the methods block or return an error? Show the server code.

**Comment by thl1991** [comment]
> > There's insufficient information in this issue to act on.
> > Why can't the server read the messages? Do the methods block or return an error? Show the server code.

![1548233420 1](https://user-images.githubusercontent.com/8097649/51594469-777b3d00-1f2f-11e9-9565-26f6c079caf9.jpg)
 no error ,no error code

**Comment by thl1991** [comment]
> There's insufficient information in this issue to act on.
> 
> Why can't the server read the messages? Do the methods block or return an error? Show the server code.

![image](https://user-images.githubusercontent.com/8097649/51594597-c0cb8c80-1f2f-11e9-962c-e6dcb91a86de.png)

**Comment by stevenscott89** [comment]
> the server can not read the messages sent by the client

Show the code where the server reads messages from the client. Describe why the messages cannot be read.   Does  read on the connection block, return an error or something else?

**Comment by thl1991** [comment]
> > the server can not read the messages sent by the client
> 
> Show the code where the server reads messages from the client. Describe why the messages cannot be read. Does read on the connection block, return an error or something else?

nothing
