### ISSUE TITLE
control frame length > 125

### ISSUE THREAD

**Issue by tshradheya** [gorilla/websocket#469]
Very frequent ` websocket: control frame length > 125` messages on `readJSON` object.

Not sure if this is due to client side or server side

**Comment by tshradheya** [comment]
Using multiple ones as clients

https://pypi.org/project/websocket-client/ and https://github.com/zwopple/PocketSocket and React Native's websocket

**Comment by stevenscott89** [comment]
Which client causes the error, or is it all of them?

**Comment by tshradheya** [comment]
Not too sure which client is it. Wanted to make sure its not the server's websocket's fault before i dig into the client sockets implementation

**Comment by tshradheya** [comment]
I am using 1.2.0 version btw. Are there any fixes made to the related code available in recent versions?

**Comment by tshradheya** [comment]
Okay thank. 

Also any idea why when i connect through web browser socket it keeps disconnecting very so often with 
```
websocket: close 1006 (abnormal closure): unexpected EOF
```

Any way to resolve this from server side?

**Comment by elithrar** [comment]
That error (1006) is typically borne from network errors, but can be _anything_.

There is not enough information to go off - are you on an unreliable network? Are your server timeouts particularly short? Are you restarting the server during development? Is there a proxy/CDN provider in-between ?

**Comment by stevenscott89** [comment]
The 1006 error is returned when the peer closes the connection without sending a close frame.  Handle this error on the server as you would any other error:  close the connection and cleanup.

While looking through the code to answer this question, I noticed an issue and reported it in #471.

**Comment by garyburd** [comment]
The peer violated the protocol by sending a control frame longer than 125 bytes.
