### ISSUE TITLE
case message := <-manager.broadcast: 

### ISSUE THREAD

**Issue by kjcx** [gorilla/websocket#470]
是否应该使用协程去推送到客户端 客户端循环发送快了导致被close掉了

**Comment by stevenscott89** [comment]
Please share more of your code.  It's difficult to comment on the problem based on the one line of application code shared in the issue title.

**Comment by kjcx** [comment]
https://github.com/gorilla/websocket/blob/master/examples/chat/hub.go#L45 例子里面代码第45行

**Comment by stevenscott89** [comment]
The code in the title of this issue does not match any of the code in the chat example. I cannot figure out what the problem is given the lack of code and the limits of Google Translate.

**Comment by kjcx** [comment]
就是聊天代码examples/chat/hub.go 第45行  这个处理消息是不是应该使用协程，要不客户端循环快递发送，就会报错
