### ISSUE TITLE
websocket 作为client 如何判断是否close

### ISSUE THREAD

**Issue by kjcx** [gorilla/websocket#472]
ws客户端连接服务端之后 ws.Close() 之后怎么判断客户端是否连接服务器

**Comment by stevenscott89** [comment]
> After the ws client connects to the server, how to determine whether the client connects to the server after ws.Close()

The client must create a new connection.  It's up to the application to determine if the new connection originated from the same client as the previous connection.

**Comment by kjcx** [comment]
是ws.Close() 之后 客户端无法判断当前连接的状态,或者说客户端在发送消息之前如何判断当前连接状态

**Comment by stevenscott89** [comment]
> After ws.Close(), the client cannot determine the status of the current connection, or how the client determines the current connection status before sending the message.

It's up to the application to cleanup after itself after closing the websocket connection.  Calls to connections methods will return an error after ws.Close() is called.

The peer will see that the connection is closed and should cleanup as a result.
