### ISSUE TITLE
websocket supported through internet proxy?

### ISSUE THREAD

**Issue by hnbakker** [gorilla/websocket#475]
Hi guys,

I've got a testcase with Rancher using the gorilla websocket to import kubernetes clusters.
Only the websocket connection through a internet proxy (squid) ain't working.

Using the env variables: http_proxy, https_proxy (and uppercase) just don't work.

Browsing the code i did find this function proxy_FromURL() in client.go (line 277), which  i find untraceable:

		if proxyURL != nil {
			dialer, err := proxy_FromURL(proxyURL, netDialerFunc(netDial))
			if err != nil {
				return nil, nil, err
			}
			netDial = dialer.Dial

Anyone who could help me out ?

Tnxs in advance.

**Comment by stevenscott89** [comment]
Proxies are supported.  Is Dialer.proxy set?  What do you mean by "untraceable"?

**Comment by hnbakker** [comment]
Dialer.Proxy is set through the env variable https_proxy.

With " untraceable" i mean i can't find the code for this routine in github.

**Comment by stevenscott89** [comment]
To use proxy configuration from environment variables, set the [Dialer.Proxy](https://godoc.org/github.com/gorilla/websocket#Dialer.Proxy) field to [http.ProxyFromEnvironment](https://godoc.org/net/http#ProxyFromEnvironment).  If the field is nil, then no proxy is used.

The ProxyField is set in the  [DefaultDialer](https://godoc.org/github.com/gorilla/websocket#DefaultDialer).

The proxy_FromURL function is located [here](https://github.com/gorilla/websocket/blob/95ba29eb981bbb27d92e1f70bf8a1949452d926b/x_net_proxy.go#L214).

**Comment by garyburd** [comment]
@hnbakker Do you still have a problem after setting Dialer.Proxy?
