### ISSUE TITLE
panic: repeated read on failed websocket connection

### ISSUE THREAD

**Issue by sdjyliqi** [gorilla/websocket#476]
type WsConn struct {
	*websocket.Conn
	proxy           string
	host            string
	path            string
	closed          bool
            ....................
}

func (ws *WsConn) StartToReceiveMessage() {
	go func() {
		for {
			t, msg, err := ws.ReadMessage()  // this line caused the panic
			if ws.closed {
				glog.V(7).Infof("websocket closed.....")
				return
			}
			ws.fireMessage(err, t, msg)
		}
	}()
}

I create the connection to the server and subsribe some api.       
run after few seconds.....

panic: repeated read on failed websocket connection

goroutine 69 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc00017a160, 0xc000092008, 0xc0003f1fa8, 0x2, 0x2, 0xb)
	D:/GoWork/src/github.com/gorilla/websocket/conn.go:968 +0x35d
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc00017a160, 0x2, 0x2, 0xb, 0x0, 0x0, 0xc0002402c0)
	D:/GoWork/src/github.com/gorilla/websocket/conn.go:1029 +0x36

Process finished with exit code 2

**Comment by elithrar** [comment]
> t, msg, err := ws.ReadMessage() // this line caused the panic

You need to handle the error and break out of the loop.

**Comment by garyburd** [comment]
Break out of the loop on error.

**Comment by khash** [comment]
I think I am breaking out of the look on error, but still getting this:

```
			_, message, err := s.conn.ReadMessage()
			if err != nil {
				if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure, websocket.CloseNormalClosure) {
					s.logger.Err(err).Msg("read error")
				}
				break
			}
```

**Comment by elithrar** [comment]
> > t, msg, err := ws.ReadMessage() // this line caused the panic
> 
> You need to handle the error and break out of the loop.

@TangMonk - without your code it's not clear if you have the same problem, but this is likely a bug in your application code, not in websocket.
