### ISSUE TITLE
ERR_INSUFFICIENT_RESOURCES error after 255 connections

### ISSUE THREAD

**Issue by Pinank** [gorilla/websocket#477]
After connecting 255 clients, its giving  following error,

> WebSocket connection to 'ws://localhost:8080/ws' failed: Error in connection establishment: net::ERR_INSUFFICIENT_RESOURCES

**Comment by elithrar** [comment]
This is a browser-level error, not a websocket error.

I assume you are trying to create 255 clients from the same browser process?

**Comment by elithrar** [comment]
Yep - so it’s a browser resource issue - consuming too much memory. This
isn’t something we can solve.

What drives the need to open > 250 connections from a single browser
session?
