### ISSUE TITLE
Is it valid to utilize request context

### ISSUE THREAD

**Issue by ldelossa** [gorilla/websocket#478]
When receiving the initial GET request, I pull the context from the http object. I pass this down into methods which call go routines. 

It does not look like a disconnect of the websocket client triggers a context close once the connection has been updated.

Is this correct?

**Comment by stevenscott89** [comment]
The request context is ignored by this package.  

If you want to use context to manage cancelation of goroutines, then call [context.WithCancel](https://godoc.org/context#WithCancel) to create a context and cancel that context is part of the application's cleanup of the websocket connection.

**Comment by ldelossa** [comment]
Thank you Steven, that works just fine
