### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davit555** [gorilla/websocket#484]
github.com/gorilla/websocket.(*Conn).SetReadDeadline:1032 runtime error: invalid memory address or nil pointer dereference

**Comment by stevenscott89** [comment]
The application called the method with a nil *Conn.  Check and handle the error returned from Upgrade and Dial.

**Comment by garyburd** [comment]
The previous comment describes the problem in the application.

**Comment by fbens** [comment]
Hello, Did you solve this problem? I also encountered the same error.
