### ISSUE TITLE
I/O timeout on first Reconnect

### ISSUE THREAD

**Issue by renevall** [gorilla/websocket#486]
Hello, we are experience the following Issue.

We have a devices that connect to a server through websockets. I built the reconnect logic which leverages on a conn.read() error. On the defer of the read goroutine I call a reconnect function that looks like this more or less:

```go
func (c *Client) reconnect() {
	u := url.URL{Scheme: "ws", Host: c.RemoteAddress, Path: "/ws"}
	log.Printf("reconnecting to %s", u.String())

	ticker := time.NewTicker(time.Duration(c.server.Config.ReconnIterval) * time.Second).C

	for {
		select {
		case <-ticker:
			conn, res, err := websocket.DefaultDialer.Dial(u.String(), h)
			if err != nil {
				log.Println("Error:", err.Error())
				continue
			}
			c.connMu.Lock()
			c.conn = conn
			c.connMu.Unlock()
			room.register <- c
			//relauch routines
			go c.readListener(room)
			go c.writeListener()
			return
		}
	}
}
```

The mutex avoids data races, but even so old routines already stop by the time we launch reconnect

The specific issue is that the first reconnect, if we simulate a long DC(unwire device) it always gives I/O timeout. But on second reconnect it works just fine. Now, if I plug and plug with a rather short interval it works just fine most of the time. I have a feeling it has to do with deadline but not sure. I make sure that I conn.Close both in Server and Device, so there is no chance that it tries to use a dead conn.

Maybe you can give me a north what to seek. 

Thanks,

**Comment by stevenscott89** [comment]
Run the application with the race detector and fix any errors.  The one Lock/Unlock shown is not sufficient to prevent a data race.

See the following for a simpler way to structure the code. Instead of reconnecting from deep in the code, unwind to the top-level and dial from there.  

      for {
	    conn, res, err := websocket.DefaultDialer.Dial(u.String(), h)
            if err != nil {
                  // sleep to prevent fast dialing
                  continue
           }
          c := &Client{conn: conn}
          go c.serveWrite()
          c.serveRead()
    }

```
func (c *Client) serveRead() {
      defer c.conn.Close()

      room.register <- c
      defer func() { room.unregister <- c }()

      for {
         messageType, r, err := conn.NextReader()
         if err != nil {
            return
       }
       .. process message 
}
```

**Comment by renevall** [comment]
@stevenscott89 Yeah I've been looking for data races using the detector. Already fixed a few of them. Let me try your approach. Your approach seems a lot simpler than mine. 

I'll keep you posted.

**Comment by stevenscott89** [comment]
Because connections are independent of each other, any problems creating a new connection are either an issue with the application or the server (perhaps the server limits connections from a user or address).  

I suggest closing the issue and opening a new issue if you find a bug in the package.

**Comment by garyburd** [comment]
Closing because it's an issue with the application, not this package.
