### ISSUE TITLE
Websocket issue

### ISSUE THREAD

**Issue by tshradheya** [gorilla/websocket#489]
Any resolution for this?

https://stackoverflow.com/questions/32643647/why-does-my-websocket-server-always-report-websocket-control-frame-length-12

**Comment by stevenscott89** [comment]
The peer sent an invalid control frame as described in the error message.

**Comment by tshradheya** [comment]
I have a confusion

In my server code I have a `readJSON()` and `setPongHandler()`


So in my code 
```go
err := conn.readJSON(&msg)
if err != nil {
        log("Error in reading message %+v with error: %s", msg, err)
```

This gives me a log message of 
`Error in reading message {default json object cause no data parsable} with error: control frame length > 125`


Since control frames are only ping and pong and my client only sends pong(), why is the pong being parsed by `readJSON` and not handled by pong handler? Or is it that server is confusing pong  something for a actual message

**Comment by stevenscott89** [comment]
The server is not confusing PONG for an actual message.  See [documentation on how control messages are processed](https://godoc.org/github.com/gorilla/websocket#hdr-Control_Messages) for more information.

Show the client code that sends the PONG.

**Comment by tshradheya** [comment]
I am using React Native's inbuild Websocket. It does not allow explicit send of PONG but if server pings it then it will send PONG on its own(it happens under the hood)

Also really appreciate your quick responses 🙂 🚀

**Comment by tshradheya** [comment]
`If an application sends ping messages, then the application should set a pong handler to receive the corresponding pong.`

Does this mean that if i dont set a pong handler, it will not recieve the pong 🤔

**Comment by stevenscott89** [comment]
It only makes sense to send a ping if the application is going to take some action in response to the pongs or lack thereof. The application must set a pong handler to detect when pong messages are received.

The control messages are ping, pong and close.   Is the client sending an invalid close message?
