### ISSUE TITLE
Example of `BufferWritePool` for Upgrade

### ISSUE THREAD

**Issue by tshradheya** [gorilla/websocket#491]
Is there an example of `BufferWritePool`. Also are there some recommended values for that parameter?

**Comment by stevenscott89** [comment]
A `*sync.Pool` is the recommended value. An example is:

```
var upgrader = websocket.Upgrader{
       WriteBufferPool: &sync.Pool{}
        ... other fields
}
```

**Comment by tshradheya** [comment]
Thank you. What about numerical values suggestions?

**Comment by stevenscott89** [comment]
There is no numerical value for `WriteBufferPool`.   Perhaps you are asking about `WriteBufferSize`.   See https://godoc.org/github.com/gorilla/websocket#hdr-Buffers for recommendations.
