### ISSUE TITLE
no doc related to hearbeat use case when connection is for push only events

### ISSUE THREAD

**Issue by jjuraszek** [gorilla/websocket#492]
right now according to doc you have to read from connection to fire `SetPongHandler` event. But if the `websocket` is used for push only it won't be fired. Solution is to use:

```
go ws.NextReader()
```

But the doc is not very straight forward about that. In my opinion there should be description of **how to setup heartbeat in case of push only usage**. Let me know if you need help with that.

**Comment by stevenscott89** [comment]
This is covered in the [section about control message](https://godoc.org/github.com/gorilla/websocket#hdr-Control_Messages).  The section includes the snippet of code to use.

**Comment by jjuraszek** [comment]
The read operation is blocking so `c.Close()` might not ever happen for unresponsive client. Therefore I think it's not right way to implement heartbeat procedure. I think it should be explicitly described procedure of using:

* `websocket.Conn.SetPongHandler` for registration of last PONG time from client
* `websocket.Conn.NextReader()` for reassurance that PONG is even obtained
* `websocket.Conn.WriteMessage(websocket.PingMessage, ...)` for sending PING and checking if there is no socket issue

I'm not saying that there is no documentation. I'm just saying that this common use case is not covered as whole neither by examples nor by documentation. All breadcrumbs are separated ;)

It takes me at least 2h to figure out how to do it right. So I can create example to save time of others working on similar case. Does it sound reasonable?

**Comment by stevenscott89** [comment]
All of the [examples](https://github.com/gorilla/websocket/tree/master/examples) except the echo example show how to use ping/pong.  

The filewatch example covers the push only scenario ([code here](https://github.com/gorilla/websocket/blob/0ec3d1bd7fe50c503d6df98ee649d81f4857c564/examples/filewatch/main.go#L59-L70)).

**Comment by garyburd** [comment]
The filewatch example covers the scenario.  Do we need to make the examples more visible?  Does the filewatch example need improvement?

**Comment by elithrar** [comment]
Closing this one out for now.

**Comment by ozgurakcali** [comment]
This definitley needs to be documented visibly IMO, the fact that we need a dummy reader for gorilla to be able to respond to ping messages on a push only scenario.

**Comment by ozgurakcali** [comment]
A dummy reader should not be necessary to be able to respond to ping messages IMO. Even if it is documented, it doesn't feel natural.

**Comment by TaylorRex** [comment]
@ozgurakcali  That would be nice, but the package cannot know if the application will read the connection or not.
