### ISSUE TITLE
Close method is called on happy path only

### ISSUE THREAD

**Issue by g7r** [gorilla/websocket#493]
See https://github.com/gorilla/websocket/blob/0ec3d1bd7fe50c503d6df98ee649d81f4857c564/conn.go#L756-L763

**Comment by stevenscott89** [comment]
Why does it need to be closed on the unhappy path?

**Comment by g7r** [comment]
We need it because `Close()` returns `c.writeBuf` to `c.writePool`.

**Comment by g7r** [comment]
See https://github.com/gorilla/websocket/blob/0ec3d1bd7fe50c503d6df98ee649d81f4857c564/conn.go#L528

**Comment by stevenscott89** [comment]
The method `endMessage` returns the buffer to the pool.  The `endMessage` method is called when Write returns an error.

**Comment by g7r** [comment]
It is somewhat surprising that cleanup isn't being done in `Close()` alone and calling it isn't mandatory.

**Comment by stevenscott89** [comment]
The call to Close() is only required to flush the message to the network.

**Comment by g7r** [comment]
The general meaning of `Close()` is to perform some kind of resource cleanup. Generally I don't have to know what kind of cleanup it performs. The pattern I see here is being replicated throughout usages of this library. I think it is safer to always call `Close()` if `Writer` has been returned.
