### ISSUE TITLE
False positive for hijack alert

### ISSUE THREAD

**Issue by mcandre** [gorilla/websocket#494]
Hi, I previously reported an issue with gorilla websockets warning about connection hijacks:

https://github.com/gorilla/websocket/issues/212

Now with Go v1.11 and no WS close signal, I still get these spurious warnings:

```console
2019/03/19 12:30:41 http: response.WriteHeader on hijacked connection
2019/03/19 12:30:41 http: response.Write on hijacked connection
```

This happens, for example, when opening a client connection with https://github.com/hashrocket/ws

**Comment by stevenscott89** [comment]
The warnings indicate that the application is calling http.ResponseWriter methods after the call to Upgrade.

**Comment by mcandre** [comment]
@stevenscott89

Thank you for clarifying!

Hmm, once the WebSocket is successfully established, is there a good way to report an error during processing using the response writer? Or should such errors be relayed strictly over WebSocket messages?

**Comment by stevenscott89** [comment]
It is not possible to revert back the HTTP protocol or simultaneously use the HTTP protocol after the connection is upgraded to the WebSocket protocol.  Use WebSocket message.
