### ISSUE TITLE
Is there a way to use only one goroutine per connection to do all the read job and write job?

### ISSUE THREAD

**Issue by danceinstyle** [gorilla/websocket#495]
I see the chat example start one goroutine for readPump() and another one for writePump(), Can we just start a single goroutine to do all the readPump() and writePump()? Just trying to start goroutine as less as possible.

**Comment by elithrar** [comment]
Can you explain why you want to do this? (Curious)

**Comment by danceinstyle** [comment]
No specific reason, just want to know that is this something we could do to reduce resource consumption like memory.

**Comment by stevenscott89** [comment]
The writing goroutine can be eliminated, but one must careful about writes that block.

The writePump goroutines can be eliminated from the chat example by writing from the hub goroutine, but the hub can stall for up to `writeWait` timeout for each connection.  That's not ideal for chat example where one wants to broadcast a message to all connected clients in a timely fashion.

If some delay on delivering messages is acceptable, then application can use a pool shared goroutines for broadcasting to all clients.  The size of the pool relative to the number of clients can be adjusted up or down to  change the average amount of delay in delivering messages.
