### ISSUE TITLE
Websocket authentication in iris using JWT

### ISSUE THREAD

**Issue by majidbigdeli** [gorilla/websocket#497]
How Websocket authentication in iris using JWT ?

How can I set a header?

**Comment by stevenscott89** [comment]
Use the` responseHeader` argument to [Upgrade](https://godoc.org/github.com/gorilla/websocket#Upgrader.Upgrade) and `requestHeader` argument to [Dial](https://godoc.org/github.com/gorilla/websocket#Dialer.Dial) to set headers.

Ask elsewhere about Iris and JWT.
