### ISSUE TITLE
I/O timeout on deadline

### ISSUE THREAD

**Issue by renevall** [gorilla/websocket#498]
Hello.

I've been struggling all day with timeouts. And it seems strictly related to what I set in the pong wait. 

Here is my test setup.

A client and Server successfully connect. I wait for a bit to make sure there is a ping back and forth. Everything looks good. 

```
[...]
        c.conn.SetReadLimit(maxMessageSize)
	c.conn.SetReadDeadline(time.Now().Add(pongWait))
	c.conn.SetPongHandler(func(string) error {
		c.conn.SetReadDeadline(time.Now().Add(pongWait))
		fmt.Println("Receive Pong from server")

		return nil
	})
```

But as soon as I open the stream of messages(currently capped at 2 mps), at exactly 54 seconds I get a I/O timeout. This is related to having the value as:

```
        writeWait      = 10 * time.Second
	pongWait       = 60 * time.Second
	pingPeriod     = (pongWait * 9) / 10
	maxMessageSize = 1024 * 1024
```

Whatever I put on, at 90% of the time, connection fails. But pings are not failing. 

I already checked for data races. Any help would be great to have.

**Comment by renevall** [comment]
Sample log

> 
19/03/27 23:48:15 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:15 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:15 Room 1122334455_video got message of type video
2019/03/27 23:48:15 sending to 1122334455
2019/03/27 23:48:15 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:15 Room 1122334455_video got message of type video
2019/03/27 23:48:15 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:15 sending to 1122334455
2019/03/27 23:48:16 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:16 Room 1122334455_video got message of type video
2019/03/27 23:48:16 sending to 1122334455
2019/03/27 23:48:16 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:16 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:16 Room 1122334455_video got message of type video
2019/03/27 23:48:16 sending to 1122334455
2019/03/27 23:48:16 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:17 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:17 Room 1122334455_video got message of type video
2019/03/27 23:48:17 sending to 1122334455
2019/03/27 23:48:17 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:17 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:17 Room 1122334455_video got message of type video
2019/03/27 23:48:17 sending to 1122334455
2019/03/27 23:48:17 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:17 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:17 Room 1122334455_video got message of type video
2019/03/27 23:48:17 sending to 1122334455
2019/03/27 23:48:17 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:17 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:17 Room 1122334455_video got message of type video
2019/03/27 23:48:17 sending to 1122334455
2019/03/27 23:48:17 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:18 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:18 Room 1122334455_video got message of type video
2019/03/27 23:48:18 sending to 1122334455
2019/03/27 23:48:18 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:18 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:18 Room 1122334455_video got message of type video
2019/03/27 23:48:18 sending to 1122334455
2019/03/27 23:48:18 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:18 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:18 Room 1122334455_video got message of type video
2019/03/27 23:48:18 sending to 1122334455
2019/03/27 23:48:18 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:18 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:18 Room 1122334455_video got message of type video
2019/03/27 23:48:18 sending to 1122334455
2019/03/27 23:48:18 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:19 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:19 Room 1122334455_video got message of type video
2019/03/27 23:48:19 sending to 1122334455
2019/03/27 23:48:19 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:19 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:19 Room 1122334455_video got message of type video
2019/03/27 23:48:19 sending to 1122334455
2019/03/27 23:48:19 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:19 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:19 Room 1122334455_video got message of type video
2019/03/27 23:48:19 sending to 1122334455
2019/03/27 23:48:19 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:19 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:19 Room 1122334455_video got message of type video
2019/03/27 23:48:19 sending to 1122334455
2019/03/27 23:48:19 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:20 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:20 Room 1122334455_video got message of type video
2019/03/27 23:48:20 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:20 sending to 1122334455
2019/03/27 23:48:20 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:20 Room 1122334455_video got message of type video
2019/03/27 23:48:20 sending to 1122334455
2019/03/27 23:48:20 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:20 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:20 Room 1122334455_video got message of type video
2019/03/27 23:48:20 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:20 sending to 1122334455
2019/03/27 23:48:20 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:20 Room 1122334455_video got message of type video
2019/03/27 23:48:20 sending to 1122334455
2019/03/27 23:48:20 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
[...]
2019/03/27 23:48:30 sending to 1122334455
2019/03/27 23:48:30 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:30 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:30 Room 1122334455_video got message of type video
2019/03/27 23:48:30 sending to 1122334455
2019/03/27 23:48:30 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:30 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:30 Room 1122334455_video got message of type video
2019/03/27 23:48:30 sending to 1122334455
2019/03/27 23:48:30 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:30 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:30 Room 1122334455_video got message of type video
2019/03/27 23:48:30 sending to 1122334455
2019/03/27 23:48:30 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:31 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:31 Room 1122334455_video got message of type video
2019/03/27 23:48:31 sending to 1122334455
2019/03/27 23:48:31 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:31 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:31 Room 1122334455_video got message of type video
2019/03/27 23:48:31 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:31 sending to 1122334455
2019/03/27 23:48:31 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:31 Room 1122334455_video got message of type video
2019/03/27 23:48:31 sending to 1122334455
2019/03/27 23:48:31 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:31 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:31 Room 1122334455_video got message of type video
2019/03/27 23:48:31 sending to 1122334455
2019/03/27 23:48:31 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:32 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:32 Room 1122334455_video got message of type video
2019/03/27 23:48:32 sending to 1122334455
2019/03/27 23:48:32 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:32 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:32 Room 1122334455_video got message of type video
2019/03/27 23:48:32 sending to 1122334455
2019/03/27 23:48:32 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:32 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:32 Room 1122334455_video got message of type video
2019/03/27 23:48:32 sending to 1122334455
2019/03/27 23:48:32 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:32 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:32 Room 1122334455_video got message of type video
2019/03/27 23:48:32 sending to 1122334455
2019/03/27 23:48:32 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:33 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:33 Room 1122334455_video got message of type video
2019/03/27 23:48:33 sending to 1122334455
2019/03/27 23:48:33 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:33 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:33 Room 1122334455_video got message of type video
2019/03/27 23:48:33 sending to 1122334455
2019/03/27 23:48:33 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:33 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:33 Room 1122334455_video got message of type video
2019/03/27 23:48:33 sending to 1122334455
2019/03/27 23:48:33 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:33 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:33 Room 1122334455_video got message of type video
2019/03/27 23:48:33 sending to 1122334455
2019/03/27 23:48:33 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:34 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:34 Room 1122334455_video got message of type video
2019/03/27 23:48:34 sending to 1122334455
2019/03/27 23:48:34 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:34 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:34 Room 1122334455_video got message of type video
2019/03/27 23:48:34 sending to 1122334455
2019/03/27 23:48:34 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:34 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:34 Room 1122334455_video got message of type video
2019/03/27 23:48:34 sending to 1122334455
2019/03/27 23:48:34 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:34 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:34 Room 1122334455_video got message of type video
2019/03/27 23:48:34 sending to 1122334455
2019/03/27 23:48:34 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:35 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:35 Room 1122334455_video got message of type video
2019/03/27 23:48:35 sending to 1122334455
2019/03/27 23:48:35 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:35 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:35 Room 1122334455_video got message of type video
2019/03/27 23:48:35 sending to 1122334455
2019/03/27 23:48:35 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:35 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:35 Room 1122334455_video got message of type video
2019/03/27 23:48:35 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:35 sending to 1122334455
2019/03/27 23:48:35 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:35 Room 1122334455_video got message of type video
2019/03/27 23:48:35 sending to 1122334455
2019/03/27 23:48:35 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:36 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:36 Room 1122334455_video got message of type video
2019/03/27 23:48:36 sending to 1122334455
2019/03/27 23:48:36 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:36 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:36 Room 1122334455_video got message of type video
2019/03/27 23:48:36 sending to 1122334455
2019/03/27 23:48:36 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:36 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:36 Room 1122334455_video got message of type video
2019/03/27 23:48:36 sending to 1122334455
2019/03/27 23:48:36 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:36 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:36 Room 1122334455_video got message of type video
2019/03/27 23:48:36 sending to 1122334455
2019/03/27 23:48:36 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:37 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:37 Room 1122334455_video got message of type video
2019/03/27 23:48:37 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:37 sending to 1122334455
2019/03/27 23:48:37 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:37 Room 1122334455_video got message of type video
2019/03/27 23:48:37 sending to 1122334455
2019/03/27 23:48:37 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:38 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:38 Room 1122334455_video got message of type video
2019/03/27 23:48:38 sending to 1122334455
2019/03/27 23:48:38 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:38 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:38 Room 1122334455_video got message of type video
2019/03/27 23:48:38 sending to 1122334455
2019/03/27 23:48:38 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:38 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:38 Room 1122334455_video got message of type video
2019/03/27 23:48:38 sending to 1122334455
2019/03/27 23:48:38 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:38 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:38 Room 1122334455_video got message of type video
2019/03/27 23:48:38 sending to 1122334455
2019/03/27 23:48:38 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:39 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:39 Room 1122334455_video got message of type video
2019/03/27 23:48:39 sending to 1122334455
2019/03/27 23:48:39 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:39 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:39 Room 1122334455_video got message of type video
2019/03/27 23:48:39 sending to 1122334455
2019/03/27 23:48:39 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:39 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:39 Room 1122334455_video got message of type video
2019/03/27 23:48:39 sending to 1122334455
2019/03/27 23:48:39 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:39 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:39 Room 1122334455_video got message of type video
2019/03/27 23:48:39 sending to 1122334455
2019/03/27 23:48:39 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:40 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:40 Room 1122334455_video got message of type video
2019/03/27 23:48:40 sending to 1122334455
2019/03/27 23:48:40 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:40 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:40 Room 1122334455_video got message of type video
2019/03/27 23:48:40 sending to 1122334455
2019/03/27 23:48:40 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:40 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:40 Room 1122334455_video got message of type video
2019/03/27 23:48:40 sending to 1122334455
2019/03/27 23:48:40 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:40 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:40 Room 1122334455_video got message of type video
2019/03/27 23:48:40 sending to 1122334455
2019/03/27 23:48:40 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:41 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:41 Room 1122334455_video got message of type video
2019/03/27 23:48:41 sending to 1122334455
2019/03/27 23:48:41 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:41 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:41 Room 1122334455_video got message of type video
2019/03/27 23:48:41 sending to 1122334455
2019/03/27 23:48:41 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:41 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:41 Room 1122334455_video got message of type video
2019/03/27 23:48:41 sending to 1122334455
2019/03/27 23:48:41 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:41 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:41 Room 1122334455_video got message of type video
2019/03/27 23:48:41 sending to 1122334455
2019/03/27 23:48:41 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:42 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:42 Room 1122334455_video got message of type video
2019/03/27 23:48:42 sending to 1122334455
2019/03/27 23:48:42 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:42 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:42 Room 1122334455_video got message of type video
2019/03/27 23:48:42 sending to 1122334455
2019/03/27 23:48:42 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:42 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:42 Room 1122334455_video got message of type video
2019/03/27 23:48:42 sending to 1122334455
2019/03/27 23:48:42 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:42 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:42 Room 1122334455_video got message of type video
2019/03/27 23:48:42 sending to 1122334455
2019/03/27 23:48:42 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:43 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:48:43 Room 1122334455_video got message of type video
2019/03/27 23:48:43 sending to 1122334455
2019/03/27 23:48:43 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:48:43 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
[...]
2019/03/27 23:49:03 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:03 ping sent
2019/03/27 23:49:03 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:03 Room 1122334455_video got message of type video
2019/03/27 23:49:03 sending to 1122334455
2019/03/27 23:49:03 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:03 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:03 Room 1122334455_video got message of type video
2019/03/27 23:49:03 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:03 sending to 1122334455
2019/03/27 23:49:04 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:04 Room 1122334455_video got message of type video
2019/03/27 23:49:04 sending to 1122334455
2019/03/27 23:49:04 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:04 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:04 Room 1122334455_video got message of type video
2019/03/27 23:49:04 sending to 1122334455
2019/03/27 23:49:04 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:04 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:04 Room 1122334455_video got message of type video
2019/03/27 23:49:04 sending to 1122334455
2019/03/27 23:49:04 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:04 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:04 Room 1122334455_video got message of type video
2019/03/27 23:49:04 sending to 1122334455
2019/03/27 23:49:04 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:05 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:05 Room 1122334455_video got message of type video
2019/03/27 23:49:05 sending to 1122334455
2019/03/27 23:49:05 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:05 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:05 Room 1122334455_video got message of type video
2019/03/27 23:49:05 sending to 1122334455
2019/03/27 23:49:05 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:05 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:05 Room 1122334455_video got message of type video
2019/03/27 23:49:05 sending to 1122334455
2019/03/27 23:49:05 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:05 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:05 Room 1122334455_video got message of type video
2019/03/27 23:49:05 sending to 1122334455
2019/03/27 23:49:05 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:06 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:06 Room 1122334455_video got message of type video
2019/03/27 23:49:06 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:06 sending to 1122334455
2019/03/27 23:49:06 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:06 Room 1122334455_video got message of type video
2019/03/27 23:49:06 sending to 1122334455
2019/03/27 23:49:06 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:06 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:06 Room 1122334455_video got message of type video
2019/03/27 23:49:06 sending to 1122334455
2019/03/27 23:49:06 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:06 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:06 Room 1122334455_video got message of type video
2019/03/27 23:49:06 sending to 1122334455
2019/03/27 23:49:06 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:07 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:07 Room 1122334455_video got message of type video
2019/03/27 23:49:07 sending to 1122334455
2019/03/27 23:49:07 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:07 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:07 Room 1122334455_video got message of type video
2019/03/27 23:49:07 sending to 1122334455
2019/03/27 23:49:07 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:08 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:08 Room 1122334455_video got message of type video
2019/03/27 23:49:08 sending to 1122334455
2019/03/27 23:49:08 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:08 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:08 Room 1122334455_video got message of type video
2019/03/27 23:49:08 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:08 sending to 1122334455
2019/03/27 23:49:08 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:08 Room 1122334455_video got message of type video
2019/03/27 23:49:08 sending to 1122334455
2019/03/27 23:49:08 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:08 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:08 Room 1122334455_video got message of type video
2019/03/27 23:49:08 sending to 1122334455
2019/03/27 23:49:08 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:09 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:09 Room 1122334455_video got message of type video
2019/03/27 23:49:09 sending to 1122334455
2019/03/27 23:49:09 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:09 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:09 Room 1122334455_video got message of type video
2019/03/27 23:49:09 sending to 1122334455
2019/03/27 23:49:09 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:09 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:09 Room 1122334455_video got message of type video
2019/03/27 23:49:09 sending to 1122334455
2019/03/27 23:49:09 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:09 Client b87ba076-d069-46cd-ae82-0d76b839cddd got message of type video
2019/03/27 23:49:09 Room 1122334455_video got message of type video
2019/03/27 23:49:09 sending to 1122334455
2019/03/27 23:49:09 sending to 13a639e6-0f3e-4cbc-a568-0273007593b2
2019/03/27 23:49:09 Error reading: read tcp [::1]:7001->[::1]:61013: i/o timeout
2019/03/27 23:49:09 Client b87ba076-d069-46cd-ae82-0d76b839cddd of type screen got disconnected, tearing down
2019/03/27 23:49:09 Client b87ba076-d069-46cd-ae82-0d76b839cddd writer exited
2019/03/27 23:49:09 Client b87ba076-d069-46cd-ae82-0d76b839cddd left channel 1122334455_video
2019/03/27 23:49:09 Room 1122334455_video has 1 clients
2019/03/27 23:49:09 Client b87ba076-d069-46cd-ae82-0d76b839cddd left channel 
>

**Comment by renevall** [comment]
After further testing issue is related to an acknowledgment cicle I created that somehow ends up breaking the conn. I guess past recommendations that have been given to similar issues still stands, to make sure server/client is able to ping back. Closing this

**Comment by Akshit8** [comment]
@renevall can you explain the issue in a bit more detail, as I am also facing the same problem.

**Comment by willie5588912** [comment]
My case is a little bit different with this issue, but just share with someone who also faces the I/O timeout error in websocket ping-pong checking mechanism. In my case, I found out the reason resulting in the I/O timeout error is really simple: I set the **pongWait** too short. 

The main reason is that I misunderstood the cover range of **pongWait**. I thought the **pongWait** starts counting just after the ping is sent for every new ping, which means that I just need to take the device reponse time into account and this period is normally short. Well, the [official example](https://github.com/gorilla/websocket/blob/a68708917c6a4f06314ab4e52493cc61359c9d42/examples/chat/conn.go#L127) uses **go routine** for writePump(), so if fact writePump() is some kind of asynchronous with the readPump(). 

In other words, the **pongWait** covers the time including the ticker time (**pingPeriod**, namely how fast you send another ping again) of writePump(). If we assume that we've just received the newest pong immediately after the ping is sent and the device reponse time is short, then **pongWait ≈ pingPeriod**, because [the read deadline only gets reset when a pong received](https://github.com/gorilla/websocket/blob/a68708917c6a4f06314ab4e52493cc61359c9d42/examples/chat/conn.go#L57). We can also found a [comment](https://github.com/gorilla/websocket/blob/a68708917c6a4f06314ab4e52493cc61359c9d42/examples/chat/conn.go#L23) mentioning that **pingPeriod** must shorter the **pongWait** just before the definition of it.

In other words, if the **pingPeriod** long, you also need to set the **pongWait** longer than it.
