### ISSUE TITLE
Reconnect Issue(I/O timeout) - Follow up on #486

### ISSUE THREAD

**Issue by renevall** [gorilla/websocket#500]
Hello guys, first of all thanks for the package, it's been quite handy to us.

I wanted to follow up on this issue. Last time I could not provide a reliable way to reproduce this bug since our codebase has quite a few of message routing. But I found time to create a sample code following repo's chat example plus creating a client in go with reconnect logic.

So with the bare bones example, I get the exact behavior. On reconnect, the handshake is good, but connection is dead. Sometimes a couple of messages go in but then it stops.

On second connect, for whatever reason, the connections is good. 

## Reproduction

In order to reproduce this bug we need(maybe) to use either two computers or a virtual machine. This is so we can reproduce a disconnection by unplugging the cable or disconnecting the ethernet interfaces.(maybe you know a better way to simulate this)

After cloning the repo: https://github.com/renevall/gorilla-websocket-reconn-error

In two terminals

```
$ go build .
$ ./<binary-file>
```

Then on a virtual machine run:
```
$ go run remote/remote.go
```

Disconnect the VM and wait until it shows reconnecting. On first reconnect you will see the conn dies away, but on the second it runs just fine.

**Comment by renevall** [comment]
this is a follow up to #486

**Comment by stevenscott89** [comment]
This is not a forum for discussing applications, but I'll dive in anyway.   

The application shares state across connections.  Remove the shared by declaring `done` and `doneR` inside the loop.   There are scenarios where a goroutine will block forever trying to send to one of these channels.  Fix by closing the channel instead of sending a value.   

Close the connection to prevent a resource leak.

	for {

		done := make(chan struct{})
		doneR := make(chan struct{})

		log.Printf("connecting to %s", u.String())

		c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
		if err != nil {
			log.Println("dial:", err)
			time.Sleep(2 * time.Second)
			continue
		}

		//write
		go func() {
			defer close(doneR)
			defer c.Close()

			ticker := time.NewTicker(time.Second)
			defer ticker.Stop()

			tickerP := time.NewTicker(pingPeriod)
			defer tickerP.Stop()

			defer log.Println("write closed")

			for {
				select {
				case <-done:
					return
				case t := <-ticker.C:
					c.SetWriteDeadline(time.Now().Add(writeWait))
					err := c.WriteMessage(websocket.TextMessage, []byte(t.String()))
					if err != nil {
						log.Println("write:", err)
						return
					}
				case <-tickerP.C:
					log.Println("sending ping")
					c.SetWriteDeadline(time.Now().Add(writeWait))
					if err := c.WriteMessage(websocket.PingMessage, nil); err != nil {
						return
					}

				}
			}
		}()

		//read
		func() {
			defer close(done)
			defer c.Close()

			c.SetReadLimit(maxMessageSize)
			c.SetReadDeadline(time.Now().Add(pongWait))
			c.SetPongHandler(func(string) error {
				c.SetReadDeadline(time.Now().Add(pongWait))
				fmt.Println("got a pong from client")
				return nil
			})
			defer log.Println("read closed")
			for {
				select {
				case <-doneR:
					return

				default:
					_, message, err := c.ReadMessage()
					if err != nil {
						log.Println("read:", err)
						return
					}
					log.Printf("recv: %s", message)
				}
			}
		}()
	}

**Comment by renevall** [comment]
@stevenscott89 thanks for your time, I appreciate your input on this. I'm trying to do my due diligence on this, that's why I'm trying to follow the sample code of the repo as close as posible. Give me a few mins.

**Comment by garyburd** [comment]
All code related to `doneR` can be deleted.  Closing the connection from the writing goroutine is sufficient to cause the read function to exit immediately.

**Comment by renevall** [comment]
@garyburd the reason I made it work like that is because sometimes read would detect a disconnect sometimes it was the write. So that created a scenario where if the reconnect happens rather fast I was getting two connection writers running. So I chose to recycle both go routines as soon as either detects a disconnect. I will check if by removing that part it helps.

**Comment by garyburd** [comment]
The `doneR` is harmless, but not needed. The writer calls `c.Close()` on error.  The function `c.ReadMessage()` returns immediately with an error when the connection is closed. 

The `done` channel is needed for fast detection of close in the writing goroutine.

**Comment by renevall** [comment]
@garyburd Gotcha. In the error I get, 99% of the time it's the read that detects the disconnect. But I will note down what happens when it's the write. 

@stevenscott89 the error still happens, but I want to try this from another machine since I test the dc mostly from vagrant and it may be corrupting the conn. Will report back.

**Comment by garyburd** [comment]
My comments are about @stevenscott89’s code, not the original.
