### ISSUE TITLE
WebSocket.onerror

### ISSUE THREAD

**Issue by GLeBaTi** [gorilla/websocket#501]
How can i write errors by server to javascript client (onerror)?

```
ws = new WebSocket("wss://localhost:9096/logs/ws")
ws.onerror = function(error) {
  console.error('WebSocket Error: ' + error);
};
```

**Comment by stevenscott89** [comment]
The server has no control over the value passed to the onerror function in a browser client.

**Comment by GLeBaTi** [comment]
> The server has no control over the value passed to the onerror function in a browser client.
Can i send some code or message to websocket client like authentification error?

**Comment by stevenscott89** [comment]
Applications should authenticate the websocket handshake they way the application authenticates other HTTP requests.  This authentication happens before the connection is upgraded to the websocket protocol. 

If you are going to authenticate over the weboscket protocol and authentication fails, then send a close message to the client and close the connection.  Something like this:

       c.WriteControlMessage(websocket.CloseMessage, websocke.FormatCloseMessage(code, message))
       c.Close()

where `code` a value in the application error code range (4000-4999) and `message` is a string with length less than 127 bytes.    Use the `onclose` handler in the browser to handle the message.

**Comment by GLeBaTi** [comment]
Thanks!
