### ISSUE TITLE
Do we share context with multiple web sockets?

### ISSUE THREAD

**Issue by nitin302** [gorilla/websocket#506]
In any real work scenario, there are always a set of load balanced servers to handle the concurrent connection load.

In such a case, say we create something like a chat room (if anyone posts a message there, all active users receive this message). The connected clients to a single chatroom may be served from multiple websocket servers.

How can we achieve this? Is there a provision already for this with this library?
Should we go for a redis, pub-sub like way to share context between web socket servers?

**Comment by stevenscott89** [comment]
This package does not provide the requested feature. Although the feature is commonly needed by applications that use WebSockets, the feature is outside the scope of implementing the WebSocket protocol.  Also, the requested feature is not specific to WebSockets.

Redis may be a good way to get started.

**Comment by nitin302** [comment]
thanks @stevenscott89
