### ISSUE TITLE
websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

### ISSUE THREAD

**Issue by dstpierre** [gorilla/websocket#507]
I'm hitting this error in production:

server.go line:126
```go
if !tokenListContainsValue(r.Header, "Connection", "upgrade") {
	return u.returnError(w, r, http.StatusBadRequest, badHandshake+"'upgrade' token not found in 'Connection' header")
```

I'm using the HTML5 web client (tried from Chromium, Chrome and Firefox) and I'm getting this error:

> websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

And from the dev console:

> WebSocket connection to 'wss://myapp.com' failed: Error during WebSocket handshake: Unexpected response code: 200

I've use a custom Upgrader as well as the default one:

```go
conn, err := websocket.Upgrade(w, r, nil, 1024, 1024)
```

And one with this Ugrader:

```go
var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}
```

Locally it works and I'm not even on the same origin in dev, but in production, I'm in the same origin and even though I'm returning `true` in the customer upgrader, I'm getting this error.

Does it have to do with using `wss://` on production instead of `ws://`?

Any pointer, I've been looking around and not finding anything relevant so far.

Thanks

**Comment by pkuca** [comment]
What's terminating TLS in production? Seems like with `wss` something's dropping the upgrade header (assuming the client is confirmed to be behaving as expected). The client hitting `wss://` should be getting a 101 (like your local setup), not 200.

**Comment by stevenscott89** [comment]
Log the value of `r.Header()`.  It looks like something is removing the upgrade header.

**Comment by dstpierre** [comment]
@pkuca I think you are on something, I'm using nginx as reverse proxy and yes indeed the forwarding does not forward as https, does that mean that I have no solution bug to implement my instances as https from nginx? I was going to use a Load Balancer at some point that also would not forward as https though.

Any suggestions here?

**Comment by dstpierre** [comment]
I'll close this issue since it's not related to this package and more to the fact that I'm doing a reverse proxy.

Thanks for your help, for related help for people finding this from a search: http://nginx.org/en/docs/http/websocket.html
