### ISSUE TITLE
Forbidden port using proxy

### ISSUE THREAD

**Issue by peterpan0708** [gorilla/websocket#508]
I set the enviroment variable http_proxy and https_proxy to "http://127.0.0.1:8123/" (my proxy address), and when I try to connect to the websocket, I got the following err: dial: Forbidden Port. Can anyone help?  It seems that If i use a proxy, I can only connect to the port 80 and 443. beyond those two port, I always got Forbidden port error when calling dial function.

![pic](https://user-images.githubusercontent.com/36805830/57272312-ca839500-70c5-11e9-890d-7298aabe7e7e.png)

**Comment by peterpan0708** [comment]
I tried to set proxyUrl to "socks5://127.0.0.1:1080" (my socks5 proxy), it works fine. Why can't i connect to the server through my http proxy?

**Comment by elithrar** [comment]
`Forbidden Port` is not related to this package, nor is that string in the Go source code.

* What is the remote end you're dialling?
* Does it happen if you dial in a browser?
* Can you provide a runnable example?

**Comment by elithrar** [comment]
(Timed out, please let us know if you have a follow-up question!)
