### ISSUE TITLE
websocket.(*Conn).WriteMessage gets stuck indefinitely

### ISSUE THREAD

**Issue by Aditya23456** [gorilla/websocket#509]
Hi,

Thanks for the library. As per documentation, I architected to have only 2 goroutines per WebSocket.  I have one goroutine which loops over and updates/sends data to all connected websocket connections simultaneously. And I have another goroutine for each Read message. When I reload the webpage most cases it works fine (during which web socket closes the connection with 1001 going away error at ReadMessage.)but sometimes I think when WriteMessage executes before ReadMessage(Because I don't see going away error), I see my server stucks up indefinitely with following goroutine trace-
`
internal/poll.runtime_pollWait(0x7f8678e9baf8, 0x77, 0x433a2b)
	/usr/local/go/src/runtime/netpoll.go:182 +0x5e
internal/poll.(*pollDesc).wait(0xc00042d098, 0x77, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x11a
internal/poll.(*pollDesc).waitWrite(0xc00042d098, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:96 +0x79
internal/poll.(*FD).Writev(0xc00042d080, 0xc0003ef120, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/writev.go:66 +0x85a
net.(*netFD).writeBuffers(0xc00042d080, 0xc0003ef120, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/writev_unix.go:26 +0x98
net.(*conn).writeBuffers(0xc0000112b0, 0xc0003ef120, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/writev_unix.go:18 +0xe8
net.(*Buffers).WriteTo(0xc0003ef120, 0x26bdae0, 0xc0000112b0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:660 +0x128
github.com/gorilla/websocket.(*Conn).writeBufs(0xc000507b80, 0xc0004906c0, 0x2, 0x2, 0x0, 0x0)
	/home/aditya/goprojects/src/github.com/gorilla/websocket/conn_write.go:13 +0x172
github.com/gorilla/websocket.(*Conn).write(0xc000507b80, 0x1, 0x0, 0x0, 0x0, 0xc00057200a, 0xff6, 0xff6, 0xc000497ff2, 0x1617, ...)
	/home/aditya/goprojects/src/github.com/gorilla/websocket/conn.go:380 +0x595
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00069b9e8, 0xf01, 0xc000497ff2, 0x1617, 0x180e, 0x0, 0x0)
	/home/aditya/goprojects/src/github.com/gorilla/websocket/conn.go:601 +0x854
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc000507b80, 0x1, 0xc000497ff2, 0x1617, 0x180e, 0x0, 0x0)
	/home/aditya/goprojects/src/github.com/gorilla/websocket/conn.go:753 +0x42c
git.ke2therm.net/anugur/AdvancedLogging/Agents.(*Platform).Safewcwrite(0xc0000ae840, 0xc000507b80, 0xc000497000, 0x2609, 0x2800, 0x0, 0x0)
	/home/aditya/goprojects/src/github.com/myproject/platform.go:243 +0xee
git.ke2therm.net/anugur/AdvancedLogging/Agents.(*Platform).WriteToSitesockets(0xc0000ae840)
`
Please help. I am using go 1.12.1 . I am not sure what more information I need to provide. I feel this is related to golang library but want to start off here first.

**Comment by pkuca** [comment]
```
internal/poll.runtime_pollWait(0x7f8678e9baf8, 0x77, 0x433a2b)
/usr/local/go/src/runtime/netpoll.go:182 +0x5e internal/poll.(*pollDesc).wait(0xc00042d098, 0x77, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x11a internal/poll.(*pollDesc).waitWrite(0xc00042d098, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:96 +0x79 internal/poll.(*FD).Writev(0xc00042d080, 0xc0003ef120, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/writev.go:66 +0x85a net.(*netFD).writeBuffers(0xc00042d080, 0xc0003ef120, 0x0, 0x0, 0x0)
/usr/local/go/src/net/writev_unix.go:26 +0x98 net.(*conn).writeBuffers(0xc0000112b0, 0xc0003ef120, 0x0, 0x0, 0x0)
/usr/local/go/src/net/writev_unix.go:18 +0xe8 net.(*Buffers).WriteTo(0xc0003ef120, 0x26bdae0, 0xc0000112b0, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:660 +0x128 github.com/gorilla/websocket.(*Conn).writeBufs(0xc000507b80, 0xc0004906c0, 0x2, 0x2, 0x0, 0x0)
/home/aditya/goprojects/src/github.com/gorilla/websocket/conn_write.go:13 +0x172
github.com/gorilla/websocket.(*Conn).write(0xc000507b80, 0x1, 0x0, 0x0, 0x0, 0xc00057200a, 0xff6, 0xff6, 0xc000497ff2, 0x1617, ...)
/home/aditya/goprojects/src/github.com/gorilla/websocket/conn.go:380 +0x595
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00069b9e8, 0xf01, 0xc000497ff2, 0x1617, 0x180e, 0x0, 0x0)
/home/aditya/goprojects/src/github.com/gorilla/websocket/conn.go:601 +0x854
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc000507b80, 0x1, 0xc000497ff2, 0x1617, 0x180e, 0x0, 0x0)
/home/aditya/goprojects/src/github.com/gorilla/websocket/conn.go:753 +0x42c
git.ke2therm.net/anugur/AdvancedLogging/Agents.(*Platform).Safewcwrite(0xc0000ae840, 0xc000507b80, 0xc000497000, 0x2609, 0x2800, 0x0, 0x0)
/home/aditya/goprojects/src/github.com/myproject/platform.go:243 +0xee
git.ke2therm.net/anugur/AdvancedLogging/Agents.(*Platform).WriteToSitesockets(0xc0000ae840)
```

Are you able to share any code from the goroutines you create for each connection?

Have you consulted the examples for guidance on how to properly handle the connection goroutines? Specifically, the chat example here: https://github.com/gorilla/websocket/tree/master/examples/chat

If your project is remotely similar to any examples, it'll help triage what the problem is without you dumping tons of source code.

**Comment by elithrar** [comment]
(Timed out, please let us know if you have a follow-up question!)
