### ISSUE TITLE
[Error Again] read tcp 127.0.0.1:8080->127.0.0.1:52901: i/o timeout

### ISSUE THREAD

**Issue by thincal** [gorilla/websocket#511]
This issue could be simply reproduced by adding the `SetReadDealine` into the official echo example ([echo server](https://github.com/gorilla/websocket/blob/master/examples/echo/server.go#L29)):

```
const (
	pongWait = 10 * time.Second
)

func echo(w http.ResponseWriter, r *http.Request) {
        ...
        c.SetReadDeadline(time.Now().Add(pongWait))
	c.SetPongHandler(func(string) error {
		c.SetReadDeadline(time.Now().Add(pongWait))
		return nil
	})
        
        for {
            ...
        }
```

Without `SetReadDeadline`, it **works fine** for both server and client.

Please help with insight or fix, thanks.

**Comment by pkuca** [comment]
You didn't change the client? If you want that to work you need to send `PongMessage`s to trigger that second read deadline. `SetPongHandler`

**Comment by thincal** [comment]
Shouldn't be the client providing the pong handler by default?

Just look at the examples/chat/homt.html, the JS client is not needed to send PongMessage explicitly by user.

**Comment by thincal** [comment]
> You didn't change the client? If you want that to work you need to send `PongMessage`s to trigger the followup read deadlines. `SetPongHandler`

And it should be set the `PingHandler` to response the Ping request from server, right ?
But it seems that neither the Ping nor the Pong handler is not be invoked in client, so the issue is still there.

**Comment by wetcucumber** [comment]
Did you add code to send PINGs?  If not, the application will not receive PONGs and therefore not adjust the deadline.

**Comment by IngCr3at1on** [comment]
> Just look at the examples/chat/homt.html, the JS client is not needed to send PongMessage explicitly by user.

In this instance, the html is being served the web handler in client.go `serveWs` which has both a ping and pong handler activated in separate go routines _for each_ connected client; this means that when a client pings each connected peer pongs back as it's passed the ping message from the hub.

As other's have noted no such ping is ever happening in the echo client so the server never has a chance to pong back.

**Comment by thincal** [comment]
> Did you add code to send PINGs? If not, the application will not receive PONGs and therefore not adjust the deadline.

So the Ping/Pong handler should be added in server and client accordingly by hand ? I will try this setup.

Btw, why not is this Ping/Pong mechanism a built-in infra ?

**Comment by thincal** [comment]
> In this instance, the html is being served the web handler in client.go `serveWs` which has both a ping and pong handler activated in separate go routines _for each_ connected client; this means that when a client pings each connected peer pongs back as it's passed the ping message from the hub.

the chat/client.go is the server part code,

In the readPump,
- which means read the message from client (web)
- where set the PongHandler to handle Pong message from client (Ping initiated by this server), so the read deadline will be reset

in the writePump,
- which means send the message to client (web)
- where sends the Ping message periodically

But, I only want to build the server for receiving message, so I need to send Ping explicitly by hand.
I think this Ping/Pong mechanism should be built-in when something enabled.

**Comment by IngCr3at1on** [comment]
> the chat/client.go is the server part code,

I understand that (in fact I said exactly that...).

> I think this Ping/Pong mechanism should be built-in when something enabled.

Interesting, to me, it makes much more sense for the implementor to decide how to handle ping...

**Comment by elithrar** [comment]
(Timed out, please let us know if you have a follow-up question!)
