### ISSUE TITLE
use tcp.Conn to upgrade

### ISSUE THREAD

**Issue by eudore** [gorilla/websocket#512]
I want to add a new method `func (u *Upgrader) UpgradeConn(net.Conn) (*Conn, error)`, which allows conversion to *websocket.Conn using net.Conn. I am not using the net/http library as the http server. After returning the Upgrade information, I want to use this library to manipulate the ws data.

**Comment by eudore** [comment]
I think *http.Request is a bad design. In http2, fastcgi, and http3, you need to create this object to implement the http.Handler interface, so you don't use net/http.

**Comment by elithrar** [comment]
Keep in mind this library was created well before HTTP/2 was final, let
alone HTTP/2 + WS (which isn’t final) yet.

“Bad design” is a poor choice of words.
