### ISSUE TITLE
Frequent 1011 (internal server error)

### ISSUE THREAD

**Issue by wgeorgecook** [gorilla/websocket#513]
Hi there, 

We've got just two goroutines running (a read and a write), but about every minute we're getting 1011 (internal server error) on our read goroutines. We're thinking it might be benign but we can't qualify that, and we can't trace back what's triggering the `CloseInternalServerErr`. Is there some way we can figure out what's going on internally that's causing the error? 

Bit of code triggering the error is from the example: 

```
_, message, err := c.conn.ReadMessage()
if err != nil {
	if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
		LogErr(err)
	}
	break
}
```

Cheers, 

Will

**Comment by wetcucumber** [comment]
The peer sent a 1011 close message.

**Comment by wgeorgecook** [comment]
Thanks for getting back to me so quickly @wetcucumber! Would the peer for this then be the browser / web app?

**Comment by wetcucumber** [comment]
If your application is server application, then the peer is the client.  If your application is a client, then the peer is the server.

It sounds like your Go application is a server.  Does the server application send 1011 errors?  If so, the 1011 read by your application might be from the closing handshake sent by the client.

**Comment by wgeorgecook** [comment]
You're correct. The websocket is a server and a React app in the browser is the client. I grepped the codebase for 1011 and came up empty. I also asked the front end folks if they're throwing 1011 ever and got a no from them.

**Comment by wetcucumber** [comment]
The package does not generate the CloseInternalServerErr (code 1011) error.  I doubt that web browser does given the error code.

Something in your Go application, the React application or a proxy (if you are using one) is responsible for the error.

**Comment by wgeorgecook** [comment]
Thinking maybe it's in the service mesh we're using then. Will have to start digging there.

**Comment by wgeorgecook** [comment]
It was definitely the service mesh. Istio can return 500s only normal closures and that triggers a 1011 in Gorilla. Thank you!
