### ISSUE TITLE
Is there a way to transfer existing websocket connection to gorilla websocket? 

### ISSUE THREAD

**Issue by shekharHPE** [gorilla/websocket#514]
I have an existing websocket client code in C. 
It just initiates the connection with server, now: 
1. I want to transfer this connection to Go.
2. And especially- transfer this connection to gorilla-websocket library. 
Is there a way in gorilla-library to convert/wrap an existing websocket-client connection to gorilla-websocket connection ?

**Comment by elithrar** [comment]
It’d be non-trivial - if the C lib is running as another process you could
pass the file descriptor to the Go process - but I’d wonder if that’s worth
it vs. just doing it in Go.

Is there a specific reason you need to keep the C client?

**Comment by elithrar** [comment]
(Timed out, please let us know if you have a follow-up question!)
