### ISSUE TITLE
This library does not support NTLM Proxy 

### ISSUE THREAD

**Issue by SakiiR** [gorilla/websocket#518]
It is not possible to authenticate with NTLM on proxy server :(

**Comment by elithrar** [comment]
This library shouldn’t impact that - you should be able to set a HTTP
header with the required NTLM digest when you call Dialer.Dial.

https://godoc.org/github.com/gorilla/websocket#Dialer.DialContext

If you’re still running into problems after trying that, please post your
code / a minimal example.

**Comment by elithrar** [comment]
(Closing - let us know if you have any more questions!)

**Comment by SakiiR** [comment]
I found an alternative.

I run out a "custom shitty proxy" locally which is communicating with NTLM proxy :)

So that each of my connections uses a really simple proxy which is then doing complex things. Thanks for the answer anyway :)

**Comment by pariseed** [comment]
Hi, i'm facing a similar issue,
currently i'm using chisel client [](https://github.com/jpillora/chisel/blob/master/client/client.go#L190), which use websocket to perform connection to a proxy.
Can you please show me how can i use in this context ntlm auth ?

**Comment by elithrar** [comment]
Take a look at https://github.com/Codehardt/go-ntlm-proxy-auth -> which has a `ntlm. WrapDialContext` function.

You can use this as part of a [`websocket.Dialer.NetDialContext`](https://godoc.org/github.com/gorilla/websocket#Dialer) to achieve this - this library doesn't interfere with any proxy authentication as it allows you to override the underlying diallers.

**Comment by pariseed** [comment]
Thank you very much  @elithrar
