### ISSUE TITLE
How to get the instance of *net.TCPConn?

### ISSUE THREAD

**Issue by hhxsv5** [gorilla/websocket#520]
**Describe the problem you're having**
I want to get the *net.TCPConn instance to invoke the method SetNoDelay.
…

**Versions**
go version go1.12.1 darwin/amd64
…

**"Show me the code!"**
```go
c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
if err != nil {
	log.Fatal("dial:", err)
}
defer c.Close()
// c.conn.UnderlyingConn().(*tls.Conn).???
// The member conn(*net.TCPConn) of tls.Conn is private, I cannot access it.
```
…

**Comment by StephenYama** [comment]
Provide the [NetDial](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDial) or [NetDialContext](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDialContext) functions and set no delay on the connection before returning it.

**Comment by elithrar** [comment]
Calling `tcpConn, ok := *websocket.Conn.UnderlyingConn().(*net.TCPConn)` as a type assertion should also work here.

**Comment by hhxsv5** [comment]
> Calling `tcpConn, ok := *websocket.Conn.UnderlyingConn().(*net.TCPConn)` as a type assertion should also work here.

It's *tls.Conn, not *net.TCPConn.

**Comment by IngCr3at1on** [comment]
Is this solved then?

**Comment by elithrar** [comment]
Closing as resolved, but let us know if any more questions.
