### ISSUE TITLE
multi-connection TLS multiplexing

### ISSUE THREAD

**Issue by weiyixuan** [gorilla/websocket#521]
Whether multi-connection TLS reuse is supported? If not, will it be implemented in the future?

**Comment by IngCr3at1on** [comment]
To my understanding (and admittedly this is something I just read up on before answering here so I may have missed something); multiplexed TLS requires the DTLS protocol which is not implemented in the STL. There is a Go DTLS implementation floating around but based on the age I'm pretty sure anything done around the TLS support in Gorilla would predate its existence.

Interesting the RFC for TLS multiplexing appears to be in draft stage and has expired...

**Comment by elithrar** [comment]
Browsers don’t support DTLS for WebSockets - only for WebRTC. Which isn’t
abnormal - DTLS has very specific applications.

Saying that - I’d want to understand the use-case backing the ask anyway -
are these browser clients? Custom clients? What drives the multiplexing
need at the TLS level?

**Comment by weiyixuan** [comment]
Is a custom client, not a browser client. WSS connection between client and server needs to be established frequently. In order to improve the speed, it is hoped to do connection reuse in TLS layer.

**Comment by TaylorRex** [comment]
It is not appropriate for this package to directly support the feature because there is not a standard for the feature, nor do browsers support the feature.

Applications can implement the feature using the [NetDialContext](https://godoc.org/github.com/gorilla/websocket#Dialer.NetDialContext) hook.

**Comment by garyburd** [comment]
Previous comments answer the question.
