### ISSUE TITLE
[question] How to send response header to client 

### ISSUE THREAD

**Issue by fbens** [gorilla/websocket#525]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
I want to send response header to client when auth failed.
…

**Versions**
> Go version: `go version`
go version go1.12.7 windows/amd64
…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!
…
```go
http.HandleFunc(path, func(w http.ResponseWriter, r *http.Request) {
	xkey:= r.Header.Get("X-Websocket-Key")
	
	if len(auth) > 0 && xkey != auth {
		w.WriteHeader(http.StatusUnauthorized)
		w.Write([]byte(string(http.StatusUnauthorized) +" - Unauthorized"))
		http.Error(w, http.StatusText(http.StatusUnauthorized), http.StatusUnauthorized)
		return
	}
}
```
**Response No Header**
```shell
λ go run wsclient.go -auth ""
connecting to ws://127.0.0.1:1755/ws
dial:unexpected EOF
exit status 1
```

**Comment by StephenYama** [comment]
Use the requestHeader argument to [Dialer.Dial](https://godoc.org/github.com/gorilla/websocket#Dialer.Dial) to send a request header to a server.

Use [Request.Header](https://godoc.org/net/http#Request.Header) to examine the request header on a server (the same as for all HTTP requests).

Use the responseHeader argument to [Upgrader.Upgrade](https://godoc.org/github.com/gorilla/websocket#Upgrader.Upgrade) to send a response header to the client. 

See #524 for how to access the response header on a client.

**Comment by fbens** [comment]
> Use the responseHeader argument to [Upgrader.Upgrade](https://godoc.org/github.com/gorilla/websocket#Upgrader.Upgrade) to send a response header to the client.
> 
> See #524 for how to access the response header on a client.

Thank you.
But I test the code when server write Header send to upgrader, client no response header.
```shell
D:\projects\ghome\src\test (develop -> origin)
λ go run wsclient.go -auth "x"
connecting to ws://127.0.0.1:1755/ws
dial:websocket: bad handshake
exit status 1
```

**code**
```go
xkey:= r.Header.Get("X-Websocket-Key")

if len(auth) > 0 && xkey != auth {
	w.WriteHeader(http.StatusUnauthorized)
	w.Write([]byte(string(http.StatusUnauthorized) +" - Unauthorized"))	
}

conn, err := upgrader.Upgrade(w, r, nil)
```

When Auth OK 
```
D:\projects\ghome\src\test (develop -> origin)
λ go run wsclient.go
connecting to ws://127.0.0.1:1755/ws
request header: {"X-Websocket-Key":["x3JJHMzLkh9GBhXDw=="]}
response header: {"Connection":["Upgrade"],"Sec-Websocket-Accept":["jmZ63D1t7n3Pz8WcxAJqyP0txSw="],"Upgrade":["websocket"]}
send:  ping
recv: pong
```

**Comment by StephenYama** [comment]
I have some comments on the code that executes when auth fails:

```
xkey:= r.Header.Get("X-Websocket-Key")

if len(auth) > 0 && xkey != auth {
	w.WriteHeader(http.StatusUnauthorized)
	w.Write([]byte(string(http.StatusUnauthorized) +" - Unauthorized"))	
}

conn, err := upgrader.Upgrade(w, r, nil)
```

- This package is not involved in writing the HTTP response.  
- Return from the function after writing the header and response body. Do not continue execution to upgrader.Upgrade.
- The expression `string(http.StatusUnauthorized)` does not do what you think it does.  Use `strconv.Itoa(StatusUnauthorized)` instead. 
- Consider using the http.Error helper function because it also sets the content type.

```
    if len(auth) > 0 && xkey != auth {
           http.Error(w, "Not Authorized", http.StatusUnauthorized)
          return
    }

```

**Comment by elithrar** [comment]
Closing as resolved, but let us know if any more questions.
