### ISSUE TITLE
[question] How to do TLS (wss://...) ?

### ISSUE THREAD

**Issue by mdavids** [gorilla/websocket#528]
**Describe the problem you're having**
A question if a feature exists and if it does, if and where the documentation is.

Question:

Looking at the API Reference and other information, it is not entirely clear to me how I can enable TLS (wss://) on the WebSocket service.

In the reference I found 'CloseTLSHandshake' and 'TLSClientConfig *tls.Config' but I'm not really sure how to apply them.

(package version: ae1634f6a98965ded3b8789c626cb4e0bd78c3de)

UPDATE: may have found the answer in https://github.com/gorilla/websocket/issues/198

**Comment by elithrar** [comment]
Call net/http’s ListenAndServeTLS (or similar) on a *http.Server where
you’ve mounted your WebSocket endpoint.

e.g.
https://github.com/gorilla/websocket/blob/master/examples/echo/server.go#L53
- changing this line

**Comment by mdavids** [comment]
Works!
