### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by shawnps-sigsci** [gorilla/websocket#530]
**Is your feature request related to a problem? Please describe.**
Hello, there are many changes in master which aren't in a release:

https://github.com/gorilla/websocket/compare/66b9c49e59c6c48f0ffce28c2d8b8a5678502c6d..ae1634f6a98965ded3b8789c626cb4e0bd78c3de

**Describe the solution you'd like**
Tag v1.5.0 or similar

**Comment by elithrar** [comment]
Is there a specific change you’re after?

The only changes are the below, which haven’t warranted a release (likely
v1.4.1) -

66b9c49
<https://github.com/gorilla/websocket/commit/66b9c49e59c6c48f0ffce28c2d8b8a5678502c6d>
Move
context to first parameter in DialContext
a9dd6e8
<https://github.com/gorilla/websocket/commit/a9dd6e883985b8aec197b50407eed3a66dd485b8>
miscellaneous
cleanup
ceae452
<https://github.com/gorilla/websocket/commit/ceae45234aa08314ede799370e6b63491f34b38c>
Add
context in the Dialer
b378cae
<https://github.com/gorilla/websocket/commit/b378caee5b2a673abe3897c40fde529bff7b986e>
Add
write buffer pooling
5fb9417
<https://github.com/gorilla/websocket/commit/5fb94172f40023670f9b65a617cdc3496062080c>
drop
Go versions prior to 1.7 in CI

**Comment by shawnps-sigsci** [comment]
@elithrar these are the two that caught my attention:

https://github.com/gorilla/websocket/commit/a51a35ae3232254685f26a0b6d995ca0e81e2248

https://github.com/gorilla/websocket/commit/3130e8d3f1986de7dc3fd86255f4ce9618677508

The first one looks like it could be a performance enhancement, second one seems to be a bug fix.

Maybe they're no big deal though? Either way I appreciate you taking a look at my ticket!

**Comment by elithrar** [comment]
Ah, missed those - the release bot didn't pick them up, for some reason.

We (at the moment, just me) try to release every 2-3 months or so, outside of major bugfixes, or special requests. websockets is looking for a new maintainer, which is why it hasn't seen active "love" in this area.

**Comment by shawnps-sigsci** [comment]
@elithrar thanks for responding. I see - I'll keep an eye out in the next couple of months for a release. Thanks again!

**Comment by elithrar** [comment]
I've published a new release, in light of a security fix, and recommend you upgrade: https://github.com/gorilla/websocket/releases/tag/v1.4.1

**Comment by shawnps-sigsci** [comment]
Thanks @elithrar!
