### ISSUE TITLE
[bug] close 1005

### ISSUE THREAD

**Issue by antiWalker** [gorilla/websocket#533]
**Describe the bug**
> A clear and concise description of what the bug is.

…
{"level":"error","time":"2019-08-15T15:02:27Z","line":"/Users/worker/websocket.go:159","msg":"readPump ReadMessage err:websocket: close 1005 (no status)","module":"worker"}
159:
<img width="1018" alt="图片" src="https://user-images.githubusercontent.com/27910878/63078793-3dc35f80-bf6f-11e9-8564-fb8a7ee0e935.png">

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?

…

**Expected behavior**
> What output or behaviour were you expecting instead?

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by IngCr3at1on** [comment]
Please fill in the required issue fields, as it stands I have absolutely no idea what you're trying to report.

**Comment by elithrar** [comment]
Timing out, but please let us know if you still need help.
