### ISSUE TITLE
NewClient Example Usage - golang based client

### ISSUE THREAD

**Issue by pctj101** [gorilla/websocket#54]
Hi folks!  

Looking to use  websocket.NewClient() to create a golang based websocket client (rather than a browser based ws client) but couldn't find any examples.

```
func NewClient(netConn net.Conn, u *url.URL, requestHeader http.Header, readBufSize, writeBufSize int) (c *Conn, response *http.Response, err error) {
```

I'm mostly stuck on what to provide for net.Conn.  I couldn't easily find anything in the existing code, tests or even google.

Is there an example someone could help point me at?

Thanks a bunch!

**Comment by cryptix** [comment]
Hey,

here is a small snippet from a golang gui that connects to a websocket server.

```go
u, err := url.Parse("http://local.host:80/ws")
if err != nil {
	return err
}

rawConn, err := net.Dial("tcp", u.Host)
if err != nil {
	return err
}

wsHeaders := http.Header{
	"Origin":                   {"http://local.host:80"},
	// your milage may differ
	"Sec-WebSocket-Extensions": {"permessage-deflate; client_max_window_bits, x-webkit-deflate-frame"},
}

wsConn, resp, err := websocket.NewClient(rawConn, u, wsHeaders, 1024, 1024)
if err != nil {
	return fmt.Errorf("websocket.NewClient Error: %s\nResp:%+v", err, resp)
}
```

The `net.Conn` is a raw tcp socket. Iiagine using netcat to talk to a http server, this is what happens here.

HTH
cryptix

**Comment by pctj101** [comment]
Thanks a bunch @cryptix  

I also found that using websocket.Dialer to make the initial connection works great.

**Comment by chrisvdb** [comment]
What is the advantage of using Dialer over NewClient?

**Comment by garyburd** [comment]
Dialer.Dial calls NewClient. Dialer.Dial handles dialing the network connection, timeouts and TLS. See the [code](https://github.com/gorilla/websocket/blob/ab5b3a61f5b6aa323d66ece457334396c4ccdd03/client.go#L159-L235) for the complete details.

**Comment by chrisvdb** [comment]
Thanks, managed to get it to work!
