### ISSUE TITLE
websocket connection keep-alive

### ISSUE THREAD

**Issue by weiyixuan** [gorilla/websocket#541]
I establish a websocket connection and want to keep it undisconnected. Is there any way to do that? Is there existing interface support?

**Comment by IngCr3at1on** [comment]
@weiyixuan, in general, a websocket does stay connected more or less indefinitely. I've used them to stream data on a backend locally for days without a disconnect.

Unfortunately, in overall practice this gets tricky when going through external services. I can tell you for a fact that anything deployed on Google Cloud by default will kill your websocket connections (forcing a refresh if in a browser) after I think it's 30 seconds of inactivity.

In the case of Google you can adjust that but in other cases, that may or may not be so.

**Comment by weiyixuan** [comment]
thanks

**Comment by cusspvz** [comment]
Unfortunately, this is not true. A keep-alive mechanism allows us to set a reconnect approach based on the quality of service, by overriding the defaults set by the system's TCP settings.

It is mainly used as well by Load Balancers to determine if a connection is numb, and some of the ones provided by the most known PaaS actually drop these connections. (ex: Heroku / ALB)

You can easily test it by exposing one of the examples through Heroku.
