### ISSUE TITLE
[question] Re-Establishing Connection on active thread

### ISSUE THREAD

**Issue by Stoyvo** [gorilla/websocket#544]
I have a web GUI that submits a form as a websocket message, on the Go server I am receiving this message and running a long-process thread, communicating progress back to the web GUI with a websocket message.

My problem is when the user loses network connection or closes the lid of their laptop (for example). When the connection comes back, everything should come back, however the pipe is broken on the Go side, and the web GUI (javascript) identifies the connection as closed. I do not want this writing of data to stop so the go process continues, but it fails to return content back to the web GUI. The web GUI cannot get any updates.

What would be the ideal way to solve a situation like this? 

**Versions**
> Go version: 1.12.5

**Comment by nhooyr** [comment]
> My problem is when the user loses network connection or closes the lid of their laptop (for example). When the connection comes back, everything should come back, however the pipe is broken on the Go side, and the web GUI (javascript) identifies the connection as closed. I do not want this writing of data to stop so the go process continues, but it fails to return content back to the web GUI. The web GUI cannot get any updates.

You need to make the frontend reconnect and persist all state on the server until the process completes. When the frontend disconnects and reconnects, the server then replays all messages to produce the state you want the frontend to have.

@elithrar This can be closed.

**Comment by Stoyvo** [comment]
> You need to make the frontend reconnect and persist all state on the server until the process completes. When the frontend disconnects and reconnects, the server then replays all messages to produce the state you want the frontend to have.

Thanks @nhooyr, how would you persist the state on the server and associate the socket to the right process?

**Comment by elithrar** [comment]
Issue the user a cookie based on their credentials -> when they reconnect,
their client will pass the (if valid) cookie back -> use that to determine
what state you need to pass them.

It’s less likely that you’ll just supply them with the existing socket -
and more that you’ll just catch them up on what they missed.

**Comment by elithrar** [comment]
Closing out - please let us know if you have any more questions around this.
