### ISSUE TITLE
[bug] Panic when response writer has nil http.Hijacker

### ISSUE THREAD

**Issue by muirrn** [gorilla/websocket#547]
**Describe the bug**

websocket/server.go checks that the ResponseWriter implements http.Hijacker, but it doesn't check that the hijacker is non-nil before calling Hijack. This can happen if the response writer doesn't implement Hijack and something like the gorilla compress handler is being used. The compress handler uses a response writer that embeds the http.Hijacker interface, so it always implements http.Hijacker even if the embedded interface value is nil.
…

**Steps to Reproduce**

Run below code snippet.

**Expected behavior**
A 500 response.

**Code Snippets**
```
type myWriter struct {
	http.Hijacker
	http.ResponseWriter
}

func main() {
	http.HandleFunc("/test", func(w http.ResponseWriter, r *http.Request) {
		var upgrader websocket.Upgrader
		upgrader.Upgrade(&myWriter{ResponseWriter: w}, r, nil)
	})

	go func() {
		log.Panic(http.ListenAndServe("127.0.0.1:1337", nil))
	}()

	time.Sleep(1 * time.Second)

	conn, _ := net.Dial("tcp", "127.0.0.1:1337")
	url, _ := url.Parse("ws://127.0.0.1:1337/test")
	websocket.NewClient(conn, url, nil, 0, 0)
}
```

**Comment by nhooyr** [comment]
This isn't a bug, your response writer needs to run a non nil error if there is no hijacker. It's just convention for errors in Go.

@elithrar Please close this.

**Comment by muirrn** [comment]
In my real case, I didn't implement the response writer (it was from a different gorilla package). Why not fix it to not panic?

**Comment by nhooyr** [comment]
> In my real case, I didn't implement the response writer (it was from a different gorilla package). Why not fix it to not panic?

We shouldn't fix it to not panic because it should panic. This is a bug in a different gorilla package. What package is producing this behaviour? We should fix that instead.

**Comment by muirrn** [comment]
> We shouldn't fix it to not panic because it should panic.

I don't really understand this sentiment. My example is valid Go code regardless of whatever convention you are talking about. The language allows it, so it will happen in real life, as we have seen. I think library packages should avoid panicking, even in unexpected/error cases. My experience as a user would have been much better if my server returned a useful error that hijacker was nil/unimplemented instead of crashing.

> What package is producing this behaviour? We should fix that instead.

I agree we should fix that bug also (I'll open it separately).

**Comment by srybacki** [comment]
The hijacker is not nil.  The panic is in myWriter's code.  There's nothing to fix here.

See https://play.golang.org/p/puJOGZTL5rQ.

**Comment by muirrn** [comment]
Ah, my mistake. I thought the hijacker was nil for some reason. Sorry for the back and forth.

**Comment by srybacki** [comment]
The FAQ entry on [Why is my nil error value not equal to nil?](https://golang.org/doc/faq#nil_error) explains the nil issue in some detail.  The entry describes a different scenario, but the discussion about about why the interface is not nil applies here.

**Comment by iamsaquib8** [comment]
@muirdm how did you resolve the 500 error response on WebSockets then?
