### ISSUE TITLE
[bug] SetReadDeadLine did not work

### ISSUE THREAD

**Issue by weiyixuan** [gorilla/websocket#549]
go version: 1.12.8
platform: win10、macos、android

When I used wsc.SetReadDeadLine, I found that the ReadMessage exited before the timeout period reached, resulting in high-frequency execution of the loop and eventually crash.

`

for {

		wsc.SetReadDeadLine(time.Now().Add(500 * time.Millisecond))

		if _, buf, err = wsc.ReadMessage(); err != nil {

			log.Error(err)

			continue

		}

		...

	}

`

**Comment by elithrar** [comment]
What is the full program? What are you reading off the socket?

The deadline won’t be reached if ReadMessage returns faster than the
deadline.

**Comment by weiyixuan** [comment]
```
func main(){
	var err error

	header := http.Header{}
        // header setting

	dialer := &websocket.Dialer{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
		HandshakeTimeout: 6 * time.Second,
	}

	var wsc *websocket.Conn
	if wsc, _, err = dialer.Dial(`wss://x.x.x.x:443/...`, header); err != nil {
		log.Error(err)
		return
	}
	for {
		wsc.SetReadDeadline(time.Now().Add(time.Second))
		_, _, err = wsc.ReadMessage()
		fmt.Println(err)
	}
}
```

result：
……
read tcp 172.20.32.62:3733->x.x.x.x:443: i/o timeout
……
read tcp 172.20.32.62:3733->x.x.x.x:443: i/o timeout
read tcp 172.20.32.62:3733->x.x.x.x:443: i/o timeout
read tcp 172.20.32.62:3733->x.x.x.x:443: i/o timeout
read tcp 172.20.32.62:3733->x.x.x.x:443: i/o timeout
panic: repeated read on failed websocket connection

**Comment by nhooyr** [comment]
You need to return from the loop if err is non nil.

**Comment by weiyixuan** [comment]
You're right. But I'm curious as to why the timeout didn't work. The above log was printed in a flash.

**Comment by nhooyr** [comment]
Well you set a deadline 1s. Also, once a deadline is hit, the connection is done, see https://github.com/gorilla/websocket/issues/474

**Comment by weiyixuan** [comment]
Ok, got it. ୧(๑•̀◡•́๑)૭
