### ISSUE TITLE
The Upgrade function returns 400 errors due to case-mismatch on Connection header check

### ISSUE THREAD

**Issue by politician** [gorilla/websocket#55]
Chrome 39.0.2171.95 sends `Connection: Upgrade` header, but the `websockets.Upgrade` function asserts that the value is lower-case `upgrade` and returns with a 400 error.  

```Bash
2015/01/15 04:49:19 ERROR: websocket: connection header != upgrade
```

https://tools.ietf.org/html/rfc6455 Section 1.2 shows the value of the header as `Upgrade` not `upgrade`, so this looks like a bug in this library.

**Comment by politician** [comment]
Nevermind, this looks like something wonky in the Google AppEngine development server -- it's stripping the Connection header out of the request and just happened to fail on that check.

**Comment by garyburd** [comment]
The package uses [strings.EqualFold](http://godoc.org/strings#EqualFold) to [compare the header value](https://github.com/gorilla/websocket/blob/1f87405cd9755fc388e111c4003caca4a2f52fa6/util.go#L21).  EqualFold is a case insensitive comparison. 

Something else is wrong.
