### ISSUE TITLE
[question] the server.go method Upgrade  support tls wss?

### ISSUE THREAD

**Issue by jiangyd** [gorilla/websocket#551]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

…

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by srybacki** [comment]
A short, but not completely accurate answer, is yes!

The longer answer is that the application is responsible for TLS on the server. If the application brings a TLS connection to the [upgrader](https://godoc.org/github.com/gorilla/websocket#Upgrader.Upgrade), then this package will use it.

See [http.ListenAndServeTLS](https://golang.org/pkg/net/http/#ListenAndServeTLS) and related functions for info on how to use TLS on the server.

**Comment by elithrar** [comment]
Closing out - please let us know if you have any more questions around this!
