### ISSUE TITLE
client connectted but can't send/receive message

### ISSUE THREAD

**Issue by lxzan** [gorilla/websocket#553]
**Describe the problem you're having**
> It's OK when I start my application. After about 10 hour, client connect server successfully
 but can't send/receive message. If send successfully, I can see some logs on server.
…

**Versions**
> Go version: `1.13`

> package version: run `v1.4.1` inside the repo
…

**Comment by elithrar** [comment]
Can you provide a minimal reproduction of this?

Is the application running on a server? A laptop? etc.

(There’s not enough detail to debug this)

**Comment by lxzan** [comment]
Running env is centos 7 cloud server. What are the possible reasons cause this problem, i know it's a little hard to solve it

**Comment by lxzan** [comment]
there are many close_wait fds.

**Comment by lxzan** [comment]
I did't close conn when received CloseMessage.
