### ISSUE TITLE
[question] Close 1001 (going away)

### ISSUE THREAD

**Issue by ad-on-is** [gorilla/websocket#556]
I'm trying to implement a websocket, and my approach is basically something like this: https://gist.github.com/tmichel/7390690

When I open the browser to http://localhost:8081, the first time, everything works fine. However, when I reload the browser, my Go-script crashes with the error-message: `websocket: close 1001 (going away) `

I tried to add a `return` statement, like this:

```
err := conn.ReadJSON(&m)
if err != nil {
   fmt.Println("Error reading json.", err)
   return
}
```
This allowed me to reload the page a view times, but then again, everything crashes with the same error.

Does anyone know how to solve this?

**Comment by srybacki** [comment]
What specifically do you mean by "crashes"? 

See important fixes below:

- Return from function on error.  If the function does not return, then function will spin a tight loop doing nothing. 
-  Close connection on error.  The underlying network connection will leak if the connection is not closed.

```
func echo(conn *websocket.Conn) {
        defer conn.Close()
	for {
		m := msg{}
		err := conn.ReadJSON(&m)
		if err != nil {
			fmt.Println("Error reading json.", err)
                          return
		}
		fmt.Printf("Got message: %#v\n", m)
		if err = conn.WriteJSON(m); err != nil {
			fmt.Println(err)
                          return
		}
	}
}

```

**Comment by ad-on-is** [comment]
@srybacki That's the strange thing, there's no stack trace. The program just "hangs". Sorry, for my missleading wording. All goroutines stop working, and the program does not exit, not even with a stack trace.

I also tried Gorilla's own example, which also does not work.

What I've found out so far, is, that something like this works fine, without hanging the program, after refreshing

```
http.HandleFunc("/echo", func(w http.ResponseWriter, r *http.Request) {
   http.ServeFile(w, r, basePath+"/index.html")
})
```

But Gorilla's implementation with the template does not work.

Maybe the error isn't even related to Gorilla's websocket, but `net/http` instead.

**Comment by srybacki** [comment]
I am still trying to understand what's happening. How did you determine that all goroutines stopped working?   

The Gorilla example works. Are you running the example with `go run server.go` and opening `http://127.0.0.1:8080/` in the browser?

**Comment by ad-on-is** [comment]
Sorry for the inconveniences, but I've just started to learn golang and wanted to implement a websocket- and UDP-service that communicate with each other.

The problem was, simply put, my lack of knowledge, how things in golang work 😅

For some reason I thought that the problem was the "close 1001" error message, but that error rightfully fires when a client disconnects from the socket.

Since I wanted the two services to talk to each other, I used a global string variable for that 🤦‍♂️... while I used the webservice  to populate the variable, my udp-service was reading that variable in a for-loop 🤦‍♂️ and was modifying some pointer-references based on the value of that variable. This led to the result, I described above.

But, now I've discovered that this approach is completely stupid, and that I need to use channels for things like that. Now everything works as it should.

**Comment by ferhatelmas** [comment]
@srybacki seems good to close.

**Comment by felexkemboi** [comment]
I am facing the same problem here,anyone out there who can help? @ferhatelmas @elithrar @ad-on-is

**Comment by elithrar** [comment]
> I am facing the same problem here,anyone out there who can help? 

Open a new bug that describes your issue and shows what you have tried, including your code.

*please* do not DM people on Twitter: this is a volunteer-led project, not a paid service with support.
