### ISSUE TITLE
When the service sends a message to the client, how does the server ensure that the client must receive it?

### ISSUE THREAD

**Issue by hihozhou** [gorilla/websocket#558]
**When the service sends a message to the client, how does the server ensure that the client must receive it?**
> I now want to make sure that the server sends a message to the client. The client must accept it successfully, but calling the `WriteMessage` method cannot ensure that the message is sent successfully.

**Comment by srybacki** [comment]
Use an application-level protocol to determine if a peer received a message.  For example, have the peer reply with a message saying "I go it!".

**Comment by hihozhou** [comment]
@srybacki thank

```go
if err := conn.WriteMessage(websocket.TextMessage, data); err != nil {
		return err
	}
	ackCh := make(chan []byte, 1000)

	go func(err *error) {
		_, ackData, ackErr := conn.ReadMessage()
		if ackErr != nil {
			err = &ackErr
			if websocket.IsUnexpectedCloseError(ackErr, websocket.CloseGoingAway) {
				fmt.Printf("IsUnexpectedCloseError error: %v", err)
			}
		}
		ackCh <- ackData
	}(&err)

	var ackMsg []byte

	select {
	case ackMsg = <-ackCh:
		fmt.Println("ackMsg" + string(ackMsg))
	case <-time.After(5 * time.Second):
		fmt.Println("TimeOut")
	}

```
