### ISSUE TITLE
[bug] Is there a concurrency problem with the map, do you need sync. map

### ISSUE THREAD

**Issue by iwalkerr** [gorilla/websocket#561]
![Xnip2019-12-17_14-32-54](https://user-images.githubusercontent.com/43042929/70970858-78cece80-20da-11ea-9939-cffce770e0a9.jpg)

**Comment by chappjc** [comment]
Did you observe a panic?

Those map accesses are sequential.

![image](https://user-images.githubusercontent.com/9373513/71002046-21ae0700-20a4-11ea-8f78-33f1ae6b01fc.png)

**Comment by srybacki** [comment]
There is no concurrent access to the map because the `Hub.run` method is executed by a single goroutine.

**Comment by iwalkerr** [comment]
Ok, thanks. I was wrong





| |
walkerr
|
|
邮箱：walkerr@163.com
|
On 12/18/2019 00:02, srybacki wrote:

There is no concurrent access to the map because the Hub.run method is executed by a single goroutine.

**Comment by iwalkerr** [comment]
There is no concurrency for a single user, but is there concurrency security for multiple users?




| |
walkerr
|
|
邮箱：walkerr@163.com
|
On 12/18/2019 00:08, walkerr wrote:
Ok, thanks. I was wrong





| |
walkerr
|
|
邮箱：walkerr@163.com
|
On 12/18/2019 00:02, srybacki wrote:

There is no concurrent access to the map because the Hub.run method is executed by a single goroutine.

**Comment by srybacki** [comment]
The example program starts exactly one goroutine to execute `Hub.run`.  No other goroutines access the map.

**Comment by iwalkerr** [comment]
> The example program starts exactly one goroutine to execute `Hub.run`. No other goroutines access the map.

thanks

**Comment by elithrar** [comment]
Closing out - please let us know if you have any more questions around this.
