### ISSUE TITLE
[bug] can't send long text message

### ISSUE THREAD

**Issue by Jack-Ji** [gorilla/websocket#562]
**Describe the bug**

I'm having trouble sending messages longer than 2k bytes from chrome to websocket server.
The NextReader didn't return any error at all.

**Versions**
> Go version: go version go1.11.5 linux/amd64
> package version: v1.4.1

**Steps to Reproduce**
> How can the bug be triggered?
Nothing special, simply deploy the server to a vps and use chrome console to connnect and send message.

**Expected behavior**
> What output or behaviour were you expecting instead?
Messages should be sent successfully

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).
```
package main

import (
        "github.com/gorilla/websocket"
        "io"
        "net/http"
)

var upGrader = websocket.Upgrader{
        ReadBufferSize:  10 * 1024,
        WriteBufferSize: 10 * 1024,
        CheckOrigin: func(r *http.Request) bool {
                return true
        },
}

func wsHandler(w http.ResponseWriter, r *http.Request) {
        ws, err := upGrader.Upgrade(w, r, nil)
        if err != nil {
                return
        }
        println("accepted wesocket connection")
        defer ws.Close()

        for {
                mt, r, err := ws.NextReader()
                if err != nil {
                        println("read failed ", err)
                        break
                }
                w, err := ws.NextWriter(mt)
                if err != nil {
                        println("write failed ", err)
                        break
                }
                if _, err := io.Copy(w, r); err != nil {
                        println("copy failed ", err)
                        break
                }
        }
}

func main() {
        bindAddress := "0.0.0.0:9090"
        http.HandleFunc("/ws", wsHandler)
        http.ListenAndServe(bindAddress, nil)
}

```

**Comment by Jack-Ji** [comment]
FYI, the WebSocket instance of web browser sill simply close without reporting any error.
![image](https://user-images.githubusercontent.com/1416077/71244708-167e0400-234e-11ea-8ee1-38efbb92d0f7.png)

**Comment by srybacki** [comment]
I edited the echo example to use the code in this issue.  I can send message longer than 2k through the example's web UI.

Show the code used on the client.

**Comment by Jack-Ji** [comment]
@srybacki Did deploy the server on your own machine or local network? As it turns out, I myself can too send message longer than 2k this way, the problem shows up when sending over public network.

Will post client code in a moment.

**Comment by Jack-Ji** [comment]
code used in chrome console:
```
socket = new WebSocket(myurl);
socket.onopen = function() {
  console.log(‘open websocket successfully!’);
}
socket.onmessage = function(msg) {
  console.log(msg.data);
}
socket.onclose = function() {
  console.log(‘websocket closed’)
}
socket.onerror = function(e) {
  console.log(e)
}

```

 Very simple code, after I got open event, I use socket.send to send some made up text to server

**Comment by Jack-Ji** [comment]
Just FYI, my coworker implemented another simple echo server using java, which works ok with text as long as megabytes.

**Comment by srybacki** [comment]
This package is known to work with large messages on the public internet.

> the problem shows up when sending over public network.

That sounds like a network infrastructure problem on your end.  Perhaps you are connecting through a firewall or proxy that does not fully support the websocket protocol.

**Comment by Jack-Ji** [comment]
Maybe I wasn't very clear in my last comment, my coworker implemented another simple echo server using java and ***deployed in exactly same vps***, which works ok without the issue.

**Comment by srybacki** [comment]
When I tested the code from the issue in the echo example, I pushed the send button over and over.  In so doing, I missed that a message is not received by the client until after the client sends the next message.  

The issue is that the server application does not close the message writer. The [documentation says](https://godoc.org/github.com/gorilla/websocket#Conn.NextWriter):

> NextWriter returns a writer for the next message to send. The writer's Close method flushes the complete message to the network.
>
> There can be at most one open writer on a connection. NextWriter closes the previous writer if the application has not already done so.

Because the application does not close the writer, the message is not flushed until after a message is received and NextWriter is called again.

Fix by closing the writer:

        for {
                mt, r, err := ws.NextReader()
                if err != nil {
                        println("read failed ", err)
                        break
                }
                w, err := ws.NextWriter(mt)
                if err != nil {
                        println("write failed ", err)
                        break
                }
                if _, err := io.Copy(w, r); err != nil {
                        println("copy failed ", err)
                        break
                }
                if err := w.Close(); err !+ nil {   // <---- add this code
                        println("close failed ", err)
                        break
                }
        }

**Comment by Jack-Ji** [comment]
@srybacki Thanks for pointing that out. That was my mistake not providing suitable example. But the problem I’m referring to is more about receiving client’s message rather than echoing back. In fact, in our project, we directly used connection’s WriteMessage methods, which closes writer automatically.

**Comment by srybacki** [comment]
Are you saying that the code in the issue is an example and not actual code that produces the problem?

**Comment by Jack-Ji** [comment]
No, I tried the example and it produces same bug I’m facing in my project: never received any long message on server’s side and cause client’s socket closed

**Comment by Jack-Ji** [comment]
In case anyone is till checking this issue, I tried another simple implementation using python, which can receive message of 10k's length just fine.

```python
import asyncio
import websockets

async def hello(websocket, path):
    while True:
        name = await websocket.recv()
        print(f"< {name}")

        greeting = f"Hello {name}!"

        await websocket.send(greeting)
        print(f"> {greeting}")

start_server = websockets.serve(hello, "0.0.0.0", 9090)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

**Comment by Jack-Ji** [comment]
I just tried example again in our server, turns out it works ok now. I guess it is cloud infrastructure's problem after all.
