### ISSUE TITLE
Does gorilla web socket support live audio/video streaming functionality ? Please mention if any protocols available. 

### ISSUE THREAD

**Issue by sainath-everest** [gorilla/websocket#571]

**Comment by srybacki** [comment]
There's nothing in this package that should limit the package's use for live audio/video streaming.   

This package implements the WebSocket protocol only.  Look elsewhere for packages that implement streaming on top of the WebSocket protocol.

**Comment by elithrar** [comment]
Closing this out - please feel free to re-open if any questions.
