### ISSUE TITLE
[question] How to use WriteBufferPool?

### ISSUE THREAD

**Issue by kpeu3i** [gorilla/websocket#574]
I can't find any usage example of `WriteBufferPool`. Can you please provide a working example here or add it to documentation? 

Is it just enough `WriteBufferPool: &sync.Pool{}`?

**Comment by srybacki** [comment]
Yes.  

The [documentation](https://godoc.org/github.com/gorilla/websocket#BufferPool) says:

> BufferPool represents a pool of buffers. The *sync.Pool type satisfies this interface.

**Comment by kpeu3i** [comment]
Got it, thx!
