### ISSUE TITLE
[bug] Connections handled by terminated web session don't release file descriptors

### ISSUE THREAD

**Issue by paullj1** [gorilla/websocket#576]
**Describe the bug**
When a web socket is closed by the client (i.e., browser closes), even when the connection is handled using ping/pong messages, and the conn object is closed, the underlying file descriptor is never released.  On dockerized apps that handle being restarted when errors occur, this isn't a problem, but for long-running applications, the maximum number of open files (/proc/sys/fs/file-max) is eventually reached.

lsof output is the easiest way to see it:
```
...
webconsol 19339 root   71u     sock    0,9      0t0 13345249 protocol: UNIX
webconsol 19339 root   72u     sock    0,9      0t0 13433538 protocol: TCP
webconsol 19339 root   73u     sock    0,9      0t0 13344209 protocol: TCP
webconsol 19339 root   74u     sock    0,9      0t0 13366143 protocol: TCPv6
webconsol 19339 root   75u     sock    0,9      0t0 13366145 protocol: UNIX
webconsol 19339 root   76u     sock    0,9      0t0 13433542 protocol: TCP
webconsol 19339 root   77u     sock    0,9      0t0 13367298 protocol: TCP
webconsol 19339 root   78u     sock    0,9      0t0 13434195 protocol: TCPv6
webconsol 19339 root   79u     sock    0,9      0t0 13434197 protocol: UNIX
webconsol 19339 root   80u     sock    0,9      0t0 13434202 protocol: TCP
webconsol 19339 root   81u     sock    0,9      0t0 13434208 protocol: TCP
webconsol 19339 root   82u     sock    0,9      0t0 13455116 protocol: TCPv6
webconsol 19339 root   83u     sock    0,9      0t0 13455816 protocol: UNIX
webconsol 19339 root   84u     sock    0,9      0t0 13501677 protocol: TCPv6
webconsol 19339 root   85u     sock    0,9      0t0 13455125 protocol: TCP
...
```

Another application:
```
...
main 9856   pi   11u     sock     0,8      0t0 2936029 protocol: TCPv6
main 9856   pi   12u     sock     0,8      0t0 2935025 protocol: TCPv6
main 9856   pi   17u     sock     0,8      0t0 2936033 protocol: TCPv6
main 9856   pi   21u     sock     0,8      0t0 2936035 protocol: TCPv6
main 9856   pi   22u     sock     0,8      0t0 2936037 protocol: TCPv6
main 9856   pi   23u     sock     0,8      0t0 2936038 protocol: TCPv6
...
```

I have confirmed that there is a new one for each terminated web socket.  When the connection closes, one of these is left in its place.

This may be an issue in Go, but this appears to be the only place I see it.

**Versions**
> Go version: `1.13.7`
> package version: c3e18be99d19e6b3e8f1559eea2c161a665c4b6b

**Steps to Reproduce**
1. Open a web socket
2. Close the client browser tab
3. Observe lsof output

**Expected behavior**
Expect all open file descriptors to be removed/cleaned up when connection is closed.

**Code Snippets**
```go
var upgrader = websocket.Upgrader {
  ReadBufferSize: 1024,
  WriteBufferSize: 1024,
}

func (app *App) TempUpdatesHandler(w http.ResponseWriter, r *http.Request) {
  conn,err := upgrader.Upgrade(w, r, nil)
  if err != nil {
    w.WriteHeader(http.StatusInternalServerError)
    w.Write([]byte("500 - Internal Server Error"))
    log.Print(err)
    return
  }
  handleUpdates(&app.em.Temperature, conn)
}

func handleUpdates(arr *[]DataPoint, conn *websocket.Conn) {

  // Poll for updates
  currLen := len(*arr)
  ticker := time.NewTicker(10 * time.Second)
  done := make(chan bool)

  defer func() {
    ticker.Stop()
    done <- true
    conn.Close()
  }()

  for {
    select {
    case <-done:
      return
    case <-ticker.C:
      conn.SetWriteDeadline(time.Now().Add(8 * time.Second))

      newLen := len(*arr)
      if currLen < newLen {
        if err := conn.WriteJSON((*arr)[currLen:]); err != nil {
          return
        }
        currLen = newLen

      } else {
        if err := conn.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
          return
        }
      }
    }
  }
}
```

**Comment by srybacki** [comment]
On return from `handleUpdates` after a write error, the deferred function blocks forever on send to the `done` channel.  The application does not close the connection as a result.

A second issue is that the application does not read the connection.  See [the documentation for more info on this](https://godoc.org/github.com/gorilla/websocket#hdr-Control_Messages).

**Comment by paullj1** [comment]
Well, I feel dumb.  Thanks.  That definitely solved the problem for this example, I'll have to dig through the code in my other project to see where I'm blocking there.

@srybacki, I really didn't intend for this to be "help me debug my code," sorry.  I thought that I had the same behavior in two applications (using totally different logic).
