### ISSUE TITLE
Why payload size use big endian. Other element(such as fin/srv/opcde) use normal small endian in frame head.

### ISSUE THREAD

**Issue by hankai17** [gorilla/websocket#578]
**Describe the problem you're having**
> Why payload size use big endian. Other element(such as fin/srv/opcde) use normal small endian in frame head.
Is there has reference?
…

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
```
switch {
	case length >= 65536:
		c.writeBuf[framePos] = b0
		c.writeBuf[framePos+1] = b1 | 127
		binary.BigEndian.PutUint64(c.writeBuf[framePos+2:], uint64(length))
	case length > 125:
		framePos += 6
		c.writeBuf[framePos] = b0
		c.writeBuf[framePos+1] = b1 | 126
		binary.BigEndian.PutUint16(c.writeBuf[framePos+2:], uint16(length))
	default:
		framePos += 8
		c.writeBuf[framePos] = b0
		c.writeBuf[framePos+1] = b1 | byte(length)
	}
```

…

**Comment by srybacki** [comment]
Length is in network byte order. Byte order is not relevant to `FIN` and `OPCODE` because these values are encoded in a single byte.  I don't know what `srv` is. 

See the [RFC for a complete description of the header layout](https://tools.ietf.org/html/rfc6455#section-5.2).

**Comment by hankai17** [comment]
Thanks
