### ISSUE TITLE
how to detect closed connection when using ReadJSON

### ISSUE THREAD

**Issue by akonsu** [gorilla/websocket#58]
`ReadJSON` returns a EOF error if either JSON is incorrect or the peer closed connection unexpectedly.

if I get an error from this function, how do I know that it is JSON that is incorrect and not that the connection is closed?

**Comment by garyburd** [comment]
If the JSON is invalid, then ReadJSON returns one of the error types defined in the JSON package.

If the JSON is incomplete, then ReadJSON returns io.ErrUnexpectedEOF.

If the peer closes the connection unexpectedly, then ReadJSON returns a [close error](https://github.com/gorilla/websocket/blob/2dbddebb8266b93c5e6b119efb54e89043186f3f/conn.go#L92).

If a message is empty or all whitespace, then ReadJSON returned io.EOF.  CL 2dbddebb8266b93c5e6b119efb54e89043186f3f changes the code to return io.ErrUnexpectedEOF in this case.
