### ISSUE TITLE
[question] a read on a closed websocket return an error instead of io.EOF

### ISSUE THREAD

**Issue by chmike** [gorilla/websocket#580]
**Describe the problem you're having**

On the web server, I have a go routine that reads messages from a websocket, and another go routine that writes messages to that websocket. 

It is the message writer go routine that performs the graceful shutdown of the websocket when requested by the server. 
When the websocket is closed, the function `ReadMessage()` called by the reader go routine returns the error: "websocket: close 1000 (normal)".  

How can I distinguish this "error" from a real error without using string comparison ? Isn’t there a better way ? Why not returning io.EOF ? 

**Versions**
> Go version:  go1.14 linux/amd64

> package version: v1.4.1 c3e18be99d19e6b3e8f1559eea2c161a665c4b6b

**Comment by pkuca** [comment]
The examples show the use of `IsUnexpectedCloseError` which does what you want.

https://pkg.go.dev/github.com/gorilla/websocket?tab=doc#example-IsUnexpectedCloseError

**Comment by chmike** [comment]
It doesn’t work. Documentation on what it does is not clear. What does `CloseGoingAway` mean ?  
`websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway)` returns true when the error is `websocket: close 1000 (normal)`.

**Comment by chmike** [comment]
It did work with ` websocket.IsUnexpectedCloseError(err, websocket.CloseNormalClosure)`. Missed that the arguments are the websocket error we want to ignore, and that `websocket.CloseNormalClosure` is the error I want to ignore. 

Thanks.
