### ISSUE TITLE
read/write buffer memory control

### ISSUE THREAD

**Issue by caleb-letsgo** [gorilla/websocket#585]
Why does websocket.dialer not provide a member that can pass in a read/write buffer? Because websocket will have a lot of space to make read and write buffers for new connections. When memory is tight, it is hard to control.

**Comment by srybacki** [comment]
An application can control the size of the buffers using [Dialer.ReadBufferSize](https://godoc.org/github.com/gorilla/websocket#Dialer.ReadBufferSize) and [Dialer.WriteBufferSize])(https://godoc.org/github.com/gorilla/websocket#Dialer.WriteBufferSize).  An application can pool write buffers using [Dialer.WriteBufferPool](https://godoc.org/github.com/gorilla/websocket#Dialer.WriteBufferPool).

The package is indeed missing a way to reuse read buffers.  Is that really important in a client scenario?

**Comment by caleb-letsgo** [comment]
Thank you very much.
When memory is tight, this is a big chunk of memory.
