### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by lightbrotherV** [gorilla/websocket#586]
**Is your feature request related to a problem? Please describe.**
print log use std

**Describe the solution you'd like**
can use log interface

**Comment by srybacki** [comment]
This package does not print or write log output.  What do you want the package to do with a log interface?  

The standard library has concrete classes for logging, but does not define an interface.  What is the interface you are referring to?

**Comment by lightbrotherV** [comment]
I read the code ,   there are some "log.Println" to println err, I want print to my logfile

**Comment by elithrar** [comment]
If you want to log specific things, consider logging before/after your calls into this package?

Importantly: what specific code is giving you problems? Logging may not be the answer.

**Comment by srybacki** [comment]
> there are some "log.Println"

The are three "log.Println" in the package comment. The examples use log.Println.  The package itself does not call log.Println.

**Comment by lightbrotherV** [comment]
sorry, it's my problem ,someone add the 'fmt.println' on our project....
