### ISSUE TITLE
How to open websocket when the first address is HTTPS 

### ISSUE THREAD

**Issue by g3rzi** [gorilla/websocket#587]
**Describe the problem you're having**

I have a server that after sending a POST message, response with status code 101: Switching Protocol and when I tried to use gorilla library to dial it, it failed with error:  

> 2020/04/04 20:44:31 dial:websocket: bad handshake  

…

**Versions**
go version go1.13 windows/amd64

**"Show me the code!"**

When I run the following function:
```
func PostRequest(client *http.Client, bodyData []byte) (*http.Response, error){
        url := "https://<node_ip>:10250/exec/default/nginxPod/nginx?command=ls&command=/&input=1&output=1&tty=0"
	req, _ := http.NewRequest("POST", url, bytes.NewBuffer(bodyData))
	req.Header.Set("X-Stream-Protocol-Version", "v2.channel.k8s.io")
	req.Header.Set("X-Stream-Protocol-Version", "channel.k8s.io")
	req.Header.Set("Upgrade", "SPDY/3.1")
	req.Header.Set("Connection","upgrade")
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := (*client).Do(req)

	return resp, err
}
```

The status of `resp` is `101 Switching Protocols`.  
I understood that I need to use websocket, so I download gorilla library and tried the code from your [example](https://github.com/gorilla/websocket/blob/master/examples/echo/client.go) but it failed on the beginning:  
```
u := url.URL{Scheme: "ws", Host: "<node_ip>:10250", Path: "/exec/default/nginxPod/nginx?command=ls&command=/&input=1&output=1&tty=1"}

		interrupt := make(chan os.Signal, 1)
		signal.Notify(interrupt, os.Interrupt)

		c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
		if err != nil {
			log.Fatal("dial:", err)
		}
		defer c.Close()
              ...

```

And printed the error:  

> 2020/04/04 20:51:25 dial:websocket: bad handshake  

Any idea what can be the reason?  
When I run regular POST request it ask to switch protocol, when I tried to use the `Dial` function it writes bad handshake.

**Comment by srybacki** [comment]
The [documentation says](https://godoc.org/github.com/gorilla/websocket#Dialer.DialContext):

> If the WebSocket handshake fails, ErrBadHandshake is returned along with a non-nil *http.Response so that callers can handle redirects, authentication, etcetera. The response body may not contain the entire response and does not need to be closed by the application.

To debug the problem, print the response [status](https://godoc.org/net/http#Response.Status), [header](https://godoc.org/net/http#Response.Header) and the contents of the [body](https://godoc.org/net/http#Response.Body).   This information often points directly to the problem.

**Comment by g3rzi** [comment]
Status: 101 Switching Protocols
Header: 
```
map[Connection:[Upgrade] Date:[Sat, 04 Apr 2020 18:26:57 GMT] Upgrade:[SPDY/3.1] X-Stream-Protocol-Version:[channel.k8s.io]] 
```

Body:  
When I run `bodyBytes, err := ioutil.ReadAll(r.Body)` to read the body, it stucked, like waiting for something so I can't see it. I suppose I need to use websocket to read this body, but I don't know how.

**Comment by srybacki** [comment]
The response does not have the required WebSocket handshake headers.  The endpoint does not support the websocket protocol.

The code `bodyBytes, err := ioutil.ReadAll(r.Body)` will never block or get stuck because response body is a bytes.NewReader (see code [here](https://github.com/gorilla/websocket/blob/b65e62901fc1c0d968042419e74789f6af455eb9/client.go#L359)).

**Comment by g3rzi** [comment]
But it block, when I debug it, afet the above line nothing happen. Like it waits for something.

**Comment by g3rzi** [comment]
The code you mentioned is refer to the case the status is **not** 101, but in my case the status is 101.

**Comment by srybacki** [comment]
The important point is that the application is not connecting to a websocket endpoint.  That's not something we can help with here.

The condition in the code I referred to is:

	resp.StatusCode != 101 ||
		!strings.EqualFold(resp.Header.Get("Upgrade"), "websocket") ||
		!strings.EqualFold(resp.Header.Get("Connection"), "upgrade") ||
		resp.Header.Get("Sec-Websocket-Accept") != computeAcceptKey(challengeKey)

The condition evaluates to true because the upgrade header is not 'websocket'.  bytes.NewReader never blocks.

**Comment by g3rzi** [comment]
I thought that this library allows me to connect to websocket server (101 Switching Protocols)...

**Comment by g3rzi** [comment]
I will search the answer for somewhere else. I think you meant that because I am using "Upgrade: SPDY/3.1", this is not related to websocket and therefore this library can't help me.

**Comment by elithrar** [comment]
Not quite - `101 Switching Protocols` is also used for SPDY, h2, etc. As @srybacki says, unless the `Upgrade: websocket` header is there, it may not be a WebSocket.

Stepping back for a second: _what_ are you trying to do in the first place? It looks like you're trying to connect to the Kubelet API on a k8s Node, which is _not_  a WebSocket endpoint.

**Comment by elithrar** [comment]
This looks to reference the core of it (the deprecated SPDY API) + the Kubelet API: https://www.openshift.com/blog/executing-commands-in-pods-using-k8s-api

**Comment by g3rzi** [comment]
I am trying to use the "/exec" API to run commands on container through the kubelet's endpoint.  
I tried to do it with `curl` which also stuck:  
```
curl -svk -X GET "https://<server_ip>:10250/exec/default/mypod/mycontainercommand=ls&command=/&input=1&output=1&tty=0" \
-H "X-Stream-Protocol-Version: v2.channel.k8s.io" \
-H "X-Stream-Protocol-Version: channel.k8s.io" \
-H "Upgrade: SPDY/3.1" -H "Accept: application/json, */*" \
-H "Connection: upgrade" \
```

So I thought maybe I need to create a websocket to the kubelet endpoint and read it with a loop.

**Comment by elithrar** [comment]
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/exec/exec.go
... is how kubectl does it.

**Comment by g3rzi** [comment]
Great, thanks, I will check it.
