### ISSUE TITLE
[question] Why to use Sec-Websocket-Protocol instead of Sec-WebSocket-Protocol

### ISSUE THREAD

**Issue by yuanlai** [gorilla/websocket#591]
The test function TestSubprotocols in server_test.go, which can be passed using the header `Sec-Websocket-Protocol` and can not be passed for header `Sec-WebSocket-Protocol`.

**Comment by srybacki** [comment]
http.Header expects keys to be in [canonical format](https://godoc.org/net/http#CanonicalHeaderKey).   The string `Websocket-Protocol` is the canonical format for `Sec-WebSocket-Protocol`.

**Comment by yuanlai** [comment]
But I see RFC document using [`Sec-WebSocket-Protocol`], is it necessary for go http header?(https://tools.ietf.org/html/rfc6455#section-11.3.4)
