### ISSUE TITLE
[bug] is it working as designed that checkOrigin doesn't accept if just port differs?

### ISSUE THREAD

**Issue by jdeltoft** [gorilla/websocket#592]
My connection is failing I believe because the checkOrigin default doesn't ignore ports?  Maybe this is WAD (working as designed) but it took me a while to debug so I figured I would see if maybe there should be an option to ignore just port differences.

https://github.com/gorilla/websocket/issues/367 lead me to the hack solution which is to ignore checkOrigin all together as a test, and it works great.  

To figure out the issue I used:

    "net/http/httputil"

and this code:

```
    requestDump, err := httputil.DumpRequest(r, true)
    if err != nil {
      fmt.Println(err)
    }
    fmt.Println(string(requestDump))

```

I then could see the header and it looked like this:

```
GET /ws HTTP/1.1
Host: mydomain.from-wi.com:1234
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: Upgrade
Origin: http://mydomain.from-wi.com
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: fZv9r7Gvfdafafafa79YQ==
Sec-Websocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
```

Error that comes back from upgrader was:

`websocket: request origin not allowed by Upgrader.CheckOrigin
`

As you can see, it's just that the websocket is running on port 1234 and Origin and Host differ by just that.  

Again, if this is normal, then please just close.  I'll try to write my own check origin function to skip port.  Btw, I'm opening the web socket with Flutter for Web in this case.  

https://pub.dev/packages/web_socket_channel#-readme-tab-

https://flutter.dev/docs/cookbook/networking/web-sockets

`go version go1.14.2 linux/amd64
`

**Comment by jdeltoft** [comment]
Oh, sorry, just found this

https://github.com/gorilla/websocket/issues/398

I'll close this as "won't fix"

**Comment by jdeltoft** [comment]
Just as FYI, I used this from other sources to solve this:

```
func checkSameOrigin(r *http.Request) bool {
    origin := r.Header["Origin"]
    if len(origin) == 0 {
        return true
    }
    u, err := url.Parse(origin[0])
    if err != nil {
        return false
    }
    if equalASCIIFold(u.Host, r.Host) {
        return true
    }
    host := r.Host
    host = strings.TrimSuffix(host, ":9590")
    return equalASCIIFold(u.Host, host)
}

func equalASCIIFold(s, t string) bool {
    for s != "" && t != "" {
        sr, size := utf8.DecodeRuneInString(s)
        s = s[size:]
        tr, size := utf8.DecodeRuneInString(t)
        t = t[size:]
        if sr == tr {
            continue
        }
        if 'A' <= sr && sr <= 'Z' {
            sr = sr + 'a' - 'A'
        }
        if 'A' <= tr && tr <= 'Z' {
            tr = tr + 'a' - 'A'
        }
        if sr != tr {
            return false
        }
    }
    return s == t
}
```

And use it like this:

`    upgrader.CheckOrigin = checkSameOrigin
`

**Comment by elithrar** [comment]
To add to this: an Origin is a (scheme, host, port) tuple. A different port
is a different Origin in the web security model, and so this library is
behaving appropriately.

https://developer.mozilla.org/en-US/docs/Glossary/Origin#Examples_of_different_origin
