### ISSUE TITLE
The code will be suspended for a few days

### ISSUE THREAD

**Issue by mbc521** [gorilla/websocket#594]
func (c *Client) writePump() {
	ticker := time.NewTicker(pingPeriod)   // 30s
	maxTicker := time.NewTicker(maxPeriod) // 1H

	defer func() {
		if p := recover(); p != nil {
			fmt.Printf("ws write pump panic recover! p: %v\n", p)
		}
	}()

	defer func() {
		ticker.Stop()
		maxTicker.Stop()
		c.hub.unregister <- c
		if err := c.conn.Close(); err != nil {
			logs.Error("ws close ws connection err ::: %+v", err)
		}

		logs.Warn("ws client ::: %+v writePump CLOSED", c.DebugID)
	}()

	for {
		select {
		case message, ok := <-c.send: // from broadcast
			c.conn.SetWriteDeadline(time.Now().Add(writeWait)) // writeWait 60s
			if !ok {
				// The hub closed the channel.
				c.conn.WriteMessage(websocket.CloseMessage, []byte{})
				logs.Warn("ws hub closed channel ID:::%+v", c.DebugID)
				return
			}
			if err := c.conn.WriteMessage(websocket.TextMessage, message); err != nil {
				logs.Error("ws client write message error ::: %+v, ID::: %+v w", err, c.DebugID)
				return
			}

			// maxTicker = time.NewTicker(maxPeriod)
		case <-ticker.C:
			c.conn.SetWriteDeadline(time.Now().Add(writeWait)) // 10s
			if err := c.conn.WriteMessage(websocket.PingMessage, nil); err != nil {
				logs.Error("ws ping pong write msg err :::%+v ID::: %+v", err, c.DebugID)
				return
			}

		case <-maxTicker.C:
			logs.Info("ws max period timeout ID::: %+v", c.DebugID)
			return
		}
	}
}

**Comment by mbc521** [comment]
github.com/gorilla/websocket v1.4.1.  
go 1.12

**Comment by elithrar** [comment]
What is the problem you are having?

**Comment by mbc521** [comment]
The connection  is broken after the code runs on the machine for a few days , c.conn.WriteMessage  disconnection the machine

**Comment by AlbiDalbi** [comment]
@mbc521  What is the error returned from WriteMessage?  Perhaps there was a network error or the peer closed the connection.
