### ISSUE TITLE
[question] When does the websocket server send a ping message?

### ISSUE THREAD

**Issue by zzj2016** [gorilla/websocket#595]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
When does the websocket server send a ping message to client? I can not find it in code. Or it only depends on that client send a ping message?
…

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by aler9** [comment]
Hi, the server by default does not send any ping request, you have to:
* schedule the sending and send the ping requests in the same goroutine in which you send every other message
* call SetPongHandler(), which set a callback that is called every time you receive a pong, and increase the read timeout every time this happens

Working example:
https://github.com/gorilla/websocket/blob/master/examples/chat/client.go

(of course it would be nice if the library could perform this automatically)

**Comment by garyburd** [comment]
@aler9 Thank you for answering the question.
