### ISSUE TITLE
Excellent resource for the README

### ISSUE THREAD

**Issue by AaronStGeorge** [gorilla/websocket#60]
I found this blog post quite helpful, perhaps it deserves a place on the README?

http://www.jonathan-petitcolas.com/2015/01/27/playing-with-websockets-in-go.html

**Comment by garyburd** [comment]
The code in the post that is directly related to websockets is nearly identical to [Gorilla's chat example](https://github.com/gorilla/websocket/tree/master/examples/chat). Is there something we can do to improve the Gorilla example?

**Comment by AaronStGeorge** [comment]
I primarily used your [blog post](http://gary.burd.info/go-websocket-chat) as a reference, which is excellent, but doesn't contain any treatment of ping and pong messages. I assumed that the [Gorilla chat example](https://github.com/gorilla/websocket/tree/master/examples/chat) had identical code. You might want to update that post or put a link at the top or something. Thanks for all the time and every you and the other creators have put into writing this software it really helped.

**Comment by garyburd** [comment]
Thank you for the feedback. I'll link my blog post to the Gorilla example.
