### ISSUE TITLE
Can we pass query parameters in websocket url

### ISSUE THREAD

**Issue by muralid9** [gorilla/websocket#608]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
When I try to pass query parameters with ? In the wss url it gives me a bad hand shake. If I don't have any ? In the url it works fine.could some one help me.
**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by elithrar** [comment]
Please show an example application.

- Query parameters should not cause a handshake failure 
- What are you using them for?
- How are you handling them?

If you send query parameters to the chat example it will handle them fine.

**Comment by TaylorRex** [comment]
Yes, query parameters can be included in the websocket URL.

**Comment by alice0ch** [comment]
client:

**Comment by garyburd** [comment]
@alice0ch Thank you for answering the question.
