### ISSUE TITLE
send BinaryMessage error

### ISSUE THREAD

**Issue by longhopefor** [gorilla/websocket#609]
when i use this websocket client to send binaryMessage，the server response invalid frame type, code is like this:

err = c.WriteMessage(websocket.BinaryMessage, buf[:n])

when i use "golang.org/x/net/websocket" to test，it works ok。so how to send BinaryMessage use this Library?

**Comment by TaylorRex** [comment]
The code in the issue correctly specifies a binary message.

What is the code that worked with x/net/websocket?
