### ISSUE TITLE
websocket.HandshakeError=websocket: upgrade != websocket

### ISSUE THREAD

**Issue by yxw2014** [gorilla/websocket#61]
36.68.88.123 - - - 127.0.0.1:7766 - [28/Apr/2015:06:13:44 +0000] "GET /ws?img_id=149046&uid=11485&sid=30206f5d-f94e-4ef1-7d63-2c6f23ee458b HTTP/1.1" 400  12 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36" www.xxx.com [0.000] - [0.000]

upgrader.Upgrade%!(websocket.HandshakeError=websocket: upgrade != websocket)

losts of 400 requests in Nginx error.log

**Comment by garyburd** [comment]
The upgrade method returned an error because the request is not a valid WebSocket handshake.  Specifically, the upgrade request header is not equal to 'websocket'.

Please check to see that you configured nginx to proxy websocket connections.

**Comment by yxw2014** [comment]
No relationship between the error and the configuration of Nginx, but with
a browser, because under the environment of PC Firefox, Chrome is no
problem.

2015-04-28 21:40 GMT+08:00 Gary Burd <notifications@github.com>:

**Comment by yxw2014** [comment]
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
upstream websocket2 {
    server 127.0.0.1:7766;
}


 location ^~ /ws {
                proxy_pass http://websocket2;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
 }


Is there some problems with the configuration  of Nginx?




2015-04-29 17:09 GMT+08:00 叶新伟 <yxw.2013.03@gmail.com>:

**Comment by garyburd** [comment]
I cannot help with Nginx. I don't have any experience using Nginx to proxy WebSocket connections.
