### ISSUE TITLE
[question] coon.WriteMessage Once timeout error occurs, TCP write 127.0.0.1:8080>127.0.0.1:2020, I /o timeout will be continuously reported

### ISSUE THREAD

**Issue by qifengzhang007** [gorilla/websocket#612]
**Describe the bug**  

```golang  
   //The code location for this test:  in '/examples/chat'
  
 // step  1 ， I set  
c.conn.SetWriteDeadline(time.Now().Add(1*time.Second))

  //step  2
  // Tudo something ...  ，this test simulation takes 2 seconds, Trigger timeout error 

  //step  3
 err:=c.conn.WriteMessage(websocket.TextMessage, v_bytes)    // in  this  block,  err  tips "TCP write 127.0.0.1:8080>127.0.0.1:2020, I /o timeout"  

// Since then, Re-execute the code the next time，Step 3 Will continue to report errors even if step 2 doesn't time out
// I want to know, even if one of the steps has a timeout error, how to avoid the continuous error？
```

**Versions**
> Go version: `go 1.14`
> package version: gorilla/websocket latest version(2020-07-24)

**Others added  text**
> if Switch the order of steps 2 and 3，then The above error does not occur 
> I want to talk about, why can't function `c.conn.WriteMessage`  be called again if something goes wrong

**Comment by echlebek** [comment]
Are you calling `SetWriteDeadline` again after? It would need to be called with the new `time.Now().Add(time.Second)`.

**Comment by qifengzhang007** [comment]
> Are you calling `SetWriteDeadline` again after? It would need to be called with the new `time.Now().Add(time.Second)`.

Even though I set `SetWriteDeadline`  on the next request, 
but the call to `c.conn.WriteMessage` still reports an error:   "write TCP  127.0.0.1:8080>127.0.0.1:2020, I /o timeout"

**Comment by TaylorRex** [comment]
The [SetWriteDeadline](https://pkg.go.dev/github.com/gorilla/websocket?tab=doc#Conn.SetWriteDeadline) documentation says:

> After a write has timed out, the websocket state is corrupt and all future writes will return an error.

The package works as documented.

**Comment by qifengzhang007** [comment]
> The [SetWriteDeadline](https://pkg.go.dev/github.com/gorilla/websocket?tab=doc#Conn.SetWriteDeadline) documentation says:
> 
> > After a write has timed out, the websocket state is corrupt and all future writes will return an error.
> 
> The package works as documented.

thank  you, In this case, developers have to set the timeout a little bit   longer  .

**Comment by mostcute** [comment]
i have only step 3 in a loop. `for {
err := Con.WriteJSON(mgs)
if err !=nil{
continue
}else{
break
}
}`
once write timeout,then the retry in the loop always report timeout

**Comment by mostcute** [comment]
so How to handle the retransmission logic after timeout

**Comment by TaylorRex** [comment]
@mostcute  The TCP stack in the operating system is responsible for retransmission logic.  The deadline specifies how long the application will wait until the connection is considered unusable by the application.
