### ISSUE TITLE
how not not check ssl certification if i want use wss? 

### ISSUE THREAD

**Issue by juewuer** [gorilla/websocket#613]
when i do my test, i used an expired ca, when the code run 
c, _, err := websocket.DefaultDialer.Dial("wss://127.0.0.1:443/", nil)
the err is 
 x509: certificate has expired or is not yet valid

how to do if i don't check the certification and ca?

**Comment by TaylorRex** [comment]
Use a dialer with [TLSConfig.InsecureSkipVerify](https://pkg.go.dev/crypto/tls?tab=doc#Config.InsecureSkipVerify) set to true.

      dialer := *websocket.DefaultDeialer
      dialer.TLSClientConfig := &tls.TLSConfig{InsecureSkipVerify: true}

**Comment by tmokmss** [comment]
For the latest version, we need the code below

```go
	dialer := *websocket.DefaultDialer
	dialer.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
```

**Comment by Binozo** [comment]
> For the latest version, we need the code below
> 
> ```go
> 	dialer := *websocket.DefaultDialer
> 	dialer.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
> ```

Sadly results in `websocket: bad handshake`
