### ISSUE TITLE
Not able to get context testing

### ISSUE THREAD

**Issue by zt9** [gorilla/websocket#615]
I expect to get the context passed into the http.handlefunc that contains the upgrader. I cannot seem to be able to read the context - do I need a different dialer?

Here is an example of what I tried and also should what I am trying to do. Playground link: [https://play.golang.org/p/LKPVoKZ23zr](https://play.golang.org/p/LKPVoKZ23zr)

```
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/gorilla/websocket"
)

var clients = make(map[*websocket.Conn]int64)
var upgrader = websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}


func WsHandler(w http.ResponseWriter, r *http.Request) {
	uid := r.Context().Value("UserId")
	fmt.Println("I am not getting uid from context here", uid)
	uid = int64(4) //force it, I should uid = 3
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Fatal(err)
	}

	clients[ws] = uid.(int64)
	ws.WriteMessage(websocket.TextMessage, []byte("hello"))
}

func TestWsHandler(t *testing.T) {
	s := httptest.NewServer(http.HandlerFunc(WsHandler))
	defer s.Close()
	u := "ws" + strings.TrimPrefix(s.URL, "http")

	ctx := context.Background()
	ctx = context.WithValue(ctx, "UserId", int64(3))

	ws, _, err := websocket.DefaultDialer.DialContext(ctx, u, nil)
	if err != nil {
		t.Fatalf("in DefaultDialer %v", err)
	}
	defer ws.Close()

	_, p, err := ws.ReadMessage()
	if err != nil {
		t.Fatalf("%v", err)
	}

	fmt.Println("read this from websocket:", string(p))

}```

**Comment by delca85** [comment]
@zt9 Did you solve this issue?

**Comment by Akomega** [comment]
@zt9 or @delca85 , were you able to get this working?

**Comment by tobias-kuendig** [comment]
Don't get confused about die `DialContext` method. It does not actually pass the context on to your handler! The context is only valid for the Dial method itself. There is a simple TCP connection in between, so the dialer and the handler don't actually know anything about each other.

You have to pass your custom mux to the `httptest.NewServer` constructor and use a middleware or custom http handler to inject your context.

```go
m := chi.NewRouter()
m.Use(injectYourContextMiddleware)
m.Handle("/something", yourHandler)

s := httptest.NewServer(m)
//...
```
