### ISSUE TITLE
ErrBadHandshake is unhelpful

### ISSUE THREAD

**Issue by pwaller** [gorilla/websocket#62]
This doesn't give me any useful information about why the handshake is failing:

https://github.com/gorilla/websocket/blob/ecff5aabe41f13b4cdf897e3c0c9bbccbe552a29/client.go#L70

See also this mailing list thread:

https://groups.google.com/d/topic/golang-nuts/so5wHa57RoM/discussion

(So I switched from x/net/websocket to gorilla/websocket only to have the same problem - I'd love to see this state of affairs improved!)

**Comment by pwaller** [comment]
So only by hacking the gorilla/websocket code could I tell that I was getting an unauthorized and why. The server I was connecting to was helpful by using the right status code and giving a body explaining how to fix it, but there is no way of inspecting that state currently.

**Comment by garyburd** [comment]
If the WebSocket handshake fails, ErrBadHandshake is returned along with a non-nil *http.Response so that callers can handle redirects, authentication, etc.

Here's an example of how to examine the status code:

    ws, resp, err := dialer.Dial(u, nil)
    if err == websocket.ErrBadHandshake {
         log.Printf("handshake failed with status %d", resp.StatusCode)
    }

I did not include the response body in the http.Response because I had not seen a server that writes anything to the body. I'll go ahead and update the code to slurp up some of the response and return it in Response.Body.

**Comment by pwaller** [comment]
Hey, that's great, thanks! That goes a long way. Is there any chance the error could include something useful, too? It's common to write code that ignores the other parameters if there is an error return.

**Comment by garyburd** [comment]
> Is there any chance the error could include something useful, too?

No. The benefits this change do not outweigh the cost.

All of the information needed by the application is included in the returned response object. There's little value in replicating this information in the error value.

The error returned on bad handshake cannot be changed without breaking applications that use the ErrBadHandshake return value. 

>  It's common to write code that ignores the other parameters if there is an error return.

It's also common to use other return values on error.  See the io.Reader interface for an example.
