### ISSUE TITLE
websocket: bad handshake (HTTP status 403 Forbidden)

### ISSUE THREAD

**Issue by fqmarkvon** [gorilla/websocket#622]
**Describe the problem you're having**

[GIN-debug] Listening and serving HTTP on:8080
2020/08/10 16:33:14 websocket: bad handshake (HTTP status 403 Forbidden)
exit status 1
…

**Versions**

go version go1.14.6 darwin/amd64

> package version: 

b65e62901fc1c0d968042419e74789f6af455eb9
…

**"Show me the code!"**

**This is the code in my main.go:**

func main() {

	configType := config.GetConfigType()

	// Setup release mode for Gin in production
	if configType == config.PROD {
		gin.SetMode(gin.ReleaseMode)
	}

	// Getting database settings
	dbConfig, err := config.GetDBConfig(configType)
	if err != nil {
		log.Fatal("Can't get DB Settings! %s", err)
	}

	// Connecting Mongo DB and defer disconnecting
	mongoDB := helpers.Connect(dbConfig.String(), dbConfig.DBname)
	defer mongoDB.Client.Disconnect(context.Background())

	// Inject store
	store := store.InjectStore(mongoDB.DB)

	// Inject services
	services := services.InjectServices(*store)

	// Run server
	Port := "8080"
	if os.Getenv("PORT") != "" {
		Port = os.Getenv("PORT")
	}

	// Setup handlers
	handlers.StartServer(*services, Port)

}

I just want to set up a local server for my ios app, it works at the beginning. But after I click "login" in my app on stimulator it suddenly became this. I don't know how to fix it, I didn’t change anything.

…

**Comment by fqmarkvon** [comment]
Never mind I fixed this issue

**Comment by Zeph0nix** [comment]
how did you fix it?

**Comment by CodeForcer** [comment]
Ugg, this was a hard one for me too. Took me a while to fix

**Comment by mattbucci** [comment]
> how did you fix it?
upgrader.CheckOrigin = func(r *http.Request) bool { return true }
