### ISSUE TITLE
Option to skip TLS verification

### ISSUE THREAD

**Issue by ARao0123** [gorilla/websocket#623]
Is there an option to skip the TLS verification when I create a new a new connection?

**Comment by TaylorRex** [comment]
Use a dialer with [TLSConfig.InsecureSkipVerify](https://pkg.go.dev/crypto/tls?tab=doc#Config.InsecureSkipVerify) set to true.

      dialer := *websocket.DefaultDialer
      dialer.TLSClientConfig := &tls.TLSConfig{InsecureSkipVerify: true}

**Comment by elithrar** [comment]
To reinforce though: you probably shouldn't do this, and should install a valid cert on your server. 

Use mkcert if this is for development or CI: https://github.com/FiloSottile/mkcert - to avoid inconsistencies.
