### ISSUE TITLE
Flush Messages Before Closing and Continuing Execution

### ISSUE THREAD

**Issue by jon-whit** [gorilla/websocket#624]
**Describe the bug**

The `Conn` struct's [`WriteJSON`](https://pkg.go.dev/github.com/gorilla/websocket@v1.4.2?tab=doc#Conn.WriteJSON) method behaves unexpectedly according to it's description. It behaves as though it's non-blocking although it is implemented and documented as though it should be. From the looks of the implementation, I'd expect the serialized messages to get flushed to the network before returning.

**Versions**
> Go version: `go version go1.14.1 darwin/amd64`
> package version: run `github.com/gorilla/websocket v1.4.2`

**Steps to Reproduce**

Executing the code below, you'll notice that the WaitGroup waits on all of the goroutines completing, and these goroutines are blocked by the `conn.WriteJSON(...)` call. Once all of the goroutines have completed, the messages *should* have been written to the network.

If you uncomment the `time.Sleep(2 * time.Second)`  line the issue resolves itself. If you do not have a delay between when the message is written and when the `conn.Close()` is called, then the messages don't necessarily ever get written.

**Expected behavior**

I feel like there is some undocumented and/or unexpected behavior with this code execution. I'd expected every message to have successfully been flushed and written out over the network before execution continues after the `wg.Wait()` step.

**Code Snippets**
```
package main

import (
    ...
)

func main() {
    var wg sync.WaitGroup
    start := time.Now()
    for i := 0; i < 2; i++ {
        wg.Add(1)

        go func() {
            defer wg.Done()

            conn, err := initWebsocketConn(addr)
            if err != nil {
                // handle error
            }
            defer conn.Close()

            for j := 0; j < 5; j++ {
                err := conn.WriteJSON(PublishInput{...})
                if err != nil {
                    // handle error
                }
            }

            //time.Sleep(2 * time.Second) uncommenting reveals the issue
        }()
    }
    wg.Wait()
    elapsed := time.Since(start)
}

```

Is this because the `conn.Close()` closes the underlying client's TCP connection without necessarily ensuring all of the packets were successfully received by the server? And if so, is the proper way to handle that by using a `CloseMessage` and then wait for the close response back from the server before closing the connection client side?

**Comment by jon-whit** [comment]
Even this doesn't resolve it:

```
var wg sync.WaitGroup
start := time.Now()
for i := 0; i < 2; i++ {
	wg.Add(1)

	go func() {
		defer wg.Done()

		conn, err := initWebsocketConn(*eventHubAddr)
		if err != nil {
			// handle error
		}

		closed := make(chan struct{})
		go func() {
			for {
				_, _, err := conn.ReadMessage()
				if err != nil {
					if websocket.IsCloseError(err, websocket.CloseNormalClosure) {
						log.Printf("CloseMessage received. Closing the WebSocket connection gracefully...")
						close(closed)
						return
					}
					// handle error
					return
				}
			}
		}()

		for j := 0; j < 5; j++ {
			msgID := uuid.New().String()

			err := conn.WriteJSON(PublishInput{...})
			if err != nil {
				// handle error
			}
		}

		err = conn.WriteMessage(websocket.CloseMessage, websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
		if err != nil {
			// handle error
		}

		select {
		case <-closed:
		case <-time.After(2 * time.Second):
			log.Printf("Timed out waiting for WebSocket CloseMessage..")
		}

		err = conn.Close()
		if err != nil {
			// handle error
		}
	}()
}
wg.Wait()
elapsed := time.Since(start)
```

I'd expect waiting on the CloseMessage to have been received would definitely resolve the issue? So what am I doing wrong?

**Comment by JackandRoses** [comment]
test

**Comment by jon-whit** [comment]
@garyburd any ideas?

**Comment by TaylorRex** [comment]
The write methods return when data is written to the operating system.  The operating system writes all data to the network before closing the connection.

I pasted your code into a simple application. It works as expected.  Update the issue with code that reproduces the problem. 

```
package main

import (
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"time"

	"github.com/gorilla/websocket"
)

func initWebsocketConn(addr string) (*websocket.Conn, error) {
	c, _, err := websocket.DefaultDialer.Dial(addr, nil)
	return c, err
}

type PublishInput struct{ Message string }

var upgrader websocket.Upgrader

func handler(w http.ResponseWriter, r *http.Request) {
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer ws.Close()
	for {
		_, p, err := ws.ReadMessage()
		if err != nil {
			break
		}
		fmt.Printf("Message: %s", p)
	}
}

func main() {
	s := httptest.NewServer(http.HandlerFunc(handler))
	defer s.Close()
	addr := "ws" + strings.TrimPrefix(s.URL, "http")
	var wg sync.WaitGroup
	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			conn, err := initWebsocketConn(addr)
			if err != nil {
				log.Fatal(err)
			}
			defer conn.Close()
			for j := 0; j < 5; j++ {
				err := conn.WriteJSON(PublishInput{fmt.Sprintf("hello %d, %d", i, j)})
				if err != nil {
					log.Fatal(err)
				}
			}
		}(i)
	}
	wg.Wait()
	time.Sleep(time.Second) // wait for handlers to finish logging messages
}
```

**Comment by jon-whit** [comment]
@TaylorRex the code I posted does produce the issue. The only way I can get it to work (like you did) was to put a `time.Sleep(..)` in at after all of the writes.

As I understood, the `conn.Close()` should flush it and write it to the underlying connection. So I shouldn't have to sleep in order for it to work, right?

**Comment by TaylorRex** [comment]
The websocket `Close()` method calls `Close()` on the underlying network connection.  Close on a network connection can return before data is written to the wire by the operating system.  

Because the websocket connection flushes each message to the underlying network conection when the message is closed,  there are no messages for the websocket `Close()` method to flush.

The call to `time.Sleep()` is not needed to ensure that data is written to the wire. The sleep call gives the operating system time to transmit data to the server and time for the server to read and log the messages before  the server handler goroutnes are terminated by the return from `main()`. 

If you want to wait for the peer to read all messages before returning from the application, then you need to wait for the peer to acknowledge receipt of the messages. One way to do this is to send a close message and wait for the peer to respond with a close message.

**Comment by jon-whit** [comment]
TaylorRex did you notice my second example in my second comment? I send a close message at the end of writing the messages. I have a go routine that listens for the close message and closed a channel when it occurs.

Sending a close message and waiting for it before returning doesn't resolve the issue either.

**Comment by TaylorRex** [comment]
This program waits sends a close message to the peer and waits for a reply.  The server logs all messages sent by the client.

```
package main

import (
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"

	"github.com/gorilla/websocket"
)

func initWebsocketConn(addr string) (*websocket.Conn, error) {
	c, _, err := websocket.DefaultDialer.Dial(addr, nil)
	return c, err
}

type PublishInput struct{ Message string }

var upgrader websocket.Upgrader

func handler(w http.ResponseWriter, r *http.Request) {
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer ws.Close()
	for {
		_, p, err := ws.ReadMessage()
		if err != nil {
			break
		}
		fmt.Printf("Message: %s", p)
	}
}

func main() {
	s := httptest.NewServer(http.HandlerFunc(handler))
	defer s.Close()
	addr := "ws" + strings.TrimPrefix(s.URL, "http")
	var wg sync.WaitGroup
	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			conn, err := initWebsocketConn(addr)
			if err != nil {
				log.Fatal(err)
			}
			defer conn.Close()
			for j := 0; j < 5; j++ {
				err := conn.WriteJSON(PublishInput{fmt.Sprintf("hello %d, %d", i, j)})
				if err != nil {
					log.Fatal(err)
				}
			}

			// Tell peer that we are done.
			err = conn.WriteMessage(websocket.CloseMessage,
				websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
			if err != nil {
				log.Fatal(err)
			}

			// Wait for peer to close connection or any other error.
			for {
				if _, _, err := conn.NextReader(); err != nil {
					break
				}
			}

		}(i)
	}
	wg.Wait()
}
```

**Comment by TaylorRex** [comment]
The network connection Write method blocks until the data is written to the operating system. The Write method does not wait for the data to be written to the network or for the peer to receive the data. The websocket Close calls Close on the underlying network connection.  The network connection Close method can return before queued data is written to the network.
