### ISSUE TITLE
WS.ReadMessage() is not terminated when WS.Close()

### ISSUE THREAD

**Issue by DaniyarGilimov** [gorilla/websocket#626]
**Describe the problem you're having**
> Sometimes very very rare, WS.ReadMessage() is not terminated when WS.Close(), and it freezes. Does anyone had the same issue?
…

**Versions**
> Go version: 1.14

> package version: run `git rev-parse HEAD` inside the repo

**Comment by DaniyarGilimov** [comment]
> Can you please provide a (minimal) example of your WebSocket handling code?

i'm using the same as chat example https://github.com/gorilla/websocket/blob/master/examples/chat/client.go

**Comment by DaniyarGilimov** [comment]
here it is: https://gist.github.com/DaniyarGilimov/9f7b2aa83aa9ab0d3987b790c78baee5

**Comment by TaylorRex** [comment]
With some guesses about the code not included in the gist, it looks like there's a data race on `pc.WR`.  Run the application with the [race detector](https://golang.org/doc/articles/race_detector.html) and fix any issues.   I also suspect there's race on send and close of `pc.Ch`.
