### ISSUE TITLE
Using long polling + rate-limiter

### ISSUE THREAD

**Issue by Skycader** [gorilla/websocket#628]
1. Does Gorilla support long polling the way socket.io does? If not, please implement it!
2. Also, is there protection from Dos/Flood attacks per IP address? Would be really appriciated.

**Comment by elithrar** [comment]
gorilla/websocket is only a WebSocket library - it does not handle HTTP long-polling. Given that WebSockets are very mature now, the need to do long-polling is pretty rare. Either way, there isn't any intent to add it here.  

DoS/flood protection is best done at the CDN level, or with rate-limiting middleware - e.g. https://github.com/uber-go/ratelimit or with a reverse proxy like [Envoy](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter).
