### ISSUE TITLE
Specifying separate dial host and http "Host:" header

### ISSUE THREAD

**Issue by pwaller** [gorilla/websocket#63]
I'm making a proxy which can handle web sockets. Everything is fine except I can't easily specify the `Host:` header correctly.

The problem is, some random client connects inbound with `example.com`, which proxies to `foo.internal`. `foo.internal` ends up seeing `Origin: example.com` and `Host: foo.internal`. I want the internal server to see `Host: example.com`.

This can be achieved in two ways I can immediately think of. I could implement my own Dial method:

https://github.com/gorilla/websocket/blob/ecff5aabe41f13b4cdf897e3c0c9bbccbe552a29/client.go#L182-L227

However, I would have to copy a great deal of the code in your library, and would not get the benefit of any fixes that might arrive in the future.

An alternative would be to extend the gorilla `Dial` method so that if a `Host` header is specified via the requestHeader parameter, it modifies the host of the URL `u` that is passed to `NewClient` (after the TCP dial has already happened), and gets deleted from the set of headers (so that it doesn't end up specified twice).

Would the latter fix be accepted as a PR, or can you think of an alternative method of achieving my goal? Thanks!

**Comment by pwaller** [comment]
I've made a pull request. The change is quite small but took me a while to work out exactly what it should be, but I'm now reasonably sure this has the semantics I need. I've tested it in a production-like configuration and I'm happy with it.

**Comment by garyburd** [comment]
An application can connect to a host different from the one specified in the URL using [Dialer.NetDial](http://godoc.org/github.com/gorilla/websocket#Dialer.NetDial):

      d := websocket.Dialer{
            NetDial: func(network, addr string) (net.Conn, error) {
                return new.Dial(network, proxyHostPort)
           }
     }
     ws, resp, err := d.Dial(u, h) // connects to proxyHostPort with Host header from u.

**Comment by pwaller** [comment]
I think I discounted that approach because of the `ServerName` in the TLS config. I want the `ServerName` to be the name of the machine I'm connecting to, not the machine I'm proxying (and for that to be arranged for me by the Dial function.

I now see that I can arrange this if I need to by setting a TLS configuration. However this is less convenient than specifying the host header (which also makes the intent of my code clear - connect to this URL, use this host header).

I'll understand though if you don't want to accept my pull request. I'll leave you to close this issue and choose whether to close or accept my pull request.

Thanks for your time the last couple of days.

**Comment by garyburd** [comment]
Fixed by 6fd0f867fef40c540fa05c59f86396de10a632a6
