### ISSUE TITLE
[question] is SetReadLimit() high values have influence on the performance?

### ISSUE THREAD

**Issue by Rogalek** [gorilla/websocket#632]
I am wondering if high values for conn.SetReadLimit() will have any influence on the performance? 
Is there like recommended value for that parameter?

**Comment by TaylorRex** [comment]
SetReadLimit has no influence on performance.  The parameter helps to protect against DoS attacks.

Set the limit to a value larger than any message you expect your application to receive.

**Comment by Rogalek** [comment]
Thank you.
