### ISSUE TITLE
[bug] server context is not cancelled when underlying connection closes

### ISSUE THREAD

**Issue by ThomasHabets** [gorilla/websocket#633]
**Describe the bug**
> A clear and concise description of what the bug is.

On the server side the context associated with the websocket does not cancel when the client's context cancels, or even when the client closes the connection.

I don't want the client side to send a message, and for this to trigger, since the client binary could have been kill-9'd, in which case it has no chance to send anything.

The server's request context should be cancelled when the underlying connection closes.

This bug is causing me to leak goroutines on long running (but rare communication) websockets. In my case the TCP connection is between nginx and the Go program on the same host, so it's not even a problem of a network glitch. nginx has closed the TCP connection an hour ago, but Go is still keeping the goroutine running with the socket, and will only discover the problem when it writes a message.

I don't want to solve this with Ping handlers, since:
1. Pings would go all the way to the end device, which is phones. Pings would do radio wakeup and waste battery on all the connected phones.
2. I want "edge triggered", not "polling". All the information is there for the Go program to know the connection is gone. Why wait for a ping?
3. I already have a timeout set in nginx. There should be no need for tuning a separate ping interval.

**Versions**
> package version: run `git rev-parse HEAD` inside the repo

> Go version: `go version`

```
go version
go version go1.14.7 linux/amd64
```

```
$ git rev-parse HEAD
c3dd95aea9779669bb3daafbd84ee0530c8ce1c1
```

**Steps to Reproduce**
> How can the bug be triggered?

See [this program](https://gist.github.com/ThomasHabets/160424730dee355ee92c5193ee6ad331).

This is the output:
```
2020/09/18 10:32:18 ---------First a normal request-------
2020/09/18 10:32:18 client> starting
2020/09/18 10:32:19 server> context finished, yay!
2020/09/18 10:32:19 client> request finished with: Get "http://localhost:4711/req": context deadline exceeded
2020/09/18 10:32:19 ---------Now a websocket request-------
2020/09/18 10:32:19 wsclient> starting
2020/09/18 10:32:20 wsclient> client context has been cancelled (server should know)
2020/09/18 10:32:20 wsclient> client has now closed connection (server *definitely* should know)
2020/09/18 10:32:29 wsserver> request timeout, boo! <-----------
```

**Expected behavior**
> What output or behaviour were you expecting instead?

I expect the server's context to be cancelled when the client context cancels. Well, the client context cancelling should trigger connection closing, which in turn should cause the server to notice the TCP connection is gone, and cancel the context on the server side.

So output should look like:

```
2020/09/18 10:32:18 ---------First a normal request-------
2020/09/18 10:32:18 client> starting
2020/09/18 10:32:19 server> context finished, yay!
2020/09/18 10:32:19 client> request finished with: Get "http://localhost:4711/req": context deadline exceeded
2020/09/18 10:32:19 ---------Now a websocket request-------
2020/09/18 10:32:19 wsclient> starting
2020/09/18 10:32:20 wsclient> client context has been cancelled (server should know)
2020/09/18 10:32:20 wsclient> client has now closed connection (server *definitely* should know)
2020/09/18 10:32:20 wsserver> context finished, yay!
```

Note the timestamp of the last request. Exactly the same second as the context is cancelled.

(if I had a `ReadMessage()` call active I'd expect the CloseHandler to be called as well)

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

See [this program](https://gist.github.com/ThomasHabets/160424730dee355ee92c5193ee6ad331).

**Comment by TaylorRex** [comment]
Detect closed connections by reading the connection as required by the package ([see doc here](https://godoc.org/github.com/gorilla/websocket#hdr-Control_Messages)).  Return from the handler to cancel the per-request context created by the net/http server:

```
func websocketHandler(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Fatalf("wsserver> websocket upgrader: %v", err)
	}
	defer conn.Close()

        // Read and discard messages until an error is detected.
	for {
		if _, _, err := conn.NextReader(); err != nil {
			break
		}
	}

	log.Print("wsserver> exiting read loop!")

         // r.Context is canceled on return from this function.
}

```

The net/http server does not monitor connections upgraded to the WebSocket protocol and therefore does not cancel the per-connection context when the connection is lost.

**Comment by TaylorRex** [comment]
@ThomasHabets Does the read loop address the issue?

**Comment by ThomasHabets** [comment]
Sorry for not following up. Yes, that does cause it to close.

I would prefer it if gorally were to use contexts to cancel readers and senders here, but yes this solves my problem.

Thank you.
