### ISSUE TITLE
[enhancement]make Sec-Websocket-Version const

### ISSUE THREAD

**Issue by Hiroya3** [gorilla/websocket#637]
## what I sugget
make Sec-Websocket-Version const

### suggested Code place
server.go

```
if !tokenListContainsValue(r.Header, "Sec-Websocket-Version", "13") {
  return u.returnError(w, r, http.StatusBadRequest, "websocket: unsupported version: 13 not found in 'Sec-Websocket-Version' header")
}
```
### reason
I think making webSocket version const is better because version should be updated.
In order to readable for developers and make it easy to change version of web-socket, I suggest about this.

### Pull Request
https://github.com/gorilla/websocket/pull/638

Thanks in advance.

**Comment by TaylorRex** [comment]
> In order to readable for developers and make it easy to change version of web-socket,

Adding support for a new version of the protocol will be more complicated than changing a single string constant.  Some of those changes might look like this:

```
if tokenListContainsValue(r.Header, "Sec-Websocket-Version", "14") {
    // code for version 14 of the protocol
} else if tokenListContainsValue(r.Header, "Sec-Websocket-Version", "13")
   // code for version 13 of the protocol
} else {
  return u.returnError(w, r, http.StatusBadRequest, "websocket: unsupported version: 13 or 14 not found in 'Sec-Websocket-Version' header")
}

```

Some people will argue that the "13" and "14" in the above code should use constants to make the code more readable:

```
const (
    secWebsocketVersion13 = "13"
    secWebsocketVersion14 = "14"
)

```

If these constants are only used in one place as the proposed `SecWebsocketVersion` constant is, then the constant only adds to what the developer must understand when reading the code.

**Comment by Hiroya3** [comment]
@TaylorRex 
Thank you for replying.
As you wrote, to use constants may be not readable.

I could learn thanks of you.
I will close this issue and PR.
