### ISSUE TITLE
[question] JSON messages

### ISSUE THREAD

**Issue by konethmelathil** [gorilla/websocket#639]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

When sending multiple messages of type JSON, they go out in an unparseable mass:
{ "a": "foo", b: true} { "a": "bar", b: false}

The Javascript parser on the other end throws an error at the open curly brace of the second message structure.
Both JSON messages show up at the client read buffer at the same time then browser app does a JSON parse and fails.

How can I prevent this other than put a timer delay of 1 millisecond or so between messages? Is there a way to send the two messages as distinct "packets". Remember this is a Websocket feed. So I am sending out messages as I get it from a process. So I cannot put in a JSON array with [] and comma etc. I get these from a Golang channel and then send on the Websocket.

Thank you

…

**Versions**
> Go version: `go version`

Go 1.15

``` go
func (c *Client) SendMsg(msg []byte) {

        select {
      
        case c.sendChannel <- msg:
        default:
                fmt.Println("don't panic")
        }

}

func (c *Client) writethread() {

        for {
                select {
                case message, ok := <-c.sendChannel:
                
                        err := c.conn.SetWriteDeadline(time.Now().Add(writeWait))
                        if err != nil {
                                logger.Printf("Error in SetWriteDeadline: %s", err.Error())
                        }
                        if !ok {
                                // The Hub closed the channel.
                                _ = c.conn.WriteMessage(websocket.CloseMessage, []byte{})
                                return
                        }

                        w, err := c.conn.NextWriter(websocket.TextMessage)
                        if err != nil {
                                logger.Printf("Error in MextWriter: %s", err.Error())
                                return
                        }

                        _, err = w.Write(message)
                        if err != nil {
                                logger.Printf("Error in writing to client: %s", err.Error())
                                return
                        }

                        // Add queued chat messages to the current websocket message.
                        n := len(c.sendChannel)
                        for i := 0; i < n; i++ {
                                _, err := w.Write(<-c.sendChannel)
                                if err != nil {
                                        logger.Printf("Error in writing to client: %s", err.Error())
                                        return
                                }
                        }

                        if err := w.Close(); err != nil {
                                return
                        }
}
```
…

**Comment by TaylorRex** [comment]
Show the code used to send the messages.

**Comment by Kunderao** [comment]
> 
> 
> Show the code used to send the messages.

Updated. Thank you.

**Comment by TaylorRex** [comment]
Delete the code appends multiple values from `c.sendChannel` to the outgoing WebSocket message.

**Comment by Kunderao** [comment]
> 
> 
> If you do not want the client to handle multiple JSON documents in a single websocket message, then delete the code appends multiple values from `c.sendChannel` to an outgoing WebSocket message.


Thank you! I assume anything you put before ```go w.Close() ``` will be packed into one "packet."

**Comment by TaylorRex** [comment]
Everything between the NextWriter and Close on the returned writer is written to a single websocket message. 

There are no guarantees on how that data is written to packets at the network layer.  Your best bet for getting everything in one network packet is to call [WriteMessage](https://godoc.org/github.com/gorilla/websocket#Conn.WriteMessage) instead of NextWriter/Write/Close.

**Comment by Kunderao** [comment]
> 
> 
> Everything between the NextWriter and Close on the returned writer is written to a single websocket message.
> 
> There are no guarantees on how that data is written to packets at the network layer. Your best bet for getting everything in one network packet is to call [WriteMessage](https://godoc.org/github.com/gorilla/websocket#Conn.WriteMessage) instead of NextWriter/Write/Close.

Sorry .. I may be misinterpreting the Websocket protocol formats.

 I just need it to insure once JSON unit of data is sent in one message regardless of how packetizing occurs at the network or media access layer. So I will continue to use NextWriter  as you have suggested. 

Thank you so much for you assistance in clearing that up!

**Comment by TaylorRex** [comment]
> So I will continue to use NextWriter as you have suggested

I didn't suggest an approach, but now I will. Use [WriteMessage](https://godoc.org/github.com/gorilla/websocket#Conn.WriteMessage) because the one method call does the work of NextWriter/Write/Close.

**Comment by Kunderao** [comment]
> 
> 
> > So I will continue to use NextWriter as you have suggested
> 
> I didn't suggest an approach, but now I will. Use [WriteMessage](https://godoc.org/github.com/gorilla/websocket#Conn.WriteMessage) because the one method call does the work of NextWriter/Write/Close.

Thanks. This was a huge help in resolving a lot of problems downstream by way of some adjustments.
