### ISSUE TITLE
[question] getting error when trying to send (NOT recieve) gzip/zlib encoded data.

### ISSUE THREAD

**Issue by codic12** [gorilla/websocket#641]
**Describe the problem you're having**
For reasons that I don't understand, the code shown below fails (note that msg is gzip compressed data) at the send line, however it successfully decodes what it gets. I want to decode it as I will validate it later, but I want to still broadcast the encoded data, hence I am sending back the original data `msg`. If I change the line `queue.broadcastToAll(msg)` to `queue.broadcastToAll(data)`, or broadcast the uncompressed version of the data, it does work. Any idea why this happens? if i switch to zlib on both the server and client end i run into the same issue.

**"Show me the code!"**
```go
package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/gorilla/websocket"
)

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin: func(_ *http.Request) bool {
		return true
	},
}

// Queue is a collection of sockets. A message can be broadcasted to all members of the queue with Queue#broadCastToAll, and sockets can be appended to the queue via the #broadcastToAll method.
type Queue struct {
	socks []*websocket.Conn
}

func (queue *Queue) addToQueue(sock *websocket.Conn) {
	queue.socks = append(queue.socks, sock)
}

func (queue Queue) broadcastToAll(message []byte) {
	for _, sock := range queue.socks {
		sock.WriteMessage(1, message)
	}
}

func main() {
	queue := Queue{}
	http.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("Got connection")
		conn, err := upgrader.Upgrade(w, r, nil) // error ignored for sake of simplicity
		if err != nil {
			panic(err)
		}
		queue.addToQueue(conn)
		for {
			// Read message from browser
			_, msg, err := conn.ReadMessage()
			if err != nil {
				panic(err)
			}

			r, err := gzip.NewReader(bytes.NewBuffer(msg))
			if err != nil {
				panic(err)
			}
			data, err := ioutil.ReadAll(r)
			if err != nil {
				panic(err)
			}

			// Print the message to the console
			fmt.Printf("%s sent: %s\n", conn.RemoteAddr(), string(data))

			// Broadcast it everywhere
			queue.broadcastToAll(msg)
		}
	})

	http.ListenAndServe(":8080", nil)
}
```

**Versions**
> Go version: `1.15.2`
> Gorilla version: `1.4.2`

**Comment by codic12** [comment]
never mind this was a client side issue

**Comment by TaylorRex** [comment]
The application has a data race on Queue.socks. Run the application with the [race detector](https://golang.org/doc/articles/race_detector.html) and fix reported issues.

Send the gizped data as a binary message ([websocket.BinaryMessage](https://godoc.org/github.com/gorilla/websocket#BinaryMessage)) instead of as a text message (1 = websocket.TextMessage).  Text messages must be valid UTF-8.

**Comment by codic12** [comment]
I will look for a race condition.
Ah, I see, thanks.
