### ISSUE TITLE
Upgrader.Upgrade not writing error response to http.ResponseWriter for invalid request with payload data

### ISSUE THREAD

**Issue by ashishwigwag** [gorilla/websocket#642]
**Describe the bug**
I'm running a websocket server that uses Upgrader.Upgrade() to handle handshake requests for switching protocols from http to websocket connection.
Upgrader.Upgrade() seems to validate all websocket headers and writes error code with response to http.ResponseWriter if any required header is missing or invalid.
But if the client sends a request with unnecessary payload data, Upgrader.Upgrade doesn't send an error response to the client.
It however returns an error to the service saying `websocket: client sent data before handshake is complete`. And the client shuts without a reply from server

On receiving this error in the server, I tried to send an error response to the client explicitly. But I can't, as the http connection is deemed 'hijacked'.

**Problem**: How should the server handle request with payload data? Do I need to validate that an incoming handshake request should have no payload, before using Upgrader.Upgrade to switch protocols?
If not, how to I send an error code to the client.
…

**Versions**
Go version: 1.11.5
package version: b65e62901fc1c0d968042419e74789f6af455eb9

…

**Steps to Reproduce**
Use Upgrader.Upgrade() to upgrade an http GET request. Send payload data in the client request. 

…

**Expected behavior**
A proper error code and response must be sent to the client for a bad handshake request if it contains an unnecessary payload data.

…

**Code Snippets**

	h, ok := w.(http.Hijacker)
	if !ok {
		return u.returnError(w, r, http.StatusInternalServerError, "websocket: response does not implement http.Hijacker")
	}
	var brw *bufio.ReadWriter
	netConn, brw, err := h.Hijack()
	if err != nil {
		return u.returnError(w, r, http.StatusInternalServerError, err.Error())
	}

	if brw.Reader.Buffered() > 0 {
		netConn.Close()
		return nil, errors.New("websocket: client sent data before handshake is complete")
	}
Originating here: https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/server.go#L185

…

**Comment by TaylorRex** [comment]
The server cannot detect that the client sent data until the connection is hijacked.  Once hijacked, the response writer is no longer useable.  

Fix by writing an HTTP response to the connection:

```
if brw.Reader.Buffered() > 0 {
	brw.WriteString( 
	    "HTTP/1.1 400 Bad Request\r\n" +
	    "Sec-Websocket-Version: 13\r\n" +
	    "Connection: close\r\n" +
	     "\r\n" +
	     "Client sent data before receiving handshake response from server.")
	brw.Flush()
	netConn.Close()
	return nil, errors.New("websocket: client sent data before handshake is complete")
}

```

**Comment by ashishwigwag** [comment]
@TaylorRex Shouldn't this be fixed in gorilla/websocket if its a bug?
I dont know if this is an expected behaviour in websocket protocol.
Couldn't find a reference in websocket std. [RFC6455](https://tools.ietf.org/html/rfc6455).

**Comment by TaylorRex** [comment]
Yes.  That's why I posted a suggested fix to the package.

The [section of the RFC on client requirements](https://tools.ietf.org/html/rfc6455#section-4.1) says:

>  Once the client's opening handshake has been sent, the client MUST wait for a response from the server before sending any further data.

The current code complies with the RFC because the RFC does not specify how the server should handle this client error. Responding with a bad status is more useful than just closing the connection.
