### ISSUE TITLE
[query] What does the error mean "websocket: internal error, unexpected bytes at end of flate stream"

### ISSUE THREAD

**Issue by vishal24tuniki** [gorilla/websocket#643]
Can someone please help me understand what the error `websocket: internal error, unexpected bytes at end of flate stream` means ? In my application i am observing it when we are trying to call `conn.WriteJSON` when we received an error from server `websocket: close 4500: Token expired`

**Comment by garyburd** [comment]
The internal connection state is corrupt. Is it possible that WriteJSON was called concurrently with other writes to the connection?

**Comment by darKing2018** [comment]
Concurrently write will panic, I guess it because of compression
Can you tell me how to reproduce the problem?
