### ISSUE TITLE
[bug]  when copying from client to backend: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by Haomeng** [gorilla/websocket#645]
**Describe the bug**
> A clear and concise description of what the bug is.

…

Encountered this error "when copying from client to backend: websocket: close 1006 (abnormal closure): unexpected EOF", looks like the wss connection is closed after dial successfully,

So any ideas about such issue?? Thanks a lot!

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

go version go1.15.2 linux/amd64

…

**Steps to Reproduce**
> How can the bug be triggered?

…

**Expected behavior**
> What output or behaviour were you expecting instead?

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by TaylorRex** [comment]
The WebSocket RFC states that a peer must send a close message before closing the network connection.  The error indicates that the peer closed the connection without sending a close message. Some WebSocket libraries allow that (like this one).

There is insufficient information to determine why the peer closed the connection.
