### ISSUE TITLE
Documentation is not enough clear about ping/pong

### ISSUE THREAD

**Issue by cocodrino** [gorilla/websocket#649]
Hi, good days, my WebSocket needs to detect client disconnections and red issues, I know that gorilla has an implementation of ping/pong but I can't found any documentation about this...

checking in the web I found this

```go
func keepAlive(c *websocket.Conn, timeout time.Duration) {
	lastResponse := time.Now()
	c.SetPongHandler(func(msg string) error {
		lastResponse = time.Now()
		return nil
	})

	go func() {
		for {
			err := c.WriteMessage(websocket.PingMessage, []byte("keepalive"))
			if err != nil {
				return
			}
			time.Sleep(timeout/2)
			if time.Now().Sub(lastResponse) > timeout {
				log.Printf("Ping don't get response, disconnecting to %s",c.LocalAddr())
				_ = c.Close()
				return
			}
		}
	}()
}
```

this seems pretty far what I need...basically I pass the client connection to this code and periodically send a ping message, my question here is 

1) what exactly do websocket.PingMessage? ...I know that this is some code related to the message type, but if I'm connecting this websocket to some browser client, does this code has some effect?...
2) in my client (browser) do I need configure an specific response?....or basically when I get an "keepalive" I just need respond "pong"?

thank you so much...

**Comment by TaylorRex** [comment]
PING and PONG messages are described in the [RFC](https://tools.ietf.org/html/rfc6455#section-5.5.2).  In summary, peers (including the browser) automatically respond to a PING message with a PONG message.

The best practice for detecting a dead client is to [read with a deadline](https://godoc.org/github.com/gorilla/websocket#Conn.SetReadDeadline).  If the client application does not send messages frequently enough for the deadline you want, then send PING messages to induce the client to send a PONG. Update the deadline in the [pong handler](https://godoc.org/github.com/gorilla/websocket#Conn.SetPongHandler) and after reading a message.

The chat, command and filewatch examples in this repository show how to use PING/PONG. 

The code you posted has a data race on `lastResponse`.

**Comment by cocodrino** [comment]
thanks for the answer @TaylorRex ..I'm checking the samples... I've got a few questions:

1) Basically I need to set some deadlines when the connection is opened

```go
	c.conn.SetWriteDeadline(time.Now().Add(pongWait))
	c.conn.SetPongHandler(func(string) error { c.conn.SetWriteDeadline(time.Now().Add(pongWait)); return nil })
```

2) I can send a ping to the client every x seconds...when the client respond I could set a new write deadline

something like this

```go
for {
		_, message, err := ws.ReadMessage() //right now I'll handle the pong like any other message
                 ws.SetWriteDeadline(time.Now().Add(writeWait))
```

3) Does gorilla WebSocket automatically close the connection if the deadline expires?...

thank you

**Comment by TaylorRex** [comment]
Set the **read** deadline. 

Read operations return an error after the read deadline is breached.  If the application is already handling read errors, no additional code is needed.

**Comment by cocodrino** [comment]
@TaylorRex  👍  thank you so much.

**Comment by cocodrino** [comment]
Hi @TaylorRex I'm having some troubles, I don't have so much experience with go and my result code seems a bit overcomplicated and it doesn't even work...

basically in my WebsocketUserHandler I upgraded the connection to build the websocket

```go
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println(err)
		return
	}

```

I set the pong handler

```go
ws.SetReadLimit(maxMessageSize)
	_ = ws.SetWriteDeadline(time.Now().Add(pongWait))
	ws.SetPongHandler(func(string) error {
		err = ws.SetWriteDeadline(time.Now().Add(pongWait))
		if err != nil {
			fmt.Println("error first setwrite deadline ", err)
		}
		return nil
	},
	)
```

and call the ClientMessageHandler, this is the place where I handle the pong message and user messages, the first question is: is ok that this is a goroutine or must call this without the go keyword?

```go
	go ClientMessageHandler(newUser)
```

now...this is the ugly part, I think that it's a better idea use SetWriteDeadline because the clients don't send so much messages to the WebSocket server, basically my WebSocket deliver messages to connected users according to some requirements

here:
1) my idea is based on this code https://chromium.googlesource.com/external/github.com/gorilla/websocket/+/v1.2.0/examples/chat/client.go

basically, my idea is to send a ping message to the client every pingPeriod time, when it fails then I close the connection

here, something that I don't like is that because I need a select, to take two channels (the ticker channel and the user message channel) I had to build a coroutine to take the *ReadMessage* and pass the data to the channel *messageChan* (is this ok?)


```go
func ClientMessageHandler(user *User) {
	ws := user.WsConn
	ticker := time.NewTicker(pingPeriod)
	messageChan := make(chan []byte)

	defer func() {
		fmt.Println("defer ClientMessageHandler user", user.UserId)
		ticker.Stop()
		disconnect(user)

		if r := recover(); r != nil {
			fmt.Println("don't panic, can't write message but it's probably because it was disconnected previously")
		}
	}()

	// this channel transform the ReadMessage into a channel
	go (func() {
		defer func() {
			fmt.Println("closing ReadMessage goroutine")

			if r := recover(); r != nil {
				fmt.Println("don't panic, but readmessage can't connect to the channel \n", r)
			}
		}()

		for {
			_, message, err := ws.ReadMessage()

			if err != nil {
				log.Println("read:", err)
				log.Println(message)
				return
			}

			messageChan <- message
		}
	})()

	for {
		select {
		case <-ticker.C:
			user.WSLock.RLock()
			_ = ws.SetWriteDeadline(time.Now().Add(pongWait))
			user.WSLock.RUnlock()
			if err := ws.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
				fmt.Println("Can't write to socket...disconnecting")
				return
			}

		case message := <-messageChan:
			user.WSLock.RLock()
			err := ws.SetWriteDeadline(time.Now().Add(pongWait))
			user.WSLock.RUnlock()

			if err != nil {
				log.Println("error writing deadline: ", err)
				break
			}

			log.Printf("recv: %s", message)
			var msg map[string]interface{}
			err = json.Unmarshal(message, &msg)
			if err != nil {
				log.Print(err)
			}
			log.Println(msg)


		}

		// _ = ws.WriteJSON(response)
	}
}

```

2) I'm getting a weird error with this corroutine, this line fails

```js
 for {
			_, message, err := ws.ReadMessage()
```

here I get a `invalid memory address or nil pointer dereference`` probably I'd need check ws before that, but I don't think it's very complicated, although I'm open to any suggestion

3) I had to use Locks because I was getting a race condition 

Do you think that this solution is over complicated or I'm in the right path? thank you so much

**Comment by TaylorRex** [comment]
As stated in my previous comment, use the read deadline to detect dead clients.  If the peer does not send messages frequently enough for your deadline, the ask the peer to send a PONG message by sending the peer a PING message. 

Changing the pong handler to set the read deadline will improve the code. 

See the chat and filewatch examples in this repository for example of how to use the read deadline.

**Comment by amaoyulong** [comment]
> Hi @TaylorRex I'm having some troubles, I don't have so much experience with go and my result code seems a bit overcomplicated and it doesn't even work...
> 
> basically in my WebsocketUserHandler I upgraded the connection to build the websocket
> 
> ```go
> 	ws, err := upgrader.Upgrade(w, r, nil)
> 	if err != nil {
> 		log.Println(err)
> 		return
> 	}
> ```
> 
> I set the pong handler
> 
> ```go
> ws.SetReadLimit(maxMessageSize)
> 	_ = ws.SetWriteDeadline(time.Now().Add(pongWait))
> 	ws.SetPongHandler(func(string) error {
> 		err = ws.SetWriteDeadline(time.Now().Add(pongWait))
> 		if err != nil {
> 			fmt.Println("error first setwrite deadline ", err)
> 		}
> 		return nil
> 	},
> 	)
> ```
> 
> and call the ClientMessageHandler, this is the place where I handle the pong message and user messages, the first question is: is ok that this is a goroutine or must call this without the go keyword?
> 
> ```go
> 	go ClientMessageHandler(newUser)
> ```
> 
> now...this is the ugly part, I think that it's a better idea use SetWriteDeadline because the clients don't send so much messages to the WebSocket server, basically my WebSocket deliver messages to connected users according to some requirements
> 
> here:
> 
> 1. my idea is based on this code https://chromium.googlesource.com/external/github.com/gorilla/websocket/+/v1.2.0/examples/chat/client.go
> 
> basically, my idea is to send a ping message to the client every pingPeriod time, when it fails then I close the connection
> 
> here, something that I don't like is that because I need a select, to take two channels (the ticker channel and the user message channel) I had to build a coroutine to take the _ReadMessage_ and pass the data to the channel _messageChan_ (is this ok?)
> 
> ```go
> func ClientMessageHandler(user *User) {
> 	ws := user.WsConn
> 	ticker := time.NewTicker(pingPeriod)
> 	messageChan := make(chan []byte)
> 
> 	defer func() {
> 		fmt.Println("defer ClientMessageHandler user", user.UserId)
> 		ticker.Stop()
> 		disconnect(user)
> 
> 		if r := recover(); r != nil {
> 			log.Printf("error %v \n %v", r, string(debug.Stack()))
> 		}
> 	}()
> 
> 	// this channel transform the ReadMessage into a channel
> 	go (func() {
> 		defer func() {
> 			fmt.Println("closing ReadMessage goroutine")
> 
> 			if r := recover(); r != nil {
> 				log.Printf("goroutine ReadMessage Error:  %v \n %v)",r, string(debug.Stack()))
> 			}
> 		}()
> 
> 		for {
> 			_, message, err := ws.ReadMessage()
> 
> 			if err != nil {
> 				if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway) {
> 					fmt.Printf("error %v", err)
> 				}
> 
> 				log.Println("read err:", err)
> 				log.Println(message)
> 				break
> 			}
> 
> 			messageChan <- message
> 
> 		}
> 	})()
> 
> 	for {
> 		select {
> 		case <-ticker.C:
> 
> 			// _ = ws.SetWriteDeadline(time.Now().Add(pongWait))
> 
> 			if err := ws.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
> 				fmt.Println("Can't write to socket...disconnecting")
> 				return
> 			}
> 
> 		case message := <-messageChan:
> 
> 			err := ws.SetWriteDeadline(time.Now().Add(pongWait))
> 
> 			if err != nil {
> 				log.Println("error writing deadline: ", err)
> 				break
> 			}
> 
> 			log.Printf("recv: %s", message)
> 			var msg map[string]interface{}
> 			err = json.Unmarshal(message, &msg)
> 			if err != nil {
> 				log.Print(err)
> 			}
> 			log.Println(msg)
> 
> 
> 		}
> 
> 		// _ = ws.WriteJSON(response)
> 	}
> }
> ```
> 
> right now I'm getting a lot of connection/disconnection and it's not enough stable...also when I try to send a message this disconnects...do you think that my code is over complicated or at least is going in the right path?

===========
conn.go->NextReader();
if frameType == TextMessage || frameType == BinaryMessage {
}
Modified to:
if frameType == TextMessage || frameType == BinaryMessage || frameType == PingMessage || frameType == PongMessage{
}

can solve your problem.
good luck.

**Comment by daonb** [comment]
This can be closed

**Comment by timfuhrmann** [comment]
The correct implementation can be found within the examples [here.](https://github.com/gorilla/websocket/blob/master/examples/chat/client.go)

**Comment by BBBao** [comment]
cool
