### ISSUE TITLE
Tries to do a DNS lookup for `user@host` if basic auth specified

### ISSUE THREAD

**Issue by pwaller** [gorilla/websocket#65]
I'm passing secret tokens via `foo@host`, and when I do that I get:

`Fatal: dial tcp: lookup foo@host: no such host`

So did gorilla just leak my secret token via DNS? :)

https://github.com/gorilla/websocket/blob/6fd0f867fef40c540fa05c59f86396de10a632a6/client.go#L102-L134

Is it reasonable to grow support for basic auth?

**Comment by garyburd** [comment]
Basic auth is possible now:

     ws, err := dialer.Dial(u, http.Header{"Authorization": {base64.StdEncoding.EncodeToString([]byte(username + ":" + password))}})

**Comment by pwaller** [comment]
@garyburd yep, and that's what I've done. However, that doesn't change the fact that if you try and use basic auth, it leaks the token via DNS.
