### ISSUE TITLE
[question] how can I close websocket goroutine immediately instead of waiting all the message queue

### ISSUE THREAD

**Issue by 1231sadqwf** [gorilla/websocket#650]
**Describe the problem you're having**
When I have too many message to send in websocket, it will caused my others goroutine cannot work properly, so I want to close the websocket goroutine and restart it
…

**Versions**
> Go version:  go version go1.13.11 linux/amd64

> package version: c3dd95a

…

**"Show me the code!"**
```
func (h *Hub) run() {
	for {
		select {
		case client := <-h.register:
			h.clients[client] = true
		case client := <-h.unregister:
			if _, ok := h.clients[client]; ok {
				delete(h.clients, client)
				close(client.send)
			}
		case message := <-h.broadcast:
			for client := range h.clients {
				if client.see == message.LogName {
					client.send <- message
				}
			}
		case <-h.stop:
			log.Println("Recv stop signal")
			return
		}
	}
}
```
close:
```
hub.close <- true
```
…

**Comment by TaylorRex** [comment]
This question is about Go programming, not about this package.  In any case, you should take a look how [the chat example solves this problem](https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/examples/chat/hub.go#L42-L50). The example uses select with default to avoid blocking a goroutine.

**Comment by 1231sadqwf** [comment]
did anyway to detect a client close the websocket connection?

**Comment by 1231sadqwf** [comment]
> The question is about Go programming, not about this package. In any case, you should take a look how [the chat example solves this problem](https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/examples/chat/hub.go#L42-L50). The example uses select with default to avoid blocking a goroutine.

but in this example, it will keep lose the broadcast message, like my message keep broadcasting, it will caused the client connection close and lose the message during the close time

**Comment by 1231sadqwf** [comment]
is ok, I solved, thank you so much

> The question is about Go programming, not about this package. In any case, you should take a look how [the chat example solves this problem](https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/examples/chat/hub.go#L42-L50). The example uses select with default to avoid blocking a goroutine.
