### ISSUE TITLE
[bug]mutli clients connect server  painc:concurrent write to websocket connection

### ISSUE THREAD

**Issue by zhuyaguang** [gorilla/websocket#651]
**Describe the bug**
> A clear and concise description of what the bug is.

when i run two websocket client to connect the server ,the server is painc 
…

**Versions**
> Go version: `go version` 1.15
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?

… run two client to recive websocket message like the chat examples in source code 
![image](https://user-images.githubusercontent.com/8857976/98906849-cb865580-24f8-11eb-8981-5838d8dd7335.png)

**Expected behavior**
> What output or behaviour were you expecting instead?

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by TaylorRex** [comment]
The application writes concurrently to the websocket connection as stated in the panic message. Concurrent writes are not supported ([documentation](https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency)).

Fix by ensuring that no more than one goroutine writes to the the connection at a time.

In the chat example, the "write pump" goroutine associated with a connection is the only goroutine that writes to the connection.  Your application is not like the chat example.

**Comment by MonicaRJones** [comment]
@zhuyaguang Was your issue resolved? If yes, then please close the issue. If no, please post code that reproduces the issue.
