### ISSUE TITLE
[question] I'm curious how to know by whom the connection was lost.

### ISSUE THREAD

**Issue by Kyocfe** [gorilla/websocket#653]
**Describe the problem you're having**
>I'm developing some kind of simulator that sends messages over a large number of websocket connections to a websocket server.
the code for readpump and writepump is written below.
the execution environment is AWS instance vcpu8, memory 16GB.
I'm thinking about 50k for the number of connections I want.
However, I keep getting the "websocket: close 1000 (normal)" error, but I don't know if the connection was first disconnected from the server due to the load on the server or the load on the client side.
currently, when I connect 5000 connections and read and write messages, the error continues to occur.
how can I fix this?

the max.proc that the go routine can use is set to the maximum, and about 4 goroutines are created per connection.

**Versions**
> Go version: 1.13.9

**Code**
```go
func readPump(liveID int, w *Worker) {
	defer w.conn.Close()
	for {
		_, message, err := w.conn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
				w.errCh <- err
			}
			break
		}

		w.readCh <- message
	}
}

func writePump(liveID int, w *Worker) {
	ticker := time.NewTicker(PingPeriod)
	defer func() {
		ticker.Stop()
		w.conn.Close()
	}()

	for {
		select {
		case msg, ok := <-w.readCh:
			if !ok {
				w.conn.WriteMessage(websocket.CloseMessage, nil)
				return
			}

			err := w.conn.WriteMessage(websocket.TextMessage, msg)
			if err != nil {
				return
			}
		case <-ticker.C:
			if err := w.conn.WriteMessage(websocket.PingMessage, nil); err != nil {
				return
			}
		}
	}
}
```

**Comment by TaylorRex** [comment]
The code in this package only sends close with status 1000 when echoing a close message back to the peer.

The posted application code does not send a close message with status 1000.

From this, we can conclude that the peer sent a close message with status 1000.  Status 1000 is "normal" closure. There's insufficient information to determine why the peer is sending the close message.

The application has code to send a close message with no status. It would be incorrect for the peer to echo that message back with status 1000, but it's possible.  Add some logging where writePump sends the close message to determine if the application is initiating the closing handshake.
