### ISSUE TITLE
Bug or something I am missing?

### ISSUE THREAD

**Issue by kylelopes** [gorilla/websocket#654]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

After (not the same time every time but roughly) an hour and a half of running the readMessage seems to block on all connections despite messages being sent from the front end, connection stays open per the front end. On go side. Nothing is received. I am quite new to golang and coding in general. I would very much appreciate your help.

…

**Versions**
> Go version: `go version`
Go Version 1.14.4
> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

`go func(conn *websocket.Conn) {
		var pongInt int
		var request []byte
		var err error
		for {
			_, request, err = conn.ReadMessage()
			if err != nil {
				_, request, err = conn.ReadMessage()
				if err != nil {
					setVitals("READ", false, connNum, nil)
					log.WithFields(log.Fields{"http.go": 114, "func": "readmessage"}).Warn(err)
					if connMap[connNum].v.wsConn {
						closeWS(conn, "http.go", 116, connNum)
						fmt.Println("close connection on read")
					}
					return
				}
			}
			setVitals("READ", true, connNum, nil)
			msg, info := msgDecode(string(request))

			switch strings.ToUpper(msg) {
			case "PING":
				pongInt++
				fmt.Println("pong increased")
				if connMap[connNum].v.wsConn {
					chanMap[connNum] <- []byte(fmt.Sprintf("{\"pong\": %v}", pongInt))
				}
				//reset timer
				timeOut.Reset(15 * time.Second)
			case "REQUEST":
				if err := json.Unmarshal([]byte(request), &q); err != nil {
					log.WithFields(log.Fields{"http.go": 138, "func": "JSON Unmarshal Request", "more": "reader"}).Warn(err)
				} else {
					qChan <- q
				}
			case "USER":
				userMap = JSONToMap2([]byte(info))
				userChan <- userMap
			case "ADD EVENT":
				if err := json.Unmarshal([]byte(info), &events); err != nil {
					log.WithFields(log.Fields{"http.go": 154, "func": "JSON Unmarshal Add Event", "more": "reader"}).Warn(err)
				} else {
					eventChan <- events
				}
			case "VITALS":
				displayMap[connNum] = connNum
			}
		}
	}(conn)`
> Hint: wrap it with backticks to format it

…

**Comment by TaylorRex** [comment]
It looks like the `displayMap`, `connMap` and `chanMap` are accessed by more than connection goroutine. If so, then the application has data races.  Run the application with the [data race detector](https://golang.org/doc/articles/race_detector.html) and fix the reported problems.

**Comment by TaylorRex** [comment]
> readMessage seems to block on all connections

Each websocket connection is independent of the others.  It's a network issue if all calls to ReadMessage block at the same time.

Confirm that the goroutines are blocked on ReadMessage.  Another possibility is that the goroutines block on a global application resource.

Fix the data races.

**Comment by kylelopes** [comment]
Thank you so much! This was the problem.

**Comment by TaylorRex** [comment]
I commented on three possible fixes.  For my own education, which one fixed the problem?

Please close the issue if your question is answered.

**Comment by kylelopes** [comment]
It was blocking on readMessage() as far as my testing indicates. However fixing the dataraces seemed to have sorted the problem out, The maps were global variables.
