### ISSUE TITLE
[question] making ReadMessage() error out by doing CloseWrite() of TCPConn

### ISSUE THREAD

**Issue by vishnuitta** [gorilla/websocket#659]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

Code snippet:
```
func (dp *DefaultProxy) HandleWebSocket(rw http.ResponseWriter, req *http.Request) {
	vars := mux.Vars(req)
	clientKey := vars["id"]
	url := fmt.Sprintf("%s://%s%s", "ws", vars["host"], vars["path"])
	dialer := websocket.Dialer{
		NetDial: dp.server.Dialer(clientKey, DefaultTimeout),
	}
	proxy, _, err := dialer.Dial(url, nil)
	if err != nil {
		http.Error(rw, err.Error(), http.StatusInternalServerError)
		return
	}
	defer proxy.Close()
	conn, err := defaultUpgrader().Upgrade(rw, req, nil)
	if err != nil {
		http.Error(rw, err.Error(), http.StatusInternalServerError)
		return
	}
	defer conn.Close()
	wg := &sync.WaitGroup{}
	wg.Add(2)
	go wscopy(conn, proxy, wg)
	go wscopy(proxy, conn, wg)
	wg.Wait()
}

// TODO use io.Copy() or some other concept to make it better
func wscopy(src, dest *websocket.Conn, wg *sync.WaitGroup) {
	defer wg.Done()
	for {
		t, b, err := src.ReadMessage()
		if err != nil {
			logrus.Errorf("Closing websocket connection error %s", err)
			closeReadWrite(src)
			closeReadWrite(dest)
			break
		}
		if err := dest.WriteMessage(t, b); err != nil {
			logrus.Errorf("Closing websocket connection error %s", err)
			closeReadWrite(src)
			closeReadWrite(dest)
			break
		}
	}
}
```

For WS proxy implementatin, we have [HandleWebsocket() method](https://github.com/mayadata-io/agent-gateway/blob/master/server/proxy/proxy_impl.go#L96) which reads data from one side connection and writes to other side in both directions. There are two goroutines to do same.

When read/write errors in a goroutine, that goroutine gets completed. But, it need to be informed to other goroutine as well to close the connection. But, other goroutine might be waiting in [ReadMessage()](https://github.com/mayadata-io/agent-gateway/blob/master/server/proxy/proxy_impl.go#L126).

Doing close on the conn can lead to race issues under load conditions where fd can get reallocated, and ReadMessage() might not error out.

So, its safe to perform half close of the connection. As websocket connection doesn't have CloseRead() and CloseWrite() methods, UnderlyingConn() need to be converted to TCPConn and perform CloseRead() and CloseWrite(). 

This is a very usual usecase, but, didn't found much examples around this.

So, I would like to share the approach we took and also would like to know community opinion on this.

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

go 1.14

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by MonicaRJones** [comment]
The standard library ensures that that a `net.Conn` does not use a closed file descriptor.  You can close the connection without concern.

Given the TODO: about using io.Copy, you should take a look at how the standard library's proxy handles websocket connections.  Search for "upgrade" in https://golang.org/src/net/http/httputil/revers to find the relevant code.

**Comment by vishnuitta** [comment]
Thanks @MonicaRJones for the response and the link to look for reverse proxy. I will go through the link.
As you said net.Conn doesn't use a closed file descriptor. But, under load, there are chances that the file descriptor got reallocated and so net.Conn might not return error on any next Read()/Write() calls as fd is still valid. This can lead to unexpected results. I noticed this while I was doing in C, but not verified in Go atleast.

**Comment by MonicaRJones** [comment]
No, an open file descriptor cannot be reallocated. Do not assume that the Go standard library has the same bugs as your C program.

**Comment by vishnuitta** [comment]
> No, an open file descriptor cannot be reallocated. Do not assume that the Go standard library has the same bugs as your C program.

I'm not talking about reallocating open fd :). Sorry if I was not clear with my scenario.
Consider goroutine1 and goroutine2 have access to 'conn' variables (similar to HandleWebSocket and two wscopy routines in above snippets). If goroutine1 closes the 'conn', and, by the time goroutine2 does the 'ReadMessage', there are chances that the same fd that got closed in goroutine1 got reallocated. So, goroutine2 shouldn't see the error when it does 'ReadMessage'.

Sequence of steps:
1. goroutine1 and goroutine2 have access to 'conn'.
2. goroutine1 closed 'conn'.
3. some other goroutine like goroutine3 created a 'conn' whose fd happened to be same as that of 'conn' in step 1 (this is possible in loaded setups with high context switches) (note that 'conn' is closed in step2)
4. goroutine2 does the 'ReadMessage' call on the 'conn' that it have access to.
Above sequence of steps leads to unexpected results.

**Comment by vishnuitta** [comment]
Above sequence of steps leads to problem in C for sure.
I'm not sure whether Go does any magic in this case similar to its 'Escape Analysis'.

**Comment by MonicaRJones** [comment]
See  [fd_mutex.go](https://golang.org/src/internal/poll/fd_mutex.go).  The standard library ensures that that a net.Conn does not use a closed file descriptor. You can close the connection without concern.

**Comment by MonicaRJones** [comment]
The documentation for [net.Conn Close](https://godoc.org/net#Conn.Close) says:

> Close closes the connection. Any blocked Read or Write operations will be unblocked and return errors.

There is no caveat for a system under load.

**Comment by vishnuitta** [comment]
> The documentation for [net.Conn Close](https://godoc.org/net#Conn.Close) says:
> 
> > Close closes the connection. Any blocked Read or Write operations will be unblocked and return errors.
> 
> There is not a caveat for a system under load.

Appreciate for all the discussion @MonicaRJones.
My worry as well is related to above message. It clearly says about blocked Read or Write operations, but, not about the operations that are going to happen.

Going back to the sequence of steps that I mentioned:
- If in step1, goroutine2 is blocked on either Read or Write operation, as mentioned in the documentation of net.Conn, it gets unblocked with error.

But, in my case, in step4 only, goroutine2 made ReadMessage() call which is after Close() in step2.

I'm making an attempt to explain the steps with more details and context switches in between:
1. goroutine1 and goroutine2 have access to 'conn'. (consider goroutine2 as wscopy as per above code snippet)
2. goroutine2 completed WriteMessage(), checked that no error happened and just before doing ReadMessage(), context switch happened and goroutine2 got kicked out. 
3. goroutine1 closed 'conn'.
4. some other goroutine like goroutine3 created a 'conn' whose fd happened to be same as that of 'conn' in step 1 (this is possible in loaded setups with high context switches) (note that 'conn' is closed in step2)
5. goroutine2 got the chance, and done 'ReadMessage' call on the 'conn' that it have access to.
This should lead to unexpected results.

**Comment by MonicaRJones** [comment]
Let's look at the code in [fd_mutex](https://golang.org/src/internal/poll/fd_mutex.go) to see how the scenario is handled.

3.  Close calls [fdMutex.increfAndClose](https://github.com/golang/go/blob/3298300ddf45a0792b4d8ea5e05f0fbceec4c9f9/src/internal/poll/fd_mutex.go#L71).  This method sets a [flag](https://github.com/golang/go/blob/3298300ddf45a0792b4d8ea5e05f0fbceec4c9f9/src/internal/poll/fd_mutex.go#L26) in the mutex indicating that the file descriptor is not available for read or write.
4. Some other goroutine creates a connection with the same file descriptor.
5. Read calls [fdMutex.incRef](https://github.com/golang/go/blob/3298300ddf45a0792b4d8ea5e05f0fbceec4c9f9/src/internal/poll/fd_mutex.go#L53) to get access to the file descriptor. fdMutex.incRef returns false because the file descriptor is no longer available to the fdMutex.  Read returns an error.  Read does not use the file descriptor.  There are no unexpected results.

**Comment by vishnuitta** [comment]
thanks for all the explanation @MonicaRJones. fdMutex and its related methods cleared my question.
Once again, thanks for your time.
