### ISSUE TITLE
[question]  why websocket client force url to be start with wss or wss, 

### ISSUE THREAD

**Issue by nnn-gif** [gorilla/websocket#664]
**Describe the problem you're having**
 
on client.go

    ````

	switch u.Scheme {
	case "ws":
		u.Scheme = "http"
	case "wss":
		u.Scheme = "https"
	default:
		return nil, nil, errMalformedURL
	}

````

if websocket url containers https this code block returns errMalformedURL, shouldn't   case "https": and case "HTTP": added over here

…

**Versions**
> Go version: `go version`
go version go1.14.2 darwin/amd64

> package version: run `git rev-parse HEAD` inside the repo
b65e62901fc1c0d968042419e74789f6af455eb9

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by MonicaRJones** [comment]
The dial method rejects URLs with `http` or `https` schemes because the dial method does no support the HTTP protocol.  It's the same reason that the dial method rejects URLs with `ftp`,  `gopher` and other schemes.   The dial method does not support the FTP,  Gopher,  etc.

**Comment by mind1949** [comment]
First of all, two schemes are defined in the rfc of websocket: ws and wss. Secondly, through scheme: ws or wss, some network middleware (such as proxy) can identify which request is websocket

**Comment by mind1949** [comment]
I think it is okay not to force it. But it is relatively simple to force ws and wss.

**Comment by MonicaRJones** [comment]
Is  your question answered? If yes, close the issue. If no, please post a followup to my comment.
