### ISSUE TITLE
[question] Can I use PreparedMessage for control frames?

### ISSUE THREAD

**Issue by System-Glitch** [gorilla/websocket#666]
**Describe the problem you're having**
I am wondering if I can use a PreparedMessage for the close message. Does it make sense too? I searched for that in the docs and on google but I'm not entirely sure.

**Versions**
Go version: `go version go1.15.6 linux/amd64`

package version: `v1.4.2`

**"Show me the code!"**
```go
pm, _ = ws.NewPreparedMessage(ws.CloseMessage, ws.FormatCloseMessage(ws.CloseInternalServerErr, "Internal server error"))

//...

err := c.WritePreparedMessage(pm)
```

**Comment by MonicaRJones** [comment]
Yes, you can you can prepare a close message.  

There's no benefit to preparing a close messages because control messages are not compressed.

**Comment by System-Glitch** [comment]
Thank you for your response!
