### ISSUE TITLE
Proper way to handle unicast + broadcast back to client with the chat example?

### ISSUE THREAD

**Issue by G2G2G2G** [gorilla/websocket#668]
https://github.com/gorilla/websocket/blob/master/examples/chat/client.go#L56

I have edited the above "readPump" to add a unicast or multiple unicast+broadcast based on the read information, is this the proper way? It works however I have ran into tons of issues with other webserver examples (in Go and other languages) and get Concurrency panics, write errors, random disconnections etc. The program is used by company employees but currently crashes randomly from concurrency issues so I am looking at replacing it. It's very simple, browsers send a request, and the messages are either broadcasted to everyone or if they fit a certain case in the switch, it does something special (responds, responds and broadcasts.. broadcasts multiple things, responds multiple things)

I showed all of the examples in the switch statement, is this safe?
Thanks

```Go
func (c *Client) readPump() {
	defer func() {
		c.hub.unregister <- c
		c.conn.Close()
	}()
	c.conn.SetReadLimit(maxMessageSize)
	c.conn.SetReadDeadline(time.Now().Add(pongWait))
	c.conn.SetPongHandler(func(string) error { c.conn.SetReadDeadline(time.Now().Add(pongWait)); return nil })
	for {
		_, message, err := c.conn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
				log.Printf("error: %v", err)
			}
			break
		}
		message = bytes.TrimSpace(bytes.Replace(message, newline, space, -1))
		v, _ := strconv.ParseInt(string(message), 10, 64)
		log.Println(v)
		switch v {
		case 1:
			log.Println("sent one")
			c.send <- []byte("one")
		case 2:
			log.Println("sent 2")
			c.send <- message
		case 3:
			log.Println("sent 3")
			c.send <- []byte("special 3 info")
			c.send <- []byte("special 3 info2")
			c.hub.broadcast <- []byte("3 info to all")
		case 4:
			log.Println("sent 4")
			c.send <- []byte("special 4 info")
			c.send <- []byte("special 4 info2")
			c.hub.broadcast <- []byte("4 info to all")
			c.hub.broadcast <- []byte("4 info to all2")
		default:
			c.hub.broadcast <- message
		}

	}
}
```

**Comment by MonicaRJones** [comment]
I don't see any obvious problems with the code.
