### ISSUE TITLE
How is this a buffered channel?

### ISSUE THREAD

**Issue by G2G2G2G** [gorilla/websocket#670]
https://github.com/gorilla/websocket/blob/master/examples/chat/client.go#L47

I read a lot of tutorials, all buffered channels seem to be in a make(chan, buffernumber) but I cannot find any examples that say they're buffered inside of a struct using that method. Is there a place to read that?

**Comment by MonicaRJones** [comment]
Yes, you can read that in the official [The Go Programming Language Specification](https://golang.org/ref/spec#Channel_types).  The quote from the specification is:

> The capacity, in number of elements, sets the size of the buffer in the channel. If the capacity is zero or absent, the channel is unbuffered and communication succeeds only when both a sender and receiver are ready. Otherwise, the channel is buffered and communication succeeds without blocking if the buffer is not full (sends) or not empty (receives). A nil channel is never ready for communication.
