### ISSUE TITLE
[question] ReadJSON not adhering to readdeadline

### ISSUE THREAD

**Issue by jamil-baz** [gorilla/websocket#672]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
In a short code form:
```
...
c.conn.SetReadDeadline(time.Time{})
err := c.conn.ReadJSON(&contestMessage)
...
```
However, after about 1 minute, I will see this error returned by `ReadJSON`,  `read tcp [::1]:8080->[::1]:53948: use of closed network connection` with error of type: `*net.OpError`. I imagine this is related to a timeout, since using [websocat](https://github.com/vi/websocat), with verbosity, right before the error on the backend, I see the following errors on the client:
```
[DEBUG websocat::ws_peer] incoming None
[DEBUG websocat::my_copy] BrokenPipe: read_done
[DEBUG websocat::my_copy] done
```

Not too sure what I am doing wrong or if this error is caused by something other than the `ReadJSON` method timing out. I am testing with one client, backend is not overloaded.

**Versions**
> Go version: `go version`
go version go1.13 darwin/amd64

> package version: run `git rev-parse HEAD` inside the repo

go mod shows version 1.4.2

**Comment by MonicaRJones** [comment]
The error message indicates that the connection was closed, not that read timed out.

**Comment by jamil-baz** [comment]
@MonicaRJones sorry I pasted the wrong message: `write tcp [::1]:8080->[::1]:54267: i/o timeout` and I think it's actually during the `setWriteDeadline` and I only call it right now when the `ping` ticker fires, however after about 1 minute it times out. 
```
case <-ticker.C:
	c.conn.SetWriteDeadline(time.Now().Add(writeWait))
	if err := c.conn.WriteMessage(websocket.PingMessage,nil); err != nil {
		fmt.Printf("error sending ping %v\n", err)
		return
        }
```

`writeWait` is 10 seconds.

**Comment by MonicaRJones** [comment]
Are you saying that ReadJSON returns the error `write tcp [::1]:8080->[::1]:54267: i/o timeout`?

**Comment by MonicaRJones** [comment]
@jamil-baz it is clear what the problem is.  Which method call returns an error and what is that error?
