### ISSUE TITLE
 write tcp xxxx:52208->xxxx:443: write: broken pipe[bug] 

### ISSUE THREAD

**Issue by gomathisolai16** [gorilla/websocket#673]
> Am integrating websocket connection , opening a connection before for loop array starts.
While running it breaks for some values. Getting differerent errors like  write tcp 192.168.225.137:52208->94.156.219.148:443: write: broken pipe  , websocket close sent , unexpected end of file. How to find the connection got closed or how to handle these errors
…

**Versions**
> Go version: `1.14.1`
> 

…

**Steps to Reproduce**
> How can the bug be triggered?

…

**Expected behavior**
> What output or behaviour were you expecting instead?

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by MonicaRJones** [comment]
About the errors:

- write broken pipe:  The peer closed the underlying TCP connection.  
- websocket close sent: Either the application sent a close message or a close message was received and echoed back to the peer.  
- unexpected end of file:  I don't know about this one. Is the application calling ReadJSON?  If so, it might be coming from there.

How to handle the errors:  Close the connection and release any resources associated with the connection.

How to prevent the errors:  Two of the errors can be result of the peer closing the connection.  There's insufficient information in the issue to know why the peer closed the connection, but closing a connection is a normal thing to do.

**Comment by gomathisolai16** [comment]
@MonicaRJones thanks for your suggestions. I have to reuse the websocket connection for loop values . But after 4 or 5 loop am getting those error. Before opening new  connection how can i know  connection got closed? Is there any function available in gorilla websocket. Am new to websocket integration, can you please advice ?

**Comment by MonicaRJones** [comment]
With the exception of squelching log noise, the application should not distinguish close errors from other errors.  For all errors, the application should close the connection and release resources associated with the connection.

**Comment by gomathisolai16** [comment]
> With the exception of squelching log noise, the application should not distinguish close errors from other errors. For all errors, the application should close the connection and release resources associated with the connection.

without checking websocket connection status, can we close the connection ?

**Comment by MonicaRJones** [comment]
Call the [Close](https://pkg.go.dev/github.com/gorilla/websocket#Conn.Close) method to close a connection.  It is safe to call Close() on a closed connection.  

It is within the application's power to avoid calling Close() more than once because it is the application that calls the method.  Because it's safe to call Close() on a closed connection, it's not worth the extra work to prevent extra calls.

The call to Close() closes the the underlying network connection.  This must be done even if the application sent a close message to the peer or the peer closed its end of the TCP connection.
