### ISSUE TITLE
[question] How to avoid messages concatenating upon writing multiple small messages one after another? 

### ISSUE THREAD

**Issue by Mehdzor** [gorilla/websocket#676]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

I've multiple calls of:
`connection.WriteMessage(messageType, data)`
One right after another. 

Each 'data' contains a few (between 2 to 5) bytes of information. 
And then when I call `connection.ReadMessage()` on the receiving side, the messages get concatenated into one. 

How can I avoid that? The only workaround I've found so far is to add 10 ms pauses between writes. 
…

**Versions**
> Go version: 1.16.0

> package version: 6bd177179fd4f2ef713ef8f0f5eabd75cdceb305

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise, we're left guessing!

Sending:
```
data := []byte{1,2,3}
connection.WriteMessage(messageType, data)
connection.WriteMessage(messageType, data)
connection.WriteMessage(messageType, data)
```

Receiving:
```
for {
	_, message, err := c.conn.ReadMessage()
        // message contains all the messages combined
}

```

> Hint: wrap it with backticks to format it

…

**Comment by MonicaRJones** [comment]
Please post more information on how to reproduce the problem.

The package is written to write one websocket message for each call to WriteMessage and to read one websocket message for each call to ReadMessage.

Here's an example of code that works as expected.

```
package main

import (
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"

    "github.com/gorilla/websocket"
)

func makeWsProto(s string) string {
	return "ws" + strings.TrimPrefix(s, "http")
}


var upgrader websocket.Upgrader

func main() {

	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		c, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			log.Println(err)
			return
		}
		defer c.Close()
		for {
			_, p, err := c.ReadMessage()
			if err != nil {
				log.Println(err)
				return
			}
			fmt.Printf("message %x\n", p)
		}
	}))

	w, _, err := websocket.DefaultDialer.Dial(makeWsProto(s.URL), nil)
	if err != nil {
		log.Fatalf("Dial: %v", err)
	}
	defer w.Close()
	messageType := websocket.BinaryMessage
	data := []byte{1, 2, 3}
	w.WriteMessage(messageType, data)
	w.WriteMessage(messageType, data)
	w.WriteMessage(messageType, data)
	w.WriteMessage(websocket.CloseMessage, nil)
	for {
		_, _, err := w.ReadMessage()
		if err != nil {
			return
		}
	}
}
```

**Comment by Mehdzor** [comment]
@MonicaRJones, the issue that for a few calls of WriteMessage, I'm getting a single call of ReadMessage that contains data for all of them in a single read. I'll prepare an example and attach it.

**Comment by Mehdzor** [comment]
Nvm, it was a channel overflow somewhere in my code. Thanks for helping to figure it out.
