### ISSUE TITLE
[question] connect: cannot assign requested address

### ISSUE THREAD

**Issue by csdenboer** [gorilla/websocket#678]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

I'm trying to load test a WebSocket server. However, after setting up ~28k connections the applications exits with the following message:

2021/03/31 12:30:13 dial:dial tcp xx.xxx.xx.xxx:80: connect: cannot assign requested address

ulimit -n
1024000

Why is this happening? How can I solve this?

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

github.com/gorilla/websocket v1.4.2
go version go1.15.8 linux/amd64

**Comment by elithrar** [comment]
How many ephemeral ports are allowed?

61000 - "28000" = 33,000 (likely: 32,768) - with 32,768 - 61,000 being the default ephemeral range in most Linux distros.

If you are load testing from a single VIP, the number of FDs (as described in your ulimit output) is only one factor. Each port is consumed by a unique (src, dst, port) tuple. In the "real" world, 28000 clients would each be a unique src, but that is not the case when you load test from a single machine.

See https://stackoverflow.com/questions/28573390/how-to-view-and-edit-the-ephemeral-port-range-on-linux for details on how to check and increase the range. Servers commonly run from 15,000 - 61,000, but
