### ISSUE TITLE
Testing the examples

### ISSUE THREAD

**Issue by geoah** [gorilla/websocket#68]
I've just started playing around with gorilla/websocket and more specifically started off with the chat example as the channels seemed like the best choice for ws.
Everything is working just fine, but I can't figure out how to go about testing this.

I'm fairly new to golang and testing something like this just feels weird.
Would it be possible to get a sample test suite for the chat example, or maybe some pointers at to where I should start from?

Thank you very much in advance! :)

**Comment by mistercorea** [comment]
Yea i am on the same boat BTW on home.html - appendLog function has some missing ";"
```javascript
 function appendLog(msg) {
        var d = log[0]
        var doScroll = d.scrollTop == d.scrollHeight - d.clientHeight;
        msg.appendTo(log)
        if (doScroll) {
            d.scrollTop = d.scrollHeight - d.clientHeight;
        }
    }
```
should be
```javascript
function appendLog(msg) {
        var d = log[0];
        var doScroll = d.scrollTop - 1 < d.scrollHeight - d.clientHeight;
        msg.appendTo(log);
        if (doScroll) {
            d.scrollTop = d.scrollHeight - d.clientHeight;
        }
    }

```
so any updates made to screen will appear last item / latest message

**Comment by garyburd** [comment]
The file [client_server_test.go](https://github.com/gorilla/websocket/blob/master/client_server_test.go) is a good starting point for writing tests.  The tests in that file uses the [httptest](https://godoc.org/net/http/httptest) package to run a server in process and connect to it.
