### ISSUE TITLE
Why does NewPreparedMessage initially make a "plain server" frame

### ISSUE THREAD

**Issue by Bios-Marcel** [gorilla/websocket#681]
**EDIT**

So the reason this confused me, is because we are actually keeping that frame in memory.
If I see correctly, this is only required in order to copy the data once.
Shouldn't we then simply dereference the data afterwards so the GC can collect it?
Alternatively we could just create the frame without even saving it.

---

In prepared.go, we create a `prepareKey` which has `compression` set to `false`.

https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/prepared.go#L43-L60

As far as I understand, this frame will not be accessed, if the connections that we send the prepared message over, is using compression, since in conn.go we'll potentially call ´PreparedMessage.frame´ with a different `compression` value, causing it to create a new frame.

https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/conn.go#L728-L747

Now, if all my connections are using compression, isn't this a waste of memory and CPU time?

If so, I'd like to make a PR in order to improve this.

**Comment by MonicaRJones** [comment]
There are a couple of issues with using the caller's slice:

-  Application's that reuse buffers passed to NewPreparedMessage may rely on the fact that the function makes its a copy of the caller's data.
- Client connections mask the data.  Scribbling on an application's buffer can break applications that assume that the caller's buffer is not modified.

I don't understand the comment about GC.  All of the data associated with the prepared message will be collected.

**Comment by Bios-Marcel** [comment]
I see. Uhm, might've been a bit confused. I also forgot that slices are just views on arrays so I guess we aren't duplicating the data anyways :D

Thanks
