### ISSUE TITLE
[question] Question about the "Chat example" present in the code. Why isn't the map of the "hub" structprotected with Mutex?

### ISSUE THREAD

**Issue by EnricoPicci** [gorilla/websocket#682]
**Question**
In the Chat example, the `clients` map of the [hub](https://github.com/gorilla/websocket/blob/master/examples/chat/hub.go) is not protected by a synchronization mechanism like a Mutex. I understand that concurrent inserts and concurrent deletes are avoided by the fact that they are performed using a channel for inserts and a channel for deletes. But wouldn't it be possible that one insert and one delete operation happen concurrently?

**Comment by MonicaRJones** [comment]
There is no concurrent access to the map, therefore no mutex is required.

See [these lines of code](https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/examples/chat/main.go#L31).  The map is created in `newHub()`.  From that point on, the only access to the map is from the hub goroutine `go hub.run()`.

**Comment by EnricoPicci** [comment]
Thanks, now I think I can see how it works.
If the goroutine is processing a message coming from `register` channel it can not, at the same time, process a message coming from the `unsubscribe` channel. And viceversa.
As always it is clear ... after

**Comment by MonicaRJones** [comment]
The [memory model](https://golang.org/ref/mem#tmp_2) tells us:

> Within a single goroutine, reads and writes must behave as if they executed in the order specified by the program.

It follows that a goroutine cannot independently execute the cases in a select. 

Please close the issue if your question was answered.
