### ISSUE TITLE
[question] golang 1.15.0 fork/exec /usr/bin/ssh: Setctty set but Ctty not valid in child

### ISSUE THREAD

**Issue by iutx** [gorilla/websocket#683]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
There some errors when i change golang version from 1.13 -> 1.15
```shell
fork/exec /usr/bin/ssh: Setctty set but Ctty not valid in child
```
**Versions**
> Go version: `go version`
>1.15.0
> package version: run `git rev-parse HEAD` inside the repo
v1.4.2
**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by MonicaRJones** [comment]
How is the problem related to this package?  Are you using a [network dialer](https://pkg.go.dev/github.com/gorilla/websocket#Dialer.NetDialContext) that tunnels through ssh or something?
