### ISSUE TITLE
How can I get real "Remote Address" when there's nginx In front of the server?

### ISSUE THREAD

**Issue by rainfall2000** [gorilla/websocket#684]
How can I get real "Remote Address" when there's nginx In front of the server?

Here is part of nginx setting:
upstream wss_svr2 {
    server 127.0.0.1:15032 weight=1;
}
location / {            
                proxy_redirect off;
                proxy_pass http://wss_svr2;
                proxy_set_header Host $host;
                proxy_set_header X-Real_IP $remote_addr;
                proxy_set_header X-Forwarded-For $remote_addr:$remote_port;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection upgrade;
                proxy_ssl_server_name on;
                proxy_ssl_name "...";
        }

I always get "127.0.0.1"

**Comment by MonicaRJones** [comment]
Do it the same as you would for a plain HTTP request: configure the proxy to set a header with the real remote address, use that header in the handler to get the real remote address.

You already configured the proxy to set the X-Forwarded-For header with the real remote address.  Use this code to get the value fo the header where `req` is the `*http.Request`.

     remoteAddr := req.Header.Get("X-Fowarded-For")

**Comment by rainfall2000** [comment]
@MonicaRJones Thanks.

**Comment by MonicaRJones** [comment]
@rainfall2000 Did I answer your question? If yes,please close the issue.
