### ISSUE TITLE
How  to create  a websocket client with POST

### ISSUE THREAD

**Issue by huntercsw** [gorilla/websocket#689]
**Describe the problem you're having**
My requirement is create a websocket client with POST, and add request body.
But I only find method to create a client with GET, and I can not modify req in Dial()
```
func (d *Dialer) DialContext(ctx context.Context, urlStr string, requestHeader http.Header) (*Conn, *http.Response, error) {
      ... ...
       req := &http.Request{
		Method:     "GET",
		URL:        u,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		Header:     make(http.Header),
		Host:       `u.Host,`
	}
       ... ...
}
```
…

What should I do. Thanks!

**Versions**
> Go version: 1.13

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…
``

**Comment by MonicaRJones** [comment]
A websocket handshake mimics an HTTP GET request.   It is not possible to include a request body in the client’s handshake.   See the RFC for details.  

https://datatracker.ietf.org/doc/html/rfc6455#section-1.3
