### ISSUE TITLE
Example chat code not working

### ISSUE THREAD

**Issue by lokewate** [gorilla/websocket#69]
Not sure if I am doing something wrong, but the example code seems to be broken. Multiple issues:

In the HTML file:
1) The jquery lib url is no longer valid.

2) At the point of websocket creation, I get the following error
`WebSocket connection to 'ws://%7B%7B%24%7D%7D/ws' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`

3) When I fix the address as `ws://localhost:8080/ws`, I get:
`WebSocket connection to 'ws://localhost:8080/ws' failed: Error during WebSocket handshake: Unexpected response code: 403`
Server side I get `websocket: origin not allowed`, which seems to be coming coz the protocol is not set to http.

4) If I set the protocol to `http`, I get 
`Uncaught SyntaxError: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http' is not allowed.`

Would appreciate any help on this. I am also trying to use gorilla on server side and have a mobile app communicate with the server. Is there a way to connect to the server without upgrading an http connection? Can I directly connect through `ws://`? I can't seem to find any help online on this.

**Comment by garyburd** [comment]
To use the example, open http://localhost:8080/ in the browser.  You cannot open home.html directly.

**Comment by garyburd** [comment]
>  I am also trying to use gorilla on server side and have a mobile app communicate with the server. Is there a way to connect to the server without upgrading an http connection?

The upgrade from an HTTP connection is part of the WebSocket protocol. It is not possible to eliminate this step.

Why are you considering using WebSockets instead of opening a TCP connection directly?

**Comment by lokewate** [comment]
Thanks, I should be using TCP directly.
