### ISSUE TITLE
Deafult PingHandler will miss to send a pong message sometimes?[question] 

### ISSUE THREAD

**Issue by alice0ch** [gorilla/websocket#690]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/19197232/118305507-a65fb780-b51a-11eb-9721-d993e9ed2356.png)
server sends a ping msg every 1 second but client only replies the first ping
client uses the default ping handler
…

**Versions**
> Go version: `go version`
go 1.15
> package version: run `git rev-parse HEAD` inside the repo
github.com/gorilla/websocket v1.4.2
…

**"Show me the code!"**
> 
server:
ticker := time.NewTicker(time.Second)
defer ticker.Stop()
for {
                ... 
		select {
		case <-ticker.C:
			if err := c.Conn.Conn.WriteMessage(websocket.PingMessage, nil); err != nil {
				log.WithFields(log.Fields{"uid": c.Conn.UserID, "clientip": c.Conn.FromIP}).Error("ping err:", err)
				return
			}
		default:
			select {
			case m := <-c.sendCh:
				c.writeMessage(m)
			default:
			}
		}
	}
> Hint: wrap it with backticks to format it

…

**Comment by MonicaRJones** [comment]
The default ping handler [writes the pong](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/conn.go#L1132) with [a timeout of one second](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/conn.go#L34).

The pong is lost if the connection is busy for a second  or more.

**Comment by alice0ch** [comment]
> The default ping handler [writes the pong](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/conn.go#L1132) with [a timeout of one second](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/conn.go#L34).
> 
> The pong is lost if the connection is busy for a second or more.

![image](https://user-images.githubusercontent.com/19197232/118346406-b05ed600-b56d-11eb-9a88-fc221b3789b8.png)

the connection is not busy, but no pong msg to server

**Comment by MonicaRJones** [comment]
I cannot comment on that because the images are difficult for me to read.  

To find out what's going on, set a ping handler that logs:

    c.SetPingHandler(func(message string) error {
            err := c.WriteControl(PongMessage, []byte(message), time.Now().Add(time.Second))
            if err == websocket.ErrCloseSent {
                log.Print("PING received after close")
                return nil
            } else if e, ok := err.(net.Error); ok && e.Temporary() {
                log.Print("PING received, PONG discarded because timeout")
                return nil
            }
            log.Print("PING received, PONG sent")
            return err
        })

**Comment by alice0ch** [comment]
已经解决了
