### ISSUE TITLE
trace.GotConn should not be called if dial fails [bug] 

### ISSUE THREAD

**Issue by rittneje** [gorilla/websocket#693]
Currently this library unconditionally invokes the httptrace.ClientTrace GotConn callback after dialing.
https://github.com/gorilla/websocket/blob/b65e62901fc1c0d968042419e74789f6af455eb9/client.go#L291-L299

However, the documentation from httptrace specifically states that it will only be called after a successful dial. https://pkg.go.dev/net/http/httptrace#ClientTrace
```go
	// GotConn is called after a successful connection is
	// obtained. There is no hook for failure to obtain a
	// connection; instead, use the error from
	// Transport.RoundTrip.
	GotConn func(GotConnInfo)
```

Consequently, this library should do the error check first.

**Comment by rittneje** [comment]
ping @elithrar

**Comment by elithrar** [comment]
Please don't ping me @rittneje - unless there is a PR to merge, this doesn't seem like an urgent bug.

(Note that we are only merging fixes best effort at this point)
