### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by dcupwork** [gorilla/websocket#694]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

Constantly recieving error TLS handshake error from *.32.208.165:3870: remote error: tls: unknown certificate

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

1.15

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

```
package main

import (
	"flag"
	"log"
	"net/http"

	"github.com/gorilla/websocket"
)

//var addr = flag.String("addr", "localhost:8080", "http service address")

var upgrader = websocket.Upgrader{} // use default options

func echo(w http.ResponseWriter, r *http.Request) {
	c, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Print("upgrade:", err)
		return
	}
	defer c.Close()
	for {
		mt, message, err := c.ReadMessage()
		if err != nil {
			log.Println("read:", err)
			break
		}
		log.Printf("recv: %s", message)
		err = c.WriteMessage(mt, message)
		if err != nil {
			log.Println("write:", err)
			break
		}
	}
}


func main() {
	flag.Parse()
	log.SetFlags(0)
	http.HandleFunc("/echo", echo)
	http.HandleFunc("/", home)
	log.Fatal(http.ListenAndServeTLS(":8080", "server.crt", "server.key", nil))
}
````
> Hint: wrap it with backticks to format it

…
I have got commercial version of CA issued to a domain name. I'm trying to send request from chrome to the server and this with no luck. what I do incorrect?

**Comment by elithrar** [comment]
"Unknown certificate" usually means the certificate is invalid or in the wrong format. Can you confirm it is correct, and consult the net/http documentation for valid certificates?

You should be able to check that the certificate is valid with curl - e.g. `curl -svo /dev/bull https://IP_ADDRESS:PORT`

**Comment by elithrar** [comment]
https://golang.org/pkg/net/http/#ListenAndServeTLS

> ListenAndServeTLS acts identically to ListenAndServe, except that it expects HTTPS connections. Additionally, files containing a certificate and matching private key for the server must be provided. **If the certificate is signed by a certificate authority, the certFile should be the concatenation of the server's certificate, any intermediates, and the CA's certificate**.

**Comment by dcupwork** [comment]
Certificate authority is unknown. how can I fix it?

* Expire in 0 ms for 6 (transfer 0x561b197f2fb0)
*   Trying 10.128.0.6...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x561b197f2fb0)
* Connected to 10.128.0.6 (10.128.0.6) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [58 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1566 bytes data]
*http: TLS handshake error from 10.128.0.6:35308: remote error: tls: unknown certificate authority
 TLSv1.2 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
http: TLS handshake error from *.147.123.39:55186: tls: first record does not look like a TLS handshake

can you please explain in more details how to do this **If the certificate is signed by a certificate authority, the certFile should be the concatenation of the server's certificate, any intermediates, and the CA's certificate.**

**Comment by dcupwork** [comment]
I have trying to add CA to /usr/local/share/ca-certificates/ 
then ` sudo update-ca-certificatessudo update-ca-certificates` 
it is not helps

**Comment by dcupwork** [comment]
after combined certificates I have got following output with `curl -svo /dev/null https://IP_ADDRESS:PORT`

`* Expire in 0 ms for 6 (transfer 0x564634fe1fb0)
*   Trying 10.128.0.6...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x564634fe1fb0)
* Connected to 10.128.0.6 (10.128.0.6) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [58 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3684 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=montre.es
*  start date: May 31 00:00:00 2021 GMT
*  expire date: May 30 23:59:59 2022 GMT
*  subjectAltName does not match 10.128.0.6
* SSL: no alternative certificate subject name matches target host name '10.128.0.6'
* Closing connection 0`

it looks ok, but with request from chrome to the server error stays at the same place

**Comment by dcupwork** [comment]
I'm trying add CA to /usr/local/share/ca-certificates/
then `sudo update-ca-certificates`
it isn't helps

**Comment by dcupwork** [comment]
it works! thanks a lot
