### ISSUE TITLE
[question] Websocket server doesn't recieve more than 1 request

### ISSUE THREAD

**Issue by CypherpunkSamurai** [gorilla/websocket#695]
**Describe the problem you're having**
> I'm trying to send stdin and stdout of a exec.Cmd object to websocket client. The server stops after recieving 1 message. Please help.

…

**Versions**
> Go version: `go1.16.3`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> https://play.golang.org/p/TWzC5AIaXhE

> Hint: wrap it with backticks to format it

…

**Comment by MonicaRJones** [comment]
The `handle_stdin` function returns after reading a single message.  To read more than one message, wrap the contents of the function with a loop.

**Comment by CypherpunkSamurai** [comment]
Ok. I'll try it out and reply back. Also thanks for that fast feedback, really appreciate the help :)

**Comment by CypherpunkSamurai** [comment]
Thanks a lot @MonicaRJones :) It solved the issue, and my time searching other's repo's. This library is so widely used, it should have a good github.io documentation and quickstart page

Also, if you don't mind, can you suggest a better way to handle a disconnect check? My server currently stops abruptly after client disconnects

**Comment by MonicaRJones** [comment]
>  It solved the issue, and my time searching other's repo's.

Search this repo!  The  [command example](https://github.com/gorilla/websocket/tree/master/examples/command) matches your scenario. 

> good github.io documentation and quickstart page

The package is fully documented in the usual places for Go packages: [pkg.go.dev](https://pkg.go.dev/github.com/gorilla/websocket),  [godocs.io](https://godocs.io/github.com/gorilla/websocket).  The overview includes a quick start.

**Comment by CypherpunkSamurai** [comment]
I actually did lookup the example included, it felt a little too uncomfortable as i'm still not yet that good at golang. 

Also i did lookup golang package repos, but it's all syntaxes and few examples. I meant the package should have it's own quickstart guide for each method like other packages do.

**Comment by CypherpunkSamurai** [comment]
Ok. Anyway Thanks for the help :)

Closing this issue

**Comment by MonicaRJones** [comment]
> This library is so widely used, it should have a good github.io documentation and quickstart page

> I meant the package should have it's own quickstart guide for each method like other packages do.

The developers of this package are under no obligation to provide more documentation. 

It's unclear what additional documentation would have helped you.  It's not the job of this package to explain that a `for` loop is required to repeat a block of code.  An existing example matches your scenario. 

Your comments imply that the package documentation does not meet expected standards for Go packages.  There's always room for improvement with the documentation, but the documentation is at least adequate and perhaps good compared to other packages in the ecosystem.

(I am not a developer of this package and do not speak for them.)
