### ISSUE TITLE
[feature] Support x-webkit-deflate-frame

### ISSUE THREAD

**Issue by ejain** [gorilla/websocket#696]
Some browsers (e.g. Safari) send `Sec-WebSocket-Extensions: x-webkit-deflate-frame` instead of the (now standard) `permessage-deflate`. The behavior should be identical, otherwise.

**Comment by MonicaRJones** [comment]
@ejain Please share a link to the x-webkit-deflate-frame specification if you have one.  Based on the names alone, it seems like extensions do different things (compress one frame at a time vs. compress the concatenation of the frame data).

**Comment by ejain** [comment]
See comments on https://github.com/websockets/ws/issues/940, but it could be random luck that this works.

**Comment by MonicaRJones** [comment]
@ejain Thank you for the reference to the issue.  Because a popular browser uses the extension, this issue should remain open.

**Comment by ejain** [comment]
As of iOS 15, Safari defaults to using _NSURLSession Websocket_, which uses the standard `permessage-deflate` headers, not `x-webkit-deflate-frame`. This new implementation doesn't work with gorilla/websocket (and likely other backends) as it fails when larger messages are split, but that's another issue...

**Comment by imankur** [comment]
@ejain `This new implementation doesn't work with gorilla/websocket` - any idea what can be the fix for this?
