### ISSUE TITLE
[question]Don't you need to consider whether len() is thread safe at this point?

### ISSUE THREAD

**Issue by SilkageNet** [gorilla/websocket#699]
https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/examples/chat/client.go#L105

**Comment by MonicaRJones** [comment]
The call `len(c.send)` is thread safe. The [language specification says](https://golang.org/ref/spec#Channel_types):

> A single channel may be used in send statements, receive operations, and calls to the built-in functions cap and len by any number of goroutines without further synchronization.

The next for loop iteration picks up values sent to `c.send` after the call to `len(c,send)`.
