### ISSUE TITLE
[question] can pass cookie to websocket server by react JS?

### ISSUE THREAD

**Issue by JimmyWang** [gorilla/websocket#701]
react JS codes:
```    var headers = {};
      headers["cookie"] = `access_token=123231321321`;
      headers["hi"] = `321312`;
      const ws = new WebSocket(`ws:\\/\\/localhost:8900\\/api\\/v1\\/ws\\/project\\/111`, [], {
        'headers': headers
      });
```

**golang server codes can NOT receive cookie or hi headers:**

r.Headers:
![image](https://user-images.githubusercontent.com/6657454/122901720-61803980-d380-11eb-9373-9f7052a11495.png)

r.Cookie is nil:
![image](https://user-images.githubusercontent.com/6657454/122901730-63e29380-d380-11eb-822e-9138e212afc9.png)

can pass cookie to websocket server by react JS?

**Comment by MonicaRJones** [comment]
Call the Request [Cookie](https://pkg.go.dev/net/http#Request.Cookie) or [Cookies](https://pkg.go.dev/net/http#Request.Cookies) methods to get cookies from a websocket handshake request. The image in the issue shows that r.Cookie is a function as expected.  You must call the function to get a cookie: `c, err := r.Cookie("access_token")`.

Web browsers automatically send cookies associated with the websocket endpoint in the websocket handshake request.  Use a [Set-Cookie header](https://pkg.go.dev/net/http#SetCookie) or [document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) to associate cookies with the websocket endpoint. 

The code in the issue uses the third argument to the Websocket constructor to specify headers.  The [standard Websocket constructor](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket) does not have the third argument.

I am not aware of React doing anything special with regard to cookies and websockets, but I am by no means a React expert.  There may be a React expert lurking here, but you are more likely to get help on a React specific forum.

**Comment by JimmyWang** [comment]
> Call the Request [Cookie](https://pkg.go.dev/net/http#Request.Cookie) or [Cookies](https://pkg.go.dev/net/http#Request.Cookies) methods to get cookies from a websocket handshake request. The image in the issue shows that r.Cookie is a function as expected. You must call the function to get a cookie: `c, err := r.Cookie("access_token")`.
> 
> Web browsers automatically send cookies associated with the websocket URL in the websocket handshake request. Use a [Set-Cookie header](https://pkg.go.dev/net/http#SetCookie) or [document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) to associate cookies with the websocket URL.
> 
> The code in the issue uses the third argument to the Websocket constructor to specify headers. The [standard Websocket constructor](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket) does not have the third argument.
> 
> I am not aware of React doing anything special with regard to cookies and websockets, but I am not a React expert. There may be a React expert lurking here, but you are more likely to get help on a React specific forum.

yeah，c, err := r.Cookie("access_token") already in my codes. 

during my test:

ws protocal can NOT pass cookie to golang backgroud.
wss protocal CAN pass cookie to golang backgroud.

you can't write cookie set js code, the web request will bring current domain to backgroud service.

Thanks

**Comment by MonicaRJones** [comment]
> you can't write cookie set js code, the web request will bring current domain to backgroud

Setting the cookie SameSite may help with the problem, but I don't know for sure because you don't describe any of the domains involved for the cookie, page and websocket.

> ws protocal can NOT pass cookie to golang backgroud.

Cookies work with the ws protocol, but cookies with the Secure attribute are not sent.
