### ISSUE TITLE
WriteMessage and WriteControl do not check error from SetWriteDeadline [bug] 

### ISSUE THREAD

**Issue by rittneje** [gorilla/websocket#705]
The `SetWriteDeadline` method from `net.Conn` can return an error. https://golang.org/pkg/net/#Conn

However, this library neglects to check it.
https://github.com/gorilla/websocket/blob/b65e62901fc1c0d968042419e74789f6af455eb9/conn.go#L389
https://github.com/gorilla/websocket/blob/b65e62901fc1c0d968042419e74789f6af455eb9/conn.go#L456

**Comment by rittneje** [comment]
ping @elithrar

**Comment by hulkingshtick** [comment]
This is fixed.  I searched the code and cannot find any calls that ignore errors.
