### ISSUE TITLE
[bug] Sometimes i got "unexpected reserved bits 0x40" with client of browser-js or java-websocket or py

### ISSUE THREAD

**Issue by zhuwei** [gorilla/websocket#707]
**Describe the bug**
ReadMessage return error "unexpected reserved bits 0x40"

**Versions**
CreateFile go1.16.2: The system cannot find the file specified.
CreateFile windows/amd64: The system cannot find the path specified.

**Steps to Reproduce**
Sometimes 

**Expected behavior**
no error

**Code Snippets**
```
ws.PongHandler()
t, data, err := ws.ReadMessage()
if err != nil {
	LoggerErrorWs("read-ReadMessage", zap.Int("messageType", t), zap.Binary("data", data), zap.Error(err))
	break
}
```

**Comment by MonicaRJones** [comment]
There are two possibilities:

- The peer incorrectly sets the reserved bits.
- The application reads connection concurrently.  Run the application [with the race detector](https://golang.org/doc/articles/race_detector) and fix any reported problems.

**Comment by owulveryck** [comment]
The `chat` sample app suffers from the same problem

adding a `log.Println(err)` in the client here: https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/examples/chat/client.go#L65-L71

like this:

```go
if err != nil {
        if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
                log.Printf("error: %v", err)
        }
        log.Println(err)
        break
}
```

and running the sample (with chrome) returns:

```
2021/12/06 08:53:07 websocket: unexpected reserved bits 0x40 
```
