### ISSUE TITLE
Implementing user layer PING/PONG

### ISSUE THREAD

**Issue by christinna9031** [gorilla/websocket#708]
I want to implement a custom PING/PONG handler (as opposed to the default one) as I need to be able to check the connection's health on the client side to make sure it's still listening to events. I've seen other websockets do a similar thing, so I figured this could work for me as well. That said, I just started with Go, so I'm not sure about my own implementation.    

I wrote a simple function that listens to incoming "PING" JSON messages from the client and responds with "PONG". 
My websocket is event based, i.e. the client should not be sending anything else than PING messages and in the case they do, the websocket automatically closes the connection. 

``` 
func reader(ws *websocket.Conn) {
	pingWait := 60 * time.Second
	ws.SetReadDeadline(time.Now().Add(pingWait))
	defer func() {
	ws.Close()
	// some other stuff to do 
	}()
	for {
		_, p, err := ws.ReadMessage()
		if err != nil {
			fmt.Println(err)
			break
		}
		message := string(p)
		if message == "PING" {
		ws.SetReadDeadline(time.Now().Add(pongWait))
		ws.WriteJSON(("PONG"))
		} else {
		ws.WriteJSON(("Wrong payload. Websocket will now close."))
		break	
		}
	}
} 
```
Is this a good practice? It seems to be working flawlessly so far, but I was wondering if there could be any problems down the road that I didn't think of or if there's a way to make this more memory efficient. Also, does reader need to be running as a new go routine for each new connection?  

Right now I'm calling it from handleClient function like this: 

```
func handleClient(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		logEntry.Println(err)
		w.WriteHeader(426)
		return
	}
	reader(conn)
}
```

Thanks!

**Comment by MonicaRJones** [comment]
> Is this a good practice? 

This package and the websocket protocol do not limit or specify how the application uses data messages. 

> does reader need to be running as a new go routine for each new connection?

The application must run a read goroutine for each connection to process control messages sent from the peer ([documentation](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Control_Messages)).
