### ISSUE TITLE
[question] Why does the conn.WriteJSON() still work for a while when I turn off the network?

### ISSUE THREAD

**Issue by A1311981684** [gorilla/websocket#709]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

I am using websocket on a project, I notice that If I change the network or just turn it off, the conn.WriteJSON method won't return a error util a dozen of seconds passed, then it return an error indicates the conn is  broken.  What I expected in mind is that when the network is cut off, the method can tell me the message is not sent, so I can close the conn in time. 

Why is that?

This is my  test code:
-----------------------------
ws.go:
-----------------------------

// @Package description:
// @Title baseNotifier.go
// @Description:
// @Author wzj
// @Date 2021/7/26
// @Update wzj 2021/7/26
package main

import (
	"fmt"
	"github.com/gorilla/websocket"
	"net/http"
	"sync"
	"time"
)

type BaseNotifier struct {
	//these are added to fix the mysterious bug: server sent but client won't receive util call
	lck         sync.Mutex
	clients     map[string]*websocket.Conn
	workingChan map[string]*chan int

	name string
}

func NewBaseNotifier(name string) *BaseNotifier {
	return &BaseNotifier{
		lck:         sync.Mutex{},
		clients:     make(map[string]*websocket.Conn),
		workingChan: make(map[string]*chan int),
		name:        name,
	}
}

func (b *BaseNotifier) ServeHTTP(writer http.ResponseWriter, request *http.Request) {
	up := websocket.Upgrader{}
	up.CheckOrigin = func(r *http.Request) bool {
		return true
	}
	up.WriteBufferSize = 8

	c, err := up.Upgrade(writer, request, nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer func() {
		_ = c.Close()
	}()

	fmt.Println(b.name, "-------------> ws client in:", fmt.Sprintf("%p", c), c.RemoteAddr())
	//before accessing the maps, lock first
	b.lck.Lock()
	//add client to broadcast
	b.clients[fmt.Sprintf("%p", c)] = c
	//this chan is for stopping ws service
	ch := make(chan int)
	b.workingChan[fmt.Sprintf("%p", c)] = &ch
	//unlock
	b.lck.Unlock()
	//block here to maintain ws serving util ch receives anything
	select {
	case <-ch:
		fmt.Println(fmt.Sprintf("%p", c), b.name, " ws closed")
		//remove client
		delete(b.clients, fmt.Sprintf("%p", c))
	}
}

func (b *BaseNotifier) Send(msg interface{}) error {
	var sendContent = msg

	//accessing maps needs to be locked
	b.lck.Lock()
	defer b.lck.Unlock()
	fmt.Println(b.clients, msg)
	//broadcasting message
	for _, conn := range b.clients {
		err := conn.SetWriteDeadline(time.Now().Add(3 * time.Second))
		if err != nil {
			fmt.Println(err)
			return err
		}
		fmt.Println(b.name, conn.RemoteAddr(), "writing...")
		err = conn.WriteJSON(sendContent)
		fmt.Println(b.name, conn.RemoteAddr(), "wrote:", err)
		if err != nil {
			fmt.Println(err)
			//when error occurred, terminate ws serving
			//select with default makes sure it will never be blocked
			select {
			case *b.workingChan[fmt.Sprintf("%p", conn)] <- 1:
			default:
			}
		}
		//utils.Log.Infos("send to this client:", fmt.Sprintf("%p", conn), conn.RemoteAddr(), sendContent)
	}
	return nil
}

//------------------------------

type WebsocketMasterNotifier struct {
	port string
	name string
}

func (b *WebsocketMasterNotifier) Register(path string, handler http.Handler) {
	http.Handle(path, handler)
}

func (b *WebsocketMasterNotifier) Start() {
	go func() {
		fmt.Println(b.name, "ws server start at:", b.port)
		if err := http.ListenAndServe(":"+b.port, nil); err != nil {
			fmt.Println(err)
		}
	}()
}

func NewMasterNotifier(name, port string) *WebsocketMasterNotifier {
	return &WebsocketMasterNotifier{name: name, port: port}
}

---------------------------------
main.go
---------------------------------

package main

import (
	"fmt"
	"time"
)

func main() {
	var mws = NewMasterNotifier("wst", "19999")
	child := NewBaseNotifier("wst-child")
	mws.Register("/a", child)
	mws.Start()

	for {
		time.Sleep(time.Second * 1)
		err := child.Send("hi~")
		if err != nil {
			fmt.Println(err)
		}
	}

}

…

**Comment by FZambia** [comment]
Hello @A1311981684 , see the answer on a similar question here: https://github.com/gorilla/websocket/issues/108

**Comment by A1311981684** [comment]
> Hello @A1311981684 , see the answer on a similar question here: #108

Thanks!
