### ISSUE TITLE
Signal receive loop to stop and close the conn

### ISSUE THREAD

**Issue by slavikm** [gorilla/websocket#71]
My code looks somewhat like the following:
```
	// Start reading the messages and pumping them to the channel
	go func(ws *websocket.Conn, in chan Message) {
		defer func() {
			ws.Close()
		}()
		for {
			msg := Message{}
			err := ws.ReadJSON(&msg)
			if err != nil {
				msg.Type = "error"
				msg.Error.Code, msg.Error.Msg = 0, err.Error()
			}
			in <- msg
			if err != nil {
				close(in)
				break
			}
		}
	}(s.ws, in)
```

What I would like to do is also pass in a stop channel and do a select on both read and stop. If I receive a stop, I just break from the loop. Looking quickly at the code, I could not find an easy way to do so.
Any tips?

Thanks

**Comment by garyburd** [comment]
The simple way to stop the read loop in the code above is to close the websocket connection.

**Comment by slavikm** [comment]
Got it. Actually makes sense. Thanks much.
