### ISSUE TITLE
[question] Multiple client management

### ISSUE THREAD

**Issue by xiongbenwu** [gorilla/websocket#711]
A large number of client management, how to use the client to dynamically manage multiple clients, for example: I want to simulate users to subscribe to thousands of WS, how to use it

**Comment by MonicaRJones** [comment]
[Dial](https://pkg.go.dev/github.com/gorilla/websocket#Dialer.DialContext) connections as needed.  Each connection is independent of each other.  Management of the connections is an application concern.
