### ISSUE TITLE
Not able to download websocket module using go get.

### ISSUE THREAD

**Issue by qascade** [gorilla/websocket#712]
**Describe the bug**
> A clear and concise description of what the bug is.
Whenver I try to `go get` the module, it throws unexpected EOF error.
…

**Versions**
> Go version: `go version`
`go version go1.16.6 darwin/amd64`
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?
`go get github.com/gorilla/websocket`
…

**Terminal Output**
```
go get github.com/xuri/excelcize
go get: module github.com/xuri/excelcize: Get "https://proxy.golang.org/github.com/xuri/excelcize/@v/list": unexpected EOF
```
I am using MacOS Big Sur on Mac Book Pro 2020.

**Comment by elithrar** [comment]
websocket doesn’t import third party modules; it sounds like something in
your Go installation is broken. The “excelcise” package is not imported by
gorilla/websocket.

**Comment by qascade** [comment]
I have uninstalled and reinstalled go multiple times, but it still shows this behaviour.
Is there a way to hard reset go installation.

**Comment by elithrar** [comment]
Are you explicitly running `go get github.com/xuri/excelcize` - ? That’s not related to this package and it’s likely to be an issue with that package itself.

**Comment by qascade** [comment]
I changed my GOPATH to a new directory, and it worked.
