### ISSUE TITLE
how to set timeout

### ISSUE THREAD

**Issue by caleb-letsgo** [gorilla/websocket#713]
How do I set TLS handshake timeout?
Does HandshakeTimeout refer to websocket HandshakeTimeout? Does it include the TCP three-way handshake and the TLS handshake?

**Comment by MonicaRJones** [comment]
Set the HandshakeTimeout.  This timeout covers all aspects of establishing the websocket connection.

**Comment by garyburd** [comment]
Ghost, thank you for answering the question.
