### ISSUE TITLE
In some windows systems, the upgrade protocol will block

### ISSUE THREAD

**Issue by 19byte** [gorilla/websocket#714]
**Versions**
> Go version: `go version go1.16.2 linux/amd64`
> package version: run `github.com/gorilla/websocket v1.4.2` 

in windows,upgrade will keep blocking

**Steps to Reproduce**
> How can the bug be triggered?

connect to websocket

**Expected behavior**
> What output or behaviour were you expecting instead?

in my ubuntu system,connect and upgrade is normal

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

```
func StartWsServer(hub *Hub, w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/channel" {
		http.Error(w, "NotFound", http.StatusNotFound)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "MethodNotAllowed", http.StatusMethodNotAllowed)
		return
	}
	token := r.Header.Get("token")
	claims, err := infs.ParseToken(token)
	if err != nil {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}
	conn := Repos.PoolRedis.GetPool().Get()
	defer conn.Close()
	rt, err := redis.String(conn.Do("GET", fmt.Sprintf("user:%v:token", claims.Id)))
	if err != nil {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}
	if rt != token {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}
        // here will be blocked forever
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Error(err)
		return
	}
	client := &Client{
		hub:      hub,
		conn:     ws,
		id:       claims.Id,
		token:    token,
		state:    stateOnly,
		shutdown: make(chan struct{}),
		send:     make(chan *pb.ServerMsg, defaultSendChanBufSize),
		group:    make(map[int64]int64),
	}
	hub.register <- client
	log.Info("websocket client started ", client.id, ws.RemoteAddr())
	go client.write()
	go client.read()
	go client.event()
}
```

**Comment by MonicaRJones** [comment]
Set [Upgrader.HandshakeTimeout](https://pkg.go.dev/github.com/gorilla/websocket#Upgrader.HandshakeTimeout) to protect against clients that do not complete the handshake.

**Comment by 19byte** [comment]
> 设置[Upgrader.HandshakeTimeout](https://pkg.go.dev/github.com/gorilla/websocket#Upgrader.HandshakeTimeout)以防止客户端未完成握手。

this may be necessary for the release mode, but it is a troublesome thing when I debug it locally

**Comment by MonicaRJones** [comment]
If you are running antivirus software, disable the software to see if that fixes the problem.   

Add a comment with the complete stack trace of the stuck goroutine.

**Comment by garyburd** [comment]
There's insufficient information to debug the problem.  Describe the client and server environments in more detail. How do you know that the program is stuck in the Upgrade?  Show a stack trace.
