### ISSUE TITLE
[bug] Unexpected Reserved Bits 0x40 whenever sending data

### ISSUE THREAD

**Issue by ravenclaw900** [gorilla/websocket#717]
**Describe the bug**
> A clear and concise description of what the bug is.

When using Javascript to send data to this, it immediately closes the connection on the JS side and you get the error "unexpected reserved bits 0x40" on the Go side.

**Versions**
> Go version: `go version`
`go version go1.17 darwin/amd64`
> package version: run `git rev-parse HEAD` inside the repo
`1.14.2`

**Steps to Reproduce**
> How can the bug be triggered?

Send data using Javascript to a server running this.

**Expected behavior**
> What output or behaviour were you expecting instead?

It recieves the data.

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).
```
func echo(w http.ResponseWriter, r *http.Request) {
	c, _ := upgrader.Upgrade(w, r, nil)
	for {
		_, _, err := c.ReadMessage()
		if err != nil {
			log.Println("read:", err)
			break
		}
	}
}
```
Yes, I stole this from the example.

**Comment by MonicaRJones** [comment]
Add a comment with the JavaScript code and information about the context where the JavaScript code is running (if it’s a browser, tell us which one and version).

**Comment by ravenclaw900** [comment]
Sure, the browser is Brave 1.28.105, though I also tested on Safari.  Code:
```js
var socket;
const socketMessageListener = (e) => {
    console.log(e.data);
};
const socketOpenListener = (e) => {
    console.log('Connected');
    socket.send(JSON.stringify({ message: "hello, server" }))
};
const socketErrorListener = (e) => {
    console.error(e);
}
const socketCloseListener = (e) => {
    if (socket) {
        console.log('Disconnected.');
    }
    socket = new WebSocket("ws://localhost:8080/ws");
    socket.onopen = socketOpenListener;
    socket.onmessage = socketMessageListener;
    socket.onclose = socketCloseListener;
    socket.onerror = socketErrorListener;
};
window.addEventListener('load', (event) => {
    socketCloseListener();
});
```

**Comment by MonicaRJones** [comment]
Show the value of `upgrader`.

**Comment by ravenclaw900** [comment]
Sure.  It's just blank:
`var upgrader = websocket.Upgrader{}`.

**Comment by ravenclaw900** [comment]
If I put in `EnableCompression: true`, it then gives me the error:
```
websocket: unknown opcode 7
```

**Comment by ravenclaw900** [comment]
My bad, this seems to be a problem on my computer.  Time to figure what exactly I messed up.  Thanks!

**Comment by MonicaRJones** [comment]
Concurrent reads can cause the problem.  Run your application with the [race detector](https://golang.org/doc/articles/race_detector).

**Comment by ravenclaw900** [comment]
No, it works fine on other computers, so I don't think that's the problem.

**Comment by elithrar** [comment]
It is very likely a local proxy issue - are you behind a corporate proxy,
VPN service or privacy proxy?

**Comment by ravenclaw900** [comment]
No, the only delve into proxies I've had is i2p, and I think that I removed that.
