### ISSUE TITLE
[question]How can I distinguish the timeout reason

### ISSUE THREAD

**Issue by uzzz1** [gorilla/websocket#718]
**Describe the problem you're having**
>Every time server reads message from client, it will extend the read deadline 10s.However, if the network environment is so poor that a big buffer can`t be sent to server in 10s, and because of the big buffer server can't recieve pong, then the connect will be closed by server.  So I am wondering that, could we distinguish that server didn't recieve pong because there is a big buffer being sent, or the connect has been shut down.

…

**Versions**
> Go version: `1.14`

> package version:1. 4. 2

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by MonicaRJones** [comment]
A connection has no information about how or why the application calls the connection's SetReadDeadline method.

Some possible fixes:
- Use a timeout that's large enough to handle the a large message on a slow connection.
- Adjust the deadline when reading a message.

**Comment by uzzz1** [comment]
> A connection has no information about how or why the application calls the connection's SetReadDeadline method.
> 
> Some possible fixes:
> 
> * Use a timeout that's large enough to handle the a large message on a slow connection.
> * Adjust the deadline when reading a message.

Thank you for your advices, but for some reasons, it will bring other troubles if we set a large timeout. In other words, is there any other method to judge whether the connect is alive except ping/pong?

**Comment by MonicaRJones** [comment]
If the peer is sending data in message, then the peer is probably alive.

Call NextReader with deadline based on the PING interval. After successful return from NextReader, set a deadline before calling Read.  You could set a deadline large enough to work for all expected network conditions and message sizes.  Another option is to set a deadline based on a minimum rate that the peer should send data.

**Comment by garyburd** [comment]
Previous comments answer the question.
