### ISSUE TITLE
Succeed creating webSocket with firefox, fails with Chromium

### ISSUE THREAD

**Issue by chmike** [gorilla/websocket#721]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
Not sure it's a bug. I may do something wrong.
I first tested with a simple http server (not https) on a mac and tried to open a webSocket to localhost. It succeeded with firefox and failed with Chrome and Safari but without any error cause feedback. I found out in some stackoverflow answer that Chrome would not allow unsecure websockets to localhost for security reason.

I then changed my setup to use a caddy server with a domain name I own configured as reverse proxy to the http server. All this on an Ubuntu computer. Again, firefox manage to open the webSocket using wss, and Chromium fails by providing the feedback error: `Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`. 

I tried with another webSocket package [gobwas/ws](https://github.com/gobwas/ws/issues) and saw the same behavior. 
On the javascript side, the socket is configured to use protocolOne. 

**Versions**
> Go version: `go version`
go version go1.17 linux/amd64

> package version: run `git rev-parse HEAD` inside the repo

This is the gorilla websocket line in my go.mod
github.com/gorilla/websocket v1.4.2

$ git rev-parse HEAD
e8629af678b7fe13f35dff5e197de93b4148a909

**"Show me the code!"**
```
func webSocketGorilla(w http.ResponseWriter, r *http.Request) {
	// unsafe: allow any origin
	upgrader.CheckOrigin = func(r *http.Request) bool {
		return true
	}
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println("error:", err)
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}
	log.Println("webSocket opened")
	go func() {
		defer conn.Close()

		var i int
		for {
			msg := fmt.Sprintf("message %d", i)
			err := conn.WriteMessage(websocket.TextMessage, []byte(msg))
			if err != nil {
				log.Println("error:", err)
				break
			}
			time.Sleep(2 * time.Second)
			i++
		}
	}()
}
```

On the frontend side, the instruction that fails  is 
```
var webSocket = new WebSocket("wss://xxx/state", "protocolOne");
```

Could it be caused by the reverse proxy that converts an https connection to a local http connection ?

**Comment by mamjsn** [comment]
>  I found out in some stackoverflow answer that Chrome would not allow unsecure websockets to localhost for security reason.

The answer is not correct.  Please provide a link to the answer so that I can leave a comment on it.

> Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received.

The Chromium error message describes the problem.  The client requested sub-protocol `protocolOne`, but the server did not respond to that request.  Edit the server code to negotiate the sub-protocol **or** remove the sub-protocol request from the client code. Example client code:

    var webSocket = new WebSocket("wss://xxx/state") // or ws: when testing on localhost.

> Could it be caused by the reverse proxy that converts an https connection to a local http connection ?

That does not appear to the problem here.

**Comment by chmike** [comment]
The stackoverflow answer is the following: https://stackoverflow.com/a/50861413/75517. 

The reason I added "protocolOne" is because it is given in the example [given here](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications). That was confusing. So I can simply remove this.

I tested the code without this `protocolOne` and it worked. Thank you very much
