### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by naiming-zededa** [gorilla/websocket#722]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

I have a websocket between A and B hosts, and on A I setup a tcp server to listen on port 'a'
and on B i launch a tcp connect to remote 'b'. and I want to transport/proxy tcp service from
location A to remote 'b'

I tried to use io.Copy to 'bridge' the tcp socket to/from the websocket websocket.Conn, and
can not write to the websocket. it hangs on write.

do you have any suggestions?

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

in my go.mod, i have this version
github.com/gorilla/websocket v1.4.2

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

this is A side of the code, meant to be one client connection at a time:
```
func testWSSbridge(conn *websocket.Conn, local string) error {
	listener, err := net.Listen("tcp", local)
	if err != nil {
		return err
	}

	for {
		here, err := listener.Accept()
		if err != nil {
			return err
		}
		go func() {
			_, reader, err := conn.NextReader()
			if err != nil {
				fmt.Printf("reader err %v\n", err)
				return
			}
			io.Copy(here, reader)
		}()
		for {
			writer, err := conn.NextWriter(websocket.BinaryMessage)
			if err != nil {
				fmt.Printf("writer err %v\n", err)
				return err
			}
			defer writer.Close()
			_, err = io.Copy(writer, here)
		}
	}
}
```

**Comment by mamjsn** [comment]
The deferred `writer.Close()` calls are not executed until `testWSSbridge` returns.  That's probably a bug.

It looks like there are three entities: 
1.  the program that runs the code in the issue
2. the websocket peer of `conn`
3.  TCP client that connects to the listening socket.   

Is `B` entity 2 or entity 3?    What is the other entity?

**Comment by naiming-zededa** [comment]
this conn's websocket peer is in B, the code is not shown above (should have similar problem doing io.Copy() there with http server from B)
the http browse opens url to the A's listening address:port
thanks

**Comment by mamjsn** [comment]
The listening port in `A` does not implement the websocket protocol.  The code in `A` converts the message-based websocket protocol on `conn` to a stream of bytes on `here`.  

I am not fully grasping the scenario, but I think you want to implement a plain TCP proxy.  Browser and `B` talk the websocket protocol.  `A` transfers data between Browser and `B` with no interpretation of the bytes.

**Comment by naiming-zededa** [comment]
yes, the port listening on A is just TCP, but I assume between A<->B websocket is running, the copied over from the port is just binary data, and on B it will receive as binary data, then copy onto another socket which is TCP. I must have missed something here.

**Comment by naiming-zededa** [comment]
if I use a buf, usee the 'here.read(buf)', then use conn.WriteMessage(), it works, the traffic does go to the B and being sent to thee server. for a very simple http query using curl works fine. but a normal browser to a site does not work properly. I feel i somehow need to do io.Copy to join the connections.

**Comment by naiming-zededa** [comment]
the above code io.Copy(writer, here) hangs, I'm wondering if there is any proper way to io.Copy to websocket.Conn with some extra structure, etc.

**Comment by mamjsn** [comment]
It's not clear what you are trying to do.  What are the entities on the network?  What protocols do they speak?  

Here's one possible description:

1. Browser (http client and websocket client)
2. Proxy (is this A?)
3. B (http and websocket server?)

**Comment by naiming-zededa** [comment]
more description
1 browser to connect to A's port say 192.168.1.1:8888
2 A is websocket client, and B is server for example
3. A will relay any traffic from 192.168.1.1:8888 to remote B through websocket
4. B opens a tcp socket to say www.google.com
5. B will relay any traffic from the webssocket to tcp socket in 4
6. the browser type in http://192.168.1.1:8888 and being connected to www.google.com (assume it's not https)
7. the relay in A and B I want to use the io.Copy
8.

**Comment by mamjsn** [comment]
I think I get it.   

You are possibly seeing the effects of buffering within a websocket message.  Fix by changing `A` to write the data read from `here` as multiple messages.  

    buf := make([]byte, 1024)
    for {
         n, err := here.Read(buf)
          if n > 0 {
                  err2 := conn.WriteMessage(websocket.BinaryMessage, buf[:n])
                  if err2 != nil {
                       return err
                  }
           }
           if err != nil {
               return err
           }
    }

Given that A and B are not browsers, consider using a plain TCP proxy between A and B.  The extra layer of goop in the websocket protocol is probably not providing anything of value to your scenario.

**Comment by naiming-zededa** [comment]
I was doing exactly that code first. But the browser won't work properly. I think mainly the 'here' socket constantly gets EOF and connection is gone. I suspect the EOF is something internal to the webpage.

**Comment by naiming-zededa** [comment]
The reason websocket into play here  due to the condition of B being behind the FW, in which normal TCP connection won't work. but i'm wondering why this above code of yours won't work properly. In a simple one page return works using 'curl GET', but for real website, it stuck and timeout, etc.

**Comment by naiming-zededa** [comment]
@mamjsn an unrelated question. When I define a struct, with some int and strings, those strings are using string([]byte(data)). After I did a jdata, err := json.Marshal() of that struct, then using websocket.WriteMessage(BinaryMessage, jdata), does that suppose to work? I seem to have problem after using the json binary payload. thanks.

**Comment by garyburd** [comment]
Question is about application design, not this package.
