### ISSUE TITLE
Not able to get ping and pong message from server to go lang websocket client

### ISSUE THREAD

**Issue by vitpravin** [gorilla/websocket#723]
Go lang client - https://github.com/gorilla/websocket
From server-side we are sending the ping and pong message but the go lang client is not able to receive

Tested with different websocket client and server
Below are observations

Java server and Node Js client = Ping woking
Java server and Go, lang client, = Ping not working
Node js server and Node Js client = Ping Working
Node js server and Go lang client = Ping working

The only issue we are facing is for the java server and go lang client
Java server working with node js client and go lang client working with node js for a ping message

Only issue between java server and go lang client as now we are facing for ping and pong message
could you please help with this

That would be very helpful

Thanks

**Comment by mamjsn** [comment]
Describe "not working".  Are you saying that the Go client does respond to a PING with a PONG, or that the Go application does not [receive a PONG](https://pkg.go.dev/github.com/gorilla/websocket#Conn.SetPongHandler) after [sending a PING](https://pkg.go.dev/github.com/gorilla/websocket#Conn.WriteControl)?

**Comment by vitpravin** [comment]
Client application does not receive a PING from server (but server sending ping message) so client does respond to a PING with a PONG

But after added this code  https://pkg.go.dev/github.com/gorilla/websocket#hdr-Control_Messages
func readLoop(c *websocket.Conn) {
    for {
        if _, _, err := c.NextReader(); err != nil {
            c.Close()
            break
        }
    }
}
client received the ping message from the server and client repsond to server with a pong message

can you help to understand why this readloop is needed?
What is the problem?
Using only one nextreader only?

**Comment by mamjsn** [comment]
PING is a control message.  The [section in the documentation on control messages](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Control_Messages) says:

> The control message handler functions are called from the NextReader, ReadMessage and message reader Read methods. The default close and ping handlers can block these methods for a short time when the handler writes to the connection.

> The application must read the connection to process close, ping and pong messages sent from the peer. 

It sounds like your application was not calling NextReader or ReadMessage. Adding the `readLoop` code fixed the problem.

**Comment by garyburd** [comment]
The question is answered in the previous comment.
