### ISSUE TITLE
Not able to get Ping message from server

### ISSUE THREAD

**Issue by santanu22** [gorilla/websocket#724]
**Not able to get Ping message from server**
> I am implementing client by using Gorilla Websocket. Server side is in Java.(Java server)
Before I was not able to receive ping message from server.

dial_connection.go:
===============
	connection.SetPingHandler(func(appData string) error {
		log.Info(appData)
		connection.WriteMessage(websocket.PongMessage, []byte("ping"))
		return connection.SetReadDeadline(time.Now().Add(handshakeWait))
	})

After adding below method(readLoop), I am able to get the ping message from server.
Getting from this link: https://pkg.go.dev/github.com/gorilla/websocket#hdr-Concurrency

func readLoop(c *websocket.Conn) {
    for {
        if _, _, err := c.NextReader(); err != nil {
            c.Close()
            break
        }
    }
}

But the problem is that NextReader we can use once in the websocket.
In another file  ReceiveJobs.go  already used NextReader to get the job payload from websocket. If I run the process, then I am not getting this job payload as one NextReader we can keep.
some code snippet from **ReceiveJob.go**

func ReceiveJobs() chan *models.WebsocketJobResponse {
	jobsChan := make(chan *models.WebsocketJobResponse)

	go func(conn *websocket.Conn, c chan *models.WebsocketJobResponse) {
		for {
			wsResp := &models.WebsocketJobResponse{}
				_, r, err := conn.NextReader()

Please guide me how can I resolve this issue.

**Comment by mamjsn** [comment]
The `readLoop` example code is not needed in your application.  Delete it.

The paragraph before the `readLoop` example says:

>  If the application is not otherwise interested in messages from the peer, then the application should start a goroutine to read and discard messages from the peer. 

Your application does read messages from the peer in`ReceiveJobs`, therefore there's no need to create a loop that discards messages.

**Comment by santanu22** [comment]
Thanks for respond. If I not use the the readLoop() then I am not getting the ping message from server (java server).

**Comment by mamjsn** [comment]
The [documentation says](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Control_Messages):

> The control message handler functions are called from the NextReader, ReadMessage and message reader Read methods. 

The application calls `NextReader` in the goroutine started by `ReceiveJobs`.   Does that goroutine run for the lifetime of the connection?

Side notes: 
- Applications should not rely on a peer to send PING messages.  If the application needs PING/PONG to keep the connection alive, then the application should send PONG. 
- The application should respond to the PING with the app data: `connection.WriteMessage(websocket.PongMessage, []byte(appData))`

**Comment by santanu22** [comment]
The application calls NextReader in the goroutine started by ReceiveJobs. Does that goroutine run for the lifetime of the connection?  --Yes.

Basically we need ping message to reconnect to the device. By default the device is connected after 15mins as we are not receiving the ping message from Server (java server) even we are handling both ping and pong in our code to make sure atleast one we should get.
Added some debug statement also. But in the log its not printed.

	connection.SetPingHandler(func(appData string) error {
		log.Info(appData)
		pongTime = time.Now()
		fmt.Println("######Ping Received:")
		fmt.Println("#########pingTime", pongTime)
		connection.WriteMessage(websocket.PongMessage, []byte("ping"))
		return connection.SetReadDeadline(time.Now().Add(handshakeWait))
	})

**Comment by mamjsn** [comment]
We know that the ping handler works because the handler is invoked with the `readLoop` code.

I see two possibilities: 

- The goroutine in `ReceiveJobs` is not calling `NextReader`.   Perhaps the goroutine exited quietly or is blocked on some other operation.  Add debug logs before and after `NextReader` to see what's going on there.
- The server is not sending ping messages when you expect.

**Comment by santanu22** [comment]
1) Added debug statement before and after NextReader in ReceiveJobs, its not printed in the log. It looks its not calling.
2) Updated the SetPingHandler. 
connection.SetPingHandler(func(appData string) error {
	log.Info(appData)
	pongTime = time.Now()
	fmt.Println("######Ping Received:")
	fmt.Println("#########pingTime", pongTime)
	connection.WriteMessage(websocket.PongMessage, []byte(appData))
	return connection.SetReadDeadline(time.Now().Add(handshakeWait))
})

If we keep readLoop(), then only we received the ping message and receivejob is not called.
3)One more point observe that getting timeout error from ReadMessage() in the dial_connection.go

	connection.SetPingHandler(func(appData string) error {
		log.Info(appData)
		pongTime = time.Now()
		fmt.Println("######Ping Received:")
		fmt.Println("#########pingTime", pongTime)
		connection.WriteMessage(websocket.PongMessage, []byte(appData))
		return connection.SetReadDeadline(time.Now().Add(handshakeWait))
	})

	readLoop(connection)

	_, _, err = connection.ReadMessage()

	if err != nil {
		log.Error("failed to read message")
		return err
	}

	log.Info("Connection successful")

**error: read tcp 172.18.122.30:58786->15.89.46.62:8080: i/o timeout** -This error from log.

**Comment by mamjsn** [comment]
> Added debug statement before and after NextReader in ReceiveJobs, its not printed in the log. It looks its not calling.

This is the problem that you need to solve.  Add a debug logs to confirm that the gorouting is running:

```
go func(conn *websocket.Conn, c chan *models.WebsocketJobResponse) {
        fmt.Printf("Entering read goroutine  c=%p\n", conn)
        defer fmt.Printf("Exiting read goroutine c=%p\n", conn)
	for {
		wsResp := &models.WebsocketJobResponse{}
                  fmt.Printf("Before  NextReader c=%p\n", conn)
		_, r, err := conn.NextReader()
                  fmt.Printf("After NextReader c=%p\n", conn)
```

> If we keep readLoop(), 

Do not use `readLoop` if your goal is to run the loop in `ReceiveJobs` for the lifetime of the connection.

**Comment by mamjsn** [comment]
We know that ping messages are delivered to the application when the application calls `NextReader` (this is the case when the  `readLoop` code is used).

The bug is with `ReceiveJobs`.  The goroutine there is not calling `NextReader`. Perhaps the goroutine is stuck, the groutine exited or the goroutine was not started  Whatever the problem is, it's not a bug with this package.

Regarding your point 3 above:  Your application should not assume that the peer sends PINGs frequently enough to meet your deadline. If the application needs PING/PONG to keep the connection alive, then the application should send PONG.

**Comment by santanu22** [comment]
We are using both ping and pong handler in the code to check which message we are received. 
My question is that why we are not received the ping handler or pong handler from Server without readLoop?


	fmt.Println("#######pong message start")
	connection.SetPongHandler(func(appData string) error {
		log.Info(appData)
		//handshakeWait = 5 * time.Second
		pongTime = time.Now()
		fmt.Println("######Pong Received:")
		fmt.Println("#########pongTime", pongTime)

		// we should send response to server.
		connection.WriteMessage(websocket.PongMessage, []byte(appData))
		return connection.SetReadDeadline(time.Now().Add(handshakeWait))
	})

	fmt.Println("######Ping  message start")
	connection.SetPingHandler(func(appData string) error {
		log.Info(appData)
		pongTime = time.Now()
		fmt.Println("######Ping Received:")
		fmt.Println("#########pingTime", pongTime)
		connection.WriteMessage(websocket.PongMessage, []byte(appData))
		return connection.SetReadDeadline(time.Now().Add(handshakeWait))
	})

	readLoop(connection)

**Comment by mamjsn** [comment]
> My question is that why we are not received the ping message or pong message from Server without readLoop?

There is a bug with ReceiveJobs. The goroutine there is not calling NextReader. Perhaps the goroutine is stuck, the groutine exited or the goroutine was not started.

> We are using both ping and pong handler in the code to check which message we are received.

Do not send unsolicited PONGs to the peer.  Delete this line from the PONG handler.

    connection.WriteMessage(websocket.PongMessage, []byte(appData))
