### ISSUE TITLE
[bug] Goroutines count goes high when the chat example is load tested

### ISSUE THREAD

**Issue by sljavax** [gorilla/websocket#726]
**Describe the bug**
>  I have load tested the chat example project. When the open connections count is high, the goroutines count goes high. Seems like goroutines are not released

…

**Versions**
> Go version: `1.16.5`
> package version: e8629af678b7fe13f35dff5e197de93b4148a909

…

**Steps to Reproduce**
> How can the bug be triggered?
Send multiple requests to the endpoint which upgrades the connections.
…

**Expected behavior**
> What output or behaviour were you expecting instead?
Goroutines should be released .
…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by elithrar** [comment]
When you say "goroutines should be released" - how are you
determining that? If the concurrent connections are high, Go's HTTP server
will maintain one goroutine per client until that connection is closed -
and websocket doesn't change that. If your benchmark client holds open
connections - and many do - then those goroutines will persist.

Are you observing goroutines growing (leaking) beyond the concurrents -
e.g. running 5k concurrents, then coming back and running another 2k, and
seeing 7k goroutines?

Sharing your benchmark code, clients and parameters would be useful.

>

**Comment by garyburd** [comment]
Closing because there’s no actionable information from the OP.
