### ISSUE TITLE
/ws endpoint in examples/chat throws Bad request

### ISSUE THREAD

**Issue by beanboi7** [gorilla/websocket#727]
When I try to hit the /ws endpoint in the examples/chat application I get a "Bad Request" and in my terminal I get this: 
```websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header```

> Go version: `1.17`
> package version: run e8629af678b7fe13f35dff5e197de93b4148a909

> How can the bug be triggered?
Inside the examples/chat directory enter go run *.go and hit the localhost:8080/ws in your browser

**Comment by mamjsn** [comment]
Use the path `/` to access the chat application in a browser.  The page at `/` opens a websocket connection to the endpoint at `/ws`. 

If you used the path `/ws` in the browser, then the log message correctly describes the problem. The browser did not connect to the websocket endpoint using the websocket protocol.

**Comment by beanboi7** [comment]
Thanks for the heads up, i'm closing this issue
