### ISSUE TITLE
Fragmentation error on write

### ISSUE THREAD

**Issue by ANPez** [gorilla/websocket#73]
I'm using the method .WriteJSON to send an arbitrary amount of data through websocket, but is failing to properly write the fragmentation when the amount of data is between 4096 and 8192. I saw that you have a code like this
```if len(p) > 2*len(w.c.writeBuf) && w.c.isServer {
	// Don't buffer large messages.```

If I change the "2*len" for just "len", it works flawlessly for all json sizes.

**Comment by garyburd** [comment]
Describe the error in more detail and how you detected it. What software is running on the peer?

**Comment by garyburd** [comment]
If you can describe the error in more detail or post code that reproduces the issue, then reopen the issue.
