### ISSUE TITLE
[question] Will the readme installation portion be updated for deprecation of "go get"?

### ISSUE THREAD

**Issue by randiaz95** [gorilla/websocket#736]
Will the readme installation portion be updated for deprecation of "go get"?

I think now we need to use go install or a module. Not many people are familiar with the new updated installation system.

**Comment by mamjsn** [comment]
The build and install functionality in `go get` is deprecated.  

The current documentation says:

> ### Installation
>
>      go get github.com/gorilla/websocket

Should "Installation" be replaced with "Add this package as a dependency" or something like that?

**Comment by garyburd** [comment]
`go get` is not deprecated.
