### ISSUE TITLE
Upgrade returns concrete type *websocket.Conn instead of an interface

### ISSUE THREAD

**Issue by samzhang111** [gorilla/websocket#74]
I'd like to mock out a connection within our websocket server for unit testing. I'm finding it difficult in the current implementation because the server explicitly returns a `*Conn` type during `Upgrade`. Any interest in a PR to switch out these return values of `*Conn` with a connection interface? Or any suggestions for workarounds?

**Comment by garyburd** [comment]
Declare the interface type in the application and use that type instead of *websocket.Conn in the application. 

I will not accept the proposed change because it will break existing applications.

**Comment by yoiang** [comment]
@garyburd  Can you elaborate on how to accomplish this? If we use the `Dialer`'s `Dial` method, build an interface for a `Dialer`, mock that interface, we still are returning a solid `*websocket.Conn` and golang will not match an interface type that matches `*websocket.Conn`.

**Comment by garyburd** [comment]
type Conn interface {
        // add subset of methods used by the application
        ReadMessage() (messageType int, p []byte, err error)
        WriteMessage(messageType int, data []byte) error
    }

    type Upgrader interface {
        Upgrade(w http.ResponseWriter, r *http.Request, responseHeader http.Header) (Conn, error)
    }

    // adaptor is simple wrapper to convert *websocket.Upgrader to Upgrader
    type adaptor struct {
        upgrader websocket.Upgrader
    }

    func (a adaptor) Upgrade(w http.ResponseWriter, r *http.Request, responseHeader http.Header) (Conn, error) {
        return a.upgrader.Upgrade(w, r, responseHeader)
    }

**Comment by yoiang** [comment]
Is there a way I can obtain a `*websocket.Conn` or construct one? It seems the only way is to call into the actual `dialer.Dial(...)` method which would be outside of the bounds of the test.

To clarify my reasoning (and possibly @samzhang111 's) we have a wrapper around the **gorilla/websocket** object that manages opening, message sending and receiving and closing with respect to our protocol. The wrapper controls the lifetime of the `*websocket.Conn` (or rather an interface that matches). On an `Open` method call the object dials in on an interface that matches `*websocket.Dialer` and internally manages the results. Typically I would mock a Dialer object to pass in that would return a mocked `*websocket.Conn` that can still be operated on by the rest of the methods that need testing.

**Comment by garyburd** [comment]
See the updates to my previous comments:

> Is there a way I can obtain a *websocket.Conn or construct one? It seems the only way is to call into the actual dialer.Dial(...) method which would be outside of the bounds of the test.

You must use Upgrader.Upgrade or dialer.Dialer to create a *websocket.Conn.  If you don't want to use Upgrader.Upgrade or dialer.Dialer in your test, then you also cannot use *websocket.Conn.  You should instead define an interface with the *websocket.Conn methods you need.

**Comment by yoiang** [comment]
Gotcha, thank you for your help!
