### ISSUE TITLE
The chat sample app doesn't work (error unexpected reserved bits 0x40)

### ISSUE THREAD

**Issue by owulveryck** [gorilla/websocket#741]
I cannot get the sample `chat` app to work anymore.
I followed the step as described in the README, but when I launch the web app and send a request, the web app immediately returns "connexion closed"

adding a `log.Println(err)` in the client.go here: https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/examples/chat/client.go#L65-L71

like this:

```go
if err != nil {
        if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
                log.Printf("error: %v", err)
        }
        log.Println(err)
        break
}
```

and running the sample (with chrome) returns:

```
2021/12/06 08:53:07 websocket: unexpected reserved bits 0x40 
```

_Originally posted by @owulveryck in https://github.com/gorilla/websocket/issues/707#issuecomment-986523404_

**Comment by elithrar** [comment]
Do you have a firewall, VPN, or similar software running that might be interfering with connections?

**Comment by owulveryck** [comment]
No, It is all running on localhost. I have an antivirus, but other socket libraries does not suffer from the problem.

**Comment by orangehousebad** [comment]
Which browser are you using? Did you modify example application?

**Comment by garyburd** [comment]
@owulveryck I cannot reproduce the problem with Chrome, Safari or Firefox.  

I'd like to eliminate the possibility that antivirus is mucking with things. Please run the application with antivirus disabled to see if that fixes the problem.
