### ISSUE TITLE
[question] Why is the format of the data ping packet different sent by WriteControl and WriteMessage ? Which is the standard practice of websocket ping packet?

### ISSUE THREAD

**Issue by guanxingfeng** [gorilla/websocket#743]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

I sent websocket ping packets through WriteControl and WriteMessage respectively, and then captured and analyzed the packets through wireshark, but found that the formats of the two data packets are different. Which one is the standard practice of websocket ping packets? The two data packet formats are as follows:

![image](https://user-images.githubusercontent.com/25924966/145142133-1cb57268-7fed-45c5-96a5-4012ee283b05.png)

![image](https://user-images.githubusercontent.com/25924966/145141888-1feeeef4-8c8d-4902-9d70-6a742bfec7c0.png)

**Versions**
> Go version: `go version`
1.12.17
> package version: run `git rev-parse HEAD` inside the repo
websocket v1.4.2

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!
![image](https://user-images.githubusercontent.com/25924966/145141826-d359e576-0f75-4846-8683-7d394e4b81b1.png)

> Hint: wrap it with backticks to format it

…

**Comment by orangehousebad** [comment]
The hex encoding of the ping message on the wire is 0x89096b656570616c697665.  

The WriteControl method writes the expected data to the network. 

What is the data written by WriteMessage?

**Comment by guanxingfeng** [comment]
There is no problem, but the wireshark packet capture process is incomplete (not including the process of establishing a tcp connection, which leads to the identification of the websocket protocol as tcp)
