### ISSUE TITLE
[question] will the connection be closed automatically when Upgrade return error?

### ISSUE THREAD

**Issue by goace** [gorilla/websocket#758]
```golang
func (server *WSServer) ehcoHandler(w http.ResponseWriter, r *http.Request) {
	c, err := server.upgrader.Upgrade(w, r, nil)
	if err != nil {
		logging.Error("upgrade failed, %v", err)
		return
	}
        // ...
}
```

In this code, when Upgrade returns an error, the handler just returns, is this case will the connection be closed?

**Comment by plasticsax** [comment]
The `Upgrade` method returns a `nil` value for `*websocket.Conn` on error.  It is correct to return as shown in the examples.  The application will panic if `c.Close()` is called.

This is a common idiom in Go.
