### ISSUE TITLE
[feature] Check for and report bad protocol in TLSClientConfig.NextProtos

### ISSUE THREAD

**Issue by garyburd** [gorilla/websocket#760]
See issue #601. 

When dialing a TLS connection, check for and return an error when Dialer.TLSClientConfig.NextProtos contains "h2".   The error text should mention that this can happen when sharing a tls.Config with net/http Transport.

The problem in #601 is difficult for application developers to debug. An explicit error should help.

**Comment by ChannyClaus** [comment]
not sure if this is what you had in mind; https://github.com/gorilla/websocket/pull/788/files
