### ISSUE TITLE
[question] Websocket does not connect upon closing connection for the first time.

### ISSUE THREAD

**Issue by Ronnie147666** [gorilla/websocket#762]
Hello, I'm using your library to serve a websocket application I'm developing. 

The code:

```
import asyncio
import os
import signal

import websockets

import Rpg
import logging


async def websocket_endpoint(websocket):
    try:
        await Rpg.triggerStartGame(websocket)
    finally:
        websocket.close(1001)


async def main():
    # Set the stop condition when receiving SIGTERM.
    loop = asyncio.get_running_loop()
    stop = loop.create_future()
    loop.add_signal_handler(signal.SIGTERM, stop.set_result, None)

    port = int(os.environ.get("PORT", "5000"))
    async with websockets.serve(websocket_endpoint, "", port):
        await stop


logger = logging.getLogger('websockets')
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())

if __name__ == "__main__":
    asyncio.run(main())

```
So upon connecting to the websocket endpoint for the first time everything works ok. However, If I try to disconnect and reconnect, the application hangs. At one time I saw this message
```
Error ->received 1001 (going away); then sent 1001 (going away)
```
but it does not appear consistently.
I'm not sure if I'm not handling/closing the connection properly or if this is a bug. Can you please give me advice on how I could handle this?

PS: The ``` await Rpg.triggerStartGame(websocket)``` part, starts running a process which executes a specific flow receiving and sending message through the websocket. I think it's irrelevant but in case it helps these are the input/output functions used in it.

```
async def sendMessage(message):
    from Rpg import getWs
    conv = Ansi2HTMLConverter()
    html = conv.convert(Style.DIM + Style.BRIGHT + message)
    await getWs().send(html)


async def getMessage():
    from Rpg import getWs
    # data = await getWs().receive_text()
    data = await getWs().recv()
    return data
```
What I want is upon disconnecting and reconnecting, to start the process all over again from the beginning, not to continue the previous connection.

Thanks for your time

**Comment by garyburd** [comment]
Explain how the issue is related the gorilla/websocet package.

**Comment by Ronnie147666** [comment]
Navigating through issues in websockets I confused the libraries, oh man I'm terribly sorry.

**Comment by Ronnie147666** [comment]
Would you mind deleting the issue please, I got the package stuck on my repo screen.
