### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Clfe83** [gorilla/websocket#764]
**Describe the bug**
> A clear and concise description of what the bug is.

…

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?

…

**Expected behavior**
> What output or behaviour were you expecting instead?

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by ctlove0523** [comment]
@Clfe83 please clear describe your problem with this repository
