### ISSUE TITLE
Cannot SetKeepAlive() on the tcp socket created by Dial() also true when using .UnderlyingConn() and type-asserting as net.TCPConn from net.Conn or tls.Conn object #765

### ISSUE THREAD

**Issue by andrewhodel** [gorilla/websocket#767]
`UnderlyingConn().(*net.TCPConn).SetKeepAlive(bool)`

This is required currently to modify the TCP keep alive for a websocket created via golang gorilla Dial().

**Comment by garyburd** [comment]
Duplicate of #765.
