### ISSUE TITLE
[feature] Connection status method

### ISSUE THREAD

**Issue by kdh6429** [gorilla/websocket#768]
Do you have any thoughts on adding a method that returns the connection status of a connection? There is no way to check in the goroutine, which makes error handling very complicated.

**Comment by plasticsax** [comment]
Call the method that you would call after the proposed status method. If the method returns net.ErrClosed, then the application closed the connection.  In many scenarios, it's not necessary to distinguish ErrClosed from any other error.

**Comment by kdh6429** [comment]
Write the logic with handling ErrClosed. thank you.

**Comment by plasticsax** [comment]
Because the Close() method can be called multiple times from multiple goroutines, there's no reason to distinguish ErrClosed from other errors.   The example applications included with the package do not check for ErrClosed.  This issue is the only mention of the error in the entire repo!
