### ISSUE TITLE
How to cancel Dial with proxy?

### ISSUE THREAD

**Issue by aj3423** [gorilla/websocket#769]
**Describe the problem you're having**
> When using proxies, The `DialContext` freezes program, how to cancel it  (not by using timeout)?  I tried `context.WithCancel` but it still freezes. I can't handle it with a simple timeout because users want to cancel it at any time.

**Versions**
> Go version: `go1.17.1 linux/amd64`

> package version: run `git rev-parse HEAD` inside the repo
1.4.2

**"Show me the code!"**

```golang
package main

import (
	"context"
	"fmt"
	"net"
	"net/url"
	"time"

	"github.com/gorilla/websocket"
	"golang.org/x/net/proxy"
)

func main() {
	u := url.URL{Scheme: "wss", Host: "www.some.site", Path: "/some/path"}

	prx, _ := url.Parse("socks5://ss.com:1080") // some not-exist-proxy

	netDialer, _ := proxy.SOCKS5("tcp", prx.Host, nil, &net.Dialer{})
	dialer := websocket.Dialer{NetDial: netDialer.Dial}
	ctx, cancel := context.WithCancel(context.Background())

	go func() { // call "cancel()" after 1 second
		time.Sleep(time.Second)
		fmt.Println("now cancel()")
		cancel()
	}()

	fmt.Println("DialContext start")
	dialer.DialContext(ctx, u.String(), nil)
	fmt.Println("DialContext end")

	fmt.Println("finish")
}

// nothing happens after calling the "cancel()" above from another goroutine, the `DialContext` is still freezing.
```
How to cancel the `DialContext`?

**Comment by plasticsax** [comment]
I am not familiar with proxy.SOCKS5, but I don't see where the cancel context passed down to that dialer.  

Where is the program stuck?

**Comment by aj3423** [comment]
@plasticsax Please check the updated code, it's now runnable. It stuck at the line `dialer.DialContext(ctx, u.String(), nil)`, I try to cancel the dial after 1 second, but it takes about 16 seconds before return.

**Comment by plasticsax** [comment]
Is the problem in the application's network dialer or is the problem in the websocket package.  Run the application's dialer in isolation to test:

	go func() { // call "cancel()" after 1 second
		time.Sleep(time.Second)
		fmt.Println("now cancel()")
		cancel()
	}()

	fmt.Println("netDialer  start")
	netDialer, _ := proxy.SOCKS5("tcp", prx.Host, nil, &net.Dialer{})
        netDialer.Dial("tcp", "www.some.site:443")
	fmt.Println("netDialer  end")

As I look at it now, the context context is not supplied to the application's net dialer.  Does the proxy package have a DialContext function?

**Comment by aj3423** [comment]
Thanks. Indeed the stuck is caused by the `proxy.Dialer` interface, there is only `Dial()` but no `DialContext()`. I googled why, seems the dev [don't want break Api on most people](https://go-review.googlesource.com/c/net/+/37641). 

However casting the dialer to `proxy.ContextDialer` does the trick, the working code:
```golang
func main() {
	prx, _ := url.Parse("socks5://ss.com:1080") // some not-exist-proxy

	ctx, cancel := context.WithCancel(context.Background())

	netDialer, _ := proxy.SOCKS5("tcp", prx.Host, nil, &net.Dialer{})

	go func() { // call "cancel()" after 1 second
		time.Sleep(time.Second)
		fmt.Println("now cancel()")
		cancel()
	}()

	fmt.Println("netDialer  start")

	u := url.URL{Scheme: "wss", Host: "www.some.site", Path: "/some/path"}

	dialer := websocket.Dialer{
		NetDialContext: netDialer.(proxy.ContextDialer).DialContext}
	dialer.DialContext(ctx, u.String(), nil)

	fmt.Println("netDialer  end")
}
```
