### ISSUE TITLE
The server sends a large amount of data, but cannot receive messages from the client  

### ISSUE THREAD

**Issue by hailiangchen** [gorilla/websocket#775]
**Describe the problem you're having**
> 
When the server sends files to the client, it cannot receive messages from the client. Message including PingMessage .
When no data is sent, the PingMessage message from the client is received.

**Versions**
> go version: go1.17.7
> github.com/gorilla/websocket v1.5.0

…

**"Show me the code!"**
> Client.go 
<pre>
<code>
func read(ctx context.Context) {
	defer func() {
		client.Close()
	}()
	client.SetReadLimit(maxMessageSize)
	client.SetReadDeadline(time.Now().Add(readWait))
	client.SetPongHandler(func(s string) error {
		client.SetReadDeadline(time.Now().Add(pongWait))
		return nil
	})
	for {
		messageType, message, err := client.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
				log.Printf("error: %v", err)
			}
			break
		}

		switch messageType {
		case websocket.TextMessage:
			onTextMessage(string(message))
		case websocket.BinaryMessage:
			onBinaryMessage(message)
		default:
		}
	}
}

func write(ctx context.Context) {
	ticker := time.NewTicker(pingPeriod)
	defer func() {
		ticker.Stop()
		client.Close()
	}()

	for {
		select {
		case message, ok := <-send:
			client.SetWriteDeadline(time.Now().Add(writeWait))
			if !ok {
				client.WriteMessage(websocket.CloseMessage, []byte{})
				return
			}

			err := client.WriteMessage(message.MesgType, message.Data)
			if err != nil {
				fmt.Println("Failed to send message:", err)
			}
		case <-ticker.C:
			client.SetWriteDeadline(time.Now().Add(writeWait))
			if err := client.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
				return
			}
		}
	}
}
</code>
</pre>

> Server.go
<pre>
<code>
func (c *Client) WritePump() {
	defer func() {
		c.conn.Close()
	}()

	var pongChan = make(chan bool)
	c.conn.SetPingHandler(func(s string) error {
		c.conn.SetReadDeadline(time.Now().Add(pongWait))
		pongChan <- true
		return nil
	})

	for {
		select {
		case message, ok := <-c.send:
			c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if !ok {
				c.conn.WriteMessage(websocket.CloseMessage, nil)
				return
			}

			if err := c.conn.WriteMessage(message.MesgType, message.Data); err != nil {
				fmt.Println("Failed to send message", err)
				return
			}
		case <-pongChan:
			c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			fmt.Println("Send Pong")
			if err := c.conn.WriteMessage(websocket.PongMessage, nil); err != nil {
				fmt.Println("Failed to send message", err)
				c.conn.Close()
			}
		}

	}
}

func (c *Client) ReadPump() {
	defer func() {
		c.hub.unregister <- c
		c.conn.Close()
	}()

	c.conn.SetReadLimit(maxMessageSize)
	c.conn.SetReadDeadline(time.Now().Add(readWait))

	for {
		messageType, message, err := c.conn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
				log.Printf("error: %v", err)
			}
			break
		}

		switch messageType {
		case websocket.TextMessage:
			onTextMessage(c, string(message))
		case websocket.BinaryMessage:
			onBinaryMessage(c, message)
		default:
		}
	}
}
</code>
</pre>

…

**Comment by lanrion** [comment]
so, How did you solve the problem？

**Comment by hailiangchen** [comment]
> 
After I read the message, my handler took too long to execute and blocked the reading of the message, causing me to fail to receive ping and Pong messages。
