### ISSUE TITLE
[question] Does server and client example not needed ping pong mechanism to keep connection alive?

### ISSUE THREAD

**Issue by smanghate** [gorilla/websocket#777]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

…

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by garyburd** [comment]
Ping/pong can help keep a connection alive.  The example does not demonstrate the feature.
