### ISSUE TITLE
Feat: Add more details in bad handshake

### ISSUE THREAD

**Issue by pablodz** [gorilla/websocket#780]
Hello there :)

I was facing an issue with 429 HTTP error due to limit rate but I was getting in debug "bad handshake", I think that will be useful to print status code of the request and the body itself before sending a bad hanshake error

https://github.com/gorilla/websocket/blob/78cf1bc733a927f673fd1988a25256b425552a8a/client.go#L382-L393

**Comment by garyburd** [comment]
Dial returns the response to the application on handshake failure.  The application can print the status code and body if that’s what the application wants.
