### ISSUE TITLE
[feature] Enable setting allowed origins when "CheckOrigin" is true

### ISSUE THREAD

**Issue by Willson1220** [gorilla/websocket#781]
While the "CheckOrigin" is defined as this:
> 	// CheckOrigin returns true if the request Origin header is acceptable. If
	// CheckOrigin is nil, then a safe default is used: return false if the
	// Origin request header is present and the origin host is not equal to
	// request Host header.
	//
	// A CheckOrigin function should carefully validate the request origin to
	// prevent cross-site request forgery.
	CheckOrigin func(r *http.Request) bool

Would you please give me a way to set the allowed origins when it's  true?

**Comment by garyburd** [comment]
The CheckOrigin function is implemented by the application, not by the package.  Write a function that returns true when the request origin is in the set of origins allowed by the application.
