### ISSUE TITLE
[bug] PingHandler does not work

### ISSUE THREAD

**Issue by carmel** [gorilla/websocket#783]
**Describe the bug**

In my project, the websocket server only needs to listen for ping messages from the client and leave other types of messages alone. I customize the pinghandler via the SetPingHandler method, but it never executes.

…

**Versions**
> `go1.17.9`
> `github.com/gorilla/websocket v1.5.0`

**Steps to Reproduce**
> `SetPingHandler` does not called at all.

**Expected behavior**
> `SetPingHandler` need to be called.

**Code Snippets**
> wrong
```go
         /// …
        ws.SetPingHandler(func(m string) error {
	        err = ws.SetWriteDeadline(time.Now().Add(writeWait))
	        if err != nil {
		        return err
	        }
	        err = ws.WriteMessage(websocket.PongMessage, nil)
	        if err != nil {
		        return err
	        }
	        return nil
        })
      
        ticker := time.NewTicker(pingPeriod)
	for range ticker.C {
		err = ws.SetWriteDeadline(time.Now().Add(writeWait))
		if err != nil {
			return
		}
		err = ws.WriteMessage(websocket.PingMessage, nil)
		if err != nil {
			return
		}
	}
```

> right

```go
      go func() {
		conn.SetPingHandler(func(m string) error {
			err = conn.SetWriteDeadline(time.Now().Add(writeWait))
			if err != nil {
				return err
			}
			err = conn.WriteMessage(websocket.PongMessage, nil)
			if err != nil {
				return err
			}
			return nil
		})

		for {
			typ, _, err := conn.ReadMessage()
			fmt.Println(typ)
			if err != nil {
				if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
					h.Log.Sugar().Error("[WsAndroid PongHandler SetWriteDeadline]", err)
				}
				break
			}
		}
	}()

        ticker := time.NewTicker(pingPeriod)
	for range ticker.C {
		err = conn.SetWriteDeadline(time.Now().Add(writeWait))
		if err != nil {
			return
		}
		err = conn.WriteMessage(websocket.PingMessage, nil)
		if err != nil {
			return
		}
	}
```

Does the message here need to be read out first? 

Sorry for my shallow knowledge of this websocket piece.

When I debug, I found that ReadMessage is also executed only once through a for loop. I don't think it's necessary to use a for loop, is there any other good way?

**Comment by garyburd** [comment]
Use a pong handler to handle pongs sent by the peer in response to the pings sent by the application.   

The for loop is required.  https://pkg.go.dev/github.com/gorilla/websocket#hdr-Control_Messages

**Comment by carmel** [comment]
@garyburd Thanks.
