### ISSUE TITLE
Product min qty should be mandatory and bigger than 0

### ISSUE THREAD

**Issue by ochayoun-makor** [gorilla/websocket#784]
**Describe the bug**
> A clear and concise description of what the bug is.
for now we can insert product without min qty wich it later cause a bug since rfq widget require a default qty (if there is no default it takes the min qty so it should be required).
…

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?
you can add a product with min qty =0
…

**Expected behavior**
> What output or behaviour were you expecting instead?
shouldn't let you enter a product with min qty=0 or unidefiend
…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by easterf** [comment]
Describe how the issue is related to this repository.  i see nothing here about products.
