### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by ErenWHT** [gorilla/websocket#786]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

Hi! I want to listen to the event of connection open, how can I do.

**Versions**
> Go version: `1.17.9`

> package version: run `git rev-parse HEAD` inside the repo
`1.4.2`

**Comment by easterf** [comment]
The Dial method returns when the immediately after the websocket connection is established.  There is no need to listen for an event.
