### ISSUE TITLE
Investigating Error code 1006

### ISSUE THREAD

**Issue by mahashg** [gorilla/websocket#789]
**Investigation websocket disconnect with error code 1006*
I see many instances of websocket disconnect with error code 1006. This is an umbrella bucket where lots of reasons can go. do you have a suggestion on what can be done to investigate to figure out what happened ?

**Comment by easterf** [comment]
The 1006 code is returned to the application when the peer closes the connection before sending a close message. Search for `errUnexpectedEOF`  in [conn.go](https://github.com/gorilla/websocket/blob/master/conn.go) to see the implementation.

Take a look at the peer to figure out why this is happening.
