### ISSUE TITLE
[question]  how to use  websocket.UnderlyingConn()

### ISSUE THREAD

**Issue by Vale-sail** [gorilla/websocket#796]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

When the upgrade of the websocket and the normal message are in a tcp package, the Conn Read obtained by using UnderlyingConn cannot read the normal message, but it can be read normally by using ReadMessage

**Versions**
> Go version:   go1.17.10 darwin/arm64
> package version:  github.com/gorilla/websocket v1.4.2

**"Show me the code!"**
```
func receiveHandler(connection *websocket.Conn) {
	for {
		_, msg, err := connection.ReadMessage()
		if err != nil {
			log.Println("Error in receive:", err)
			return
		}
		log.Printf("receiveHandler: %s\n", msg)
	}
}

func receiveHandlerOnUnderlyingConn(connection *websocket.Conn) {
	var buffer = make([]byte, 1024)
	conn := connection.UnderlyingConn()
	for {
		n, err := conn.Read(buffer)
		if err != nil {
			if err != io.EOF {
				fmt.Errorf("read error %s", err)
			}
			break
		}
		fmt.Printf("receiveHandlerOnUnderlyingConn %d %s\n", n, buffer[:n])
	}
}

func main() {
	var socketUrl = ""
	conn, _, err := websocket.DefaultDialer.Dial(socketUrl, nil)
	if err != nil {
		log.Fatal("Error connecting to Websocket Server:", err)
	}
	defer conn.Close()
	receiveHandlerOnUnderlyingConn(conn)
}
```
1. tcpdump screenshots
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/12558433/176122323-8fef153a-bd0c-463a-95cc-2aa397c6a2b5.png">
2. run  screenshots
<img width="658" alt="image" src="https://user-images.githubusercontent.com/12558433/176121735-a9443413-39d3-42be-a847-7a629b3b360b.png">

**Comment by easterf** [comment]
The purpose of the method  is to set flags and options on the network connection.  Use the websocket connection methods to read and write data to the connection.

**Comment by amustaque97** [comment]
`UnderlyingConn` is deprecated now. You shouldn't use it directly to read data. You can use it to configure some network options. For example here: https://go.dev/play/p/Hq0Wxn4Vuvl?v=gotip

To learn more about it. You can check previous issues like: https://github.com/gorilla/websocket/issues/765
