### ISSUE TITLE
[question] RSV1 set, bad opcode 7, bad MASK

### ISSUE THREAD

**Issue by uday1331** [gorilla/websocket#797]
**Describe the problem you're having**
Running any of the sample codes provided with `gorilla/websocket` produces an error:

```
 websocket: RSV1 set, bad opcode 7, bad MASK
```

The error is happening on a MacBook Pro 2019. I have successfully been able to run the code inside a docker container with `go 1.17.5` and another machine with `go 1.18.2` which makes it confusing. Any help here would be appreciated.
…

**Versions**
`go version go1.18.3 darwin/amd64`
…

**Comment by garyburd** [comment]
Give specific steps for reproducing the problem:  What is the command that you used to run the example?   What is the client that you used?  If the client is a browser, what is the URL that you entered to run the example.

Double check that that you are running the code as is from this repository.

**Comment by uday1331** [comment]
The issue fixed itself on its own after a computer restart. I spent a sufficient amount of time trying to recreate the problem but was not able to. I will close the issue since it looks like something that has been faced just on my machine.
