### ISSUE TITLE
How many users does it support?

### ISSUE THREAD

**Issue by hosseinkhojany** [gorilla/websocket#799]
I have a question. Is it possible to create a chat program with this web socket that supports 100,000 active users?

**Comment by amustaque97** [comment]
Number of users depends on a lot of factors. There is no single answer to this. All I can say is it depends on how you manage things.  There was a similar issue raised in the past, request you to please go through it. https://github.com/gorilla/websocket/issues/72

Regards

**Comment by amustaque97** [comment]
@garyburd we can close this issue.
