### ISSUE TITLE
 Multithreading Call Coon.WriteMessage

### ISSUE THREAD

**Issue by upccup** [gorilla/websocket#80]
hi I found that in the course of the same if I call a client at the same time in two or more threads Conn.WriteMessage methods may be abnormal.  
simply put I think the function of Conn.WriteMessage is not thread safety.
This situation is what you expected of it?

**Comment by garyburd** [comment]
See http://godoc.org/github.com/gorilla/websocket#hdr-Concurrency.

Use a [mutex](http://godoc.org/sync#Mutex), [goroutine](https://github.com/gorilla/websocket/blob/39cd638460acf1c01aaac38effc6e54ee7e04bca/examples/chat/conn.go#L67-L89) or some other mechanism to ensure that only one goroutine writes at a time.

**Comment by JunyiHe** [comment]
Yes, I am falling in this trap before When I call Conn.WriteMessage in multi-goroutine.It will cause "invalid frame header" and the other websocket header error.

**Comment by garyburd** [comment]
Use a mutex to protect the connection:

      mu.Lock()
      err := c.WriteMessage(...)
      mu.Unlock()

The reason that the application is responsible for locking is that the application can make more than one call to the connection to write a single message. The connection cannot coordinate these calls for the application.

**Comment by JunyiHe** [comment]
Yes, I done it and now work correctly.And I think will be more powerful and popular if it implement with thread safety  :)
