### ISSUE TITLE
[question] concurrent write to websocket connection panic occurs when I call Write function and Close function in two goroutine.

### ISSUE THREAD

**Issue by H-hao** [gorilla/websocket#802]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

`concurrent write to websocket connection` panic occurs when I call Write function and Close function in two goroutine.
But the doc says: `The Close and WriteControl methods can be called concurrently with all other methods.`

Why the different between my test and the doc. Is my code wrong?

**Versions**
> Go version: `go version`

go version go1.18.3 windows/amd64

> package version: run `git rev-parse HEAD` inside the repo

`github.com/gorilla/websocket v1.5.0` in my `go.mod` file

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

I did not call `SetWriteDeadline` funcation because of it will BROKE the connection after a write had timed out.
```
nextWriter, _ := conn.NextWriter(websocket.BinaryMessage)
go func() {
    _, e2 := nextWriter.Write([]byte(myData))
    done <- e2
}()
select {
    case <-time.After(time.Duration(myTimeout) * time.Millisecond):
        logging.Debugf("timeout.")
    case e := <-done:
        logging.Debugf("done. e(?)= %s", e)
    }
}
e3 := nextWriter.Close() // timeout or done, then close. THIS LINE OCCURS `concurrent write to websocket connection` PANIC.
if e3 != nil {
    return e3
}
```

**Comment by FZambia** [comment]
Hello, the doc means [Conn.Close](https://pkg.go.dev/github.com/gorilla/websocket#Conn.Close) method I believe.

**Comment by H-hao** [comment]
> Hello, the doc means [Conn.Close](https://pkg.go.dev/github.com/gorilla/websocket#Conn.Close) method I believe.

oh, i understand. Thanks.

**Comment by H-hao** [comment]
Is there any way that can cancel or close current write?

**Comment by volkerite** [comment]
You can cancel a blocked write call by calling conn.Close().

What is the higher-level problem that you are trying to solve?  I am having trouble understanding the goal of the code in the issue.

**Comment by H-hao** [comment]
> You can cancel a blocked write call by calling conn.Close().
> 
> What is the higher-level problem that you are trying to solve? I am having trouble understanding the goal of the code in the issue.

When `Write` a big file binary data, it may speend mush time.

So I want to set a timeout to write file binary data operation, but the `WirteDeadline` is not what I expected because of it will BROKE the connection(I want to keep the connection).
So I'm looking for other solutions.

**Comment by volkerite** [comment]
Is your goal to 

a.  Prevent a goroutine from waiting on a large write
b. Abort a large write if the write takes too long.  

Goal (b) has issues at the protocol level.  Once the length of a frame is written to the network, the entire frame must be written to the network.

**Comment by H-hao** [comment]
> Is your goal to
> 
> a. Prevent a goroutine from waiting on a large write b. Abort a large write if the write takes too long.
> 
> Goal (b) has issues at the protocol level. Once the length of a frame is written to the network, the entire frame must be written to the network.

Got it! Thanks.
