### ISSUE TITLE
[question] why the WriteControl and SetWriteDeadline can be called concurrently?

### ISSUE THREAD

**Issue by H-hao** [gorilla/websocket#803]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

In the doc([Concurrency](https://pkg.go.dev/github.com/gorilla/websocket@v1.5.0#hdr-Concurrency)), it says: `The Close and WriteControl methods can be called concurrently with all other methods`.
In the `WriteControl` code, it calls `c.conn.SetWriteDeadline(deadline)`.

Are them conflicting? Is safe when two goroutines call the `SetWriteDeadline` function?

**Versions**
> Go version: `go version`

go version go1.18.3 windows/amd64
> package version: run `git rev-parse HEAD` inside the repo

github.com/gorilla/websocket v1.5.0 in my go.mod file

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

![image](https://user-images.githubusercontent.com/19198314/182515986-0f7cff86-583e-401c-b946-37c488ea7f5d.png)

**Comment by volkerite** [comment]
The implementation does not conflict with the documentation.
[Conn.WriteControl](https://godoc.org/gorilla/websocket#Conn.WriteControl] does not call [Conn.SetWriteDeadline](https://godoc.org/websocket#Conn.SetWriteDeadline), directly or indirectly.   

The call `c.conn.SetWriteDeadline` is not a call to Conn.SetWriteDeadline.

**Comment by H-hao** [comment]
> The implementation does not conflict with the documentation. [Conn.WriteControl](https://godoc.org/github.com/gorilla/websocket#Conn.WriteControl) does not call [Conn.SetWriteDeadline](https://godoc.org/github.com/gorilla/websocket#Conn.SetWriteDeadline), directly or indirectly.
> 
> The call `c.conn.SetWriteDeadline` is not a call to Conn.SetWriteDeadline.

It's ture that the call `c.conn.SetWriteDeadline` is not a call to Conn.SetWriteDeadline.

But usually, I will call [WriteMessage](https://pkg.go.dev/github.com/gorilla/websocket@v1.5.0#Conn.WriteMessage) after [SetWriteDeadline](https://pkg.go.dev/github.com/gorilla/websocket@v1.5.0#Conn.SetWriteDeadline) called.
Actually, `WriteMessage`'s implementation contains `c.conn.SetWriteDeadline(deadline)`.

The following is `WriteMessage`'s implemention:
1. When I call `conn.SetWriteDeadline` and `conn.WriteMessage`, code goes into `messageWriter.flushFrame()`.
![image](https://user-images.githubusercontent.com/19198314/182519947-ee2f7b0a-34b7-4a60-b992-866296e5d777.png)

2. In `flushFrame` funcation, `Conn.write` funcation is called.(The `c.writeDeadline` is coming form my `conn.SetWriteDeadline`)
![image](https://user-images.githubusercontent.com/19198314/182520330-0c4e20c9-d60e-441d-8ccd-f1a3634a325d.png)

3. In `Conn.Write` funcation, `c.conn.SetWriteDeadline(deadline)` is called.
![image](https://user-images.githubusercontent.com/19198314/182520395-ec21f472-e68e-4091-a890-2598474bb50f.png)

So in step(3), I think it maybe not safe when another goroutines `SetWriteDeadline` is called.

**Comment by volkerite** [comment]
The calls to c.conn.SetWriteDeadline are protected by a [channel implementation of a mutual exclusion lock](https://github.com/gorilla/websocket/blob/af47554f343b4675b30172ac301638d350db34a5/conn.go#L248).

**Comment by H-hao** [comment]
> The calls to c.conn.SetWriteDeadline are protected by a [channel implementation of a mutual exclusion lock](https://github.com/gorilla/websocket/blob/af47554f343b4675b30172ac301638d350db34a5/conn.go#L248).

Got that, thanks.
