### ISSUE TITLE
JSONRPC2 + Gorilla Websockets Example?

### ISSUE THREAD

**Issue by jrbrodie77** [gorilla/websocket#804]
Wondering if anyone is aware of complete server and client examples of JSONRPC2 + websocket using Gorilla? With all the flavors of codec and registering and other forms of indirection, it's taking me longer than expect to figure this out. I've seen some partial examples, but nothing that does both ends. Any help would be greatly appreciated.

**Comment by FZambia** [comment]
Hello, not a JSONRPC2 (not sure how critical is this for you), but pretty complete - with JSON and Protobuf protocols, scalability to many machines, channel (room) concept, client SDKs for JS/Dart/Swift/Go/Java, etc – https://github.com/centrifugal/centrifuge

**Comment by volkerite** [comment]
I found these packages using a search for jsonrpc and websocket.  I cannot vouch for them, but they may help you get going.

https://pkg.go.dev/github.com/ethereum/go-ethereum/rpc
https://pkg.go.dev/github.com/mafredri/cdp/rpcc
https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client/v4/gethrpc
https://pkg.go.dev/github.com/elastos/Elastos.ELA.SideChain.ESC/rpc
https://pkg.go.dev/github.com/ava-labs/coreth/rpc
https://pkg.go.dev/github.com/expanse-org/go-expanse/rpc
