### ISSUE TITLE
After a long time of listen, the Binance will close ws connection [question] 

### ISSUE THREAD

**Issue by ybina** [gorilla/websocket#805]
After a long time of listen(more than 10 hour), the Binance will close ws connection, and should redail the connection, if not, will receive a lot of read err msg.

Is there any way to avoid this problem?

**Comment by FZambia** [comment]
@ybina hello, are you talking about https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md ?

If yes, the link above mentions:

> A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark

So it seems normal that binance WS API disconnects connection from time to time. From the client perspective you need to handle `Read` error and reconnect to a server.

**Comment by ybina** [comment]
@FZambia So is there any plan to add a new function of reconnect ws per 24 hour?

**Comment by volkerite** [comment]
> So is there any plan to add a new function of reconnect ws per 24 hour?

Handle disconnects with a for loop in your appliication:

```
backoff := time.Second

for {
   ws, _, err := websocket.Dial(url, nil)
   if err != nil {
          time.Sleep(backoff)
          backoff = backoff * 2
          continue
   }
   backoff = time.Second // reset backoff on success

   for {
        // add your original code for working with websocket
        // handle errors like this:
        if err != nil  {
            break
       }
}

```
