### ISSUE TITLE
[question] why are there  the same of two  function excute SetWriteDeadline

### ISSUE THREAD

**Issue by baiyutang** [gorilla/websocket#806]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
the source code, in  https://github.com/gorilla/websocket/blob/master/server.go#L254  and https://github.com/gorilla/websocket/blob/master/server.go#L261

why are there the same function with diff  time params?
 

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it
```
	if u.HandshakeTimeout > 0 {
		netConn.SetWriteDeadline(time.Now().Add(u.HandshakeTimeout))
	}
	if _, err = netConn.Write(p); err != nil {
		netConn.Close()
		return nil, err
	}
	if u.HandshakeTimeout > 0 {
		netConn.SetWriteDeadline(time.Time{})
	}
```
…

**Comment by volkerite** [comment]
The calls implement the handshake timeout.   See the Upgrader documentation in this package for information on the timeout.  See the Conn documentation in the net package for information on deadlines.
