### ISSUE TITLE
Why does the websocket connections getting closed on intervals, after sometime it closes permanently [bug] 

### ISSUE THREAD

**Issue by developer-ram** [gorilla/websocket#807]
I am using Gorilla websocket with Go 1.15 as a backend. Angular had been used in frontend. I am facing the problem that the websocket getting disconnected on every few minutes. No idea why it is happening? I have implemented the retry connecting mechanism, which will connect again. But it happens frequently, So After some time, the complete connection will be lost. Please help me out. 
> A clear and concise description of what the bug is.

…

**Versions**
> Go version: `go version`
> package version: run `git rev-parse HEAD` inside the repo

…

**Steps to Reproduce**
> How can the bug be triggered?

…

**Expected behavior**
> What output or behaviour were you expecting instead?

…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by volkerite** [comment]
Something external to this package is causing the connection to close.  It could be the client code, the server code, or a proxy if you are using one.

**Comment by bellacbs** [comment]
> I am using Gorilla websocket with Go 1.15 as a backend. Angular had been used in frontend. I am facing the problem that the websocket getting disconnected on every few minutes. No idea why it is happening? I have implemented the retry connecting mechanism, which will connect again. But it happens frequently, So After some time, the complete connection will be lost. Please help me out.
> 
> > A clear and concise description of what the bug is.
> 
> …
> 
> **Versions**
> 
> > Go version: `go version`
> > package version: run `git rev-parse HEAD` inside the repo
> 
> …
> 
> **Steps to Reproduce**
> 
> > How can the bug be triggered?
> 
> …
> 
> **Expected behavior**
> 
> > What output or behaviour were you expecting instead?
> 
> …
> 
> **Code Snippets**
> 
> > A minimum viable code snippet can be useful! (use backticks to format it).
> 
> …

Hi, I'm having the same problem. Did you get to solve it?

**Comment by bellacbs** [comment]
Hi, I'm having the same problem. Did you get to solve it?

**Comment by developer-ram** [comment]
No, Could not resolve the issue.

**Comment by amustaque97** [comment]
You can configure your system to keep the connection alive. Here are a few links to the issues reported in the past on similar lines https://github.com/gorilla/websocket/issues/765, https://github.com/gorilla/websocket/issues/777. Please go through them if the problem still exists, feel free to share details.

**Comment by garyburd** [comment]
Network connections fail for a number of reasons outside the control of this package.  Write your application to expect connection failures.

As noted in a previous comment, the errors returned from the websocket connection methods may help you debug network connection issues.
