### ISSUE TITLE
[question] Socks5 proxy throwing error:

### ISSUE THREAD

**Issue by seal** [gorilla/websocket#809]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
Currently can't use a socks5 proxy with example code provided 
Errors:
panic: write tcp 127.0.0.1:54724->127.0.0.1:54722: use of closed network connection
or sometimes:
panic: navigation failed: net::ERR_SOCKS_CONNECTION_FAILED

Proxy works as:
![image](https://user-images.githubusercontent.com/25641834/186701448-41ca8ec8-9181-4eb0-8e5b-7894f3e1b1c3.png)

…

**Versions**
> Go version: `go version`
go version go1.18.1 windows/amd64
> package version: run `git rev-parse HEAD` inside the repo
660bb46677a59d9964b2967e926a313f04ae1b1b
…

**"Show me the code!"**
```
func PlaySong(account Account) {
	url := launcher.New().
		Headless(false).
		Set(flags.ProxyServer, "socks5://"+account.Proxy).
		//Proxy(). Have tried Set and Proxy, neither work 
		Delete("use-mock-keychain"). // delete flag "--use-mock-keychain"
		MustLaunch()

	browser := rod.New().ControlURL(url).MustConnect()
	browser.MustIgnoreCertErrors(true)
	defer browser.MustClose()
	go browser.MustHandleAuth(account.ProxyUser, account.ProxyPass)()

	browser.MustPage("http://ip-api.com/json")
	time.Sleep(100 * time.Second)

}
```
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by volkerite** [comment]
How is the issue related to this project?

**Comment by seal** [comment]
Ah shit I left the issue on the wrong repo
