### ISSUE TITLE
No way to test if Messages available for reading without blocking

### ISSUE THREAD

**Issue by niklas88** [gorilla/websocket#81]
I can't find a way to test whether there is a  message available for reading. This is particular problematic if one wants to have a single goroutine that writes messages periodically but also handles pings and messages from the client e.g. to control what is send periodically. Maybe this clashes with how WebSockets work?

**Comment by garyburd** [comment]
Use two goroutines.  

The  [chat example](https://github.com/gorilla/websocket/tree/master/examples/chat) shows one way to structure the goroutines.  

This limitation comes from the underlying network connection. It is not possible to check for data on a Go network connection without blocking.

**Comment by niklas88** [comment]
Yes it is by setting a readDeadline and checking whether the error is just a timeout
On Oct 3, 2015 16:09, Gary Burd <notifications@github.com> wrote:Use two goroutines.  

The  chat example shows one way to structure the goroutines.  

This limitation comes from the underlying network connection. It is not possible to check for data on a Go network connection without blocking.

**Comment by garyburd** [comment]
Read with deadline blocks until the deadline. Go programs typically use two goroutines for this scenario.
