### ISSUE TITLE
How to communicate multiple events and data between client and server

### ISSUE THREAD

**Issue by git136975643** [gorilla/websocket#810]
How to use like node(https://socket.io) like this:Similar to the emit and on methods in node。
```
client: 
   on("eventA",()=>{...})
   emit("eventB",dataB)

server:
   on("eventB",()=>{...})
   emit("eventA",dataA)
```

**Comment by amustaque97** [comment]
Hi, @git136975643 are you asking for the client side or the server side?
Can you share an example for better understanding?

Thank you

**Comment by volkerite** [comment]
See the [documentation and examples](https://github.com/gorilla/websocket#documentation) for information on how to send and receive multiple messages.  In short, use a for loop to [read](https://pkg.go.dev/github.com/gorilla/websocket#Conn.ReadMessage) multiple messages.   

If you are specifically asking about the Socket IO protocol, then use a package that supports the Socket IO protocol.  Websocket and Socket IO are different protocols.

**Comment by git136975643** [comment]
I want to monitor mouse and keyboard events and send data corresponding to the events, such as the position of the mouse movement, the key pressed by the keyboard

**Comment by garyburd** [comment]
A previous comment describes how to send and receive multiple messages.  Write application code to send messages for mouse and keyboard events.
