### ISSUE TITLE
[question] Why read operation from websocket.Conn make write operation to another Tcp conn error?

### ISSUE THREAD

**Issue by SKTT1Ryze** [gorilla/websocket#812]
## **It seems that read operation from websocket effects write operation to another tcp connection.**
There is a game that use Tcp as data protocol between client and server, and I want to port it on web.
Web app only support Websocket protocol, so I wrote a [proxy](https://github.com/DarkNeos/ygopro-proxy) between Tcp server and my web application [neos-ts](https://github.com/DarkNeos/neos-ts).

In the proxy program, it will establish a Tcp connection with game server when accepting Websocket connection from web. Also, It will spawn two goroutines, the one is loop read from Websocket, and write with Tcp connection(WS goroutine), the other is loop read from Tcp, and write with Websocket connection(TCP goroutine).

It successfully established two connections, the one is Websocket with web application, the other is Tcp connection with game server.
```
Websocket connected
Tcp connected
```

**But when the WS goroutine read from Websocket and write to TCP goroutine, the TCP goroutine read `connection reset by peer` error from Tcp connection.**
![Screen Shot 2022-09-14 at 23 51 06](https://user-images.githubusercontent.com/56007649/190202582-107d642a-70bf-48e2-b471-1c83818bc15b.png)

**If I remove the read operation from Websocket in WS goroutine, and write the same buffer to Tcp connection in TCP goroutine, everything is normal. So I think it's not a game server problem.**

What I can't understand is **why reading data from websocket results in an error writing data to tcp**?

Can someone help me with this doubt? Thank you very much!

**Versions**
```
go 1.17

require (
	github.com/gorilla/websocket v1.5.0 // indirect
)
```

## **"Show me the code!"**
[repo](https://github.com/DarkNeos/ygopro-proxy)

```go
package main

import (
	"bufio"
	"io"
	"log"
	"net"
	"net/http"
	"sync"

	"github.com/gorilla/websocket"
	darkneos "github.com/sktt1ryze/ygopro-proxy/DarkNeos"
)

const TARGET_PORT = ":8000"
const PROXY_PORT = ":3344"
const CHANNEL_SIZE = 0x1000
const BUFFER_SIZE = 0x1000

var upgrader = websocket.Upgrader{
	ReadBufferSize:  0x1000,
	WriteBufferSize: 0x1000,
}

func ygoEndpoint(w http.ResponseWriter, r *http.Request) {
	var wg sync.WaitGroup

	upgrader.CheckOrigin = wsChecker

	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer ws.Close()

	log.Println("Websocket connected")

	tcp, err := net.Dial("tcp", "127.0.0.1"+PROXY_PORT)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("Tcp connected")

	defer tcp.Close()

	wg.Add(2)
	go wsProxy(ws, &tcp, &wg)
	go tcpProxy(&tcp, ws, &wg)
	wg.Wait()
}

func wsProxy(ws *websocket.Conn, tcp *net.Conn, wg *sync.WaitGroup) {
	defer wg.Done()

	for {
		messageType, buffer, err := ws.ReadMessage() // read from websocket
		if err != nil {
			log.Println(err)
			break
		}

		if messageType == websocket.CloseMessage {
			log.Println("Websocket closed")
			break
		}

		buffer, err = darkneos.Transform(buffer, darkneos.ProtobufToRawBuf)
		if err != nil {
			log.Fatal(err)
			break
		}

		_, err = (*tcp).Write(buffer)
		if err != nil {
			log.Fatal(err)
			break
		}
	}
}

func tcpProxy(tcp *net.Conn, ws *websocket.Conn, wg *sync.WaitGroup) {
	defer wg.Done()

	reader := bufio.NewReader(*tcp)
	buffer := make([]byte, BUFFER_SIZE)

	for {
		_, err := reader.Read(buffer) // connection reset by peer error throw from here
		if err != nil {
			if err == io.EOF {
				continue
			}

			log.Println("Tcp read message error: ", err)
			break
		}

		buffer, err = darkneos.Transform(buffer, darkneos.RawBufToProtobuf)
		if err != nil {
			log.Fatal(err)
			break
		}

		err = ws.WriteMessage(websocket.BinaryMessage, buffer)
		if err != nil {
			log.Fatal(err)
			break
		}
	}
}

func wsChecker(r *http.Request) bool { return true }

func setupRoutes() {
	http.HandleFunc("/", ygoEndpoint)
}

func main() {
	setupRoutes()

	log.Fatal(http.ListenAndServe(TARGET_PORT, nil))
}
```

**Comment by SKTT1Ryze** [comment]
IP address and ports:
```
Web application(React): http://localhost:3000
Websocket listen on: 127.0.0.1:8000
Tcp listen on: 127.0.0.1:3344
```

`lsof` when Websocket and Tcp all connected:
![Screen Shot 2022-09-15 at 00 08 25](https://user-images.githubusercontent.com/56007649/190206966-deda2161-729c-4718-acaf-453ff71e7655.png)

**Comment by volkerite** [comment]
The only relationship between the websocket connection and the tcp connection is through your application code.  It's unlikely that the websocket connection is responsible for the problem.

The more likely problem is that the TCP connection peer closed the connection because the game application received unexpected data or the game application timed out the connection. Double check that your application is sending correct data to the game.

**Comment by SKTT1Ryze** [comment]
> The only relationship between the websocket connection and the tcp connection is through your application code. It's unlikely that the websocket connection is responsible for the problem.
> 
> The more likely problem is that the TCP connection peer closed the connection because the game application received unexpected data or the game application timed out the connection. Double check that your application is sending correct data to the game.

Yes, you're right.
The TCP server set the timeout(2s) when connected :)

Thanks for your patience.
