### ISSUE TITLE
[feature] Will it support client send msg before handshake is completed ? 

### ISSUE THREAD

**Issue by seeadoog** [gorilla/websocket#816]
**Is your feature request related to a problem? Please describe.**
This  websocket lib seems does not support client send message before  handshake is completed. I think support this feature can satisfy more peoples' need.
…

**Describe the solution you'd like**
Make this websocket Server support client send message before  handshake is completed  and add interface to support client get the websocket connection after tcp connections is established at once rather than wait until  handshake completed.
… 

**Describe alternatives you've considered**
the handshake time can be reduced  about 1 RTT  by supporting this feature. which will accelerate request a lot  in some high latency network。
…

**Comment by volkerite** [comment]
The [RFC](https://www.rfc-editor.org/rfc/rfc6455#section-4.1) requires that the client wait for and validate the server response.

**Comment by amustaque97** [comment]
@volkerite is correct, can we close this issue @seeadoog? 

Thank you!
