### ISSUE TITLE
[feature] Avoid flushing frame twice when calling WriteJSON

### ISSUE THREAD

**Issue by xieyuschen** [gorilla/websocket#817]
**Is your feature request related to a problem? Please describe.**
Currently, the function `WriteJSON` function implementation is shown as the following code snippet.
```go
func (c *Conn) WriteJSON(v interface{}) error {
	w, err := c.NextWriter(TextMessage)
	if err != nil {
		return err
	}
	err1 := json.NewEncoder(w).Encode(v)
	err2 := w.Close()
	if err1 != nil {
		return err1
	}
	return err2
}
```
We will call `w.Close` whatever the `json.NewEncoder(w).Encode(v)` gets an error or not.
The errors raised by the `Encode` method have two types:
- no matter with writing data to the connection.
- error when writing to connection, this is actually raised by the `flushFrame` method.

As a result, if we receive a non-nil error from `json.NewEncoder(w).Encode(v)`, we can return the error directly and no need to flush it twice.

**Describe the solution you'd like**
Return the error directly instead of `flushFrame` twice.
```go
func (c *Conn) WriteJSON(v interface{}) error {
    w, err := c.NextWriter(TextMessage)
    if err != nil {
        return err
    }
    
    if err = json.NewEncoder(w).Encode(v); err != nil {
        return err
    }
    
    return w.Close()
}
```

**Describe alternatives you've considered**
N/A

I'm not sure whether there was a special consideration here. I have searched the issues but found no one. If there are some docs about this, please ping me.
Best regards, thanks.

**Comment by volkerite** [comment]
If  `json.NewEncoder(w).Encode(v)` returned an error because `v` cannot be encoded to JSON, then `w.Close()` should be called to finalize the message.   

If  `json.NewEncoder(w).Encode(v)` returned an error because the write on the network connection failed, then `w.Close()` returns before calling flushFrame.

**Comment by xieyuschen** [comment]
@volkerite 
`json.NewEncoder(w).Encode(v)` raises errors in two cases:
- marshal error, we would do nothing but return the error to callers, it's their fault to pass a non-json based data.
- error raised when writing the websocket connection, actually the `flushFrame` function. For this case, call `w.Close` will call `flushFrame` twice, but why do we need to flush it twice? The flush is already failed and shouldn't flush it twice.

**Comment by volkerite** [comment]
Take a look at the code for Close.  If there was an error writing to the network connection, then the method returns before calling flushFrame.

Note that Close calls writes the final frame to the network (the final argument is true). All messages must have final frame (which can also be the first frame).

**Comment by xieyuschen** [comment]
> Note that Close calls writes the final frame to the network (the final argument is true).

Get it, you are right, it's my fault to ignore it, thanks.

But why it doesn't implement like this?
```go
        err1 := json.NewEncoder(w).Encode(v)
	if err1 != nil {
		return err1
	}
        return w.Close()
```
Instead of:
```go
	err1 := json.NewEncoder(w).Encode(v)
	err2 := w.Close()
	if err1 != nil {
		return err1
	}
	return err2
```

**Comment by volkerite** [comment]
> But why it doesn't implement like this?

The call  `json.NewEncoder(w).Encode(v)` can write one or more frames to the network before an encoding failure. 
The current code ensures that the partial message, if any, is finalized.

**Comment by amustaque97** [comment]
@xieyuschen, can we close this issue? If there are no questions/queries.

**Comment by xieyuschen** [comment]
> @xieyuschen, can we close this issue? If there are no questions/queries.

sure thanks
