### ISSUE TITLE
[question] How to verify tls client?

### ISSUE THREAD

**Issue by ivanjaros** [gorilla/websocket#820]
I have a http server where one of the paths is a websocket.

I need the client that is connecting to this websocket to provide my self-signed tls certificate, which can be done via `websocket.Dialrer.TLSClientConfig`, and then i need to validate this certificate in the handler as authorization mechanism.

My understanding is that the initial http and then ws goes through the https connection of the http(s) server(it's just a protocol upgrade but the connection is still the same), so the connection itself is secured but then I need to verify the client has access to this websocket and I want to do it with TLS instead of cookie or token.

How should I validate this in the serve's handler? I have the tls.Config which I use on the client, as mentioned above, and I just need a way to validate this in the server. How do I do that and do I do it before the connection is upgraded to ws or before?

**Comment by volkerite** [comment]
Authenticate using the peer certificate from [the request's TLS connection state](https://pkg.go.dev/net/http#Request.TLS).

**Comment by ivanjaros** [comment]
> Authenticate using the peer certificate from [the request's TLS connection state](https://pkg.go.dev/net/http#Request.TLS).

i know that, but how?

**Comment by ivanjaros** [comment]
nevermind, this is not possible per handler, let alone ws, only per entire server
