### ISSUE TITLE
[feature] why not support permessage-deflate?

### ISSUE THREAD

**Issue by garyfu9527** [gorilla/websocket#821]
I see EnableCompression used in Upgrader function,But it cannot be set outside this function, why not support it?

**Comment by volkerite** [comment]
The upgrader field is for negotiating compression.  The connection method turns write compression on or off (when negotiated).

**Comment by garyfu9527** [comment]
> The upgrader field is for negotiating compression. The connection method turns write compression on or off (when negotiated).

but in Upgrade function, you have do something about compress,look below:
`	// Negotiate PMCE
	var compress bool
	if u.EnableCompression {
		for _, ext := range parseExtensions(r.Header) {
			if ext[""] != "permessage-deflate" {
				continue
			}
			compress = true
			break
		}
	}
...
	if compress {
		c.newCompressionWriter = compressNoContextTakeover
		c.newDecompressionReader = decompressNoContextTakeover
	}
...
	if compress {
		p = append(p, "Sec-WebSocket-Extensions: permessage-deflate; server_no_context_takeover; client_no_context_takeover\r\n"...)
	}
`

Are you sure that it can set compression flag in connection method?

**Comment by garyfu9527** [comment]
I rewrite Upgrade function,and set EnableCompression to true, it looks like ok.
