### ISSUE TITLE
[question] cancelled context is ignored?

### ISSUE THREAD

**Issue by ivanjaros** [gorilla/websocket#825]
I have dialer:
```
d := websocket.Dialer{
		ReadBufferSize:    1024 * 4,
		WriteBufferSize:   1024 * 4,
		EnableCompression: false,
}
```

and I am using ` d.DialContext()` to dial the server. So far it looks like cancelling the context will not close the connection, so my client "hangs" when the app is requested to be stopped by context cancellation.

Is this a bug or expected behavior or I might have a bug elsewhere?

**Comment by volkerite** [comment]
If the context expires before the connection is complete, an error is returned. Once successfully connected, any expiration of the context will not affect the connection.

**Comment by ivanjaros** [comment]
> If the context expires before the connection is complete, an error is returned. Once successfully connected, any expiration of the context will not affect the connection.

i don't use timeout but cancel function. so if what you say is true how am i supposed to close the connection when reading is blocking so i cannot use select to listen for cancel channel?

**Comment by volkerite** [comment]
>  this essentially makes this entire library useless.

My [previous comment](https://github.com/gorilla/websocket/issues/825#issuecomment-1292191596) is a direct quote  from the standard net package [dialer.DialContext documentation](https://pkg.go.dev/net#Dialer.DialContext).  Are [network connections](https://pkg.go.dev/net#Conn) in the standard library also useless?
