### ISSUE TITLE
What about the problem of passing different message structures on the same connection

### ISSUE THREAD

**Issue by vic220309** [gorilla/websocket#829]
Now there is a requirement to pass different message bodies in the same connection. How can the server and client resolve such messages, for example
1.  message DataByte {
bytes  data = 1;
}

2. message KeyStr {
string  data = 1;
string newData = 2;
}

It's all going to be passed on the same connection, so how does the server figure out which structure is the byte secondary stream

**Comment by chatmando** [comment]
To pass different message bodies over the same connection in a system using the Protobuf serialization format, you can use the oneof feature of the Protobuf language. This feature allows you to define a single field in your message that can hold one of several different types of data, depending on the specific message being sent.

For example, in your scenario, you can define a message that uses the oneof feature to hold either a DataByte or a KeyStr message, like this:

```
message DataMessage {
  oneof message_type {
    DataByte data_byte = 1;
    KeyStr key_str = 2;
  }
}
```

This message defines a message_type field that can hold either a DataByte message or a KeyStr message, depending on the specific message being sent. To send a message using this format, the client and server can simply set the appropriate field in the DataMessage object, and then serialize the object to send it over the connection.

When the server receives a DataMessage object, it can use the message_type field to determine which type of message is contained in the object, and then access the appropriate field to get the data contained in the message.
