### ISSUE TITLE
[question] How to know whether a websocket.Conn is disconnected ?

### ISSUE THREAD

**Issue by soducool** [gorilla/websocket#830]
I'm tring to manage a connection pool of *websocket.Conn, which makes it simple to broadcast message to every client web page. AND to limit the scale of this pool, i have to remove the connection which is disconnected in time. 

But i didn't seen to see a convenient method to check whether a *websocket.Conn is disconnected.

What im doing now is send a heartbeat message periodically, and remove the connection if the sending was failed. Which looks not graceful at all.

**Comment by garyburd** [comment]
Follow the examples: Send PINGs and expect PONGs with a deadline to detect dead connections.  Read on the connection fails when the connection fails.
