### ISSUE TITLE
[question] some questions

### ISSUE THREAD

**Issue by hktalent** [gorilla/websocket#832]
- EnableCompression
https://github.com/gorilla/websocket/blob/af47554f343b4675b30172ac301638d350db34a5/client.go#L238
```
func (d *Dialer) DialContext(...)
...
if d.EnableCompression {
		req.Header["Sec-WebSocket-Extensions"] = []string{"permessage-deflate; server_no_context_takeover; client_no_context_takeover"}
	}

```
but
SetCompressionLevel and EnableWriteCompression
Did not change the header, I don't know if it will have an impact

- example 
https://github.com/gorilla/websocket/blob/af47554f343b4675b30172ac301638d350db34a5/examples/chat/client.go#L106
not 
w, err := c.conn.NextWriter(websocket.TextMessage)
I don't know if there will be a problem

**Comment by hktalent** [comment]
- 3、not support http2
websocket: bad handshake

**Comment by chatmando** [comment]
The SetCompressionLevel and EnableWriteCompression methods are used to enable and configure compression for the websocket connection  The methods not to change the headers used in the handshake.

**Comment by shillbie** [comment]
how do fix it?
