### ISSUE TITLE
[question] read tcp 172.29.229.168:8081->172.29.224.1:57917: i/o timeout

### ISSUE THREAD

**Issue by ah-its-andy** [gorilla/websocket#833]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
I have run a 'chat' same as the one in the samples, when I have a javascript client connected to the server, it will be disconnected in about 1 minutes, because of 'ReadMessage()' returns an errors 'read tcp 172.29.229.168:8081->172.29.224.1:57917: i/o timeout'.

…

**Versions**
> Go version: `go version`
1.17

> package version: run `git rev-parse HEAD` inside the repo
github.com/gorilla/websocket v1.4.1
…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!
```
for {
		messageType, message, err := c.RawConn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
				c.logger.Errorf("websocket readmessage UnexpectedClose from %s: %v", c.connectionID, err)
			}
			c.logger.Debugf("websocket readmessage closed from %s: %v", c.connectionID, err)
			break
		}
		fmt.Printf("%s", message)
	}
```
> Hint: wrap it with backticks to format it

…

**Comment by garyburd** [comment]
The application sets a read deadline that's to short or the application does not change the deadline as in the examples.
