### ISSUE TITLE
[question] socks5 over webrtc,but never entered，help me thanks

### ISSUE THREAD

**Issue by hktalent** [gorilla/websocket#834]
socks5 over webrtc,but ...
dataChannel.OnOpen(func() {
never entered

<img width="744" alt="image" src="https://user-images.githubusercontent.com/18223385/205620290-986f3f1f-66e0-4da2-9585-19a9819554b6.png">
<img width="867" alt="image" src="https://user-images.githubusercontent.com/18223385/205620325-301852bb-9161-46b1-944d-7391535dc2d6.png">

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/18223385/205619906-5a17b6ee-b130-4f4e-9d65-aec7c8d71ec7.png">
answer
<img width="703" alt="image" src="https://user-images.githubusercontent.com/18223385/205619993-814a54c4-b87e-4ba5-b239-70c17d646182.png">

**Comment by garyburd** [comment]
This is not a question about websocket package.
