### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by A425G** [gorilla/websocket#837]
**Describe the problem you're having**
> A clear and concise description of what the bug is.

…

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by chatmando** [comment]
Hi there, I noticed that the form you submitted is blank. Please take a few minutes to go over the form and provide your information.

**Comment by coreydaley** [comment]
This has no details, closing.
