### ISSUE TITLE
unreasonable

### ISSUE THREAD

**Issue by hangever147** [gorilla/websocket#838]
c.readErrCount++
if c.readErrCount >= 1000 {
		panic("repeated read on failed websocket connection")
}
application  long time  run maybe  happen error ,therefore  shouldn't panic.

**Comment by chatmando** [comment]
Hi there! Thank you for reporting this issue on GitHub. After reviewing your report, I have determined that it is similar to several previous issues that have already been addressed. Many of the solutions provided in those issues should also apply to your situation. I recommend that you read the previous issues to see if you can find a solution that works for you. If you are unable to find a solution, please let us know.

#362
#264
#657

**Comment by nikolaydimitrov** [comment]
You can always fork it and change that piece of code

**Comment by ayjayt** [comment]
The documentation makes it pretty clear that any error for NextReader means the connection needs to be reestablished.

This is to help the developer not build a zombie application.

Your readErrCount should never get above 1, after it returns an error you should retry the connection, grab a new Conn, and therefore have readErrCount == 0

not a bug.
