### ISSUE TITLE
WriteControl() changes WriteDeadline permanently

### ISSUE THREAD

**Issue by ayjayt** [gorilla/websocket#841]
I will, later, dig out more information to support this.

https://github.com/gorilla/websocket/blob/9111bb834a68b893cebbbaed5060bdbc1d9ab7d2/conn.go#L463C4-L463C35

> func (*Conn) [WriteControl](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L413) [¶](https://pkg.go.dev/github.com/gorilla/websocket#Conn.WriteControl)
>` func (c *Conn) WriteControl(messageType int, data []byte, deadline time.Time) error`
> WriteControl writes a control message with the given deadline. The allowed message types are CloseMessage, PingMessage and PongMessage.

The issue here that the documentation implies that the deadline is set for this one message, whereas it actually calls `SetWriteDeadline()` and changes the deadline for all subsequent writes as well. It also uses a non-documented default value if supplied time zero `&time.Time{}` so you should expect this function to change your configuration.

**Comment by mylo88** [comment]
The network connection's `SetWriteDeadline` method is called [from WriteControl](https://github.com/gorilla/websocket/blob/8983b963247d87e6caf0e3b72db2539590f1b2c6/conn.go#L390) and the [internal method used by all other writes](https://github.com/gorilla/websocket/blob/8983b963247d87e6caf0e3b72db2539590f1b2c6/conn.go#L390).  These calls to `SetWriteDeadline` establish the appropriate deadline before the network connection's `Write` method is called.

**Comment by mylo88** [comment]
The deadline default value is interesting. It is idiomatic in Go to use a zero time value to specify no deadline. The WriteControl method uses the zero time value to specify a deadline 1000 hours in the future. 

There's not a practical difference between no deadline and a deadline 1000 hours in the future, so this is not something that will have an impact on applications.  

It is strange.

**Comment by ayjayt** [comment]
> A bug this severe seemed unlikely in this popular package.

The bug isn't that they don't...  the bug is that all `write` calls call `SetWriteDeadline` in a way that overwrite the user's calls to `SetWriteDeadline`, but the function descriptions in the docs apply that the write deadline would be set for that single write.

**Comment by ayjayt** [comment]
The solution is to change the documentation but also accept that accepting a write deadline in the write helper function was unnecessary, let the developer use SetWriteDeadline. Explicit is good.

**Comment by mylo88** [comment]
The package works as currently documented.  

The **websocket** connection `SetWriteDeadline` method stores that deadline in a [field](https://github.com/gorilla/websocket/blob/8983b963247d87e6caf0e3b72db2539590f1b2c6/conn.go#L252).  The internal `write` function calls the **network** connection `SetWriteDeadline` with the value from the [field](https://github.com/gorilla/websocket/blob/8983b963247d87e6caf0e3b72db2539590f1b2c6/conn.go#L252).

The `WriteControl` method calls the **network** connection `SetWriteDeadline` method before writing to the network connection.

The documented deadline is used in both code paths.

```
myConn.SetWriteDeadline(myTime) // stores myTime in field
myConn.WriteControl(websocket.PingMessage, []byte("Hello"), 200 * time.Millisecond) // does not change deadline in field
myConn.WriteMessage(...) // uses deadline from field
```

**Comment by ayjayt** [comment]
The documentation is *not* clear. The function, the api, and the documentation suggest that the change is temporary.

I am concerned about the fact that I'm arguing with someone who has what looks like a fake account. Github really needs a verification feature. I have no interest in arguing with anonymous accounts.

**Comment by ayjayt** [comment]
Also, documenting a poor design decision does NOT qualify it as a feature.

**Comment by jaitaiwan** [comment]
Thanks for the comment @JannikGM, I'll close this one out, but agree based on the feedback in this thread that the behaviour is unexpected.

**Comment by GreenMarmot** [comment]
Unexpected?  Deadline management works as documented and would be useless if it worked the way OP assumes that it does.

**Comment by jaitaiwan** [comment]
I was referring to
> 0 deadline being 1000 hours

Thanks

**Comment by GreenMarmot** [comment]
Sorry.  Yes, that is weird.
