### ISSUE TITLE
Any size limit/configuration for the JSON written with Conn.WriteJSON or read with Conn.ReadJSON ?

### ISSUE THREAD

**Issue by ssmails** [gorilla/websocket#842]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
Any size limit/configuration on the JSON written with Conn.WriteJSON or read with Conn.ReadJSON ?
https://pkg.go.dev/github.com/gorilla/websocket#Conn.WriteJSON
https://pkg.go.dev/github.com/gorilla/websocket#Conn.ReadJSON

**Versions**
> Go version: `go version`
1.19

> package version: run `git rev-parse HEAD` inside the repo
github.com/gorilla/websocket v1.5.0

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by mylo88** [comment]
[SetReadLimit](https://pkg.go.dev/github.com/gorilla/websocket#Conn.SetReadLimit) sets the maximum size in bytes for a message read from the peer.  This limit applies to messages read through the ReadJSON helper method.

There is not a limit on WriteJSON.

**Comment by ssmails** [comment]
Thank you
