### ISSUE TITLE
[BUG] websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by zzdboy** [gorilla/websocket#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Testing websoket with Apifox worked without problems. However, using js to connect to websocket will report the following error.

send ping err: write tcp 192.168.101.48:9000->192.168.101.48:60053: wsasend: An established connection was aborted by the software in your host machine.

websocket: close 1006 (abnormal closure): unexpected EOF

### Steps To Reproduce

package controllers

import (
	"archives/app/models"
	"archives/app/services"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

var (

	news = make(map[string]chan interface{})
	client = make(map[string]*websocket.Conn)
	mux sync.Mutex
)

type Websocket struct {
}

func (c Websocket) Index(ctx *gin.Context) {

	UserAccount := ctx.MustGet("user").(models.Users)

	uid := 1

	WsHandler(ctx, uid)

}

func (c Websocket) DeleteClient(ctx *gin.Context) {
	id := ctx.Param("id")

	conn, exist := getClient(id)
	if exist {
		conn.Close()
		deleteClient(id)
	} else {
		ctx.JSON(http.StatusOK, gin.H{
			"mesg": "no message",
		})
	}

	_, exist = getNewsChannel(id)
	if exist {
		deleteNewsChannel(id)
	}
}

// websocket Upgrader
var wsupgrader = websocket.Upgrader{
	ReadBufferSize:   1024,
	WriteBufferSize:  1024,
	HandshakeTimeout: 5 * time.Second,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

func WsHandler(ctx *gin.Context, id string) {
	var conn *websocket.Conn
	var err error
	var exist bool

	pingTicker := time.NewTicker(time.Second * 10)
	conn, err = wsupgrader.Upgrade(ctx.Writer, ctx.Request, nil)
	if err != nil {

		return
	}

	addClient(id, conn)

	m, exist := getNewsChannel(id)
	if !exist {
		m = make(chan interface{})
		addNewsChannel(id, m)
	}

	conn.SetCloseHandler(func(code int, text string) error {
		fmt.Println(code, text)
		deleteClient(id)
		return nil
	})

	conn.SetPingHandler(func(appData string) error {
		fmt.Println("WEBSOCKER Ping:" + appData)
		return nil
	})

	conn.SetPongHandler(func(appData string) error {
		fmt.Println("WEBSOCKER Pong:" + appData)
		return nil
	})

	go func() {
		for {
			_, message, err := conn.ReadMessage()
			if err != nil || err == io.EOF {
				fmt.Println("WebSocket:" + err.Error())
				break
			}

			m <- string(message)
		}
	}()

	for {

		select {
		case content, ok := <-m:

			body_map := map[string]interface{}{}

			s, ok := content.(string)

			if ok && len(s) > 0 {
				err := json.Unmarshal([]byte(s), &body_map)
				if err != nil {
					fmt.Println("Error:", err)
					return
				}
			}

			data := make(map[string]interface{})

			if _, ok = body_map["type"]; ok {

				ctype := body_map["type"].(string)

				if ctype == "new_message" {

					data["code"] = 200
					data["msg"] = "111"
					data["data"] = list

				} else if ctype == "new_todo" {

					data["code"] = 200
					data["msg"] = "222"
					data["data"] = list

					err = conn.WriteJSON(data)
					if err != nil {
						fmt.Println(err)
						conn.Close()
						deleteClient(id)
						return
					}
				} else {
					data["code"] = 200
					data["msg"] = "333"
					data["data"] = body_map

					err = conn.WriteJSON(data)
					if err != nil {
						fmt.Println(err)
						conn.Close()
						deleteClient(id)
						return
					}
				}
			}

		case <-pingTicker.C:

			conn.SetWriteDeadline(time.Now().Add(time.Second * 20))

			data := make(map[string]interface{})

			if has {
				data["code"] = 200
				data["msg"] = "1111"
				data["data"] = "11111"

				err = conn.WriteJSON(data)
				if err != nil {
					fmt.Println("send ping err:", err)
					conn.Close()
					deleteClient(id)
					return
				}
			} else {

				data["code"] = 200
				data["msg"] = "2222"

				err = conn.WriteJSON(data)
				if err != nil {
					fmt.Println("send ping err:", err)
					conn.Close()
					deleteClient(id)
					return
				}
			}

		}
	}
}

func addClient(id string, conn *websocket.Conn) {

	mux.Lock()
	client[id] = conn
	mux.Unlock()
}

func getClient(id string) (conn *websocket.Conn, exist bool) {

	mux.Lock()
	conn, exist = client[id]
	mux.Unlock()
	return
}

func deleteClient(id string) {

	mux.Lock()
	delete(client, id)
	mux.Unlock()
}

func addNewsChannel(id string, m chan interface{}) {
	mux.Lock()
	news[id] = m
	mux.Unlock()
}

func getNewsChannel(id string) (m chan interface{}, exist bool) {
	mux.Lock()
	m, exist = news[id]
	mux.Unlock()
	return
}

func deleteNewsChannel(id string) {
	mux.Lock()
	if m, ok := news[id]; ok {
		close(m)
		delete(news, id)
	}
	mux.Unlock()
}

**Comment by zzdboy** [comment]
Thank you for your reply. I have modified the code according to your instructions, but it still doesn't work. I test with the following basic code. Also report the following error.

server read: websocket: close 1006 (abnormal closure): unexpected EOF

package controllers

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sync"
	"time"

	"github.com/duke-git/lancet/v2/convertor"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

// websocket Upgrader
var wsupgrader = websocket.Upgrader{
	ReadBufferSize:   1024,
	WriteBufferSize:  1024,
	HandshakeTimeout: 100 * time.Second,
	// 取消ws跨域校验
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

type Websocket struct {
}

func (c Websocket) Index(ctx *gin.Context) {

	token := ctx.MustGet("token").(string)
	UserAccount := ctx.MustGet("user").(models.Users)

	uid := convertor.ToString(UserAccount.Id)

	fmt.Println(token)
	fmt.Println("WEBSOCKER user id:" + uid + " user name:" + UserAccount.Name)

	// 升级get请求为webSocket协议
	ws, err := wsupgrader.Upgrade(ctx.Writer, ctx.Request, nil)
	if err != nil {
		return
	}
	defer ws.Close() 
	for {
		mt, message, err := ws.ReadMessage()
		if err != nil {
			fmt.Println("server read:", err)
			break
		}
		fmt.Printf("server recv msg: %s", message)
		msg := string(message)
		if msg == "woshi client1" {
			message = []byte("client1 Went to the service")

		} else if msg == "woshi client2" {
			message = []byte("client2 Went to the service")
		}

		err = ws.WriteMessage(mt, message)
		if err != nil {
			fmt.Println(" server write err:", err)
			break
		}
	}
}


The following is the request header

ws://192.168.20.86:9000/websocket/notify
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cache-Control:no-cache
Connection:Upgrade
Host:192.168.20.86:9000
Origin:http://192.168.20.6:8080
Pragma:no-cache
Sec-Websocket-Extensions:permessage-deflate; client_max_window_bits
Sec-Websocket-Key:bTYgAkbbP68rfEwyhdbXDA==
Sec-Websocket-Protocol:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNjkzNjEzNDkxLCJuYmYiOjE2OTM1MjcwOTEsImlhdCI6MTY5MzUyNzA5MX0.MNNsjTGfZrwMkKeRONHwLTfQCJTDQs4Yl5pJObgRV0k
Sec-Websocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.62

**Comment by HaloArrow** [comment]
The error `websocket: close 1006 (abnormal closure): unexpected EOF` indicates that the client closed the connection without sending a close message.   Is the problem that you are expecting normal closure, or is it unexpected that the connection is closed?  

There's insufficient information to determine why the client closed the connection.
