### ISSUE TITLE
NextReader() only returns the data in the buffer when message length > buffer size.

### ISSUE THREAD

**Issue by RealHacker** [gorilla/websocket#85]
In my application:
 
    message_type, r, err := ws.NextReader()

When I read from r:

    reader := bufio.NewReader(r)
    data, err := reader.ReadBytes('\n')
    // only first 1024 bytes returned in data, causing JSON parse to fail 

The reader only reads  the first 1024 bytes of the message (1024 is the ReadBufferSize I set to the connection).

**Comment by garyburd** [comment]
Please show the code that calls Read.

**Comment by RealHacker** [comment]
I have updated the comment above.

**Comment by RealHacker** [comment]
In conn.go, `messageReader.Read()`, the code only read once from the buffer and returned:

    		if r.c.readRemaining > 0 {
			if int64(len(b)) > r.c.readRemaining {
				b = b[:r.c.readRemaining]
			}
			n, err := r.c.br.Read(b)
			r.c.readErr = hideTempErr(err)
			if r.c.isServer {
				r.c.readMaskPos = maskBytes(r.c.readMaskKey, r.c.readMaskPos, b[:n])
			}
			r.c.readRemaining -= int64(n)
			return n, r.c.readErr
		}

**Comment by garyburd** [comment]
Show your code.

**Comment by RealHacker** [comment]
It is in my first comment, I was just using bufio.NewReader to read from r.

**Comment by garyburd** [comment]
Sorry, missed comment above.  What is the value of err?

**Comment by garyburd** [comment]
I added a [test for this scenario](https://github.com/gorilla/websocket/commit/c66b764651cdca39f42d263b07a507c6e8b58ee9). The test succeeds.  Please comment on what might be different between the test and your application.

**Comment by RealHacker** [comment]
After changing the ReadBufferSize to 4096, I can no longer reproduce this error, but when calling `message_type, r, err := ws.NextReader()`, err is [EOF], when does this error occur?

**Comment by garyburd** [comment]
Changing the buffer size does not change the data returned by the bufio.Reader `ReadBytes` method.
The messageReader `Read`  follows the io.Reader convention that `Read` returns the data available before waiting for more.  The bufio.Reader `ReadBytes` method is written to this convention.  `ReadBytes` calls `Read` in a loop until the delimiter is found or an error is returned.

The `NextReader` method [does not return io.EOF](https://github.com/gorilla/websocket/blob/c66b764651cdca39f42d263b07a507c6e8b58ee9/conn.go#L551-L553).

To read JSON from a message, do the following:

	_, r, err := ws.NextReader()
	if err != nil {
                // handle errror
	}
	err = json.NewDecoder(r).Decode(v)
	if err == io.EOF {
                // handle error
	}

or call [ReadJSON](https://godoc.org/github.com/gorilla/websocket#Conn.ReadJSON).
