### ISSUE TITLE
[BUG] Undefined Error When Running go get github.com/gorilla/websocket with Go 1.15.11 Without Enabling GO111MODULE

### ISSUE THREAD

**Issue by K8lyN-4ever** [gorilla/websocket#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Go version 1.15.11 and have not enabled GO111MODULE. When I run go get github.com/gorilla/websocket, I encounter an "undefined" error. How can I resolve this issue?

### Steps To Reproduce

just run go get github.com/gorilla/websocket

### Anything else?

![Snipaste_2023-09-04_09-46-53](https://github.com/gorilla/websocket/assets/56858689/26fc2026-d8c6-4465-98b0-834bdac509cd)

**Comment by HaloArrow** [comment]
The websocket module requires Go 1.16 and possibly a more recent version of Go.  

Upgrade to a newer version of Go to fix the reported error.

**Comment by K8lyN-4ever** [comment]
> The websocket module requires Go 1.16 and possibly a more recent version of Go.
> 
> Upgrade to a newer version of Go to fix the reported error.

thank u, i can get websocket now.
