### ISSUE TITLE
[BUG] Debug messages are printed to log

### ISSUE THREAD

**Issue by jbarlowbignell** [gorilla/websocket#852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The code has started printing debug messages to via log.Printf(). For example:

`2023/09/19 09:27:23 websocket: discarding reader close error: io: read/write on closed pipe`

It seems to have been introduced recently:

https://github.com/gorilla/websocket/blame/666c197fc9157896b57515c3a3326c3f8c8319fe/conn.go#L1025

### Expected Behavior

No debug messages are printed to the console.

**Comment by jbarlowbignell** [comment]
From the pull request notes, it seems like there were comments saying that writing to the application's stderr is unfriendly. I agree...

https://github.com/gorilla/websocket/pull/840

**Comment by jvegaseg** [comment]
Is there a way to get rid of those log messages?
If it is not possible, how could I check if connection is closed before to call ReadMessage?

Regards
