### ISSUE TITLE
Default PingHandler return value

### ISSUE THREAD

**Issue by hochhaus** [gorilla/websocket#86]
Should the default PingHandler return the error value from WriteControl instead of nil?

    h = func(message string) error {
    	return c.WriteControl(PongMessage, []byte(message), time.Now().Add(writeWait))
    }

**Comment by garyburd** [comment]
Yeah, but not all errors.  [ErrCloseSent](https://github.com/gorilla/websocket/blob/c66b764651cdca39f42d263b07a507c6e8b58ee9/conn.go#L293) should be ignored.  Perhaps [errTimeout](https://github.com/gorilla/websocket/blob/c66b764651cdca39f42d263b07a507c6e8b58ee9/conn.go#L293) should also be ignored.
