### ISSUE TITLE
golang.org/x/net is vendored in branch 1.5.1

### ISSUE THREAD

**Issue by jech** [gorilla/websocket#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a directory vendor with golang.org/x/net included.

### Expected Behavior

There is no vendor directory in the library, the dependency is declared in `go.mod`

### Steps To Reproduce

1. Type `ls vendor/`

**Comment by hulkingshtick** [comment]
Is this fixed? There is not a vendor directory in this project (and it would be bad if there is).

**Comment by jaitaiwan** [comment]
Yes we can close this out for release 1.5.3
