### ISSUE TITLE
[BUG] Potential Handle Leak?

### ISSUE THREAD

**Issue by stasos24** [gorilla/websocket#875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/gorilla/websocket/blob/6f5d2139f4b96d5edfe6c1aac4fe87fed8d7f9fd/proxy.go#L70
According to https://pkg.go.dev/net/http#ReadResponse
`Clients must call resp.Body.Close when finished reading resp.Body`

### Expected Behavior

defer resp.Body.Close() at 77?

**Comment by GreenMarmot** [comment]
The handle `conn` is returned to the caller a few lines after the code linked from the issue.
