### ISSUE TITLE
Setting deadline only for ping messages (?)

### ISSUE THREAD

**Issue by orangesoup** [gorilla/websocket#88]
I'm not sure if this is the correct way to do stuff, but meh. Been trying for hours.

I have a reader like this: 
````go
ws.SetReadDeadline(time.Now().Add(pongWait))
ws.SetPongHandler(func(string) error { ws.SetReadDeadline(time.Now().Add(pongWait)); return nil })
for {
	var msg request
	err := ws.ReadJSON(&msg)
	if err != nil {
		break
	}
	message <- msg
}
````
And the writer like this (simplified):
````go
go func(ws *websocket.Conn) {
	pingTicker := time.NewTicker(time.Second * 30)
	defer func() {
		pingTicker.Stop()
		ws.Close()
	}()

	for {
		select {
		case <-pingTicker.C:
			ws.SetWriteDeadline(time.Now().Add(writeWait))
			if err := ws.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
				return
			}
		case m := <-message:
			if m.Whatever {
				ws.WriteJSON(...)
			}
		}
	}
}()
````
If I don't write to the socket at all then it works (well, it doesn't disconnect and I can send data from the client). However, when I write to the socket after the `writeWait` deadline I get `write tcp 127.0.0.1:8888->127.0.0.1:33219: i/o timeout`. It seems after the first message I send from the server the pingTicker sets the deadline and waits for a response from the client, but the client shouldn't response to these messages. Is there a way to set write deadline only for ping messages? Or am I doing something totally wrong here?

**Comment by garyburd** [comment]
The deadline is a absolute time after which write operations will fail. The deadline applies to all future writes, not just the write following the call to set the deadline. If you don't want the deadline to apply to a write call, then clear the deadline:

        select {
        case <-pingTicker.C:
            ws.SetWriteDeadline(time.Now().Add(writeWait))
            if err := ws.WriteMessage(websocket.PingMessage, []byte{}); err != nil {
                return
            }
        case m := <-message:
            if m.Whatever {
                 ws.SetWriteDeadline(time.Time{})  // clear any previous deadline
                ws.WriteJSON(...)
            }

I don't understand the reasoning for setting the deadline on ping only. If any write call takes to long, then it's a good indication that the peer is stuck or dead. It does not matter if you expect the peer respond to the message or not.

Some comments about the specifics of your code:

- The ping tick ticker duration must be less than `pongWait`, but that relationship is not declared in the code.  If the ping ticker duration is greater than `pongWait` and the peer is not sending any other messages, then ReadJSON will fail with a timeout message.
- The writer should check for errors on all write operations, not just the ping write.

**Comment by orangesoup** [comment]
Thanks, got it working!

* The ticker was less than `pongWait` that's why I didn't even post it, sorry about that.
* The writer does check for error on all write operations, sorry for leaving it out from the example.

The problem in fact was that I didn't set write deadline on every single messages, only for pings. After reading your comment it makes sense to set it every time a write happens! Thank you again!
