### ISSUE TITLE
[question] error: RSV1 set, bad opcode 7, bad MASK 

### ISSUE THREAD

**Issue by jiangbo202** [gorilla/websocket#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I will follow this example（ https://github.com/gorilla/websocket/tree/main/examples/chat ）Start the machine locally, then open it through Google Chrome, enter "test" and click send, but it will directly display: Connection closed.
By adding the print on line 70 of the client.go file, log Println ("xxxX:", err)
Result: websocket: RSV1 set, bad opcode 7, bad MASK

![image](https://github.com/gorilla/websocket/assets/12761320/e0f1877f-62be-4d4b-adf4-fc9caf83aad6)
![image](https://github.com/gorilla/websocket/assets/12761320/0cd1d058-ced4-4dce-8553-0c12d549e9ad)

I checked  #797 , but it worked fine after restarting the computer. However, I have restarted the computer multiple times and it still hasn't worked

I tried other people's computers, and the systems such as Win and Mac Intel chips were all working properly. I also closed all proxy software on my computer, but it didn't work

The error is happening on a MacBook Pro 2021 M1 Pro. 
go version: go version go1.20.6 darwin/arm64

**Comment by canselcik** [comment]
Similar error, happened today.
```
2024/02/13 19:30:43 Error sent to GenericAnonSessionContext dispatch loop: websocket: RSV2 set, RSV3 set, FIN not set on control
panic: runtime error: slice bounds out of range [:5472] with capacity 4096
goroutine 2743107 [running]:
 bufio.(*Reader).Read(0xc021f567e0, {0xc000293a04?, 0x4fc?, 0x1000?})
         /root/go/src/bufio/bufio.go:257 +0x2d0
 github.com/gorilla/websocket.(*messageReader).Read(0xc00013b150, {0xc000293a04, 0x4fc, 0x4fc})
         /root/serversrc/server/vendor/github.com/gorilla/websocket/conn.go:1075 +0x1c5
 io.ReadAll({0x7fa3e8131498, 0xc00013b150})
         /root/go/src/io/io.go:704 +0x7e
 github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0179c70e0?)
         /root/serversrc/server/vendor/github.com/gorilla/websocket/conn.go:1124 +0x3b
```

**Comment by GreenMarmot** [comment]
The `slice bounds out of range` panic indicates that the application called the websocket connection read methods concurrently.  [Concurrent calls are not allowed](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Concurrency).

**Comment by canselcik** [comment]
Thank you @GreenMarmot. I am aware of that and both read and writes are guarded with mutexes. I have also ran the application with the go race detector and haven't hit any results pointing in that direction.

**Comment by GreenMarmot** [comment]
The panic is in bufio.Reader. It's highly unlikely that package has a bug, hence my claim of concurrent calls. 

The `RSV1 set, bad opcode 7, bad MASK` error indicates that the peer sent bad data or the websocket connection is somehow out of sync with the data on the wire.  The latter can be induced by concurrent reads.

**Comment by Nasar165** [comment]
Hi where any one able to find any solution to the issue I'm getting a similar error on my M1 machine I've tried running in docker, VM (UTM) Ubuntu server (ARM version) without any success, I've also tried to to reset the MAC to factory without any success. This specific issue seems isolated to M1 since the code works without any issue on m2 also tried using on my AMD cpu and no issues.

# Failing Environment
MacBook Pro Apple M1  Sonoma 14.4 16GB Ram
- Go version 1.22.1 (ARM)
- Docker (ARM)
- Ubuntu 22  server version (ARM) (UTM VM)
- Chrome 122.0.6261.129 (Official Build) (arm64)
- Safari  17.4

# Successful environment
- AMD CPU
- INTEL CPU
- MacBook Pro Apple M2  Sonoma 14.4 16GB Ram

# Error
RSV1 set, bad opcode 7, bad Mask
- Frametype is set to 7 which crashes in the select loop 

# Hint 
- if Compression is enabled RSV1 disappears
- Attempted other Golang packages fashhttp ,ws  all crash
- Python works without any issues
- no proxies installed
- able to send message from server to client
- only crash when client send to server

**Comment by Nasar165** [comment]
For those who get the following error using Apple MacBook: RSV1 set, bad opcode 7, bad Mask when trying to connect from any client within the system can try and disable Content & Privacy that can be found in settings > Screen time > Content & Privacy and then disable Content & Privacy. This solved my issue on my MacBook M1 running Sonoma 14.4. 

# Possible reason
Possible reason is that the WebFilter service was filtering the payload modifying the Frame leading to malformed frames unaware if this is intentional of a bug from apple.

**Comment by jiangbo202** [comment]
Thank you @Nasar165 , using your method also solved my problem

**Comment by Nasar165** [comment]
Happy to be of help @jiangbo202

**Comment by tubzby** [comment]
Got a similar panic, is it `concurrent read` your case @canselcik ?

```
 level=error msg="read error: websocket: RSV2 set, RSV3 set, FIN not set on control" file=signal/ws.go line=87 mo
 panic: runtime error: slice bounds out of range [:4200] with capacity 4096
 goroutine 10353098 [running]:
 bufio.(*Reader).Read(0x40015a7740, {0x4000e15fc8?, 
         /usr/local/go/src/bufio/bufio.go:250 +0x334
 github.com/gorilla/websocket.(*messageReader).Read
         /go/pkg/mod/github.com/gorilla/websocket@v1.5.
 io.ReadAll({0x7f63384600, 0x4002dfa1e0})
         /usr/local/go/src/io/io.go:701 +0xe4
 io/ioutil.ReadAll(...)
         /usr/local/go/src/io/ioutil/ioutil.go:27
 github.com/gorilla/websocket.(*Conn).ReadMessage
         /go/pkg/mod/github.com/gorilla/websocket@v1.5.
 gdcx.com/rtsp2webrtc/signal.(*wsSignal).connectLoop.
         /usr/src/myapp/signal/ws.go:85 +0xc0
 created by gdcx.com/rtsp2webrtc/signal.(*wsSignal).
         /usr/src/myapp/signal/ws.go:81 +0x274
service: Main process exited, code=exited, status=2/
service: Failed with result 'exit-code'.
```

My logic is quite simple:

```
for shouldConnect {
    for {
           connect until success
    }

   go func() {
     for {
         // read until error
         // panic here
          ws.ReadMessage()
          send to channel
     }
   }()

  // read from channel
  // or wait a specific amount of time, send `KeepAlive` to peer.
  for {
  }
}
```

In my case, read/write might be concurrent, but there's only one reader for a connection.

**Comment by canselcik** [comment]
Yes, @tubzby, it was. @GreenMarmot was spot on.

In your case I believe if you changed your code to do something like the following, the issue will be addressed:

```go
go func(ws *websocket.Conn) {
     for {
         // read until error
         // panic here
          ws.ReadMessage()
          send to channel
     }
   }(ws)
```

**Comment by tubzby** [comment]
@canselcik Thanks for your suggestion, will try that, I'm convinced this was the root cause.

**Comment by Dan-Sones** [comment]
Thank you @Nasar165 - this bug has been driving me crazy!

**Comment by Nasar165** [comment]
@Dan-Sones no problems drove me just as insane when I was facing this issue

**Comment by TomMonkeyMan** [comment]
@Nasar165 thanks dude, I have been debugging this for a week. it works for me either!

**Comment by Nasar165** [comment]
Happy that I could be of some help :) @TomMonkeyMan

**Comment by akashagarwal7** [comment]
> # Solution
> For those who get the following error using Apple MacBook: RSV1 set, bad opcode 7, bad Mask when trying to connect from any client within the system can try and disable Content & Privacy that can be found in settings > Screen time > Content & Privacy and then disable Content & Privacy. This solved my issue on my MacBook M1 running Sonoma 14.4.
> 
> ps: do disable share across device before disabling to not disable on other devices and then restart the laptop and web filter service should be gone.
> 
> # Command to view services
> sudo lsof -i -P | grep LISTEN
> 
> # Possible reason
> Possible reason is that the WebFilter service was filtering the payload modifying the Frame leading to malformed frames unaware if this is intentional or a bug from apple.

Thanks heaps, this worked! More precise, you need to execute:
```sh
sudo lsof -i -P | grep LISTEN | grep webfilter
```

and nothing should show.
