### ISSUE TITLE
Documentation oversight after updating io/ioutl functions to io functions

### ISSUE THREAD

**Issue by midedickson** [gorilla/websocket#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="699" alt="Screenshot 2024-01-14 at 14 46 21" src="https://github.com/gorilla/websocket/assets/45410601/19c431cf-8088-4551-b2a7-4b1b391fde1a">

The picture above shows missed documentation after changing the deprecated ioutil library to io and os libraries

### Expected Behavior

<img width="699" alt="Screenshot 2024-01-14 at 14 46 54" src="https://github.com/gorilla/websocket/assets/45410601/b78fae6c-4c21-4122-b51c-10e9d1154483">

This picture updates the documentation comment to meet the new io library

### Steps To Reproduce

1. examples > autobahn > server.go

**Comment by Hayden-Chang** [comment]
The issue that you mention is fix [here](https://github.com/gorilla/websocket/pull/881/files).

**Comment by AlexVulaj** [comment]
Closing this issue as it's been resolved in the above linked PR, https://github.com/gorilla/websocket/pull/881
