### ISSUE TITLE
Why does specifying the proxy address not work?

### ISSUE THREAD

**Issue by stricklandye** [gorilla/websocket#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi there.
I want to specify proxy address for websocket connection instead of  setting environment variables `http_proxy` and `https_proxy`. I copied code from[#107 ](https://github.com/gorilla/websocket/issues/107) and it's like:

```golang
dg.Dialer = &websocket.Dialer{
  Proxy: http.ProxyURL(&url.URL{
	  Scheme: "http", // or "https" depending on your proxy
	  Host:   "localhost:7890",
  }),
}
```
I have also tried to use `https`  but it still doesn't work.  However,  if use `http_proxy` and `https_proxy` env variables  with `http.ProxyFromEnvironment`, it works fine. code snippet：

```golang
os.Setenv("http_proxy", "http://localhost:7890")
os.Setenv("https_proxy", "http://localhost:7890")
os.Setenv("HTTP_PROXY", "http://localhost:7890")
os.Setenv("HTTPs_PROXY", "http://localhost:7890")
dg, err := discordgo.New("Bot " + botToken)
dg.Dialer = &websocket.Dialer{
   Proxy: http.ProxyFromEnvironment,
}
```

### Expected Behavior

I want to specify proxy address for websokct addres instead of setting environment variables http_proxy and https_proxy. Because it affects other http connection that don't want to go through the proxy. 

### Anything else?

I am using [discordgo](https://github.com/bwmarrin/discordgo) which uses this repo inside. So it maybe not a right place to open the issue here. Hope someone could explain why setting proxy for `Dialer` does not work as I expect.

**Comment by jaitaiwan** [comment]
As you're providing the dialer to the discordgo client then I'd say you'd need to open the issue there. It's likely you need to find a way to pass the dialer to websocket itself. Have a search of issues with "proxy" in it. There's tons of discussions/pr/etc  that have been opened and closed around proxy issues.
