### ISSUE TITLE
[BUG] If `deadline` argument to `WriteControl` is `deadline.IsZero()` then 1000 hours (~41 days) are used as unexpected and undocumented fallback

### ISSUE THREAD

**Issue by JannikGM** [gorilla/websocket#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the `deadline` argument is `deadline.IsZero()` then 1000 hours are used instead:

https://github.com/gorilla/websocket/blob/d08ee1ad9b8a1bad1b388165f85f7794a604b8e1/conn.go#L448-L456

### Expected Behavior

Behaviour should be documented and better design decision has to be made:

Either:
- ignore zero as invalid argument: return `errWriteTimeout`.
- ignore zero deadline: The maximum possible deadline should be used, not arbitrary value of 1000 hours.
- respect zero as valid deadline: Fail request immediately.

### Steps To Reproduce

Call `WriteControl` with a zero-deadline but fail to respond for ~41 days.

This is rather theoretical, but a non-conformant websocket or bad firewall might lead to this.

### Anything else?

Originally reported in https://github.com/gorilla/websocket/issues/841#issue-1814538001.
Confirmed as "unexpected" by maintainer in https://github.com/gorilla/websocket/issues/841#issuecomment-1936818588.

In practice probably doesn't affect anybody; it's just weird.

**Comment by jaitaiwan** [comment]
Nothing in the [RFC](https://www.rfc-editor.org/rfc/rfc6455) seems to indicate any sane value for this. I don't know of any websocket extensions that need to be accounted for in any changes here.

It appears to me that this code is used in both client and server connections, so this probably is a more important function when it comes to clients being unable to write to the server.

Based on that information I think that the following actions should be taken:

1. The default is documented as a warning
1. Any examples should be updated to include setting this deadline to a sane standard
1. This issue should be left open and marked for a v2 as changing this could be a nasty surprise for implementors that don't know about this

**Comment by GreenMarmot** [comment]
In the Go ecosystem, a zero value for deadline is usually taken to mean no deadline.  A deadline in 1000 hours is not the same thing as no deadline, but it's a good approximation for most applications.  Close the gap between what this package does and the expectations for deadlines by using the following code:

	if deadline.IsZero() {
		<-c.mu
	} else {
		d = time.Until(deadline)
		if d < 0 {
			return errWriteTimeout
		}
		select {
		case <-c.mu:
		default:
			timer := time.NewTimer(d)
			select {
			case <-c.mu:
				timer.Stop()
			case <-timer.C:
				return errWriteTimeout
			}
		}
	}

**Comment by GreenMarmot** [comment]
After obtaining the mutex, the [deadline is set on the network connection](https://github.com/gorilla/websocket/blob/d08ee1ad9b8a1bad1b388165f85f7794a604b8e1/conn.go#L478).  A zero value for a network [connection deadline](https://pkg.go.dev/net#Conn.SetWriteDeadline) means that the i/o operation does not timeout.

In practice, the 41 day deadline is the same as not timing out. To trigger the 41 day timeout, another goroutine must be blocked on write to the network connection 41 days The network connection will fail in some way before the 41 days elapses..  

Although the 41 day deadline is not an issue in practice, the code should be changed to not timeout for a zero deadline value.  See  #898.
