### ISSUE TITLE
[BUG] <SRV send msg to client and close the conn right no, client can't receive the msg>

### ISSUE THREAD

**Issue by go-slark** [gorilla/websocket#903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

client can't receive msg from client

### Expected Behavior

client can receive msg from srv

### Steps To Reproduce

// srv pseudo code
ws.Send(msg)
ws.Close()

### Anything else?

// srv pseudo code
ws.Send(msg)
time.sleep(time.second)
ws.Close()
// In this case, client can receive msg from srv

**Comment by jaitaiwan** [comment]
Hi, other folks who use this library have no issues with a basic send. Are you able to provide further information?

To me it seems like you're client isn't ready when the first message is sent which is a client issue.
