### ISSUE TITLE
[BUG]  FormatMessageType returns empty string for unknown type 

### ISSUE THREAD

**Issue by GreenMarmot** [gorilla/websocket#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

FormatMessageType returns the empty string for an unknown message type. 

### Expected Behavior

FormatMessageType should return the decimal representation of the type when the type is unknown. 

### Steps To Reproduce

     fmt.Println(websocket.FormatMessageType(7777))

Actual output: blank line 
Expected output:  7777 

### Anything else?

Cc @rfyiamcool

**Comment by rfyiamcool** [comment]
@GreenMarmot 

Do you want expected value when call `fmt.Println(websocket.FormatMessageType(7777))` ?  Currently input an unknown type, returns an empty string.

I'm sorry, I don't understand your question.

**Comment by GreenMarmot** [comment]
The call `websocket.FormatMessageType(7777)` should return a useful string such as `7777` instead of a blank string.

**Comment by bharat-rajani** [comment]
@rfyiamcool @GreenMarmot We can document the FormatMessageType function's expected return value through a descriptive Go doc comment

**Comment by GreenMarmot** [comment]
@bharat-rajani  Documenting the return value is a great idea, but that does not address this issue.

Debug logging is an important scenario for `FormatMessageType`, but the function comes up short for this scenario.  The function returns the empty string in the case where one would most want to know the value, namely an invalid message type.  It seems like it's a no-brainer to return `strconv.Itoa(mt)`.

As an aside,  the `FormatMessageType` function is not needed in the  [function's example code](https://github.com/gorilla/websocket/blob/09a6bab4667fc302c7f23ad770ce48be6fc2d15f/examples/echo/client.go#L49C1-L50C1).    Because the value of `mt` can only be text or binary, the code could have been written as `log.Printf("recv: %s, is text: %v", message, mt == websocket.TextMessage)`

**Comment by bharat-rajani** [comment]
IMHO returning an empty string or the string representation of the opcode value (`strconv.Itoa(input integer)`) may not convey enough information about the error condition, potentially leading to more confusion or ambiguity.
I think returning a string like "InvalidOpcode", "InvalidMessageType", "unknown opcode" , would make function's behavior more explicit and easier to handle.

Let me know your thoughts!
