### ISSUE TITLE
[BUG] ssh: tcpChan: deadline not supported

### ISSUE THREAD

**Issue by totoro52** [gorilla/websocket#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
		sshConfig := &ssh.ClientConfig{
			User: "xxx",
			Auth: []ssh.AuthMethod{
				ssh.Password("xxx"),
			},
			HostKeyCallback: ssh.InsecureIgnoreHostKey(),
			Timeout:         10 * time.Second,
		}
		client, err := ssh.Dial("tcp", "xxx:22", sshConfig)
		if err != nil {
			log.Fatal("Failed to dial: ", err)
		}
		defer client.Close()
		dialer = websocket.Dialer{Proxy: nil, HandshakeTimeout: 10 * time.Second}
		dialer.NetDialContext = func(ctx context.Context, network, addr string) (net.Conn, error) {
			return client.Dial(network, addr)
		}
               dialer = websocket.Dialer{Proxy: nil, HandshakeTimeout: 10 * time.Second}
```
I am using the SSH tunnel as a proxy, but it doesn't seem to work properly. Can I do that?

**Comment by GreenMarmot** [comment]
The result of`client.Dial(network, addr)` does not have a functional `SetReadDeadline` method ([source](https://cs.opensource.google/go/x/crypto/+/refs/tags/v0.22.0:ssh/tcpip.go;l=502)).

Easy, but no so good fix:   Wrap the `net.Conn` returned by `client.Dial(network, addr)` with a `SetReadDeadline` that squelches errors.

     type wrap struct {
          net.Conn
     }

     func (w wrap) SetReadDeadline(t time.Time) error {
          w.Conn.SetReadDeadline(t)
          return nil
    }

    ...
    c, err := client.Dial(network, addr)
    return wrap{c}, err

Better fix: Get the ssh connection's underlying `net.Conn` and call through to `SetReadDeadline` on that `net.Conn`.  I am not familiar enough with the ssh package to tell you how to do that.

**Comment by GreenMarmot** [comment]
Another possible fix is to remove the timeout from the dialer: `dialer = websocket.Dialer{}`.   With this change, the dialer does not call SetReadDeadline on the network connection supplied by the application.

**Comment by totoro52** [comment]
Thank you for your reply, I have followed the first method you said, as for the elimination of dialer timeout this method I have tried, but it does not work.
