### ISSUE TITLE
[FEATURE] expose newConn function for custom Upgrader

### ISSUE THREAD

**Issue by adhocore** [gorilla/websocket#914]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

i was running into a situation where it required newConn() to be exposed. i needed to have a custom Upgrader. however the complexity of unexposed fields in newConn() made wiring it all up impossible.

is it possible to have it exposed as NewConn() or if not what would be the workaround? (previous issue #573)

### Describe the solution that you would like.

renaming newConn() to NewConn()

### Describe alternatives you have considered.

custom patch with 

```diff
diff --git a/conn.go b/conn.go
index 221e6cf..9a7fbdd 100644
--- a/conn.go
+++ b/conn.go
@@ -289,6 +289,10 @@ type Conn struct {
 	newDecompressionReader func(io.Reader) io.ReadCloser
 }
 
+func NewConn(c net.Conn, s bool, r, w int, wp BufferPool, br *bufio.Reader, wb []byte) *Conn {
+	return newConn(c, s, r, w, wp, br, wb)
+}
+
 func newConn(conn net.Conn, isServer bool, readBufferSize, writeBufferSize int, writeBufferPool BufferPool, br *bufio.Reader, writeBuf []byte) *Conn {
 
 	if br == nil {
```

**Comment by GreenMarmot** [comment]
Why do you need a custom upgrader?   What is the underlying problem that you are trying to solve?

**Comment by adhocore** [comment]
2 cases as to why: for api surfaces unrelated to net/http; for custom requirements/logic in conn upgrades. 

most things in Go provide New() as public api for handy usage of struct instantiation so not sure why that has to be secret private api here.

**Comment by GreenMarmot** [comment]
> 2 cases as to why

I am not a maintainer of this package, but I'd want more details before adding a new public API.  There's a lot of flexibility with Upgrade as is.

> most things in Go provide New() as public api for handy usage of struct

Not true. As an example, there are no New methods in the standard net package.

> so not sure why that has to be secret private api here.

Typical practice in Go is use unexported identifiers for internal APIs. There's a cost for exporting an API:
- The maintainers must support the public API.  
- Package users need to learn about the API, even if it's to learn it's not something they need.

**Comment by adhocore** [comment]
ok seeking alternative ws then
