### ISSUE TITLE
[BUG] go test @ 1.5.2 fails

### ISSUE THREAD

**Issue by tebuka** [gorilla/websocket#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `go test` command reports failure.

### Expected Behavior

The tests pass. 

### Steps To Reproduce

```
$ mkdir fail
$ cd fail
$ go mod init fail.com
$ go get github.com/gorilla/websocket@v1.5.2
$  go test github.com/gorilla/websocket
# go test prints fail message
```

### Anything else?

The maintainers should run the tests before cutting a new release.

**Comment by FZambia** [comment]
There was a fix for tests submitted actually - https://github.com/gorilla/websocket/pull/920 – but it was missed/ignored.
