### ISSUE TITLE
[Question] Why are username and password not allowed in websocket URIs?

### ISSUE THREAD

**Issue by xray-bit** [gorilla/websocket#940]
https://github.com/gorilla/websocket/blob/1d5465562bd18517af0ba4b272bfdb5ec0cfd8ca/client.go#L183-L186

Postman and other similar tools support this type of URI. I also did not find any relevant instructions in RFC6455.

**Comment by canelohill** [comment]
See [WebSocket URIs](https://datatracker.ietf.org/doc/html/rfc6455#section-3) in RFC 6455.  [User information](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1) is not included in the WebSocket URI syntax.

**Comment by xray-bit** [comment]
thanks. sorry i missed that.
