### ISSUE TITLE
[BUG] panic: concurrent read to websocket connection bug

### ISSUE THREAD

**Issue by weitemi** [gorilla/websocket#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

goroutine 2567035 [IO wait]:
internal/poll.runtime_pollWait(0x7f53582b39d8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc003712600?, 0xc001d57c00?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc003712600, {0xc001d57c00, 0x400, 0x400})
	/usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc003712600, {0xc001d57c00?, 0x41a318?, 0x7f53584546f8?})
	/usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc001946310, {0xc001d57c00?, 0xc0029a5d40?, 0xc0029a5d48?})
	/usr/local/go/src/net/net.go:179 +0x45
bufio.(*Reader).fill(0xc00282a7e0)
	/usr/local/go/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc00282a7e0, 0x2)
	/usr/local/go/src/bufio/bufio.go:148 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc001ee8b00, 0xc0029cde90?)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc001ee8b00)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc001ee8b00)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc003038210?)
	/root/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1120 +0x13
hotgo/internal/websocket.(*Client).read(0xc003038210)
	/home/admin-web/server/internal/websocket/client.go:88 +0xa8
created by hotgo/internal/websocket.WsPage in goroutine 2567170
	/home/admin-web/server/internal/websocket/init.go:52 +0x133

**Comment by canelohill** [comment]
The package does not panic with the text "concurrent **read** to websocket connection".  Is the actual panic text "concurrent **write** to websocket connection"? 

Either way, [connections support one concurrent reader and one concurrent writer.](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Concurrency) Modify the application to ensure that there is no more than one reader and one writer at a time.
