### ISSUE TITLE
Chat example.

### ISSUE THREAD

**Issue by mistercorea** [gorilla/websocket#95]
in examples/chat/hub.go
```
case m := <-h.broadcast:
			for c := range h.connections {
				select {
				case c.send <- m:
				default:
					close(c.send)
					delete(h.connections, c)
				}
			}
		}
```
by default was necessary to have close and delete?

I thought closing connection would be handled by unregister call?
I am actually trying to understand the code so I can implement my own utility.

Thank you for the support in advance.

**Comment by garyburd** [comment]
The call to close ensures that the [writePump function will exit](https://github.com/gorilla/websocket/blob/361d4c0ffd78338ebe0a9e6320cdbe115d7dc026/examples/chat/conn.go#L76-L79).

**Comment by mistercorea** [comment]
how do i add the label? i am trying to add the label but i cant do it. this is a question btw

**Comment by garyburd** [comment]
Are you referring to the issue label? That can only be set by an admin.

**Comment by mistercorea** [comment]
oh that make sense. thanks

**Comment by mistercorea** [comment]
I have another quick question, hopefully, so when connection is upgraded from main -> h.run -> wsServe ->h.register
it will do goroutine to do writePump so when message is sent it will distribute the messages.
and readPump to get original message sent from broswer?

**Comment by mistercorea** [comment]
nvm I think I am very confused. almost everything that is related is handled in WritePump and ReadPump

**Comment by garyburd** [comment]
Should I assume nvm means that you figured it out? If not, what are the remaining questions?

**Comment by mistercorea** [comment]
I have a feeling to understand this fully I have to read conn.go, client.go and server.go probably.
If i do come up with more question I will post here or PM you directly.

Thank you for your answers.

**Comment by garyburd** [comment]
You might find this helpful: http://gary.burd.info/go-websocket-chat/

**Comment by mistercorea** [comment]
Yes perfect this is the content i wanted !!!!
Thanks

**Comment by mistercorea** [comment]
```
type my_struct strcut{
    	socket_connection *tls.Conn
        ..... other user information
}

// connections.
type hub struct {
	// Registered connections.
	connections map[*connection]bool
	conn_pair map[*connection]my_struct // pairing connection with websocket with some socket connection.

	// Inbound messages from the connections.
	broadcast chan []byte

	// Register requests from the connections.
	register chan *connection

	// Unregister requests from connections.
	unregister chan *connection
}


var h = hub{
	broadcast:   make(chan []byte),
	register:    make(chan *connection),
	unregister:  make(chan *connection),
	connections: make(map[*connection]bool),
	conn_pair:   make(map[*connection]my_struct),
}
```

I have quick question why cant i create map with map[*connection]my_struct while map[*connection]bool is valid?

**Comment by garyburd** [comment]
I don't expect either to work because connection is not [comparable](https://golang.org/ref/spec#Comparison_operators).

Try `map[*connection]my_struct`.

**Comment by mistercorea** [comment]
What do you mean? @.@ I did try map[*connection]my_struct by creating variable call conn_pair.
so when i try to call or save values h.conn_pair[c] compiler is not happy lol
I am soo lost.

**Comment by mistercorea** [comment]
Ultimately I am trying to create map [*connection address value] my_struct so that i can track connections  

this way i can create key server.

**Comment by mistercorea** [comment]
I think I am getting trouble because my_struct has some pointer method.
and i cant call those method from map.

**Comment by mistercorea** [comment]
YEY I GOT IT.
map[*connection]*my_struct
this way i can call struct pointer methods too.
