### ISSUE TITLE
[BUG] WriteMessage leading Out of memory on using WriteBufferPool

### ISSUE THREAD

**Issue by San-B-09** [gorilla/websocket#953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've upgraded to websocket with following upgrader
```
var upgrader = websocket.Upgrader{
	ReadBufferSize:    1024,
	WriteBufferPool:   &writeBufferPool,
	EnableCompression: false,
}

var writeBufferPool = sync.Pool{
	New: func() interface{} {
		return make([]byte, 1024)
	},
}
```

On using `WriteBufferPool`, memory consumption pattern is almost similar as using upgrader without `WriteBufferPool`.

I came across `beginMessage` method that initiates buffer as following. Here pool buffer is being typecasted to a private type that isn't exposed to create `WriteBufferPool`. I suspect if this is leading to buffer remaining unused.
```
if c.writeBuf == nil {
	wpd, ok := c.writePool.Get().(writePoolData)
	if ok {
		c.writeBuf = wpd.buf
	} else {
		c.writeBuf = make([]byte, c.writeBufSize)
	}
}
``` 

Can you help here if I'm missing something while using `WriteBufferPool`

**Comment by hulkingshtick** [comment]
The BufferPool documentation says that pool value is unspecified, not the []byte. 

Remove the pool New function to avoid the unnecessary allocation. 

```
var upgrader = websocket.Upgrader{
	ReadBufferSize:    1024,
	WriteBufferPool:   &writeBufferPool,
	EnableCompression: false,
}

var writeBufferPool = sync.Pool{
}
```

**Comment by San-B-09** [comment]
Is there a way to cap pool buffer size here ? I'm trying to resolve a memory leak I'm experiencing in `WriteMessage` and I think keeping buffer pool uncapped won't help here.

**Comment by hulkingshtick** [comment]
A pool may not be appropriate for your application.  See  [Buffers](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Buffers).

Capping the number of idle buffers in a sync.Pool should not be necessary.  The point of sync.Pool is that it automatically releases items when the program is under memory pressure.

Fix the code as shown in my comment.  Run the heap profiler on your application to find what's leaking.  Report back here with the results.

**Comment by San-B-09** [comment]
Thanks @hulkingshtick. Remove the pool New function worked for `WriteBufferPool`.
