### ISSUE TITLE
[FEATURE] <implement acknowledgement>

### ISSUE THREAD

**Issue by BisarAhmed** [gorilla/websocket#956]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe the solution that you would like.

like XMPP and socket.io we need to have acknowledgment feature read this for more explanation [socketio ack](https://socket.io/docs/v3/emitting-events/#acknowledgements)

**Comment by jaitaiwan** [comment]
Hey thanks for opening this feature request. I'm going to close it as won't implement for the following reasons:
1. This functionality can be easily made by the consumers of this library
2. If folks want request/response behaviour - just use the technology that is built that way: HTTP

In saying that if folks felt so highly about it that they felt compelled to create a PR, I would consider accepting it.

**Comment by hulkingshtick** [comment]
> if folks felt so highly about it that they felt compelled to create a PR, I would consider accepting it.

The request/response feature is at a layer above the websocket protocol.  If you accept a PR for request/response, will you also accept PRs for other features that are commonly built on the websocket protocol?  Event broadcasting is an example of one of these features.  Where will you draw the line on what's accepted here? Are you prepared to support this stuff in to the future?

> XMPP and socket.io we need to have acknowledgment feature read

If a Go application requires features in the socketio protocol, then the application should use a socketio package. There's a least one socketio package.  Note that socketio can use websocket as the underlying transport.

**Comment by jaitaiwan** [comment]
Possibly, like I said it would be considered. I'd lean in the direction of keeping this library simpler despite that and finding other suitable socketio implementations would be a part of those considerations.

**Comment by hulkingshtick** [comment]
@jaitaiwan  What socketio implementation are you referring to when  say "other suitable socketio implementations"?  Other as opposed to what?

**Comment by jaitaiwan** [comment]
As in libraries, I would look for lists of socketio libraries that fit the mark better.

**Comment by hulkingshtick** [comment]
I am still confused about what you are asking.  You want a list of socketio libraries that X better than Y.  What is X and Y?  Is Y the gorilla/websocket package?

**Comment by jaitaiwan** [comment]
I'm not asking anything. Let me recap: should someone be so excited as to create a PR with the requested functionality, I would look at it and consider the scope of whether or not to add it to gorilla/websockets. This would include whether or not other libraries were available and more suitable than adding a PR to this repo.

Like I said previously:
> This functionality can be easily made by the consumers of this library

Which includes the fact that almost certainly others have made libraries that better suit, so it's unlikely that it would be approved, but I'd still make a full effort to consider it.

**Comment by hulkingshtick** [comment]
You should state up front whether the feature can be included in this package, not after the excited person does the work to implement the feature and submit a PR.

github.com/zishang520/socket.io implements socketio, including the ack feature of the protocol.  That zishang520/socket.io package uses gorilla/websocket for websocket transport.
