### ISSUE TITLE
Is it possible to access session variables or anything through websockets?

### ISSUE THREAD

**Issue by Gacnt** [gorilla/websocket#96]
Just a generic question not really an issue. Thanks.

**Comment by garyburd** [comment]
Yes, an application can manage session state using cookies.  Cookie headers can be found in the request and the application can specify Set-Cookie headers in the handshake response.

**Comment by Gacnt** [comment]
@garyburd Thanks for your reply, how do I access a `*Request` object from a websocket response? I don't see it in the `ws` struct. Thanks.

**Comment by garyburd** [comment]
Use the request argument to the handler function to access the HTTP request.  

What are you referring to when you mention the `ws` struct?  The package does not have a type or variable with that name.

**Comment by Gacnt** [comment]
@garyburd  https://github.com/gorilla/websocket/blob/master/examples/chat/conn.go looking at this, looks like readPump does not have a request object

**Comment by garyburd** [comment]
The [request is passed to the handler](https://github.com/gorilla/websocket/blob/361d4c0ffd78338ebe0a9e6320cdbe115d7dc026/examples/chat/conn.go#L92).  The handler [calls the read pump](https://github.com/gorilla/websocket/blob/361d4c0ffd78338ebe0a9e6320cdbe115d7dc026/examples/chat/conn.go#L92).  It's a simple change to modify the example to pass the request from the handler to the read pump.

**Comment by Gacnt** [comment]
@garyburd Oh, I thought after the initial websocket connection it doesn't ever visit the serve method anymore and would just go straight to ReadPump, like if I connection and then do a `socket.send(data)` <- wouldn't hit the serve first, wouldn't it go straight to read pump not taking the Request struct with it?

**Comment by garyburd** [comment]
The `serveWs` function is called once per connection.  The `readPump` function is called once per connection by `serveWs`.  There are no other calls to `readPump`.  

The example can be modified to pass any data in `serveWs` to `readPump` using function arguments.
