### ISSUE TITLE
SetReadDeadline - Chat example (remove idle clients)

### ISSUE THREAD

**Issue by sofasurfa** [gorilla/websocket#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used chat example to modify some code, added **clients map** and **send chan**.  The example makes sense that after pongWait the next reads return err and cause defer to be called thus calling `c.hub.unregister <- c`. Happy days.
```
**hub.go**
---

type Hub struct {
	// Registered clients.
	clients map[uuid.UUID]*Client

	// Send to specific user
	send chan Message

	// Inbound messages from the clients.
	broadcast chan []byte

	// Register requests from the clients.
	register chan *Client

	// Unregister requests from clients.
	unregister chan *Client
}
```
```
**client.go**
---
func (c *Client) readPump(env *config.Env) {
	defer func() {
		c.hub.unregister <- c
		c.conn.Close()
	}()
	c.conn.SetReadLimit(maxMessageSize)
	c.conn.SetReadDeadline(time.Now().Add(pongWait))
	// Reset pongWait after we get the pong
	// to keep client conn opened.
	c.conn.SetPongHandler(func(string) error { c.conn.SetReadDeadline(time.Now().Add(pongWait)); return nil })

for {

		err := c.conn.ReadJSON(&msg)
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
				env.SugaredLogger.Error("error in ws ReadJSON:", err)
			}
			break
		}
 		c.hub.send <- msg
	}
}
```

### Expected Behavior

Let's say app user exits, and pong never comes back (thus no next read)... that means the socket is still opened (kind of blocked now but still open)? That socket/connection should be deleted for good after ReadDeadline, it's not. How can I make defer work (that will call `c.hub.unregister <- c`) after pongWait without waiting for the next read which might not happen. I might have missed something obvious in the code or should have another goroutine checking clients and if they have expired and remove manually? Thanks. Hopefully this will help other developers who are a little confused.
@garyburd

**Comment by hulkingshtick** [comment]
> How can I make defer work (that will call c.hub.unregister <- c) after pongWait without waiting for the next read which might not happen.

The code in `readPump` looks correct.  Read on the websocket connection returns with an error when the peer closes write on the TCP connection or when the read deadline is exceeded. 

> That socket/connection should be deleted for good after ReadDeadline, it's not.
 
We cannot determine why this is happening because you don't show the code that manages the collection of `Client` or connections. In any case, that's an application issue and not a websocket issue.

**Comment by sofasurfa** [comment]
@hulkingshtick thx for response, my code assumes it's the same as in the chat example. So you're saying that ReadJSON will return `err` once the user exists the app? Thus breaking the for loop, and defer will be called?

**Comment by sofasurfa** [comment]
@hulkingshtick but in cases when let's say phone battery dies and websocket close isn't sent from client, thus read isn't called on server? Then the connection will still be left opened, right?

**Comment by hulkingshtick** [comment]
I edited my previous comment to be more accurate.  What specifically is the scenario where one of those conditions will not be true, but the peer is gone?

The hub code in your application is **not** the same as the hub code in the application.  Perhaps you have a bug there.

**Comment by sofasurfa** [comment]
@hulkingshtick thx, just re-read what you wrote, so you're saying ReadJSON will return err itself without client sending anything? It's just the comment explaining the function says otherwise, that why I'm confused I guess:
`"
// SetReadDeadline sets the read deadline on the underlying network connection.
// After a read has timed out, the websocket connection state is corrupt and
// all future reads will return an error. A zero value for t means reads will
// not time out.
func (c *Conn) SetReadDeadline(t time.Time) error {
	return c.conn.SetReadDeadline(t)
}
"`

**Comment by sofasurfa** [comment]
@garyburd @hulkingshtick would appreciate if you could confirm this "in case someone's phone battery dies or client network doesn't send a websocket close(), then ReadJSON won't return err at all even after ReadDeadline bcz a read never came through"

**Comment by sofasurfa** [comment]
@garyburd @hulkingshtick I think I found the code in`conn.go` in `func (c *Conn) NextReader()` 
```
for c.readErr == nil {
		frameType, err := c.advanceFrame()
		if err != nil {
			c.readErr = hideTempErr(err)
			break
		}
...
```
which means indeed like you said, ReadJSON will return err after `SetReadDeadline`, supported by the comment for this function as well

```
// Applications must break out of the application's read loop when this method
// returns a non-nil error value. Errors returned from this method are
// permanent. Once this method returns a non-nil error, all subsequent calls to
// this method return the same error.
```
So maybe making ReadJSON comment more clear about err being returned after `SetReadDeadline` so it's more clear to avoid my confusion?

**Comment by hulkingshtick** [comment]
In the Go, a read [deadline](https://pkg.go.dev/net#Conn.SetDeadline) in the context of network [connections](https://pkg.go.dev/net#Conn) is a time limit set on reading from a network connection. The deadline specifies how long the program will wait for data to be received before giving up and returning an error.

**Comment by sofasurfa** [comment]
@hulkingshtick ahh see it's an internal go pkg. Thx for clarifying that
